manipulation.constraint_graph_factory.ConstraintFactory Class Reference
manipulation.constraint_graph_factory.ConstraintFactory Class Reference
Default implementation of ConstraintFactoryAbstract.
Public Member Functions
def __init__ (self, graphfactory, graph)
def buildGrasp (self, g, h)
Calls ConstraintGraph.createGraph and ConstraintGraph.createPreGrasp.
def buildPlacement (self, o)
def buildStrictPlacement (self, o)
This implements strict placement manifolds, where the parameterization constraints is the complement of the placement constraint.
def buildRelaxedPlacement (self, o)
This implements relaxed placement manifolds, where the parameterization constraints is the LockedJoint of the object root joint.
Public Member Functions inherited from manipulation.constraint_graph_factory.ConstraintFactoryAbstract
def __init__ (self, graphfactory)
def buildGrasp (self, g, h)
Function called to create grasp constraints.
def buildPlacement (self, o)
Function called to create placement constraints.
def getGrasp (self, gripper, handle)
def g (self, gripper, handle, what)
def getPlacement (self, object)
def p (self, object, what)
Public Attributes
graph
strict
Select whether placement should be strict or relaxed.
Public Attributes inherited from manipulation.constraint_graph_factory.ConstraintFactoryAbstract
graphfactory
Static Public Attributes
tuple gfields = ('grasp', 'graspComplement', 'preGrasp')
tuple pfields = ('placement', 'placementComplement', 'prePlacement')
Detailed Description
Default implementation of ConstraintFactoryAbstract.
Constructor & Destructor Documentation
def manipulation.constraint_graph_factory.ConstraintFactory.__init__ (self, graphfactory, graph)
Member Function Documentation
def manipulation.constraint_graph_factory.ConstraintFactory.buildGrasp (self, g, h)
Calls ConstraintGraph.createGraph and ConstraintGraph.createPreGrasp.
Parameters
g gripper string
h handle string
References manipulation.constraint_graph_factory.ConstraintFactory.gfields.
def manipulation.constraint_graph_factory.ConstraintFactory.buildPlacement (self, o)
References manipulation.constraint_graph_factory.ConstraintFactory.buildRelaxedPlacement(), manipulation.constraint_graph_factory.ConstraintFactory.buildStrictPlacement(), and manipulation.constraint_graph_factory.ConstraintFactory.strict.
def manipulation.constraint_graph_factory.ConstraintFactory.buildRelaxedPlacement (self, o)
This implements relaxed placement manifolds, where the parameterization constraints is the LockedJoint of the object root joint.
Parameters
o string
References manipulation.constraint_graph_factory.ConstraintFactory.pfields.
Referenced by manipulation.constraint_graph_factory.ConstraintFactory.buildPlacement().
def manipulation.constraint_graph_factory.ConstraintFactory.buildStrictPlacement (self, o)
This implements strict placement manifolds, where the parameterization constraints is the complement of the placement constraint.
Parameters
o string
References manipulation.constraint_graph_factory.ConstraintFactory.pfields.
Referenced by manipulation.constraint_graph_factory.ConstraintFactory.buildPlacement().
Member Data Documentation
tuple manipulation.constraint_graph_factory.ConstraintFactory.gfields = ('grasp', 'graspComplement', 'preGrasp') static
Referenced by manipulation.constraint_graph_factory.ConstraintFactory.buildGrasp().
manipulation.constraint_graph_factory.ConstraintFactory.graph
tuple manipulation.constraint_graph_factory.ConstraintFactory.pfields = ('placement', 'placementComplement', 'prePlacement') static
Referenced by manipulation.constraint_graph_factory.ConstraintFactory.buildRelaxedPlacement(), and manipulation.constraint_graph_factory.ConstraintFactory.buildStrictPlacement().
manipulation.constraint_graph_factory.ConstraintFactory.strict
Select whether placement should be strict or relaxed.
See also
buildStrictPlacement, buildRelaxedPlacement
Referenced by manipulation.constraint_graph_factory.ConstraintFactory.buildPlacement().