# DO NOT EDIT THIS FILE!
#
# Python module hpp.manipulation_idl.graph_idl generated by omniidl

import omniORB
omniORB.updateModule("hpp_idl.hpp.manipulation_idl.graph_idl")

# ** 1. Stub files contributing to this module
import hpp_stubs.manipulation._graph_idl
import hpp_stubs.manipulation._problem_idl

# ** 2. Sub-modules

# ** 3. End
