hpp::constraints::JointFrame Class Reference
hpp::constraints::JointFrame Class Reference
Symbolic calculus
#include <hpp/constraints/symbolic-calculus.hh>
Public Types
typedef CalculusBase< JointFrame, ValueType_t, JacobianType_t > Parent_t
Public Types inherited from hpp::constraints::CalculusBaseAbstract< Eigen::Matrix< value_type, 6, 1 >, Eigen::Matrix< value_type, 6, Eigen::Dynamic > >
typedef Eigen::Matrix< value_type, 6, 1 > ValueType_t
typedef Eigen::Matrix< value_type, 6, Eigen::Dynamic > JacobianType_t
Public Member Functions
JointFrame ()
JointFrame (const Parent_t &other)
JointFrame (const JointFrame &jf)
JointFrame (const JointPtr_t &joint)
const JointPtr_t & joint () const
void impl_value (const ConfigurationIn_t)
void impl_jacobian (const ConfigurationIn_t arg)
Public Member Functions inherited from hpp::constraints::CalculusBase< JointFrame, Eigen::Matrix< value_type, 6, 1 >, Eigen::Matrix< value_type, 6, Eigen::Dynamic > >
CalculusBase ()
CalculusBase (const Eigen::Matrix< value_type, 6, 1 > &value, const Eigen::Matrix< value_type, 6, Eigen::Dynamic > &jacobian)
CalculusBase (const CalculusBase &o)
const Eigen::Matrix< value_type, 6, 1 > & value () const
const Eigen::Matrix< value_type, 6, Eigen::Dynamic > & jacobian () const
void computeValue (const ConfigurationIn_t arg)
void computeJacobian (const ConfigurationIn_t arg)
void invalidate ()
const CrossMatrix & cross () const
void computeCrossValue (const ConfigurationIn_t arg)
Protected Attributes
JointPtr_t joint_
double theta_
Protected Attributes inherited from hpp::constraints::CalculusBase< JointFrame, Eigen::Matrix< value_type, 6, 1 >, Eigen::Matrix< value_type, 6, Eigen::Dynamic > >
Eigen::Matrix< value_type, 6, 1 > value_
Eigen::Matrix< value_type, 6, Eigen::Dynamic > jacobian_
CrossMatrix cross_
bool vValid_
bool jValid_
bool cValid_
Additional Inherited Members
Protected Member Functions inherited from hpp::constraints::CalculusBase< JointFrame, Eigen::Matrix< value_type, 6, 1 >, Eigen::Matrix< value_type, 6, Eigen::Dynamic > >
void init (const typename Traits< JointFrame >::Ptr_t &ptr)
Member Typedef Documentation
typedef CalculusBase<JointFrame, ValueType_t, JacobianType_t > hpp::constraints::JointFrame::Parent_t
Constructor & Destructor Documentation
hpp::constraints::JointFrame::JointFrame () inline
hpp::constraints::JointFrame::JointFrame (const Parent_t & other) inline
hpp::constraints::JointFrame::JointFrame (const JointFrame & jf) inline
hpp::constraints::JointFrame::JointFrame (const JointPtr_t & joint) inline
References Eigen::assert().
Member Function Documentation
void hpp::constraints::JointFrame::impl_jacobian (const ConfigurationIn_t arg) inline
References Eigen::assert(), and hpp::constraints::JlogSO3().
void hpp::constraints::JointFrame::impl_value (const ConfigurationIn_t) inline
References hpp::constraints::logSO3().
const JointPtr_t& hpp::constraints::JointFrame::joint () const inline
Member Data Documentation
JointPtr_t hpp::constraints::JointFrame::joint_ protected
double hpp::constraints::JointFrame::theta_ protected