hpp::constraints::solver::HierarchicalIterative Class Reference
hpp::constraints::solver::HierarchicalIterative Class Reference
Constraint solvers
Solve a system of non-linear equations on a robot configuration.
#include <hpp/constraints/solver/hierarchical-iterative.hh>
Classes
struct Data
Public Types
enum Status {
ERROR_INCREASED,
MAX_ITERATION_REACHED,
INFEASIBLE,
SUCCESS
}
typedef Eigen::RowBlockIndices Indices_t
typedef lineSearch::FixedSequence DefaultLineSearch
typedef boost::function< bool(vectorIn_t q, vectorOut_t qSat, Eigen::VectorXi &saturation)> Saturation_t
This function checks which degrees of freedom are saturated.
Public Member Functions
HierarchicalIterative (const LiegroupSpacePtr_t &configSpace)
HierarchicalIterative (const HierarchicalIterative &other)
virtual ~HierarchicalIterative ()
value_type residualError () const
Returns the squared norm of the error vector.
void residualError (vectorOut_t error) const
Returns the error vector.
bool definesSubmanifoldOf (const HierarchicalIterative &solver) const
Inclusion of manifolds.
virtual std::ostream & print (std::ostream &os) const
template<typename LineSearchType >
solver::HierarchicalIterative::Status solve (vectorOut_t arg, LineSearchType lineSearch) const
Problem definition
const LiegroupSpacePtr_t & configSpace () const
Get configuration space on which constraints are defined.
virtual bool contains (const ImplicitPtr_t &numericalConstraint) const
Check whether a numerical constraint has been added.
void add (const DifferentiableFunctionPtr_t &f, const std::size_t &priority) HPP_CONSTRAINTS_DEPRECATED
Add an implicit equality constraint.
void add (const DifferentiableFunctionPtr_t &f, const std::size_t &priority, const ComparisonTypes_t &comp) HPP_CONSTRAINTS_DEPRECATED
Add an implicit constraint.
void add (const ImplicitPtr_t &constraint, const std::size_t &priority)
Add an implicit constraint.
virtual void merge (const HierarchicalIterative &other)
add constraints of another solver
void saturation (const Saturation_t &saturate)
Set the saturation function.
const Saturation_t & saturation () const
Get the saturation function.
Problem resolution
template<typename LineSearchType >
Status solve (vectorOut_t arg, LineSearchType ls=LineSearchType()) const
Solve the system of non linear equations.
Status solve (vectorOut_t arg) const
Solve the system of non linear equations.
bool isSatisfied (vectorIn_t arg) const
bool isConstraintSatisfied (const ImplicitPtr_t &constraint, vectorIn_t arg, vectorOut_t error, bool &constraintFound) const
Whether a constraint is satisfied for an input vector.
const value_type & sigma () const
Returns the lowest singular value.
Parameters
void freeVariables (const segments_t intervals)
Set free velocity variables.
void freeVariables (const Indices_t &indices)
Set free velocity variables.
const Indices_t & freeVariables () const
Get free velocity variables.
void maxIterations (size_type iterations)
Set maximal number of iterations.
size_type maxIterations () const
Get maximal number of iterations in config projector.
void errorThreshold (const value_type &threshold)
Set error threshold.
value_type errorThreshold () const
Get error threshold.
value_type squaredErrorThreshold () const
Get error threshold.
value_type inequalityThreshold () const
Get the inequality threshold.
void inequalityThreshold (const value_type &it)
set the inequality threshold
void lastIsOptional (bool optional)
bool lastIsOptional () const
Stack
const ImplicitConstraintSet & constraints (const std::size_t priority)
Get set of constraints for a give priority level.
const NumericalConstraints_t & constraints () const
Get constraints (implicit and explicit)
std::size_t numberStacks () const
const size_type & dimension () const
const size_type & reducedDimension () const
Dimension of the problem after removing the rows of the jacobian which do not influence the error (only zeros along those lines).
ArrayXb activeParameters () const
Configuration parameters involved in the constraint resolution.
ArrayXb activeDerivativeParameters () const
Velocity parameters involved in the constraint resolution.
Right hand side accessors
vector_t rightHandSideFromConfig (ConfigurationIn_t config)
Compute right hand side of equality constraints from a configuration.
virtual bool rightHandSideFromConfig (const ImplicitPtr_t &constraint, ConfigurationIn_t config)
Compute right hand side of a constraint from a configuration.
virtual bool rightHandSide (const ImplicitPtr_t &constraint, vectorIn_t rhs)
Set right hand side of a constraints.
virtual bool getRightHandSide (const ImplicitPtr_t &constraint, vectorOut_t rhs) const
Get right hand side of a constraints.
virtual void rightHandSide (vectorIn_t rhs)
Set the right hand side.
void rightHandSideAt (const value_type &s)
Set the right hand side at a given parameter.
vector_t rightHandSide () const
Get the right hand side.
size_type rightHandSideSize () const
Get size of the right hand side.
Access to internal data
You should know what you do when you call these functions
template<bool ComputeJac>
void computeValue (vectorIn_t arg) const
Compute the value of each level, and the jacobian if ComputeJac is true.
void computeSaturation (vectorIn_t arg) const
void getValue (vectorOut_t v) const
void getReducedJacobian (matrixOut_t J) const
void computeError () const
If lastIsOptional() is true, then the last level is ignored.
const vector_t & lastStep () const
Accessor to the last step done.
virtual bool integrate (vectorIn_t from, vectorIn_t velocity, vectorOut_t result) const
Protected Types
typedef Eigen::JacobiSVD< matrix_t > SVD_t
Protected Member Functions
void update ()
Allocate datas and update sizes of the problem Should be called whenever the stack is modified.
virtual void computeActiveRowsOfJ (std::size_t iStack)
Compute which rows of the jacobian of stack_[iStack] are not zero, using the activeDerivativeParameters of the functions.
void computeDescentDirection () const
Compute a SVD decomposition of each level and find the best descent direction at the first order.
void expandDqSmall () const
void saturate (vectorOut_t arg) const
Protected Attributes
value_type squaredErrorThreshold_
value_type inequalityThreshold_
size_type maxIterations_
std::vector< ImplicitConstraintSet > stacks_
LiegroupSpacePtr_t configSpace_
size_type dimension_
size_type reducedDimension_
bool lastIsOptional_
Indices_t freeVariables_
Unknown of the set of implicit constraints.
Saturation_t saturate_
NumericalConstraints_t constraints_
Members moved from core::ConfigProjector.
std::map< DifferentiableFunctionPtr_t, size_type > iq_
Value rank of constraint in its priority level.
std::map< DifferentiableFunctionPtr_t, size_type > iv_
Derivative rank of constraint in its priority level.
std::map< DifferentiableFunctionPtr_t, std::size_t > priority_
Priority level of constraint.
value_type sigma_
The smallest non-zero singular value.
vector_t dq_
vector_t dqSmall_
matrix_t reducedJ_
Eigen::VectorXi saturation_
Eigen::VectorXi reducedSaturation_
Configuration_t qSat_
ArrayXb tmpSat_
value_type squaredNorm_
std::vector< Data > datas_
SVD_t svd_
vector_t OM_
vector_t OP_
mutable::hpp::statistics::SuccessStatistics statistics_
Friends
struct lineSearch::Backtracking
Detailed Description
Solve a system of non-linear equations on a robot configuration.
The non-linear system of equations is built by adding equations with method HierarchicalIterative::add.
Note that a hierarchy between the equations can be provided. In this case, the solver will try to solve the highest priority equations first, and then to solve the lower priority equations. Note that priorities are in decreasing order: 0 has higher priority than 1.
The algorithm used is a Newton-Raphson like algorithm that works as follows: let \(f (\mathbf{q}) = 0\) be the system of equations where \(f\) is a \(C^1\) mapping from the robot configuration space to a Lie group space \(\mathcal{L}\).
Starting from initial guess \(\mathbf{q}_0\), the method HierarchicalIterative::solve builds a sequence of configurations \(\mathbf{q}_i\) as follows:
\begin{eqnarray*} \mathbf{q}_{i+1} = \mathbf{q}_i - \alpha_i \frac{\partial f}{\partial \mathbf{q}}(\mathbf{q}_i)^{+} f (\mathbf{q}_i) \end{eqnarray*}
where
\(\frac{\partial f}{\partial \mathbf{q}}(\mathbf{q}_i)^{+}\) is the Moore-Penrose pseudo-inverse of the system Jacobian,
\(\alpha_i\) is a sequence of real numbers depending on the line search strategy. Possible line-search strategies are lineSearch::Constant, lineSearch::Backtracking, lineSearch::FixedSequence, lineSearch::ErrorNormBased. until
the residual \(\|f(\mathbf{q})\|\) is below an error threshold, or
the maximal number of iterations has been reached.
The error threshold can be accessed by methods HierarchicalIterative::errorThreshold. The maximal number of iterations can be accessed by methods HierarchicalIterative::maxIterations.
Note
Lie group
The unknowns \(\mathbf{q}\) may take values in a more general set than the configuration space of a robot. This set should be a Cartesian product of Lie groups: hpp::pinocchio::LiegroupSpace.
Note
Saturation
To prevent configuration variables to get out of joint limits during Newton Raphson iterations, the user may provide a method of type HierarchicalIterative::Saturation_t using setter and getter HierarchicalIterative::saturation.
Note
Right hand side and comparison types
Instead of \(f(\mathbf{q}) = 0\), other constraints can be defined. Several comparison types are available:
Equality: \(f(\mathbf{q}) = rhs\), where \(rhs\) is a parameterizable right hand side,
EqualToZero: \(f(\mathbf{q}) = 0\),
Superior: \(f(\mathbf{q}) > 0\)
Inferior: \(f(\mathbf{q}) < 0\) If several constraint are of type equality, the right hand side of the system of equations can be modified by methods HierarchicalIterative::rightHandSideFromInput, HierarchicalIterative::rightHandSide.
Note
Free variables
Some variables can be locked, or computed explicitely. In this case, the iterative resolution will only change the other variables called free variables.
See also
methods
freeVariables (const Indices_t& indices) and
freeVariables (const Indices_t& indices).
Member Typedef Documentation
typedef lineSearch::FixedSequence hpp::constraints::solver::HierarchicalIterative::DefaultLineSearch
typedef Eigen::RowBlockIndices hpp::constraints::solver::HierarchicalIterative::Indices_t
typedef boost::function<bool (vectorIn_t q, vectorOut_t qSat, Eigen::VectorXi& saturation)> hpp::constraints::solver::HierarchicalIterative::Saturation_t
This function checks which degrees of freedom are saturated.
Parameters
q a configuration,
Return values
qSat configuration after saturing values out of bounds
saturation vector: for each degree of freedom, saturation is set to
-1 if the lower bound is reached,
1 if the upper bound is reached,
0 otherwise.
Returns
true if and only if at least one degree of freedom has been saturated
typedef Eigen::JacobiSVD<matrix_t> hpp::constraints::solver::HierarchicalIterative::SVD_t protected
Member Enumeration Documentation
enum hpp::constraints::solver::HierarchicalIterative::Status
Enumerator
ERROR_INCREASED
MAX_ITERATION_REACHED
INFEASIBLE
SUCCESS
Constructor & Destructor Documentation
hpp::constraints::solver::HierarchicalIterative::HierarchicalIterative (const LiegroupSpacePtr_t & configSpace)
hpp::constraints::solver::HierarchicalIterative::HierarchicalIterative (const HierarchicalIterative & other)
virtual hpp::constraints::solver::HierarchicalIterative::~HierarchicalIterative () inline virtual
Member Function Documentation
ArrayXb hpp::constraints::solver::HierarchicalIterative::activeDerivativeParameters () const
Velocity parameters involved in the constraint resolution.
ArrayXb hpp::constraints::solver::HierarchicalIterative::activeParameters () const
Configuration parameters involved in the constraint resolution.
void hpp::constraints::solver::HierarchicalIterative::add (const DifferentiableFunctionPtr_t & f, const std::size_t & priority)
Add an implicit equality constraint.
Parameters
f differentiable function from the robot configuration space to a Lie group (See hpp::pinocchio::LiegroupSpace),
priority level of priority of the constraint: priority are in decreasing order: 0 is the highest priority level.
Constraint is defined by \(f (\mathbf{q}) = 0\).
void hpp::constraints::solver::HierarchicalIterative::add (const DifferentiableFunctionPtr_t & f, const std::size_t & priority, const ComparisonTypes_t & comp)
Add an implicit constraint.
Parameters
f differentiable function from the robot configuration space to a Lie group (See hpp::pinocchio::LiegroupSpace),
priority level of priority of the constraint: priority are in decreasing order: 0 is the highest priority level,
comp comparison type. See class documentation for details.
void hpp::constraints::solver::HierarchicalIterative::add (const ImplicitPtr_t & constraint, const std::size_t & priority)
Add an implicit constraint.
Parameters
constraint implicit constraint
priority level of priority of the constraint: priority are in decreasing order: 0 is the highest priority level,
virtual void hpp::constraints::solver::HierarchicalIterative::computeActiveRowsOfJ (std::size_t iStack) protected virtual
Compute which rows of the jacobian of stack_[iStack] are not zero, using the activeDerivativeParameters of the functions.
The result is stored in datas_[i].activeRowsOfJ
Reimplemented in hpp::constraints::solver::BySubstitution.
void hpp::constraints::solver::HierarchicalIterative::computeDescentDirection () const protected
Compute a SVD decomposition of each level and find the best descent direction at the first order.
Linearization of the system of equations rhs - v_{i} = J (q_i) (dq_{i+1} - q_{i}) q_{i+1} - q_{i} = J(q_i)^{+} (rhs - v_{i}) dq = J(q_i)^{+} (rhs - v_{i})
Warning
computeValue<true> must have been called first.
Referenced by hpp::constraints::solver::BySubstitution::impl_solve().
void hpp::constraints::solver::HierarchicalIterative::computeError () const
If lastIsOptional() is true, then the last level is ignored.
Warning
computeValue must have been called first.
Referenced by hpp::constraints::solver::BySubstitution::impl_solve().
void hpp::constraints::solver::HierarchicalIterative::computeSaturation (vectorIn_t arg) const
Referenced by hpp::constraints::solver::BySubstitution::impl_solve().
template<bool ComputeJac> void hpp::constraints::solver::HierarchicalIterative::computeValue (vectorIn_t arg) const
Compute the value of each level, and the jacobian if ComputeJac is true.
const LiegroupSpacePtr_t& hpp::constraints::solver::HierarchicalIterative::configSpace () const inline
Get configuration space on which constraints are defined.
const ImplicitConstraintSet& hpp::constraints::solver::HierarchicalIterative::constraints (const std::size_t priority) inline
Get set of constraints for a give priority level.
References Eigen::assert().
const NumericalConstraints_t& hpp::constraints::solver::HierarchicalIterative::constraints () const inline
Get constraints (implicit and explicit)
virtual bool hpp::constraints::solver::HierarchicalIterative::contains (const ImplicitPtr_t & numericalConstraint) const virtual
Check whether a numerical constraint has been added.
Parameters
numericalConstraint numerical constraint
Returns
true if numerical constraint is already in the solver whatever the passive dofs are.
Note
Comparison between constraints is performed by function names. This means that two constraints with the same function names are considered as equal.
Reimplemented in hpp::constraints::solver::BySubstitution.
bool hpp::constraints::solver::HierarchicalIterative::definesSubmanifoldOf (const HierarchicalIterative & solver) const
Inclusion of manifolds.
Parameters
solver another solver
This function returns true if the solution manifold of the solver given as input is a submanifold of the solution manifold of this solver. The function tests whether constraints of the input solver are also in this solver.
const size_type& hpp::constraints::solver::HierarchicalIterative::dimension () const inline
void hpp::constraints::solver::HierarchicalIterative::errorThreshold (const value_type & threshold) inline
Set error threshold.
value_type hpp::constraints::solver::HierarchicalIterative::errorThreshold () const inline
Get error threshold.
Referenced by hpp::constraints::solver::BySubstitution::errorThreshold().
void hpp::constraints::solver::HierarchicalIterative::expandDqSmall () const protected
void hpp::constraints::solver::HierarchicalIterative::freeVariables (const segments_t intervals) inline
Set free velocity variables.
The other variables will be left unchanged by the iterative resolution.
Parameters
intervals set of index intervals
void hpp::constraints::solver::HierarchicalIterative::freeVariables (const Indices_t & indices) inline
Set free velocity variables.
The other variables will be left unchanged by the iterative resolution.
const Indices_t& hpp::constraints::solver::HierarchicalIterative::freeVariables () const inline
Get free velocity variables.
void hpp::constraints::solver::HierarchicalIterative::getReducedJacobian (matrixOut_t J) const
virtual bool hpp::constraints::solver::HierarchicalIterative::getRightHandSide (const ImplicitPtr_t & constraint, vectorOut_t rhs) const virtual
Get right hand side of a constraints.
Reimplemented in hpp::constraints::solver::BySubstitution.
void hpp::constraints::solver::HierarchicalIterative::getValue (vectorOut_t v) const
value_type hpp::constraints::solver::HierarchicalIterative::inequalityThreshold () const inline
Get the inequality threshold.
void hpp::constraints::solver::HierarchicalIterative::inequalityThreshold (const value_type & it) inline
set the inequality threshold
virtual bool hpp::constraints::solver::HierarchicalIterative::integrate (vectorIn_t from, vectorIn_t velocity, vectorOut_t result) const virtual
Reimplemented in hpp::constraints::solver::BySubstitution.
Referenced by hpp::constraints::solver::BySubstitution::integrate().
bool hpp::constraints::solver::HierarchicalIterative::isConstraintSatisfied (const ImplicitPtr_t & constraint, vectorIn_t arg, vectorOut_t error, bool & constraintFound) const
Whether a constraint is satisfied for an input vector.
Parameters
constraint,the constraint in the solver,
arg the input vector
Return values
error the error of the constraint.
constraintFound whether the constraint belongs to the solver,
Returns
true if constraint belongs to solver and error is below the threshold, false otherwise.
bool hpp::constraints::solver::HierarchicalIterative::isSatisfied (vectorIn_t arg) const inline
Referenced by hpp::constraints::solver::BySubstitution::isSatisfied(), and hpp::constraints::solver::BySubstitution::oneStep().
void hpp::constraints::solver::HierarchicalIterative::lastIsOptional (bool optional) inline
bool hpp::constraints::solver::HierarchicalIterative::lastIsOptional () const inline
const vector_t& hpp::constraints::solver::HierarchicalIterative::lastStep () const inline
Accessor to the last step done.
References integrate().
void hpp::constraints::solver::HierarchicalIterative::maxIterations (size_type iterations) inline
Set maximal number of iterations.
size_type hpp::constraints::solver::HierarchicalIterative::maxIterations () const inline
Get maximal number of iterations in config projector.
virtual void hpp::constraints::solver::HierarchicalIterative::merge (const HierarchicalIterative & other) virtual
add constraints of another solver
Parameters
other other solver
Add constraints of other to this solver.
Note
right hand side of other is not copied.
std::size_t hpp::constraints::solver::HierarchicalIterative::numberStacks () const inline
virtual std::ostream& hpp::constraints::solver::HierarchicalIterative::print (std::ostream & os) const virtual
Reimplemented in hpp::constraints::solver::BySubstitution.
const size_type& hpp::constraints::solver::HierarchicalIterative::reducedDimension () const inline
Dimension of the problem after removing the rows of the jacobian which do not influence the error (only zeros along those lines).
value_type hpp::constraints::solver::HierarchicalIterative::residualError () const inline
Returns the squared norm of the error vector.
void hpp::constraints::solver::HierarchicalIterative::residualError (vectorOut_t error) const
Returns the error vector.
virtual bool hpp::constraints::solver::HierarchicalIterative::rightHandSide (const ImplicitPtr_t & constraint, vectorIn_t rhs) virtual
Set right hand side of a constraints.
Parameters
constraint the constraint,
rhs right hand side.
Note
Size of rhs should be equal to the total dimension of parameterizable constraints (type Equality) .
Reimplemented in hpp::constraints::solver::BySubstitution.
virtual void hpp::constraints::solver::HierarchicalIterative::rightHandSide (vectorIn_t rhs) virtual
Set the right hand side.
Parameters
rhs the right hand side
Note
Size of rhs should be equal to the total dimension of parameterizable constraints (type Equality).
Reimplemented in hpp::constraints::solver::BySubstitution.
vector_t hpp::constraints::solver::HierarchicalIterative::rightHandSide () const
Get the right hand side.
Returns
the right hand side
Note
size of result is equal to total dimension of parameterizable constraints (type Equality).
void hpp::constraints::solver::HierarchicalIterative::rightHandSideAt (const value_type & s)
Set the right hand side at a given parameter.
Parameters
s parameter passed to Implicit::rightHandSideAt
vector_t hpp::constraints::solver::HierarchicalIterative::rightHandSideFromConfig (ConfigurationIn_t config)
Compute right hand side of equality constraints from a configuration.
Parameters
config a configuration.
for each constraint of type Equality, set right hand side as \(rhs = f(\mathbf{q})\).
Note
Only parameterizable constraints (type Equality) are set
virtual bool hpp::constraints::solver::HierarchicalIterative::rightHandSideFromConfig (const ImplicitPtr_t & constraint, ConfigurationIn_t config) virtual
Compute right hand side of a constraint from a configuration.
Parameters
constraint the constraint,
config a configuration.
Set right hand side as \(rhs = f(\mathbf{q})\).
Note
Only parameterizable constraints (type Equality) are set
Reimplemented in hpp::constraints::solver::BySubstitution.
size_type hpp::constraints::solver::HierarchicalIterative::rightHandSideSize () const
Get size of the right hand side.
Returns
sum of dimensions of parameterizable constraints (type Equality)
void hpp::constraints::solver::HierarchicalIterative::saturate (vectorOut_t arg) const protected
void hpp::constraints::solver::HierarchicalIterative::saturation (const Saturation_t & saturate) inline
Set the saturation function.
const Saturation_t& hpp::constraints::solver::HierarchicalIterative::saturation () const inline
Get the saturation function.
const value_type& hpp::constraints::solver::HierarchicalIterative::sigma () const inline
Returns the lowest singular value.
If the jacobian has maximum rank r, then it corresponds to r-th greatest singular value. This value is zero when the jacobian is singular.
template<typename LineSearchType > solver::HierarchicalIterative::Status hpp::constraints::solver::HierarchicalIterative::solve (vectorOut_t arg, LineSearchType lineSearch) const inline
References Eigen::assert().
template<typename LineSearchType > Status hpp::constraints::solver::HierarchicalIterative::solve (vectorOut_t arg, LineSearchType ls = LineSearchType()) const
Solve the system of non linear equations.
Parameters
arg initial guess,
ls line search method used.
Use Newton Rhapson like iterative method until the error is below the threshold, or until the maximal number of iterations has been reached.
Note
Explicit constraints are expressed in their implicit form: \(\mathbf{q}_2 = f (\mathbf{q}_1)\) is replaced by \(\mathbf{q}_2 - f (\mathbf{q}_1) = 0\), where \(\mathbf{q}_1\) and \(\mathbf{q}_2\) are vectors composed of the components of \(\mathbf{q}\).
Status hpp::constraints::solver::HierarchicalIterative::solve (vectorOut_t arg) const inline
Solve the system of non linear equations.
Parameters
arg initial guess,
Use Newton Rhapson like iterative method until the error is below the threshold, or until the maximal number of iterations has been reached. Use the default line search method (fixed sequence of \(\alpha_i\)).
Note
Explicit constraints are expressed in their implicit form: \(\mathbf{q}_2 = f (\mathbf{q}_1)\) is replaced by \(\mathbf{q}_2 - f (\mathbf{q}_1) = 0\), where \(\mathbf{q}_1\) and \(\mathbf{q}_2\) are vectors composed of the components of \(\mathbf{q}\).
value_type hpp::constraints::solver::HierarchicalIterative::squaredErrorThreshold () const inline
Get error threshold.
void hpp::constraints::solver::HierarchicalIterative::update () protected
Allocate datas and update sizes of the problem Should be called whenever the stack is modified.
Friends And Related Function Documentation
friend struct lineSearch::Backtracking friend
Member Data Documentation
LiegroupSpacePtr_t hpp::constraints::solver::HierarchicalIterative::configSpace_ protected
NumericalConstraints_t hpp::constraints::solver::HierarchicalIterative::constraints_ protected
Members moved from core::ConfigProjector.
std::vector<Data> hpp::constraints::solver::HierarchicalIterative::datas_ mutable protected
Referenced by hpp::constraints::solver::BySubstitution::impl_solve().
size_type hpp::constraints::solver::HierarchicalIterative::dimension_ protected
vector_t hpp::constraints::solver::HierarchicalIterative::dq_ mutable protected
Referenced by hpp::constraints::solver::BySubstitution::impl_solve().
vector_t hpp::constraints::solver::HierarchicalIterative::dqSmall_ mutable protected
Indices_t hpp::constraints::solver::HierarchicalIterative::freeVariables_ protected
Unknown of the set of implicit constraints.
value_type hpp::constraints::solver::HierarchicalIterative::inequalityThreshold_ protected
std::map<DifferentiableFunctionPtr_t, size_type> hpp::constraints::solver::HierarchicalIterative::iq_ protected
Value rank of constraint in its priority level.
std::map<DifferentiableFunctionPtr_t, size_type> hpp::constraints::solver::HierarchicalIterative::iv_ protected
Derivative rank of constraint in its priority level.
bool hpp::constraints::solver::HierarchicalIterative::lastIsOptional_ protected
Referenced by hpp::constraints::solver::BySubstitution::impl_solve().
size_type hpp::constraints::solver::HierarchicalIterative::maxIterations_ protected
Referenced by hpp::constraints::solver::BySubstitution::impl_solve().
vector_t hpp::constraints::solver::HierarchicalIterative::OM_ mutable protected
vector_t hpp::constraints::solver::HierarchicalIterative::OP_ mutable protected
std::map<DifferentiableFunctionPtr_t, std::size_t> hpp::constraints::solver::HierarchicalIterative::priority_ protected
Priority level of constraint.
Configuration_t hpp::constraints::solver::HierarchicalIterative::qSat_ mutable protected
size_type hpp::constraints::solver::HierarchicalIterative::reducedDimension_ protected
Referenced by hpp::constraints::solver::BySubstitution::impl_solve().
matrix_t hpp::constraints::solver::HierarchicalIterative::reducedJ_ mutable protected
Eigen::VectorXi hpp::constraints::solver::HierarchicalIterative::reducedSaturation_ mutable protected
Saturation_t hpp::constraints::solver::HierarchicalIterative::saturate_ protected
Eigen::VectorXi hpp::constraints::solver::HierarchicalIterative::saturation_ mutable protected
value_type hpp::constraints::solver::HierarchicalIterative::sigma_ mutable protected
The smallest non-zero singular value.
value_type hpp::constraints::solver::HierarchicalIterative::squaredErrorThreshold_ protected
Referenced by hpp::constraints::solver::BySubstitution::impl_solve().
value_type hpp::constraints::solver::HierarchicalIterative::squaredNorm_ mutable protected
Referenced by hpp::constraints::solver::BySubstitution::impl_solve().
std::vector<ImplicitConstraintSet> hpp::constraints::solver::HierarchicalIterative::stacks_ protected
mutable ::hpp::statistics::SuccessStatistics hpp::constraints::solver::HierarchicalIterative::statistics_ protected
SVD_t hpp::constraints::solver::HierarchicalIterative::svd_ mutable protected
ArrayXb hpp::constraints::solver::HierarchicalIterative::tmpSat_ mutable protected