hpp::constraints::ImplicitConstraintSet Class Reference
hpp::constraints::ImplicitConstraintSet Class Reference
Constraints
Set of implicit constraints.
#include <hpp/constraints/implicit-constraint-set.hh>
Public Types
typedef std::vector< ImplicitPtr_t > Implicits_t
Public Member Functions
virtual ~ImplicitConstraintSet () throw ()
std::ostream & print (std::ostream &os) const
ImplicitConstraintSet (const std::string &name)
Constructor.
ImplicitConstraintSet ()
ImplicitConstraintSet (const ImplicitConstraintSet &o)
Function stack management
void add (const ImplicitPtr_t &constraint)
const std::vector< std::size_t > & inequalityIndices () const
Get indices of constraint coordinates that are inequality.
const Eigen::RowBlockIndices & equalityIndices () const
Get indices of constraint coordinates that are equality.
const Implicits_t & constraints () const
Get constraints.
void merge (const ImplicitConstraintSetPtr_t &other)
The output columns selection of other is not taken into account.
Public Member Functions inherited from hpp::constraints::Implicit
bool operator== (const Implicit &other) const
Operator equality.
virtual ImplicitPtr_t copy () const
Copy object and return shared pointer to copy.
virtual ~Implicit ()
DifferentiableFunction & function () const
Return a reference to function \(h\).
const DifferentiableFunctionPtr_t & functionPtr () const
Return a reference to function \(h\).
void rightHandSideFromConfig (ConfigurationIn_t config)
Set the right hand side from a configuration.
void rightHandSide (vectorIn_t rhs)
Set the right hand side of the equation.
vectorIn_t rightHandSide () const
Return the right hand side of the equation.
size_type rhsSize () const HPP_CONSTRAINTS_DEPRECATED
Return the dimension of the left hand side function tangent output space.
size_type parameterSize () const
Get size of parameter defining the right hand side of the constraint.
size_type rightHandSideSize () const
Get size of right hand side of the constraint.
const ComparisonTypes_t & comparisonType () const
Return the ComparisonType.
void comparisonType (const ComparisonTypes_t &comp)
Set the comparison type.
bool constantRightHandSide () const HPP_CONSTRAINTS_DEPRECATED
Whether right hand side is constant.
vectorOut_t rightHandSide ()
Return a modifiable reference to right hand side of equation.
vectorOut_t nonConstRightHandSide () HPP_CONSTRAINTS_DEPRECATED
Return a modifiable reference to right hand side of equation.
void rightHandSideFunction (const DifferentiableFunctionPtr_t &rhsF)
Set time-varying right hand side.
const DifferentiableFunctionPtr_t & rightHandSideFunction () const
Get time-varying right hand side.
vectorIn_t rightHandSideAt (const value_type &s)
Evaluate and set right hand side at given time.
Static Public Member Functions
static ImplicitConstraintSetPtr_t create (const std::string &name)
Return a shared pointer to a new instance.
Static Public Member Functions inherited from hpp::constraints::Implicit
static ImplicitPtr_t create (const DifferentiableFunctionPtr_t &function)
Create a shared pointer to a new instance.
static ImplicitPtr_t create (const DifferentiableFunctionPtr_t &function, ComparisonTypes_t comp)
Create a shared pointer to a new instance.
static ImplicitPtr_t create (const DifferentiableFunctionPtr_t &function, ComparisonTypes_t comp, vectorIn_t rhs)
Create a shared pointer to a new instance.
static ImplicitPtr_t createCopy (const ImplicitPtr_t &other)
Create a copy and return shared pointer.
Additional Inherited Members
Protected Member Functions inherited from hpp::constraints::Implicit
Implicit (const DifferentiableFunctionPtr_t &function, ComparisonTypes_t comp)
Constructor.
Implicit (const DifferentiableFunctionPtr_t &function, ComparisonTypes_t comp, vectorIn_t rhs)
Constructor.
Implicit (const Implicit &other)
Copy constructor.
virtual bool isEqual (const Implicit &other, bool swapAndTest) const
Test equality with other instance.
void init (const ImplicitWkPtr_t &weak)
Detailed Description
Set of implicit constraints.
This class also handles selection of cols of the output matrix.
Member Typedef Documentation
typedef std::vector<ImplicitPtr_t> hpp::constraints::ImplicitConstraintSet::Implicits_t
Constructor & Destructor Documentation
virtual hpp::constraints::ImplicitConstraintSet::~ImplicitConstraintSet () throw () inline virtual
hpp::constraints::ImplicitConstraintSet::ImplicitConstraintSet (const std::string & name) inline
Constructor.
Parameters
name the name of the constraints,
hpp::constraints::ImplicitConstraintSet::ImplicitConstraintSet () inline
hpp::constraints::ImplicitConstraintSet::ImplicitConstraintSet (const ImplicitConstraintSet & o) inline
References constraints().
Member Function Documentation
void hpp::constraints::ImplicitConstraintSet::add (const ImplicitPtr_t & constraint) inline
References Eigen::assert(), hpp::constraints::Equality, hpp::constraints::Inferior, and hpp::constraints::Superior.
const Implicits_t& hpp::constraints::ImplicitConstraintSet::constraints () const inline
Get constraints.
Referenced by ImplicitConstraintSet().
static ImplicitConstraintSetPtr_t hpp::constraints::ImplicitConstraintSet::create (const std::string & name) inline static
Return a shared pointer to a new instance.
Parameters
name the name of the constraints,
const Eigen::RowBlockIndices& hpp::constraints::ImplicitConstraintSet::equalityIndices () const inline
Get indices of constraint coordinates that are equality.
const std::vector<std::size_t>& hpp::constraints::ImplicitConstraintSet::inequalityIndices () const inline
Get indices of constraint coordinates that are inequality.
void hpp::constraints::ImplicitConstraintSet::merge (const ImplicitConstraintSetPtr_t & other) inline
The output columns selection of other is not taken into account.
std::ostream& hpp::constraints::ImplicitConstraintSet::print (std::ostream & os) const inline