Eigen::MatrixBlockView< _ArgType, _Rows, _Cols, _allRows, _allCols >::block_iterator Struct Reference
Eigen::MatrixBlockView< _ArgType, _Rows, _Cols, _allRows, _allCols >::block_iterator Struct Reference
#include <hpp/constraints/matrix-view.hh>
Public Member Functions
block_iterator (const MatrixBlockView &v)
size_type ro () const
Row in the Output matrix
size_type co () const
Col in the Output matrix
size_type ri () const
Row in the Input matrix
size_type ci () const
Col in the Input matrix
size_type rs () const
number of RowS
size_type cs () const
number of ColS
block_iterator & operator++ ()
block_iterator operator++ (int)
bool valid () const
Public Attributes
const MatrixBlockView & view
size_type row
size_type col
internal::variable_if_dynamic< size_type,(_allRows?0:Dynamic) > _ro
internal::variable_if_dynamic< size_type,(_allCols?0:Dynamic) > _co
Constructor & Destructor Documentation
template<typename _ArgType , int _Rows = _ArgType::RowsAtCompileTime, int _Cols = _ArgType::ColsAtCompileTime, bool _allRows = false, bool _allCols = false> Eigen::MatrixBlockView< _ArgType, _Rows, _Cols, _allRows, _allCols >::block_iterator::block_iterator (const MatrixBlockView & v) inline
Member Function Documentation
template<typename _ArgType , int _Rows = _ArgType::RowsAtCompileTime, int _Cols = _ArgType::ColsAtCompileTime, bool _allRows = false, bool _allCols = false> size_type Eigen::MatrixBlockView< _ArgType, _Rows, _Cols, _allRows, _allCols >::block_iterator::ci () const inline
Col in the Input matrix
References Eigen::MatrixBlockView< _ArgType, _Rows, _Cols, _allRows, _allCols >::m_cols, Eigen::MatrixBlockView< _ArgType, _Rows, _Cols, _allRows, _allCols >::m_nbCols, and Eigen::internal::get_if< If >::run().
Referenced by Eigen::MatrixBlockView< _ArgType, _Rows, _Cols, _allRows, _allCols >::_block().
template<typename _ArgType , int _Rows = _ArgType::RowsAtCompileTime, int _Cols = _ArgType::ColsAtCompileTime, bool _allRows = false, bool _allCols = false> size_type Eigen::MatrixBlockView< _ArgType, _Rows, _Cols, _allRows, _allCols >::block_iterator::co () const inline
Col in the Output matrix
template<typename _ArgType , int _Rows = _ArgType::RowsAtCompileTime, int _Cols = _ArgType::ColsAtCompileTime, bool _allRows = false, bool _allCols = false> size_type Eigen::MatrixBlockView< _ArgType, _Rows, _Cols, _allRows, _allCols >::block_iterator::cs () const inline
number of ColS
References Eigen::MatrixBlockView< _ArgType, _Rows, _Cols, _allRows, _allCols >::m_cols, Eigen::MatrixBlockView< _ArgType, _Rows, _Cols, _allRows, _allCols >::m_nbCols, and Eigen::internal::get_if< If >::run().
Referenced by Eigen::MatrixBlockView< _ArgType, _Rows, _Cols, _allRows, _allCols >::_block().
template<typename _ArgType , int _Rows = _ArgType::RowsAtCompileTime, int _Cols = _ArgType::ColsAtCompileTime, bool _allRows = false, bool _allCols = false> block_iterator& Eigen::MatrixBlockView< _ArgType, _Rows, _Cols, _allRows, _allCols >::block_iterator::operator++ () inline
References Eigen::MatrixBlockView< _ArgType, _Rows, _Cols, _allRows, _allCols >::m_rows.
template<typename _ArgType , int _Rows = _ArgType::RowsAtCompileTime, int _Cols = _ArgType::ColsAtCompileTime, bool _allRows = false, bool _allCols = false> block_iterator Eigen::MatrixBlockView< _ArgType, _Rows, _Cols, _allRows, _allCols >::block_iterator::operator++ (int) inline
References Eigen::MatrixBlockView< _ArgType, _Rows, _Cols, _allRows, _allCols >::block_iterator::operator++().
Referenced by Eigen::MatrixBlockView< _ArgType, _Rows, _Cols, _allRows, _allCols >::block_iterator::operator++().
template<typename _ArgType , int _Rows = _ArgType::RowsAtCompileTime, int _Cols = _ArgType::ColsAtCompileTime, bool _allRows = false, bool _allCols = false> size_type Eigen::MatrixBlockView< _ArgType, _Rows, _Cols, _allRows, _allCols >::block_iterator::ri () const inline
Row in the Input matrix
References Eigen::MatrixBlockView< _ArgType, _Rows, _Cols, _allRows, _allCols >::m_nbRows, Eigen::MatrixBlockView< _ArgType, _Rows, _Cols, _allRows, _allCols >::m_rows, and Eigen::internal::get_if< If >::run().
Referenced by Eigen::MatrixBlockView< _ArgType, _Rows, _Cols, _allRows, _allCols >::_block().
template<typename _ArgType , int _Rows = _ArgType::RowsAtCompileTime, int _Cols = _ArgType::ColsAtCompileTime, bool _allRows = false, bool _allCols = false> size_type Eigen::MatrixBlockView< _ArgType, _Rows, _Cols, _allRows, _allCols >::block_iterator::ro () const inline
Row in the Output matrix
template<typename _ArgType , int _Rows = _ArgType::RowsAtCompileTime, int _Cols = _ArgType::ColsAtCompileTime, bool _allRows = false, bool _allCols = false> size_type Eigen::MatrixBlockView< _ArgType, _Rows, _Cols, _allRows, _allCols >::block_iterator::rs () const inline
number of RowS
References Eigen::MatrixBlockView< _ArgType, _Rows, _Cols, _allRows, _allCols >::m_nbRows, Eigen::MatrixBlockView< _ArgType, _Rows, _Cols, _allRows, _allCols >::m_rows, and Eigen::internal::get_if< If >::run().
Referenced by Eigen::MatrixBlockView< _ArgType, _Rows, _Cols, _allRows, _allCols >::_block().
template<typename _ArgType , int _Rows = _ArgType::RowsAtCompileTime, int _Cols = _ArgType::ColsAtCompileTime, bool _allRows = false, bool _allCols = false> bool Eigen::MatrixBlockView< _ArgType, _Rows, _Cols, _allRows, _allCols >::block_iterator::valid () const inline
References Eigen::MatrixBlockView< _ArgType, _Rows, _Cols, _allRows, _allCols >::m_cols, and Eigen::MatrixBlockView< _ArgType, _Rows, _Cols, _allRows, _allCols >::m_rows.
Referenced by Eigen::MatrixBlockView< _ArgType, _Rows, _Cols, _allRows, _allCols >::isZero(), Eigen::internal::eval_matrix_block_view_to< Src, MatrixBlockView< _ArgType, _Rows, _Cols, _allRows, _allCols > >::run(), Eigen::internal::eval_matrix_block_view_to< MatrixBlockView< _ArgType, _Rows, _Cols, _allRows, _allCols >, Dst >::run(), and Eigen::internal::eval_matrix_block_view_to< MatrixBlockView< _ArgType, _Rows, _Cols, _allRows, _allCols >, MatrixBlockView< _ArgType2, _Rows2, _Cols2, _allRows2, _allCols2 > >::run().
Member Data Documentation
template<typename _ArgType , int _Rows = _ArgType::RowsAtCompileTime, int _Cols = _ArgType::ColsAtCompileTime, bool _allRows = false, bool _allCols = false> internal::variable_if_dynamic<size_type, (_allCols ? 0 : Dynamic) > Eigen::MatrixBlockView< _ArgType, _Rows, _Cols, _allRows, _allCols >::block_iterator::_co
template<typename _ArgType , int _Rows = _ArgType::RowsAtCompileTime, int _Cols = _ArgType::ColsAtCompileTime, bool _allRows = false, bool _allCols = false> internal::variable_if_dynamic<size_type, (_allRows ? 0 : Dynamic) > Eigen::MatrixBlockView< _ArgType, _Rows, _Cols, _allRows, _allCols >::block_iterator::_ro
template<typename _ArgType , int _Rows = _ArgType::RowsAtCompileTime, int _Cols = _ArgType::ColsAtCompileTime, bool _allRows = false, bool _allCols = false> size_type Eigen::MatrixBlockView< _ArgType, _Rows, _Cols, _allRows, _allCols >::block_iterator::col
template<typename _ArgType , int _Rows = _ArgType::RowsAtCompileTime, int _Cols = _ArgType::ColsAtCompileTime, bool _allRows = false, bool _allCols = false> size_type Eigen::MatrixBlockView< _ArgType, _Rows, _Cols, _allRows, _allCols >::block_iterator::row
template<typename _ArgType , int _Rows = _ArgType::RowsAtCompileTime, int _Cols = _ArgType::ColsAtCompileTime, bool _allRows = false, bool _allCols = false> const MatrixBlockView& Eigen::MatrixBlockView< _ArgType, _Rows, _Cols, _allRows, _allCols >::block_iterator::view