Eigen Namespace Reference
Eigen Namespace Reference
Copyright (c) 2014 CNRS Authors: Florent Lamiraux.
Namespaces
internal
Classes
struct BlockIndex
List of integer intervals.
class MatrixBlocks
Collection of indices of matrix blocks.
class MatrixBlocksBase
class MatrixBlocksRef
class MatrixBlockView
A view of an Eigen matrix.
Typedefs
typedef const Rhs_t::template block_t< typename Rhs_t::ArgType >::type BlockRhs
typedef CwiseBinaryOp< BinaryOp, BlockLhs, BlockRhs > BlockCwiseBOp
typedef Eigen::MatrixBlocks< false, true > RowBlockIndices
typedef Eigen::MatrixBlocks< true, false > ColBlockIndices
Functions
HPP_EIGEN_SPECIALIZE_CwiseBinaryOpImpl (HPP_EIGEN_LHS_TPL, HPP_EIGEN_LHS_TYPE, HPP_EIGEN_RHS_TPL, HPP_EIGEN_RHS_TYPE) HPP_EIGEN_DEFINE_CwiseBinaryOpImpl_evalTo(HPP_EIGEN_LHS_TPL
for (typename Rhs_t::block_iterator block(d.rhs());block.valid();++block)
for (typename Lhs_t::block_iterator block(d.lhs());block.valid();++block)
assert (d.lhs()._blocks()==d.rhs()._blocks())
Lhs_t::block_iterator lblock (d.lhs())
Rhs_t::block_iterator rblock (d.rhs())
while (lblock.valid())
assert (!lblock.valid()&&!rblock.valid())
template<typename Derived >
std::ostream & operator<< (std::ostream &os, const MatrixBlocksBase< Derived > &mbi)
Variables
HPP_EIGEN_LHS_TYPE
HPP_EIGEN_RHS_TPL
HPP_EIGEN_RHS_TYPE
const Derived & d = derived()
Detailed Description
Copyright (c) 2014 CNRS Authors: Florent Lamiraux.
Typedef Documentation
typedef CwiseBinaryOp< BinaryOp, BlockLhs, BlockRhs > Eigen::BlockCwiseBOp
typedef const Rhs_t::template block_t< typename Rhs_t::ArgType >::type Eigen::BlockRhs
Function Documentation
Eigen::assert (d. lhs)._blocks(= =d.rhs()._blocks())
Referenced by hpp::constraints::ImplicitConstraintSet::add(), hpp::constraints::DifferentiableFunctionSet::add(), hpp::constraints::AffineFunction::AffineFunction(), hpp::constraints::ConvexShapeData::alignedPositionInJoint(), Eigen::MatrixBlockView< _ArgType, _Rows, _Cols, _allRows, _allCols >::coeff(), Eigen::MatrixBlockView< _ArgType, _Rows, _Cols, _allRows, _allCols >::coeffRef(), hpp::constraints::MatrixOfExpressions< eigen::vector3_t, JacobianMatrix >::computePseudoInverseJacobian(), hpp::constraints::solver::HierarchicalIterative::constraints(), hpp::constraints::SymbolicFunction< Expression >::create(), hpp::constraints::ConvexShape::distanceLocal(), hpp::constraints::JointFrame::impl_jacobian(), hpp::constraints::MatrixOfExpressions< eigen::vector3_t, JacobianMatrix >::impl_jacobian(), hpp::constraints::solver::BySubstitution::impl_solve(), hpp::constraints::MatrixOfExpressions< eigen::vector3_t, JacobianMatrix >::impl_value(), hpp::constraints::ConvexShape::isInsideLocal(), hpp::constraints::solver::BySubstitution::isSatisfied(), hpp::constraints::DifferentiableFunction::jacobian(), hpp::constraints::MatrixOfExpressions< eigen::vector3_t, JacobianMatrix >::jacobianTimes(), hpp::constraints::MatrixOfExpressions< eigen::vector3_t, JacobianMatrix >::jacobianTransposeTimes(), hpp::constraints::GenericTransformation< _Options >::joint1(), hpp::constraints::GenericTransformation< _Options >::joint2(), hpp::constraints::JointFrame::JointFrame(), Eigen::MatrixBlocksBase< MatrixBlocks< _allRows, _allCols > >::keepCols(), Eigen::MatrixBlocksBase< MatrixBlocks< _allRows, _allCols > >::keepRows(), hpp::constraints::linePlaneIntersection(), hpp::constraints::logSE3(), hpp::constraints::logSO3(), Eigen::MatrixBlocks< false, false >::MatrixBlocks(), hpp::constraints::matrixToQuat(), hpp::constraints::DifferentiableFunction::operator()(), hpp::constraints::ConvexShape::planeXaxis(), hpp::constraints::ConvexShape::planeYaxis(), hpp::constraints::PointInJoint::PointInJoint(), Eigen::internal::eval_matrix_block_view_to< MatrixBlockView< _ArgType, _Rows, _Cols, _allRows, _allCols >, MatrixBlockView< _ArgType2, _Rows2, _Cols2, _allRows2, _allCols2 > >::run(), hpp::constraints::se3ToConfig(), hpp::constraints::solver::HierarchicalIterative::solve(), hpp::constraints::DifferentiableFunction::value(), and while().
Eigen::assert (!lblock. valid)&&!rblock.valid()
Eigen::for (typename Rhs_t::block_iterator block(d.rhs());block.valid();++ block)
Eigen::for (typename Lhs_t::block_iterator block(d.lhs());block.valid();++ block)
References HPP_EIGEN_LHS_TPL, HPP_EIGEN_LHS_TYPE, HPP_EIGEN_RHS_TPL, HPP_EIGEN_RHS_TYPE, and HPP_EIGEN_SPECIALIZE_ASSIGN_SELECTOR.
Eigen::HPP_EIGEN_SPECIALIZE_CwiseBinaryOpImpl (HPP_EIGEN_LHS_TPL , HPP_EIGEN_LHS_TYPE , HPP_EIGEN_RHS_TPL , HPP_EIGEN_RHS_TYPE)
Lhs_t::block_iterator Eigen::lblock (d. lhs())
Referenced by while().
Rhs_t::block_iterator Eigen::rblock (d. rhs())
Referenced by while().
Eigen::while (lblock. valid())
References assert(), HPP_EIGEN_SPECIALIZE_ASSIGN_SELECTOR, lblock(), and rblock().
Variable Documentation
const Derived & Eigen::d = derived()
Referenced by hpp::constraints::solver::lineSearch::Backtracking::computeLocalSlope(), and hpp::constraints::ConvexShape::distanceLocal().
Eigen::HPP_EIGEN_LHS_TYPE
Referenced by for().
Eigen::HPP_EIGEN_RHS_TPL
Referenced by for().
Eigen::HPP_EIGEN_RHS_TYPE
Initial value:
{
        typedef const Block<Lhs_t> BlockLhs
Referenced by for().