hpp::core::configurationShooter::Gaussian Class Reference
hpp::core::configurationShooter::Gaussian Class Reference
Configuration Sampling
Sample configuration using a gaussian distribution around a configuration.
#include <hpp/core/configuration-shooter/gaussian.hh>
Public Member Functions
virtual void shoot (Configuration_t &q) const
Shoot a random configuration.
void center (ConfigurationIn_t c)
const Configuration_t & center () const
void sigma (const value_type &factor)
Set the standard deviation proportional to a default value.
void sigmas (vectorIn_t s)
const vector_t & sigmas () const
Public Member Functions inherited from hpp::core::ConfigurationShooter
virtual ConfigurationPtr_t shoot () const
Shoot a random configuration.
virtual ~ConfigurationShooter ()
Static Public Member Functions
static GaussianPtr_t create (const DevicePtr_t &robot)
Protected Member Functions
Gaussian (const DevicePtr_t &robot)
Create a gaussian distribution centered in the robot current configuration.
void init (const GaussianPtr_t &self)
Protected Member Functions inherited from hpp::core::ConfigurationShooter
ConfigurationShooter ()
void init (const ConfigurationShooterWkPtr_t &weak)
Store weak pointer to itself.
Detailed Description
Sample configuration using a gaussian distribution around a configuration.
Constructor & Destructor Documentation
hpp::core::configurationShooter::Gaussian::Gaussian (const DevicePtr_t & robot) inline protected
Create a gaussian distribution centered in the robot current configuration.
The standard deviation is computed as sigma(0.25)
See also
Gaussian::sigma
Member Function Documentation
void hpp::core::configurationShooter::Gaussian::center (ConfigurationIn_t c) inline
const Configuration_t& hpp::core::configurationShooter::Gaussian::center () const inline
static GaussianPtr_t hpp::core::configurationShooter::Gaussian::create (const DevicePtr_t & robot) inline static
References init().
void hpp::core::configurationShooter::Gaussian::init (const GaussianPtr_t & self) inline protected
References hpp::core::ConfigurationShooter::init().
Referenced by create().
virtual void hpp::core::configurationShooter::Gaussian::shoot (Configuration_t & q) const virtual
Shoot a random configuration.
Parameters
q the configuration (resized if necessary).
Implements hpp::core::ConfigurationShooter.
void hpp::core::configurationShooter::Gaussian::sigma (const value_type & factor)
Set the standard deviation proportional to a default value.
The default value is:
for vector spaces, the difference between the upper and the lower bounds,
for SO(n), \(\frac{2\pi}{\sqrt{2n-3}}\) on each of the \(2n-3 \) dimensions,
SE(n) is treated as \(R^n \times SO(n) \).
void hpp::core::configurationShooter::Gaussian::sigmas (vectorIn_t s) inline
References assert().
const vector_t& hpp::core::configurationShooter::Gaussian::sigmas () const inline