hpp::core::KinodynamicPath Class Reference
hpp::core::KinodynamicPath Class Reference
Path
Kino-dynamic straight path.
#include <hpp/core/kinodynamic-path.hh>
Public Types
typedef StraightPath parent_t
Public Types inherited from hpp::core::StraightPath
typedef Path parent_t
Public Member Functions
virtual ~KinodynamicPath () throw ()
Destructor.
virtual PathPtr_t copy () const
Return a shared pointer to this.
virtual PathPtr_t copy (const ConstraintSetPtr_t &constraints) const
Return a shared pointer to a copy of this and set constraints.
virtual PathPtr_t impl_extract (const interval_t &paramInterval) const throw (projection_error)
Extraction/Reversion of a sub-path.
vector_t getT0 ()
vector_t getT1 ()
vector_t getT2 ()
vector_t getTv ()
vector_t getA1 ()
Public Member Functions inherited from hpp::core::StraightPath
virtual ~StraightPath () throw ()
Destructor.
void initialConfig (ConfigurationIn_t initial)
Modify initial configuration.
void endConfig (ConfigurationIn_t end)
Modify end configuration.
DevicePtr_t device () const
Return the internal robot.
Configuration_t initial () const
Get the initial configuration.
Configuration_t end () const
Get the final configuration.
Public Member Functions inherited from hpp::core::Path
virtual ~Path () throw ()
Destructor.
template<class T >
boost::shared_ptr< T > as (void)
Static cast into a derived type.
template<class T >
boost::shared_ptr< const T > as (void) const
Static cast into a derived type.
PathPtr_t extract (const interval_t &subInterval) const throw (projection_error)
PathPtr_t extract (const value_type &tmin, const value_type &tmax) const throw (projection_error)
virtual PathPtr_t reverse () const
Reversion of a path.
Configuration_t operator() (const value_type &time) const HPP_CORE_DEPRECATED
Configuration_t operator() (const value_type &time, bool &success) const
bool operator() (ConfigurationOut_t result, const value_type &time) const throw ()
Configuration_t eval (const value_type &time, bool &success) const
bool eval (ConfigurationOut_t result, const value_type &time) const throw ()
bool at (const value_type &time, ConfigurationOut_t result) const
Get the configuration at a parameter without applying the constraints.
void derivative (vectorOut_t result, const value_type &time, size_type order) const
Get derivative with respect to parameter at given parameter.
void velocityBound (vectorOut_t result, const value_type &t0, const value_type &t1) const
Get an upper bound of the velocity on a sub-interval.
size_type outputSize () const
Get size of configuration space.
size_type outputDerivativeSize () const
Get size of velocity.
const interval_t & timeRange () const
Get interval of definition.
virtual value_type length () const
Get length of definition interval.
const ConstraintSetPtr_t & constraints () const
Get constraints the path is subject to.
const interval_t & paramRange () const
Get interval of parameters.
void timeParameterization (const TimeParameterizationPtr_t &tp, const interval_t &tr)
Set the time parameterization function.
Static Public Member Functions
static KinodynamicPathPtr_t create (const DevicePtr_t &device, ConfigurationIn_t init, ConfigurationIn_t end, value_type length, ConfigurationIn_t a1, ConfigurationIn_t t0, ConfigurationIn_t t1, ConfigurationIn_t tv, ConfigurationIn_t t2, ConfigurationIn_t vLim)
Create instance and return shared pointer.
static KinodynamicPathPtr_t create (const DevicePtr_t &device, ConfigurationIn_t init, ConfigurationIn_t end, value_type length, ConfigurationIn_t a1, ConfigurationIn_t t0, ConfigurationIn_t t1, ConfigurationIn_t tv, ConfigurationIn_t t2, ConfigurationIn_t vLim, ConstraintSetPtr_t constraints)
Create instance and return shared pointer.
static KinodynamicPathPtr_t createCopy (const KinodynamicPathPtr_t &path)
Create copy and return shared pointer.
static KinodynamicPathPtr_t createCopy (const KinodynamicPathPtr_t &path, const ConstraintSetPtr_t &constraints)
Create copy and return shared pointer.
Static Public Member Functions inherited from hpp::core::StraightPath
static StraightPathPtr_t create (const DevicePtr_t &device, ConfigurationIn_t init, ConfigurationIn_t end, value_type length)
Create instance and return shared pointer.
static StraightPathPtr_t create (const DevicePtr_t &device, ConfigurationIn_t init, ConfigurationIn_t end, interval_t interval)
Create instance and return shared pointer.
static StraightPathPtr_t create (const DevicePtr_t &device, ConfigurationIn_t init, ConfigurationIn_t end, value_type length, ConstraintSetPtr_t constraints)
Create instance and return shared pointer.
static StraightPathPtr_t create (const DevicePtr_t &device, ConfigurationIn_t init, ConfigurationIn_t end, interval_t interval, ConstraintSetPtr_t constraints)
Create instance and return shared pointer.
static StraightPathPtr_t createCopy (const StraightPathPtr_t &path)
Create copy and return shared pointer.
static StraightPathPtr_t createCopy (const StraightPathPtr_t &path, const ConstraintSetPtr_t &constraints)
Create copy and return shared pointer.
Protected Member Functions
virtual std::ostream & print (std::ostream &os) const
Print path in a stream.
KinodynamicPath (const DevicePtr_t &robot, ConfigurationIn_t init, ConfigurationIn_t end, value_type length, ConfigurationIn_t a1, ConfigurationIn_t t0, ConfigurationIn_t t1, ConfigurationIn_t tv, ConfigurationIn_t t2, ConfigurationIn_t vLim)
Constructor.
KinodynamicPath (const DevicePtr_t &robot, ConfigurationIn_t init, ConfigurationIn_t end, value_type length, ConfigurationIn_t a1, ConfigurationIn_t t0, ConfigurationIn_t t1, ConfigurationIn_t tv, ConfigurationIn_t t2, ConfigurationIn_t vLim, ConstraintSetPtr_t constraints)
Constructor with constraints.
KinodynamicPath (const KinodynamicPath &path)
Copy constructor.
KinodynamicPath (const KinodynamicPath &path, const ConstraintSetPtr_t &constraints)
Copy constructor with constraints.
void init (KinodynamicPathPtr_t self)
virtual bool impl_compute (ConfigurationOut_t result, value_type t) const
Function evaluation without applying constraints.
double sgnenum (double val) const
int sgn (double d) const
double sgnf (double d) const
Protected Member Functions inherited from hpp::core::StraightPath
StraightPath (const DevicePtr_t &robot, ConfigurationIn_t init, ConfigurationIn_t end, value_type length)
Constructor.
StraightPath (const DevicePtr_t &robot, ConfigurationIn_t init, ConfigurationIn_t end, interval_t interval)
Constructor.
StraightPath (const DevicePtr_t &robot, ConfigurationIn_t init, ConfigurationIn_t end, value_type length, ConstraintSetPtr_t constraints)
Constructor with constraints.
StraightPath (const DevicePtr_t &robot, ConfigurationIn_t init, ConfigurationIn_t end, interval_t interval, ConstraintSetPtr_t constraints)
Constructor with constraints.
StraightPath (const StraightPath &path)
Copy constructor.
StraightPath (const StraightPath &path, const ConstraintSetPtr_t &constraints)
Copy constructor with constraints.
void init (StraightPathPtr_t self)
virtual void impl_derivative (vectorOut_t result, const value_type &t, size_type order) const
Virtual implementation of derivative.
virtual void impl_velocityBound (vectorOut_t result, const value_type &, const value_type &) const
Virtual implementation of velocityBound.
PathPtr_t impl_extract (const interval_t &subInterval) const throw (projection_error)
Extraction/Reversion of a sub-path.
Protected Member Functions inherited from hpp::core::Path
Path (const interval_t &interval, size_type outputSize, size_type outputDerivativeSize, const ConstraintSetPtr_t &constraints)
Constructor.
Path (const interval_t &interval, size_type outputSize, size_type outputDerivativeSize)
Constructor.
Path (const Path &path)
Copy constructor.
Path (const Path &path, const ConstraintSetPtr_t &constraints)
Copy constructor with constraints.
void init (const PathWkPtr_t &self)
Store weak pointer to itself.
void constraints (const ConstraintSetPtr_t &constraint)
Set the constraints.
virtual void checkPath () const
Should be called by child classes after having init.
void timeRange (const interval_t &timeRange)
const TimeParameterizationPtr_t & timeParameterization () const
value_type paramLength () const
Configuration_t configAtParam (const value_type &param, bool &success) const
Additional Inherited Members
Protected Attributes inherited from hpp::core::StraightPath
DevicePtr_t device_
Configuration_t initial_
Configuration_t end_
Protected Attributes inherited from hpp::core::Path
interval_t paramRange_
Interval of parameters.
Detailed Description
Kino-dynamic straight path.
This Path has the same behavior as the StraightPath class except for the translation part of the free-flyer. For the translation part of the free-flyer KinodynamicPath store a "bang-bang" trajectory dependent on time with either 2 segment of constant acceleration or 3 segments with a constant velocity segment
In current implementation, only the translation part of the freeflyer joint is considered by this class. The value of all other joint are interpolated between the initial and end value using the interpolate() method.
The current implementation assume that :
The first joint of the robot is a freeflyer
The robot have an extra Config Space of dimension >= 6. The first 3 values of the extraConfig are the velocity of the root and the 3 other values are the aceleration.
Member Typedef Documentation
typedef StraightPath hpp::core::KinodynamicPath::parent_t
Constructor & Destructor Documentation
virtual hpp::core::KinodynamicPath::~KinodynamicPath () throw () inline virtual
Destructor.
hpp::core::KinodynamicPath::KinodynamicPath (const DevicePtr_t & robot, ConfigurationIn_t init, ConfigurationIn_t end, value_type length, ConfigurationIn_t a1, ConfigurationIn_t t0, ConfigurationIn_t t1, ConfigurationIn_t tv, ConfigurationIn_t t2, ConfigurationIn_t vLim) protected
Constructor.
hpp::core::KinodynamicPath::KinodynamicPath (const DevicePtr_t & robot, ConfigurationIn_t init, ConfigurationIn_t end, value_type length, ConfigurationIn_t a1, ConfigurationIn_t t0, ConfigurationIn_t t1, ConfigurationIn_t tv, ConfigurationIn_t t2, ConfigurationIn_t vLim, ConstraintSetPtr_t constraints) protected
Constructor with constraints.
hpp::core::KinodynamicPath::KinodynamicPath (const KinodynamicPath & path) protected
Copy constructor.
hpp::core::KinodynamicPath::KinodynamicPath (const KinodynamicPath & path, const ConstraintSetPtr_t & constraints) protected
Copy constructor with constraints.
Member Function Documentation
virtual PathPtr_t hpp::core::KinodynamicPath::copy () const inline virtual
Return a shared pointer to this.
As StaightPath are immutable, and refered to by shared pointers, they do not need to be copied.
Reimplemented from hpp::core::StraightPath.
Reimplemented in hpp::core::KinodynamicOrientedPath.
virtual PathPtr_t hpp::core::KinodynamicPath::copy (const ConstraintSetPtr_t & constraints) const inline virtual
Return a shared pointer to a copy of this and set constraints.
Parameters
constraints constraints to apply to the copy
Precondition
*this should not have constraints.
Reimplemented from hpp::core::StraightPath.
Reimplemented in hpp::core::KinodynamicOrientedPath.
static KinodynamicPathPtr_t hpp::core::KinodynamicPath::create (const DevicePtr_t & device, ConfigurationIn_t init, ConfigurationIn_t end, value_type length, ConfigurationIn_t a1, ConfigurationIn_t t0, ConfigurationIn_t t1, ConfigurationIn_t tv, ConfigurationIn_t t2, ConfigurationIn_t vLim) inline static
Create instance and return shared pointer.
Parameters
device Robot corresponding to configurations
init,end Start and end configurations of the path
length Distance between the configurations.
References hpp::core::Path::checkPath(), and init().
static KinodynamicPathPtr_t hpp::core::KinodynamicPath::create (const DevicePtr_t & device, ConfigurationIn_t init, ConfigurationIn_t end, value_type length, ConfigurationIn_t a1, ConfigurationIn_t t0, ConfigurationIn_t t1, ConfigurationIn_t tv, ConfigurationIn_t t2, ConfigurationIn_t vLim, ConstraintSetPtr_t constraints) inline static
Create instance and return shared pointer.
Parameters
device Robot corresponding to configurations
init,end Start and end configurations of the path
length Distance between the configurations.
constraints the path is subject to
References hpp::core::Path::checkPath(), and init().
static KinodynamicPathPtr_t hpp::core::KinodynamicPath::createCopy (const KinodynamicPathPtr_t & path) inline static
Create copy and return shared pointer.
Parameters
path path to copy
References hpp::core::Path::checkPath(), and init().
static KinodynamicPathPtr_t hpp::core::KinodynamicPath::createCopy (const KinodynamicPathPtr_t & path, const ConstraintSetPtr_t & constraints) inline static
Create copy and return shared pointer.
Parameters
path path to copy
constraints the path is subject to
References hpp::core::Path::checkPath(), and init().
vector_t hpp::core::KinodynamicPath::getA1 () inline
vector_t hpp::core::KinodynamicPath::getT0 () inline
vector_t hpp::core::KinodynamicPath::getT1 () inline
vector_t hpp::core::KinodynamicPath::getT2 () inline
vector_t hpp::core::KinodynamicPath::getTv () inline
virtual bool hpp::core::KinodynamicPath::impl_compute (ConfigurationOut_t configuration, value_type param) const protected virtual
Function evaluation without applying constraints.
Returns
true if everything went good.
Reimplemented from hpp::core::StraightPath.
Reimplemented in hpp::core::KinodynamicOrientedPath.
virtual PathPtr_t hpp::core::KinodynamicPath::impl_extract (const interval_t & paramInterval) const throw (projection_error) virtual
Extraction/Reversion of a sub-path.
Parameters
subInterval interval of definition of the extract path If upper bound of subInterval is smaller than lower bound, return an empty path
Reimplemented from hpp::core::Path.
Reimplemented in hpp::core::KinodynamicOrientedPath.
void hpp::core::KinodynamicPath::init (KinodynamicPathPtr_t self) inline protected
Referenced by create(), and createCopy().
virtual std::ostream& hpp::core::KinodynamicPath::print (std::ostream & os) const inline protected virtual
Print path in a stream.
Reimplemented from hpp::core::StraightPath.
Reimplemented in hpp::core::KinodynamicOrientedPath.
References hpp::pinocchio::displayConfig().
int hpp::core::KinodynamicPath::sgn (double d) const inline protected
double hpp::core::KinodynamicPath::sgnenum (double val) const inline protected
double hpp::core::KinodynamicPath::sgnf (double d) const inline protected