hpp::core::continuousValidation::BodyPairCollision Class Reference
hpp::core::continuousValidation::BodyPairCollision Class Reference abstract
Computation of collision-free sub-intervals of a path.
#include <hpp/core/continuous-validation/body-pair-collision.hh>
Public Types
typedef std::pair< CollisionObjectConstPtr_t, CollisionObjectConstPtr_t > CollisionPair_t
typedef std::vector< CollisionPair_t > CollisionPairs_t
Public Member Functions
bool validateConfiguration (const value_type &t, interval_t &interval, CollisionValidationReportPtr_t &report, pinocchio::DeviceData &data)
Validate interval centered on a path parameter.
const CollisionPairs_t & pairs () const
CollisionPairs_t & pairs ()
value_type maximalVelocity () const
virtual size_type indexJointA () const
Returns joint A index or -1 if no such joint exists.
virtual size_type indexJointB () const
Returns joint B index or -1 if no such joint exists.
virtual bool removeObjectTo_b (const CollisionObjectConstPtr_t &)
virtual void addCollisionPair (const CollisionObjectConstPtr_t &, const CollisionObjectConstPtr_t &)
virtual std::string name () const =0
virtual std::ostream & print (std::ostream &os) const =0
virtual BodyPairCollisionPtr_t copy () const =0
Public Member Functions inherited from hpp::core::continuousValidation::IntervalValidation< CollisionValidationReportPtr_t >
void path (const PathPtr_t &path, bool reverse)
Set path to validate.
PathConstPtr_t path () const
Get path.
value_type tolerance () const
Protected Member Functions
BodyPairCollision (value_type tolerance)
Constructor of body pair collision.
BodyPairCollision (const BodyPairCollision &other)
Copy constructor.
virtual void setReport (CollisionValidationReportPtr_t &report, fcl::CollisionResult result, CollisionPair_t _pair) const
Protected Member Functions inherited from hpp::core::continuousValidation::IntervalValidation< CollisionValidationReportPtr_t >
IntervalValidation (value_type tolerance)
Constructor of interval validation element.
IntervalValidation (const IntervalValidation &other)
Additional Inherited Members
Protected Types inherited from hpp::core::continuousValidation::IntervalValidation< CollisionValidationReportPtr_t >
typedef boost::icl::continuous_interval< value_type > continuous_interval
typedef boost::icl::interval_set< value_type > interval_set
Protected Attributes inherited from hpp::core::continuousValidation::IntervalValidation< CollisionValidationReportPtr_t >
PathPtr_t path_
value_type tolerance_
bool reverse_
bool refine_
bool valid_
interval_set validInterval_
Detailed Description
Computation of collision-free sub-intervals of a path.
This class aims at validating a path for the absence of collision between two bodies of a robot, which are in most common cases two solid bodies (see SolidSolidCollision). With this abstraction, other bodies (like cables) can also be checked for collision.
The interval of definition of the path is successively covered by intervals where boths bodies are proved to be collision-free. Each interval is computed by bounding from above the velocity of all points of body 1 in the reference frame of body 2.
See this document for details.
Member Typedef Documentation
typedef std::pair<CollisionObjectConstPtr_t, CollisionObjectConstPtr_t> hpp::core::continuousValidation::BodyPairCollision::CollisionPair_t
typedef std::vector<CollisionPair_t> hpp::core::continuousValidation::BodyPairCollision::CollisionPairs_t
Constructor & Destructor Documentation
hpp::core::continuousValidation::BodyPairCollision::BodyPairCollision (value_type tolerance) inline protected
Constructor of body pair collision.
Parameters
tolerance allowed penetration should be positive
hpp::core::continuousValidation::BodyPairCollision::BodyPairCollision (const BodyPairCollision & other) inline protected
Copy constructor.
Member Function Documentation
virtual void hpp::core::continuousValidation::BodyPairCollision::addCollisionPair (const CollisionObjectConstPtr_t & , const CollisionObjectConstPtr_t &) inline virtual
Reimplemented in hpp::core::continuousValidation::SolidSolidCollision.
References copy(), name(), and print().
virtual BodyPairCollisionPtr_t hpp::core::continuousValidation::BodyPairCollision::copy () const pure virtual
Implemented in hpp::core::continuousValidation::SolidSolidCollision.
Referenced by addCollisionPair().
virtual size_type hpp::core::continuousValidation::BodyPairCollision::indexJointA () const inline virtual
Returns joint A index or -1 if no such joint exists.
Reimplemented in hpp::core::continuousValidation::SolidSolidCollision.
virtual size_type hpp::core::continuousValidation::BodyPairCollision::indexJointB () const inline virtual
Returns joint B index or -1 if no such joint exists.
Reimplemented in hpp::core::continuousValidation::SolidSolidCollision.
value_type hpp::core::continuousValidation::BodyPairCollision::maximalVelocity () const inline
virtual std::string hpp::core::continuousValidation::BodyPairCollision::name () const pure virtual
Implements hpp::core::continuousValidation::IntervalValidation< CollisionValidationReportPtr_t >.
Implemented in hpp::core::continuousValidation::SolidSolidCollision.
Referenced by addCollisionPair().
const CollisionPairs_t& hpp::core::continuousValidation::BodyPairCollision::pairs () const inline
Referenced by setReport().
CollisionPairs_t& hpp::core::continuousValidation::BodyPairCollision::pairs () inline
virtual std::ostream& hpp::core::continuousValidation::BodyPairCollision::print (std::ostream & os) const pure virtual
Implements hpp::core::continuousValidation::IntervalValidation< CollisionValidationReportPtr_t >.
Implemented in hpp::core::continuousValidation::SolidSolidCollision.
Referenced by addCollisionPair(), and hpp::core::continuousValidation::operator<<().
virtual bool hpp::core::continuousValidation::BodyPairCollision::removeObjectTo_b (const CollisionObjectConstPtr_t &) inline virtual
Reimplemented in hpp::core::continuousValidation::SolidSolidCollision.
virtual void hpp::core::continuousValidation::BodyPairCollision::setReport (CollisionValidationReportPtr_t & report, fcl::CollisionResult result, CollisionPair_t _pair) const inline protected virtual
References pairs().
bool hpp::core::continuousValidation::BodyPairCollision::validateConfiguration (const value_type & t, interval_t & interval, CollisionValidationReportPtr_t & report, pinocchio::DeviceData & data) virtual
Validate interval centered on a path parameter.
Parameters
t parameter value in the path interval of definition
[in,out] interval as input, interval over which collision checking must be performed. As output, interval over which pair is collision-free, not necessarily included in definition interval.
report the collision validation report
Returns
true if the body pair is collision free for this parameter value, false if the body pair is in collision.
Note
object should be in the positions defined by the configuration of parameter t on the path.
Implements hpp::core::continuousValidation::IntervalValidation< CollisionValidationReportPtr_t >.