hpp::core::steeringMethod::CarLike Class Reference
hpp::core::steeringMethod::CarLike Class Reference
Steering method and distance functions
Abstract class that implements various type of trajectories for carlike vehicles.
#include <hpp/core/steering-method/car-like.hh>
Public Member Functions
virtual ~CarLike ()
void setWheelJoints (const std::vector< JointPtr_t > wheels)
Set the wheels.
void computeRadius ()
Compute the turning radius.
Public Member Functions inherited from hpp::core::SteeringMethod
PathPtr_t operator() (ConfigurationIn_t q1, ConfigurationIn_t q2) const
create a path between two configurations
PathPtr_t steer (ConfigurationIn_t q1, ConfigurationIn_t q2) const
virtual ~SteeringMethod ()
virtual SteeringMethodPtr_t copy () const =0
Copy instance and return shared pointer.
const Problem & problem () const
void constraints (const ConstraintSetPtr_t &constraints)
Set constraint set.
const ConstraintSetPtr_t & constraints () const
Get constraint set.
Protected Member Functions
CarLike (const Problem &problem)
Constructor.
CarLike (const Problem &problem, const value_type turningRadius, JointPtr_t xyJoint, JointPtr_t rzJoint, std::vector< JointPtr_t > wheels)
Constructor.
CarLike (const CarLike &other)
Copy constructor.
void init (CarLikeWkPtr_t weak)
Store weak pointer to itself.
Protected Member Functions inherited from hpp::core::SteeringMethod
SteeringMethod (const Problem &problem)
Constructor.
SteeringMethod (const SteeringMethod &other)
Copy constructor.
virtual PathPtr_t impl_compute (ConfigurationIn_t q1, ConfigurationIn_t q2) const =0
create a path between two configurations
void init (SteeringMethodWkPtr_t weak)
Store weak pointer to itself.
Protected Attributes
DeviceWkPtr_t device_
value_type rho_
JointPtr_t xy_
JointPtr_t rz_
size_type xyId_
size_type rzId_
std::vector< JointPtr_t > wheels_
Protected Attributes inherited from hpp::core::SteeringMethod
const Problem & problem_
Detailed Description
Abstract class that implements various type of trajectories for carlike vehicles.
Constructor & Destructor Documentation
virtual hpp::core::steeringMethod::CarLike::~CarLike () inline virtual
hpp::core::steeringMethod::CarLike::CarLike (const Problem & problem) protected
Constructor.
hpp::core::steeringMethod::CarLike::CarLike (const Problem & problem, const value_type turningRadius, JointPtr_t xyJoint, JointPtr_t rzJoint, std::vector< JointPtr_t > wheels) protected
Constructor.
hpp::core::steeringMethod::CarLike::CarLike (const CarLike & other) protected
Copy constructor.
Member Function Documentation
void hpp::core::steeringMethod::CarLike::computeRadius ()
Compute the turning radius.
The turning radius is the maximum of the turning radius of each wheel. The turning radius of a wheel is the radius of the circle defined by:
its center is on the plane x = 0 in the frame of joint RZ,
the origin of joint RZ is on the circle,
the bounds of the joint wheel are saturated.
void hpp::core::steeringMethod::CarLike::init (CarLikeWkPtr_t weak) inline protected
Store weak pointer to itself.
References hpp::core::SteeringMethod::init().
Referenced by hpp::core::steeringMethod::ReedsShepp::init(), hpp::core::steeringMethod::Snibud::init(), and hpp::core::steeringMethod::Dubins::init().
void hpp::core::steeringMethod::CarLike::setWheelJoints (const std::vector< JointPtr_t > wheels) inline
Set the wheels.
Member Data Documentation
DeviceWkPtr_t hpp::core::steeringMethod::CarLike::device_ protected
value_type hpp::core::steeringMethod::CarLike::rho_ protected
JointPtr_t hpp::core::steeringMethod::CarLike::rz_ protected
size_type hpp::core::steeringMethod::CarLike::rzId_ protected
std::vector<JointPtr_t> hpp::core::steeringMethod::CarLike::wheels_ protected
JointPtr_t hpp::core::steeringMethod::CarLike::xy_ protected
size_type hpp::core::steeringMethod::CarLike::xyId_ protected