hpp::core::steeringMethod::ReedsShepp Class Reference
hpp::core::steeringMethod::ReedsShepp Class Reference
Steering method and distance functions
Steering method that creates ReedsSheppPath instances.
#include <hpp/core/steering-method/reeds-shepp.hh>
Public Member Functions
virtual SteeringMethodPtr_t copy () const
Copy instance and return shared pointer.
virtual PathPtr_t impl_compute (ConfigurationIn_t q1, ConfigurationIn_t q2) const
create a path between two configurations
Public Member Functions inherited from hpp::core::steeringMethod::CarLike
virtual ~CarLike ()
void setWheelJoints (const std::vector< JointPtr_t > wheels)
Set the wheels.
void computeRadius ()
Compute the turning radius.
Public Member Functions inherited from hpp::core::SteeringMethod
PathPtr_t operator() (ConfigurationIn_t q1, ConfigurationIn_t q2) const
create a path between two configurations
PathPtr_t steer (ConfigurationIn_t q1, ConfigurationIn_t q2) const
virtual ~SteeringMethod ()
const Problem & problem () const
void constraints (const ConstraintSetPtr_t &constraints)
Set constraint set.
const ConstraintSetPtr_t & constraints () const
Get constraint set.
Static Public Member Functions
static ReedsSheppPtr_t createWithGuess (const Problem &problem)
Create an instance.
static ReedsSheppPtr_t create (const Problem &problem, const value_type turningRadius, JointPtr_t xyJoint, JointPtr_t rzJoint, std::vector< JointPtr_t > wheels=std::vector< JointPtr_t >())
Create an instance.
static ReedsSheppPtr_t createCopy (const ReedsSheppPtr_t &other)
Copy instance and return shared pointer.
Protected Member Functions
ReedsShepp (const Problem &problem)
Constructor.
ReedsShepp (const Problem &problem, const value_type turningRadius, JointPtr_t xyJoint, JointPtr_t rzJoint, std::vector< JointPtr_t > wheels)
Constructor.
ReedsShepp (const ReedsShepp &other)
Copy constructor.
void init (ReedsSheppWkPtr_t weak)
Store weak pointer to itself.
Protected Member Functions inherited from hpp::core::steeringMethod::CarLike
CarLike (const Problem &problem)
Constructor.
CarLike (const Problem &problem, const value_type turningRadius, JointPtr_t xyJoint, JointPtr_t rzJoint, std::vector< JointPtr_t > wheels)
Constructor.
CarLike (const CarLike &other)
Copy constructor.
void init (CarLikeWkPtr_t weak)
Store weak pointer to itself.
Protected Member Functions inherited from hpp::core::SteeringMethod
SteeringMethod (const Problem &problem)
Constructor.
SteeringMethod (const SteeringMethod &other)
Copy constructor.
void init (SteeringMethodWkPtr_t weak)
Store weak pointer to itself.
Additional Inherited Members
Protected Attributes inherited from hpp::core::steeringMethod::CarLike
DeviceWkPtr_t device_
value_type rho_
JointPtr_t xy_
JointPtr_t rz_
size_type xyId_
size_type rzId_
std::vector< JointPtr_t > wheels_
Protected Attributes inherited from hpp::core::SteeringMethod
const Problem & problem_
Detailed Description
Steering method that creates ReedsSheppPath instances.
Constructor & Destructor Documentation
hpp::core::steeringMethod::ReedsShepp::ReedsShepp (const Problem & problem) protected
Constructor.
hpp::core::steeringMethod::ReedsShepp::ReedsShepp (const Problem & problem, const value_type turningRadius, JointPtr_t xyJoint, JointPtr_t rzJoint, std::vector< JointPtr_t > wheels) protected
Constructor.
hpp::core::steeringMethod::ReedsShepp::ReedsShepp (const ReedsShepp & other) protected
Copy constructor.
Member Function Documentation
virtual SteeringMethodPtr_t hpp::core::steeringMethod::ReedsShepp::copy () const inline virtual
Copy instance and return shared pointer.
Implements hpp::core::SteeringMethod.
static ReedsSheppPtr_t hpp::core::steeringMethod::ReedsShepp::create (const Problem & problem, const value_type turningRadius, JointPtr_t xyJoint, JointPtr_t rzJoint, std::vector< JointPtr_t > wheels = std::vector<JointPtr_t>()) inline static
Create an instance.
This constructor does no assumption.
References init().
static ReedsSheppPtr_t hpp::core::steeringMethod::ReedsShepp::createCopy (const ReedsSheppPtr_t & other) inline static
Copy instance and return shared pointer.
References init().
static ReedsSheppPtr_t hpp::core::steeringMethod::ReedsShepp::createWithGuess (const Problem & problem) inline static
Create an instance.
This constructor assumes that:
the 2 parameters of the configurations corresponds to the XY translation joint,
the 2 following parameters corresponds to the RZ unbounded rotation joint. Use Carlike::setWheelJoints to set the wheel joints.
References init().
virtual PathPtr_t hpp::core::steeringMethod::ReedsShepp::impl_compute (ConfigurationIn_t q1, ConfigurationIn_t q2) const virtual
create a path between two configurations
Implements hpp::core::SteeringMethod.
void hpp::core::steeringMethod::ReedsShepp::init (ReedsSheppWkPtr_t weak) inline protected
Store weak pointer to itself.
References hpp::core::steeringMethod::CarLike::init().
Referenced by create(), createCopy(), and createWithGuess().