hpp::core::SteeringMethod Class Reference
hpp::core::SteeringMethod Class Reference abstract
Steering method and distance functions
Steering method.
#include <hpp/core/steering-method.hh>
Public Member Functions
PathPtr_t operator() (ConfigurationIn_t q1, ConfigurationIn_t q2) const
create a path between two configurations
PathPtr_t steer (ConfigurationIn_t q1, ConfigurationIn_t q2) const
virtual ~SteeringMethod ()
virtual SteeringMethodPtr_t copy () const =0
Copy instance and return shared pointer.
const Problem & problem () const
Constraints applicable to the robot.
These constraints are not automatically taken into account.
Child class can use it if they need.
void constraints (const ConstraintSetPtr_t &constraints)
Set constraint set.
const ConstraintSetPtr_t & constraints () const
Get constraint set.
Protected Member Functions
SteeringMethod (const Problem &problem)
Constructor.
SteeringMethod (const SteeringMethod &other)
Copy constructor.
virtual PathPtr_t impl_compute (ConfigurationIn_t q1, ConfigurationIn_t q2) const =0
create a path between two configurations
void init (SteeringMethodWkPtr_t weak)
Store weak pointer to itself.
Protected Attributes
const Problem & problem_
Detailed Description
Steering method.
A steering method creates paths between pairs of configurations for a robot. They are usually used to take into account nonholonomic constraints of some robots
Constructor & Destructor Documentation
virtual hpp::core::SteeringMethod::~SteeringMethod () inline virtual
hpp::core::SteeringMethod::SteeringMethod (const Problem & problem) inline protected
Constructor.
hpp::core::SteeringMethod::SteeringMethod (const SteeringMethod & other) inline protected
Copy constructor.
Constraints are copied
References HPP_DYNAMIC_PTR_CAST.
Member Function Documentation
void hpp::core::SteeringMethod::constraints (const ConstraintSetPtr_t & constraints) inline
Set constraint set.
const ConstraintSetPtr_t& hpp::core::SteeringMethod::constraints () const inline
Get constraint set.
virtual SteeringMethodPtr_t hpp::core::SteeringMethod::copy () const pure virtual
Copy instance and return shared pointer.
Implemented in hpp::core::steeringMethod::Dubins, hpp::core::steeringMethod::ReedsShepp, hpp::core::steeringMethod::Snibud, hpp::core::steeringMethod::Spline< _PolynomeBasis, _SplineOrder >, hpp::core::steeringMethod::Kinodynamic, hpp::core::steeringMethod::Interpolated, hpp::core::steeringMethod::Straight, and hpp::core::steeringMethod::Hermite.
virtual PathPtr_t hpp::core::SteeringMethod::impl_compute (ConfigurationIn_t q1, ConfigurationIn_t q2) const protected pure virtual
create a path between two configurations
Implemented in hpp::core::steeringMethod::Dubins, hpp::core::steeringMethod::ReedsShepp, hpp::core::steeringMethod::Snibud, hpp::core::steeringMethod::Spline< _PolynomeBasis, _SplineOrder >, hpp::core::steeringMethod::Kinodynamic, hpp::core::steeringMethod::Interpolated, hpp::core::steeringMethod::Straight, and hpp::core::steeringMethod::Hermite.
void hpp::core::SteeringMethod::init (SteeringMethodWkPtr_t weak) inline protected
Store weak pointer to itself.
Referenced by hpp::core::steeringMethod::CarLike::init(), hpp::core::steeringMethod::Hermite::init(), hpp::core::steeringMethod::Spline< _PolynomeBasis, _SplineOrder >::init(), hpp::core::steeringMethod::Straight::init(), hpp::core::steeringMethod::Interpolated::init(), and hpp::core::steeringMethod::Kinodynamic::init().
PathPtr_t hpp::core::SteeringMethod::operator() (ConfigurationIn_t q1, ConfigurationIn_t q2) const inline
create a path between two configurations
Returns
a Path from q1 to q2 if found. An empty Path if Path could not be built.
References hppDout, and hpp::core::projection_error::what().
const Problem& hpp::core::SteeringMethod::problem () const inline
PathPtr_t hpp::core::SteeringMethod::steer (ConfigurationIn_t q1, ConfigurationIn_t q2) const inline
Member Data Documentation
const Problem& hpp::core::SteeringMethod::problem_ protected