hpp::core::steeringMethod::Spline< _PolynomeBasis, _SplineOrder > Class Template Reference
hpp::core::steeringMethod::Spline< _PolynomeBasis, _SplineOrder > Class Template Reference
Steering method and distance functions
Steering method that creates path::Spline instances.
#include <hpp/core/steering-method/spline.hh>
Public Types
enum {
PolynomeBasis = _PolynomeBasis,
SplineOrder = _SplineOrder
}
typedef path::Spline< PolynomeBasis, SplineOrder > SplinePath
typedef SplinePath::Ptr_t SplinePathPtr_t
typedef boost::shared_ptr< Spline > Ptr_t
typedef boost::weak_ptr< Spline > WkPtr_t
Public Member Functions
virtual SteeringMethodPtr_t copy () const
Copy instance and return shared pointer.
virtual PathPtr_t impl_compute (ConfigurationIn_t q1, ConfigurationIn_t q2) const
create a path between two configurations
PathPtr_t steer (ConfigurationIn_t q1, std::vector< int > order1, matrixIn_t derivatives1, ConfigurationIn_t q2, std::vector< int > order2, matrixIn_t derivatives2) const
create a path between two configurations
Public Member Functions inherited from hpp::core::SteeringMethod
PathPtr_t operator() (ConfigurationIn_t q1, ConfigurationIn_t q2) const
create a path between two configurations
PathPtr_t steer (ConfigurationIn_t q1, ConfigurationIn_t q2) const
virtual ~SteeringMethod ()
const Problem & problem () const
void constraints (const ConstraintSetPtr_t &constraints)
Set constraint set.
const ConstraintSetPtr_t & constraints () const
Get constraint set.
Static Public Member Functions
static Ptr_t create (const Problem &problem)
static Ptr_t createCopy (const Ptr_t &other)
Copy instance and return shared pointer.
Protected Member Functions
Spline (const Problem &problem)
Constructor.
Spline (const Spline &other)
Copy constructor.
void init (WkPtr_t weak)
Store weak pointer to itself.
Protected Member Functions inherited from hpp::core::SteeringMethod
SteeringMethod (const Problem &problem)
Constructor.
SteeringMethod (const SteeringMethod &other)
Copy constructor.
void init (SteeringMethodWkPtr_t weak)
Store weak pointer to itself.
Additional Inherited Members
Protected Attributes inherited from hpp::core::SteeringMethod
const Problem & problem_
Detailed Description
template<int _PolynomeBasis, int _SplineOrder>
class hpp::core::steeringMethod::Spline< _PolynomeBasis, _SplineOrder >
Steering method that creates path::Spline instances.
Member Typedef Documentation
template<int _PolynomeBasis, int _SplineOrder> typedef boost::shared_ptr<Spline> hpp::core::steeringMethod::Spline< _PolynomeBasis, _SplineOrder >::Ptr_t
template<int _PolynomeBasis, int _SplineOrder> typedef path::Spline<PolynomeBasis, SplineOrder> hpp::core::steeringMethod::Spline< _PolynomeBasis, _SplineOrder >::SplinePath
template<int _PolynomeBasis, int _SplineOrder> typedef SplinePath::Ptr_t hpp::core::steeringMethod::Spline< _PolynomeBasis, _SplineOrder >::SplinePathPtr_t
template<int _PolynomeBasis, int _SplineOrder> typedef boost::weak_ptr<Spline> hpp::core::steeringMethod::Spline< _PolynomeBasis, _SplineOrder >::WkPtr_t
Member Enumeration Documentation
template<int _PolynomeBasis, int _SplineOrder> anonymous enum
Enumerator
PolynomeBasis
SplineOrder
Constructor & Destructor Documentation
template<int _PolynomeBasis, int _SplineOrder> hpp::core::steeringMethod::Spline< _PolynomeBasis, _SplineOrder >::Spline (const Problem & problem) protected
Constructor.
template<int _PolynomeBasis, int _SplineOrder> hpp::core::steeringMethod::Spline< _PolynomeBasis, _SplineOrder >::Spline (const Spline< _PolynomeBasis, _SplineOrder > & other) protected
Copy constructor.
Member Function Documentation
template<int _PolynomeBasis, int _SplineOrder> virtual SteeringMethodPtr_t hpp::core::steeringMethod::Spline< _PolynomeBasis, _SplineOrder >::copy () const inline virtual
Copy instance and return shared pointer.
Implements hpp::core::SteeringMethod.
template<int _PolynomeBasis, int _SplineOrder> static Ptr_t hpp::core::steeringMethod::Spline< _PolynomeBasis, _SplineOrder >::create (const Problem & problem) inline static
References hpp::core::steeringMethod::Spline< _PolynomeBasis, _SplineOrder >::init().
template<int _PolynomeBasis, int _SplineOrder> static Ptr_t hpp::core::steeringMethod::Spline< _PolynomeBasis, _SplineOrder >::createCopy (const Ptr_t & other) inline static
Copy instance and return shared pointer.
References hpp::core::steeringMethod::Spline< _PolynomeBasis, _SplineOrder >::init().
template<int _PolynomeBasis, int _SplineOrder> virtual PathPtr_t hpp::core::steeringMethod::Spline< _PolynomeBasis, _SplineOrder >::impl_compute (ConfigurationIn_t q1, ConfigurationIn_t q2) const virtual
create a path between two configurations
Implements hpp::core::SteeringMethod.
template<int _PolynomeBasis, int _SplineOrder> void hpp::core::steeringMethod::Spline< _PolynomeBasis, _SplineOrder >::init (WkPtr_t weak) inline protected
Store weak pointer to itself.
References hpp::core::SteeringMethod::init().
Referenced by hpp::core::steeringMethod::Spline< _PolynomeBasis, _SplineOrder >::create(), and hpp::core::steeringMethod::Spline< _PolynomeBasis, _SplineOrder >::createCopy().
template<int _PolynomeBasis, int _SplineOrder> PathPtr_t hpp::core::steeringMethod::Spline< _PolynomeBasis, _SplineOrder >::steer (ConfigurationIn_t q1, std::vector< int > order1, matrixIn_t derivatives1, ConfigurationIn_t q2, std::vector< int > order2, matrixIn_t derivatives2) const
create a path between two configurations