hpp::core::PathVector Class Reference
hpp::core::PathVector Class Reference
Path
Concatenation of several paths.
#include <hpp/core/path-vector.hh>
Public Types
typedef Path parent_t
Public Member Functions
std::size_t numberPaths () const
Get the number of sub paths.
PathPtr_t pathAtRank (std::size_t rank) const
Get a path in the vector.
std::size_t rankAtParam (const value_type &param, value_type &localParam) const
Get rank of direct path in vector at param.
void appendPath (const PathPtr_t &path)
Append a path at the end of the vector.
void concatenate (const PathVector &path) HPP_CORE_DEPRECATED
Concatenate two vectors of path.
void concatenate (const PathVectorPtr_t &path)
Concatenate two vectors of path.
virtual Configuration_t initial () const
Get the initial configuration.
virtual Configuration_t end () const
Get the final configuration.
void flatten (PathVectorPtr_t flattenedPath) const
Return the a path vector representing the same path but ensuring that there is no PathVector in the PathVector.
Public Member Functions inherited from hpp::core::Path
virtual ~Path () throw ()
Destructor.
template<class T >
boost::shared_ptr< T > as (void)
Static cast into a derived type.
template<class T >
boost::shared_ptr< const T > as (void) const
Static cast into a derived type.
PathPtr_t extract (const interval_t &subInterval) const throw (projection_error)
PathPtr_t extract (const value_type &tmin, const value_type &tmax) const throw (projection_error)
virtual PathPtr_t reverse () const
Reversion of a path.
Configuration_t operator() (const value_type &time) const HPP_CORE_DEPRECATED
Configuration_t operator() (const value_type &time, bool &success) const
bool operator() (ConfigurationOut_t result, const value_type &time) const throw ()
Configuration_t eval (const value_type &time, bool &success) const
bool eval (ConfigurationOut_t result, const value_type &time) const throw ()
bool at (const value_type &time, ConfigurationOut_t result) const
Get the configuration at a parameter without applying the constraints.
void derivative (vectorOut_t result, const value_type &time, size_type order) const
Get derivative with respect to parameter at given parameter.
void velocityBound (vectorOut_t result, const value_type &t0, const value_type &t1) const
Get an upper bound of the velocity on a sub-interval.
size_type outputSize () const
Get size of configuration space.
size_type outputDerivativeSize () const
Get size of velocity.
const interval_t & timeRange () const
Get interval of definition.
virtual value_type length () const
Get length of definition interval.
const ConstraintSetPtr_t & constraints () const
Get constraints the path is subject to.
const interval_t & paramRange () const
Get interval of parameters.
void timeParameterization (const TimeParameterizationPtr_t &tp, const interval_t &tr)
Set the time parameterization function.
Protected Member Functions
virtual std::ostream & print (std::ostream &os) const
Print path in a stream.
PathVector (std::size_t outputSize, std::size_t outputDerivativeSize)
Constructor.
PathVector (const PathVector &path)
Copy constructor.
PathVector (const PathVector &path, const ConstraintSetPtr_t &constraints)
Copy constructor with constraints.
void init (PathVectorPtr_t self)
virtual bool impl_compute (ConfigurationOut_t result, value_type t) const
Function evaluation without applying constraints.
virtual void impl_derivative (vectorOut_t result, const value_type &t, size_type order) const
Virtual implementation of derivative.
virtual PathPtr_t impl_extract (const interval_t &subInterval) const throw (projection_error)
Extraction of a sub-path.
Protected Member Functions inherited from hpp::core::Path
Path (const interval_t &interval, size_type outputSize, size_type outputDerivativeSize, const ConstraintSetPtr_t &constraints)
Constructor.
Path (const interval_t &interval, size_type outputSize, size_type outputDerivativeSize)
Constructor.
Path (const Path &path)
Copy constructor.
Path (const Path &path, const ConstraintSetPtr_t &constraints)
Copy constructor with constraints.
void init (const PathWkPtr_t &self)
Store weak pointer to itself.
void constraints (const ConstraintSetPtr_t &constraint)
Set the constraints.
virtual void checkPath () const
Should be called by child classes after having init.
void timeRange (const interval_t &timeRange)
const TimeParameterizationPtr_t & timeParameterization () const
value_type paramLength () const
Configuration_t configAtParam (const value_type &param, bool &success) const
virtual void impl_velocityBound (vectorOut_t bound, const value_type &param0, const value_type &param1) const
Virtual implementation of velocityBound.
Construction, destruction, copy
static PathVectorPtr_t create (size_type outputSize, size_type outputDerivativeSize)
Create instance and return shared pointer.
static PathVectorPtr_t createCopy (const PathVectorPtr_t &original)
Create instance and return shared pointer.
static PathVectorPtr_t createCopy (const PathVectorPtr_t &original, const ConstraintSetPtr_t &constraints)
Create instance and return shared pointer.
virtual PathPtr_t copy () const
Return a shared pointer to a copy of this.
virtual PathPtr_t copy (const ConstraintSetPtr_t &constraints) const
Return a shared pointer to a copy of this with constraints.
virtual ~PathVector () throw ()
Destructor.
Additional Inherited Members
Protected Attributes inherited from hpp::core::Path
interval_t paramRange_
Interval of parameters.
Detailed Description
Concatenation of several paths.
Member Typedef Documentation
typedef Path hpp::core::PathVector::parent_t
Constructor & Destructor Documentation
virtual hpp::core::PathVector::~PathVector () throw () inline virtual
Destructor.
hpp::core::PathVector::PathVector (std::size_t outputSize, std::size_t outputDerivativeSize) inline protected
Constructor.
hpp::core::PathVector::PathVector (const PathVector & path) inline protected
Copy constructor.
References assert(), and hpp::core::Path::timeRange().
hpp::core::PathVector::PathVector (const PathVector & path, const ConstraintSetPtr_t & constraints) inline protected
Copy constructor with constraints.
References assert(), and hpp::core::Path::timeRange().
Member Function Documentation
void hpp::core::PathVector::appendPath (const PathPtr_t & path)
Append a path at the end of the vector.
void hpp::core::PathVector::concatenate (const PathVector & path)
Concatenate two vectors of path.
Deprecated:
use void method concatenate (const PathVectorPtr_t& path) instead.
void hpp::core::PathVector::concatenate (const PathVectorPtr_t & path)
Concatenate two vectors of path.
Parameters
path path to append at the end of this one
Each element of path is appended to this one.
virtual PathPtr_t hpp::core::PathVector::copy () const inline virtual
Return a shared pointer to a copy of this.
Implements hpp::core::Path.
Reimplemented in hpp::core::DubinsPath, and hpp::core::ReedsSheppPath.
virtual PathPtr_t hpp::core::PathVector::copy (const ConstraintSetPtr_t & constraints) const inline virtual
Return a shared pointer to a copy of this with constraints.
Parameters
constraints constraints to apply to the copy
Precondition
*this should not have constraints.
Implements hpp::core::Path.
Reimplemented in hpp::core::DubinsPath, and hpp::core::ReedsSheppPath.
static PathVectorPtr_t hpp::core::PathVector::create (size_type outputSize, size_type outputDerivativeSize) inline static
Create instance and return shared pointer.
References init().
static PathVectorPtr_t hpp::core::PathVector::createCopy (const PathVectorPtr_t & original) inline static
Create instance and return shared pointer.
References init().
static PathVectorPtr_t hpp::core::PathVector::createCopy (const PathVectorPtr_t & original, const ConstraintSetPtr_t & constraints) inline static
Create instance and return shared pointer.
References init().
virtual Configuration_t hpp::core::PathVector::end () const inline virtual
Get the final configuration.
Implements hpp::core::Path.
Reimplemented in hpp::core::DubinsPath, and hpp::core::ReedsSheppPath.
void hpp::core::PathVector::flatten (PathVectorPtr_t flattenedPath) const
Return the a path vector representing the same path but ensuring that there is no PathVector in the PathVector.
virtual bool hpp::core::PathVector::impl_compute (ConfigurationOut_t configuration, value_type param) const protected virtual
Function evaluation without applying constraints.
Returns
true if everything went good.
Implements hpp::core::Path.
virtual void hpp::core::PathVector::impl_derivative (vectorOut_t result, const value_type & t, size_type order) const protected virtual
Virtual implementation of derivative.
Reimplemented from hpp::core::Path.
Reimplemented in hpp::core::ReedsSheppPath.
virtual PathPtr_t hpp::core::PathVector::impl_extract (const interval_t & subInterval) const throw (projection_error) protected virtual
Extraction of a sub-path.
Parameters
subInterval interval of definition of the extract path
Reimplemented from hpp::core::Path.
void hpp::core::PathVector::init (PathVectorPtr_t self) inline protected
Referenced by create(), and createCopy().
virtual Configuration_t hpp::core::PathVector::initial () const inline virtual
Get the initial configuration.
Implements hpp::core::Path.
Reimplemented in hpp::core::DubinsPath, and hpp::core::ReedsSheppPath.
Referenced by hpp::core::pathOptimization::ConfigOptimizationTraits::getGoal().
std::size_t hpp::core::PathVector::numberPaths () const inline
Get the number of sub paths.
PathPtr_t hpp::core::PathVector::pathAtRank (std::size_t rank) const
Get a path in the vector.
Parameters
rank rank of the path in the vector. Should be between 0 and numberPaths ().
Returns
shared pointer to a copy of the path at requested rank with constraints applicable to the PathVector.
virtual std::ostream& hpp::core::PathVector::print (std::ostream & os) const inline protected virtual
Print path in a stream.
Reimplemented from hpp::core::Path.
Reimplemented in hpp::core::DubinsPath, and hpp::core::ReedsSheppPath.
References hpp::core::Path::print().
std::size_t hpp::core::PathVector::rankAtParam (const value_type & param, value_type & localParam) const
Get rank of direct path in vector at param.
Parameters
param parameter in interval of definition,
Return values
localParam parameter on sub-path
Returns
rank of direct path in vector