hpp::core::steeringMethod::Hermite Class Reference
hpp::core::steeringMethod::Hermite Class Reference
Steering method and distance functions
Steering method that creates path::Hermite instances.
#include <hpp/core/steering-method/hermite.hh>
Public Member Functions
virtual SteeringMethodPtr_t copy () const
Copy instance and return shared pointer.
virtual PathPtr_t impl_compute (ConfigurationIn_t q1, ConfigurationIn_t q2) const
create a path between two configurations
Public Member Functions inherited from hpp::core::SteeringMethod
PathPtr_t operator() (ConfigurationIn_t q1, ConfigurationIn_t q2) const
create a path between two configurations
PathPtr_t steer (ConfigurationIn_t q1, ConfigurationIn_t q2) const
virtual ~SteeringMethod ()
const Problem & problem () const
void constraints (const ConstraintSetPtr_t &constraints)
Set constraint set.
const ConstraintSetPtr_t & constraints () const
Get constraint set.
Static Public Member Functions
static HermitePtr_t create (const Problem &problem)
Create instance and return shared pointer.
static HermitePtr_t createCopy (const HermitePtr_t &other)
Copy instance and return shared pointer.
Protected Member Functions
Hermite (const Problem &problem)
Constructor with weighed distance.
Hermite (const Hermite &other)
Copy constructor.
void init (HermiteWkPtr_t weak)
Store weak pointer to itself.
Protected Member Functions inherited from hpp::core::SteeringMethod
SteeringMethod (const Problem &problem)
Constructor.
SteeringMethod (const SteeringMethod &other)
Copy constructor.
void init (SteeringMethodWkPtr_t weak)
Store weak pointer to itself.
Additional Inherited Members
Protected Attributes inherited from hpp::core::SteeringMethod
const Problem & problem_
Detailed Description
Steering method that creates path::Hermite instances.
Constructor & Destructor Documentation
hpp::core::steeringMethod::Hermite::Hermite (const Problem & problem) inline protected
Constructor with weighed distance.
hpp::core::steeringMethod::Hermite::Hermite (const Hermite & other) inline protected
Copy constructor.
Member Function Documentation
virtual SteeringMethodPtr_t hpp::core::steeringMethod::Hermite::copy () const inline virtual
Copy instance and return shared pointer.
Implements hpp::core::SteeringMethod.
static HermitePtr_t hpp::core::steeringMethod::Hermite::create (const Problem & problem) inline static
Create instance and return shared pointer.
References init().
static HermitePtr_t hpp::core::steeringMethod::Hermite::createCopy (const HermitePtr_t & other) inline static
Copy instance and return shared pointer.
References init().
virtual PathPtr_t hpp::core::steeringMethod::Hermite::impl_compute (ConfigurationIn_t q1, ConfigurationIn_t q2) const inline virtual
create a path between two configurations
Implements hpp::core::SteeringMethod.
References hpp::core::path::Hermite::create().
void hpp::core::steeringMethod::Hermite::init (HermiteWkPtr_t weak) inline protected
Store weak pointer to itself.
References hpp::core::SteeringMethod::init().
Referenced by create(), and createCopy().