hpp::core::Path Class Reference
hpp::core::Path Class Reference abstract
Path
Abstraction of paths: mapping from time to configuration space.
#include <hpp/core/path.hh>
Public Member Functions
Construction, destruction, copy
virtual ~Path () throw ()
Destructor.
virtual PathPtr_t copy () const =0
Return a shared pointer to a copy of this.
virtual PathPtr_t copy (const ConstraintSetPtr_t &constraints) const =0
Return a shared pointer to a copy of this and set constraints.
template<class T >
boost::shared_ptr< T > as (void)
Static cast into a derived type.
template<class T >
boost::shared_ptr< const T > as (void) const
Static cast into a derived type.
Extraction/Reversion of a sub-path
PathPtr_t extract (const interval_t &subInterval) const throw (projection_error)
PathPtr_t extract (const value_type &tmin, const value_type &tmax) const throw (projection_error)
virtual PathPtr_t reverse () const
Reversion of a path.
Evalutation of the path
Configuration_t operator() (const value_type &time) const HPP_CORE_DEPRECATED
Configuration_t operator() (const value_type &time, bool &success) const
bool operator() (ConfigurationOut_t result, const value_type &time) const throw ()
Configuration_t eval (const value_type &time, bool &success) const
bool eval (ConfigurationOut_t result, const value_type &time) const throw ()
bool at (const value_type &time, ConfigurationOut_t result) const
Get the configuration at a parameter without applying the constraints.
void derivative (vectorOut_t result, const value_type &time, size_type order) const
Get derivative with respect to parameter at given parameter.
void velocityBound (vectorOut_t result, const value_type &t0, const value_type &t1) const
Get an upper bound of the velocity on a sub-interval.
Path definition
size_type outputSize () const
Get size of configuration space.
size_type outputDerivativeSize () const
Get size of velocity.
const interval_t & timeRange () const
Get interval of definition.
virtual value_type length () const
Get length of definition interval.
virtual Configuration_t initial () const =0
Get the initial configuration.
virtual Configuration_t end () const =0
Get the final configuration.
const ConstraintSetPtr_t & constraints () const
Get constraints the path is subject to.
Time parameterizarion
Time parameterization is handled by this class so child classes need not to handle it.
const interval_t & paramRange () const
Get interval of parameters.
void timeParameterization (const TimeParameterizationPtr_t &tp, const interval_t &tr)
Set the time parameterization function.
Protected Member Functions
virtual std::ostream & print (std::ostream &os) const
Print interval of definition (and of parameters if relevant) in a stream.
Path (const interval_t &interval, size_type outputSize, size_type outputDerivativeSize, const ConstraintSetPtr_t &constraints)
Constructor.
Path (const interval_t &interval, size_type outputSize, size_type outputDerivativeSize)
Constructor.
Path (const Path &path)
Copy constructor.
Path (const Path &path, const ConstraintSetPtr_t &constraints)
Copy constructor with constraints.
void init (const PathWkPtr_t &self)
Store weak pointer to itself.
void constraints (const ConstraintSetPtr_t &constraint)
Set the constraints.
virtual void checkPath () const
Should be called by child classes after having init.
void timeRange (const interval_t &timeRange)
const TimeParameterizationPtr_t & timeParameterization () const
value_type paramLength () const
Configuration_t configAtParam (const value_type &param, bool &success) const
virtual bool impl_compute (ConfigurationOut_t configuration, value_type param) const =0
Function evaluation without applying constraints.
virtual void impl_derivative (vectorOut_t derivative, const value_type &param, size_type order) const
Virtual implementation of derivative.
virtual void impl_velocityBound (vectorOut_t bound, const value_type &param0, const value_type &param1) const
Virtual implementation of velocityBound.
virtual PathPtr_t impl_extract (const interval_t &paramInterval) const throw (projection_error)
Virtual implementation of extract.
Protected Attributes
interval_t paramRange_
Interval of parameters.
Friends
std::ostream & operator<< (std::ostream &os, const Path &path)
Detailed Description
Abstraction of paths: mapping from time to configuration space.
A path \(p \) is defined by:
\begin{eqnarray*} p : [t_0, t_1] &\to & \mathcal{C} \\ t &\mapsto & constraints.apply(q(t)) \end{eqnarray*}
where
\([t_0, t_1] \) is given by timeRange
\(q(t) \) is the child class implementation of impl_compute
constraints.apply corresponds to calling Constraint::apply to constraints
Optionally, it is possible to time-parameterize the path with a function \(s \). By default, \(s \) is the identity. The model becomes:
\begin{eqnarray*} p : [t_0, t_1] &\to & \mathcal{C} \\ t &\mapsto & constraints.apply(q(s(t))) \end{eqnarray*}
where \(s \) is the timeParameterization, from timeRange to paramRange.
Constructor & Destructor Documentation
virtual hpp::core::Path::~Path () throw () inline virtual
Destructor.
hpp::core::Path::Path (const interval_t & interval, size_type outputSize, size_type outputDerivativeSize, const ConstraintSetPtr_t & constraints) protected
Constructor.
Parameters
interval interval of definition of the path,
outputSize size of the output configuration,
outputDerivativeSize number of degrees of freedom of the underlying robot
constraints constraints the set is subject to, constraints are solved at each evaluation of the output configuration.
Note
Constraints are copied.
hpp::core::Path::Path (const interval_t & interval, size_type outputSize, size_type outputDerivativeSize) protected
Constructor.
Parameters
interval interval of definition of the path,
outputSize size of the output configuration,
outputDerivativeSize number of degrees of freedom of the underlying robot
hpp::core::Path::Path (const Path & path) protected
Copy constructor.
hpp::core::Path::Path (const Path & path, const ConstraintSetPtr_t & constraints) protected
Copy constructor with constraints.
Member Function Documentation
template<class T > boost::shared_ptr<T> hpp::core::Path::as (void) inline
Static cast into a derived type.
References assert(), HPP_DYNAMIC_PTR_CAST, and HPP_STATIC_PTR_CAST.
template<class T > boost::shared_ptr<const T> hpp::core::Path::as (void) const inline
Static cast into a derived type.
References assert(), HPP_DYNAMIC_PTR_CAST, and HPP_STATIC_PTR_CAST.
bool hpp::core::Path::at (const value_type & time, ConfigurationOut_t result) const inline
Get the configuration at a parameter without applying the constraints.
virtual void hpp::core::Path::checkPath () const protected virtual
Should be called by child classes after having init.
Referenced by hpp::core::KinodynamicOrientedPath::create(), hpp::core::KinodynamicPath::create(), hpp::core::StraightPath::create(), hpp::core::KinodynamicOrientedPath::createCopy(), hpp::core::KinodynamicPath::createCopy(), and hpp::core::StraightPath::createCopy().
Configuration_t hpp::core::Path::configAtParam (const value_type & param, bool & success) const inline protected
const ConstraintSetPtr_t& hpp::core::Path::constraints () const inline
Get constraints the path is subject to.
Referenced by hpp::core::SubchainPath::copy(), hpp::core::steeringMethod::ConstantCurvature::copy(), hpp::core::DubinsPath::copy(), hpp::core::steeringMethod::ConstantCurvature::~ConstantCurvature(), and hpp::core::DubinsPath::~DubinsPath().
void hpp::core::Path::constraints (const ConstraintSetPtr_t & constraint) inline protected
Set the constraints.
Warning
this method is protected for child classes that need to initialize themselves before being sure that the initial and end configuration satisfy the constraints
virtual PathPtr_t hpp::core::Path::copy () const pure virtual
Return a shared pointer to a copy of this.
Implemented in hpp::core::path::Spline< _PolynomeBasis, _Order >, hpp::core::path::Spline< BernsteinBasis, 3 >, hpp::core::StraightPath, hpp::core::InterpolatedPath, hpp::core::KinodynamicPath, hpp::core::DubinsPath, hpp::core::KinodynamicOrientedPath, hpp::core::ReedsSheppPath, hpp::core::path::Hermite, hpp::core::PathVector, hpp::core::steeringMethod::ConstantCurvature, and hpp::core::SubchainPath.
virtual PathPtr_t hpp::core::Path::copy (const ConstraintSetPtr_t & constraints) const pure virtual
Return a shared pointer to a copy of this and set constraints.
Parameters
constraints constraints to apply to the copy
Precondition
*this should not have constraints.
Implemented in hpp::core::path::Spline< _PolynomeBasis, _Order >, hpp::core::path::Spline< BernsteinBasis, 3 >, hpp::core::StraightPath, hpp::core::InterpolatedPath, hpp::core::KinodynamicPath, hpp::core::DubinsPath, hpp::core::KinodynamicOrientedPath, hpp::core::ReedsSheppPath, hpp::core::path::Hermite, hpp::core::PathVector, hpp::core::steeringMethod::ConstantCurvature, and hpp::core::SubchainPath.
void hpp::core::Path::derivative (vectorOut_t result, const value_type & time, size_type order) const
Get derivative with respect to parameter at given parameter.
Parameters
time value of the time in the definition interval,
order order of the derivative
Return values
result derivative. Should be allocated and of correct size.
Warning
the method is not implemented in this class and throws if called without being implemented in the derived class.
Note
unless otherwise stated, this method is not compatible with constraints. The derivative of the non-constrained path will be computed.
virtual Configuration_t hpp::core::Path::end () const pure virtual
Get the final configuration.
Implemented in hpp::core::path::Spline< _PolynomeBasis, _Order >, hpp::core::path::Spline< BernsteinBasis, 3 >, hpp::core::StraightPath, hpp::core::InterpolatedPath, hpp::core::DubinsPath, hpp::core::ReedsSheppPath, hpp::core::PathVector, hpp::core::path::Hermite, hpp::core::SubchainPath, and hpp::core::steeringMethod::ConstantCurvature.
Configuration_t hpp::core::Path::eval (const value_type & time, bool & success) const inline
bool hpp::core::Path::eval (ConfigurationOut_t result, const value_type & time) const throw () inline
PathPtr_t hpp::core::Path::extract (const interval_t & subInterval) const throw (projection_error)
Parameters
subInterval interval of definition of the extract path If upper bound of subInterval is smaller than lower bound, result is reversed.
Exceptions
projection_error is thrown when an end configuration of the returned path could not be computed due to projection failure.
PathPtr_t hpp::core::Path::extract (const value_type & tmin, const value_type & tmax) const throw (projection_error) inline
Parameters
subInterval interval of definition of the extract path If upper bound of subInterval is smaller than lower bound, result is reversed.
Exceptions
projection_error is thrown when an end configuration of the returned path could not be computed due to projection failure.
virtual bool hpp::core::Path::impl_compute (ConfigurationOut_t configuration, value_type param) const protected pure virtual
Function evaluation without applying constraints.
Returns
true if everything went good.
Implemented in hpp::core::path::Spline< _PolynomeBasis, _Order >, hpp::core::path::Spline< BernsteinBasis, 3 >, hpp::core::StraightPath, hpp::core::InterpolatedPath, hpp::core::PathVector, hpp::core::KinodynamicPath, hpp::core::KinodynamicOrientedPath, hpp::core::steeringMethod::ConstantCurvature, and hpp::core::SubchainPath.
virtual void hpp::core::Path::impl_derivative (vectorOut_t derivative, const value_type & param, size_type order) const inline protected virtual
Virtual implementation of derivative.
Parameters
param parameter within paramRange
order order of derivation.
Return values
derivative
Reimplemented in hpp::core::path::Spline< _PolynomeBasis, _Order >, hpp::core::path::Spline< BernsteinBasis, 3 >, hpp::core::StraightPath, hpp::core::InterpolatedPath, hpp::core::PathVector, hpp::core::ReedsSheppPath, and hpp::core::steeringMethod::ConstantCurvature.
References HPP_THROW_EXCEPTION.
virtual PathPtr_t hpp::core::Path::impl_extract (const interval_t & paramInterval) const throw (projection_error) protected virtual
Virtual implementation of extract.
Reimplemented in hpp::core::StraightPath, hpp::core::InterpolatedPath, hpp::core::PathVector, hpp::core::KinodynamicOrientedPath, hpp::core::steeringMethod::ConstantCurvature, and hpp::core::KinodynamicPath.
virtual void hpp::core::Path::impl_velocityBound (vectorOut_t bound, const value_type & param0, const value_type & param1) const inline protected virtual
Virtual implementation of velocityBound.
Parameters
param0,param1 interval of parameter
Return values
bound
Reimplemented in hpp::core::path::Spline< _PolynomeBasis, _Order >, hpp::core::path::Spline< BernsteinBasis, 3 >, hpp::core::StraightPath, hpp::core::InterpolatedPath, and hpp::core::steeringMethod::ConstantCurvature.
References HPP_THROW_EXCEPTION, and hpp::core::operator<<().
void hpp::core::Path::init (const PathWkPtr_t & self) protected
Store weak pointer to itself.
should be called at construction of derived class instances
Referenced by hpp::core::SubchainPath::init(), hpp::core::steeringMethod::ConstantCurvature::init(), and hpp::core::path::Spline< BernsteinBasis, 3 >::init().
virtual Configuration_t hpp::core::Path::initial () const pure virtual
Get the initial configuration.
Implemented in hpp::core::path::Spline< _PolynomeBasis, _Order >, hpp::core::path::Spline< BernsteinBasis, 3 >, hpp::core::StraightPath, hpp::core::InterpolatedPath, hpp::core::DubinsPath, hpp::core::ReedsSheppPath, hpp::core::PathVector, hpp::core::path::Hermite, hpp::core::SubchainPath, and hpp::core::steeringMethod::ConstantCurvature.
virtual value_type hpp::core::Path::length () const inline virtual
Get length of definition interval.
Configuration_t hpp::core::Path::operator() (const value_type & time) const inline
Deprecated:
Use operator()(value_type, bool)
Configuration_t hpp::core::Path::operator() (const value_type & time, bool & success) const inline
bool hpp::core::Path::operator() (ConfigurationOut_t result, const value_type & time) const throw () inline
size_type hpp::core::Path::outputDerivativeSize () const inline
Get size of velocity.
size_type hpp::core::Path::outputSize () const inline
Get size of configuration space.
Referenced by hpp::core::SubchainPath::end(), and hpp::core::SubchainPath::initial().
value_type hpp::core::Path::paramLength () const inline protected
const interval_t& hpp::core::Path::paramRange () const inline
Get interval of parameters.
Returns
the result of applying the timeParameterization to timeRange().
Note
The time parameterization defaults to identity.
virtual std::ostream& hpp::core::Path::print (std::ostream & os) const protected virtual
Print interval of definition (and of parameters if relevant) in a stream.
Reimplemented in hpp::core::path::Spline< _PolynomeBasis, _Order >, hpp::core::path::Spline< BernsteinBasis, 3 >, hpp::core::StraightPath, hpp::core::InterpolatedPath, hpp::core::KinodynamicPath, hpp::core::DubinsPath, hpp::core::PathVector, hpp::core::path::Hermite, hpp::core::ReedsSheppPath, hpp::core::KinodynamicOrientedPath, hpp::core::SubchainPath, and hpp::core::steeringMethod::ConstantCurvature.
Referenced by hpp::core::operator<<(), hpp::core::path::Hermite::print(), hpp::core::PathVector::print(), hpp::core::DubinsPath::print(), hpp::core::InterpolatedPath::print(), and hpp::core::StraightPath::print().
virtual PathPtr_t hpp::core::Path::reverse () const virtual
Reversion of a path.
Returns
a new path that is this one reversed.
Reimplemented in hpp::core::InterpolatedPath.
void hpp::core::Path::timeParameterization (const TimeParameterizationPtr_t & tp, const interval_t & tr) inline
Set the time parameterization function.
const TimeParameterizationPtr_t& hpp::core::Path::timeParameterization () const inline protected
const interval_t& hpp::core::Path::timeRange () const inline
Get interval of definition.
Referenced by hpp::core::PathVector::PathVector().
void hpp::core::Path::timeRange (const interval_t & timeRange) inline protected
void hpp::core::Path::velocityBound (vectorOut_t result, const value_type & t0, const value_type & t1) const inline
Get an upper bound of the velocity on a sub-interval.
The result is a coefficient-wise.
Parameters
t0 begin of the interval
t1 end of the interval
Return values
result maximal derivative on the sub-interval. Should be allocated and of correct size.
Warning
the method is not implemented in this class and throws if called without being implemented in the derived class.
Note
unless otherwise stated, this method is not compatible with constraints. The derivative of the non-constrained path will be computed.
References assert().
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & os, const Path & path) friend
Member Data Documentation
interval_t hpp::core::Path::paramRange_ protected
Interval of parameters.