hpp::core::ReedsSheppPath Class Reference
hpp::core::ReedsSheppPath Class Reference
Path
Car like motion.
#include <hpp/core/reeds-shepp-path.hh>
Public Types
typedef core::PathVector parent_t
Public Types inherited from hpp::core::PathVector
typedef Path parent_t
Public Member Functions
virtual ~ReedsSheppPath () throw ()
Destructor.
virtual PathPtr_t copy () const
Return a shared pointer to a copy of this object.
virtual PathPtr_t copy (const ConstraintSetPtr_t &constraints) const
Return a shared pointer to a copy of this and set constraints.
DevicePtr_t device () const
Return the internal robot.
Configuration_t initial () const
Get the initial configuration.
Configuration_t end () const
Get the final configuration.
Public Member Functions inherited from hpp::core::PathVector
std::size_t numberPaths () const
Get the number of sub paths.
PathPtr_t pathAtRank (std::size_t rank) const
Get a path in the vector.
std::size_t rankAtParam (const value_type &param, value_type &localParam) const
Get rank of direct path in vector at param.
void appendPath (const PathPtr_t &path)
Append a path at the end of the vector.
void concatenate (const PathVector &path) HPP_CORE_DEPRECATED
Concatenate two vectors of path.
void concatenate (const PathVectorPtr_t &path)
Concatenate two vectors of path.
void flatten (PathVectorPtr_t flattenedPath) const
Return the a path vector representing the same path but ensuring that there is no PathVector in the PathVector.
virtual ~PathVector () throw ()
Destructor.
Public Member Functions inherited from hpp::core::Path
virtual ~Path () throw ()
Destructor.
template<class T >
boost::shared_ptr< T > as (void)
Static cast into a derived type.
template<class T >
boost::shared_ptr< const T > as (void) const
Static cast into a derived type.
PathPtr_t extract (const interval_t &subInterval) const throw (projection_error)
PathPtr_t extract (const value_type &tmin, const value_type &tmax) const throw (projection_error)
virtual PathPtr_t reverse () const
Reversion of a path.
Configuration_t operator() (const value_type &time) const HPP_CORE_DEPRECATED
Configuration_t operator() (const value_type &time, bool &success) const
bool operator() (ConfigurationOut_t result, const value_type &time) const throw ()
Configuration_t eval (const value_type &time, bool &success) const
bool eval (ConfigurationOut_t result, const value_type &time) const throw ()
bool at (const value_type &time, ConfigurationOut_t result) const
Get the configuration at a parameter without applying the constraints.
void derivative (vectorOut_t result, const value_type &time, size_type order) const
Get derivative with respect to parameter at given parameter.
void velocityBound (vectorOut_t result, const value_type &t0, const value_type &t1) const
Get an upper bound of the velocity on a sub-interval.
size_type outputSize () const
Get size of configuration space.
size_type outputDerivativeSize () const
Get size of velocity.
const interval_t & timeRange () const
Get interval of definition.
virtual value_type length () const
Get length of definition interval.
const ConstraintSetPtr_t & constraints () const
Get constraints the path is subject to.
const interval_t & paramRange () const
Get interval of parameters.
void timeParameterization (const TimeParameterizationPtr_t &tp, const interval_t &tr)
Set the time parameterization function.
Static Public Member Functions
static ReedsSheppPathPtr_t create (const pinocchio::DevicePtr_t &device, ConfigurationIn_t init, ConfigurationIn_t end, value_type extraLength, value_type rho, size_type xyId, size_type rzId, const std::vector< JointPtr_t > wheels)
Create instance and return shared pointer.
static ReedsSheppPathPtr_t create (const DevicePtr_t &device, ConfigurationIn_t init, ConfigurationIn_t end, value_type extraLength, value_type rho, size_type xyId, size_type rzId, const std::vector< JointPtr_t > wheels, ConstraintSetPtr_t constraints)
Create instance and return shared pointer.
static ReedsSheppPathPtr_t createCopy (const ReedsSheppPathPtr_t &path)
Create copy and return shared pointer.
static ReedsSheppPathPtr_t createCopy (const ReedsSheppPathPtr_t &path, const ConstraintSetPtr_t &constraints)
Create copy and return shared pointer.
Static Public Member Functions inherited from hpp::core::PathVector
static PathVectorPtr_t create (size_type outputSize, size_type outputDerivativeSize)
Create instance and return shared pointer.
static PathVectorPtr_t createCopy (const PathVectorPtr_t &original)
Create instance and return shared pointer.
static PathVectorPtr_t createCopy (const PathVectorPtr_t &original, const ConstraintSetPtr_t &constraints)
Create instance and return shared pointer.
Protected Member Functions
virtual std::ostream & print (std::ostream &os) const
Print path in a stream.
ReedsSheppPath (const DevicePtr_t &robot, ConfigurationIn_t init, ConfigurationIn_t end, value_type extraLength, value_type rho, size_type xyId, size_type rzId, const std::vector< JointPtr_t > wheels)
Constructor.
ReedsSheppPath (const DevicePtr_t &robot, ConfigurationIn_t init, ConfigurationIn_t end, value_type extraLength, value_type rho, size_type xyId, size_type rzId, const std::vector< JointPtr_t > wheels, ConstraintSetPtr_t constraints)
Constructor with constraints.
ReedsSheppPath (const ReedsSheppPath &path)
Copy constructor.
ReedsSheppPath (const ReedsSheppPath &path, const ConstraintSetPtr_t &constraints)
Copy constructor with constraints.
void init (ReedsSheppPathPtr_t self)
virtual void impl_derivative (vectorOut_t result, const value_type &t, size_type order) const
Virtual implementation of derivative.
Protected Member Functions inherited from hpp::core::PathVector
PathVector (std::size_t outputSize, std::size_t outputDerivativeSize)
Constructor.
PathVector (const PathVector &path)
Copy constructor.
PathVector (const PathVector &path, const ConstraintSetPtr_t &constraints)
Copy constructor with constraints.
void init (PathVectorPtr_t self)
virtual bool impl_compute (ConfigurationOut_t result, value_type t) const
Function evaluation without applying constraints.
virtual PathPtr_t impl_extract (const interval_t &subInterval) const throw (projection_error)
Extraction of a sub-path.
Protected Member Functions inherited from hpp::core::Path
Path (const interval_t &interval, size_type outputSize, size_type outputDerivativeSize, const ConstraintSetPtr_t &constraints)
Constructor.
Path (const interval_t &interval, size_type outputSize, size_type outputDerivativeSize)
Constructor.
Path (const Path &path)
Copy constructor.
Path (const Path &path, const ConstraintSetPtr_t &constraints)
Copy constructor with constraints.
void init (const PathWkPtr_t &self)
Store weak pointer to itself.
void constraints (const ConstraintSetPtr_t &constraint)
Set the constraints.
virtual void checkPath () const
Should be called by child classes after having init.
void timeRange (const interval_t &timeRange)
const TimeParameterizationPtr_t & timeParameterization () const
value_type paramLength () const
Configuration_t configAtParam (const value_type &param, bool &success) const
virtual void impl_velocityBound (vectorOut_t bound, const value_type &param0, const value_type &param1) const
Virtual implementation of velocityBound.
Additional Inherited Members
Protected Attributes inherited from hpp::core::Path
interval_t paramRange_
Interval of parameters.
Detailed Description
Car like motion.
Implement a Reeds and Shepp motion generation on the base joint. Degrees of freedom are interpolated depending on the type of joint they parameterize: The following interpolation is made:
Reeds and Shepp interpolation for the base_joint_xy and base_joint_rz
If the wheel joints are passed using setWheelJoints, the configuration parameter of those joints are computed so that the wheel is aligned with the velocity.
linear interpolation for the other joints
Member Typedef Documentation
typedef core::PathVector hpp::core::ReedsSheppPath::parent_t
Constructor & Destructor Documentation
virtual hpp::core::ReedsSheppPath::~ReedsSheppPath () throw () inline virtual
Destructor.
References create().
hpp::core::ReedsSheppPath::ReedsSheppPath (const DevicePtr_t & robot, ConfigurationIn_t init, ConfigurationIn_t end, value_type extraLength, value_type rho, size_type xyId, size_type rzId, const std::vector< JointPtr_t > wheels) protected
Constructor.
hpp::core::ReedsSheppPath::ReedsSheppPath (const DevicePtr_t & robot, ConfigurationIn_t init, ConfigurationIn_t end, value_type extraLength, value_type rho, size_type xyId, size_type rzId, const std::vector< JointPtr_t > wheels, ConstraintSetPtr_t constraints) protected
Constructor with constraints.
hpp::core::ReedsSheppPath::ReedsSheppPath (const ReedsSheppPath & path) protected
Copy constructor.
hpp::core::ReedsSheppPath::ReedsSheppPath (const ReedsSheppPath & path, const ConstraintSetPtr_t & constraints) protected
Copy constructor with constraints.
Member Function Documentation
virtual PathPtr_t hpp::core::ReedsSheppPath::copy () const inline virtual
Return a shared pointer to a copy of this object.
Reimplemented from hpp::core::PathVector.
virtual PathPtr_t hpp::core::ReedsSheppPath::copy (const ConstraintSetPtr_t & constraints) const inline virtual
Return a shared pointer to a copy of this and set constraints.
Parameters
constraints constraints to apply to the copy
Precondition
*this should not have constraints.
Reimplemented from hpp::core::PathVector.
static ReedsSheppPathPtr_t hpp::core::ReedsSheppPath::create (const pinocchio::DevicePtr_t & device, ConfigurationIn_t init, ConfigurationIn_t end, value_type extraLength, value_type rho, size_type xyId, size_type rzId, const std::vector< JointPtr_t > wheels) static
Create instance and return shared pointer.
Parameters
device Robot corresponding to configurations
init,end Start and end configurations of the path
rho The radius of a turn.
extraLength the length of the path due to the non RS DoF
static ReedsSheppPathPtr_t hpp::core::ReedsSheppPath::create (const DevicePtr_t & device, ConfigurationIn_t init, ConfigurationIn_t end, value_type extraLength, value_type rho, size_type xyId, size_type rzId, const std::vector< JointPtr_t > wheels, ConstraintSetPtr_t constraints) static
Create instance and return shared pointer.
Parameters
device Robot corresponding to configurations
init,end Start and end configurations of the path
rho The radius of a turn.
extraLength the length of the path due to the non RS DoF
constraints the path is subject to
static ReedsSheppPathPtr_t hpp::core::ReedsSheppPath::createCopy (const ReedsSheppPathPtr_t & path) inline static
Create copy and return shared pointer.
Parameters
path path to copy
References init().
static ReedsSheppPathPtr_t hpp::core::ReedsSheppPath::createCopy (const ReedsSheppPathPtr_t & path, const ConstraintSetPtr_t & constraints) inline static
Create copy and return shared pointer.
Parameters
path path to copy
constraints the path is subject to
References init().
DevicePtr_t hpp::core::ReedsSheppPath::device () const inline
Return the internal robot.
Configuration_t hpp::core::ReedsSheppPath::end () const inline virtual
Get the final configuration.
Reimplemented from hpp::core::PathVector.
virtual void hpp::core::ReedsSheppPath::impl_derivative (vectorOut_t result, const value_type & t, size_type order) const protected virtual
Virtual implementation of derivative.
Reimplemented from hpp::core::PathVector.
void hpp::core::ReedsSheppPath::init (ReedsSheppPathPtr_t self) protected
Referenced by createCopy().
Configuration_t hpp::core::ReedsSheppPath::initial () const inline virtual
Get the initial configuration.
Reimplemented from hpp::core::PathVector.
virtual std::ostream& hpp::core::ReedsSheppPath::print (std::ostream & os) const protected virtual
Print path in a stream.
Reimplemented from hpp::core::PathVector.