hpp::core::path::Hermite Class Reference
hpp::core::path::Hermite Class Reference
Path
#include <hpp/core/path/hermite.hh>
Public Types
typedef Spline< BernsteinBasis, 3 > parent_t
Public Types inherited from hpp::core::path::Spline< BernsteinBasis, 3 >
enum
typedef internal::sbf_traits< PolynomeBasis, Order > sbf_traits
typedef internal::spline_basis_function< PolynomeBasis, Order > BasisFunction_t
typedef Eigen::Matrix< value_type, NbPowerOfT, 1 > PowersOfT_t
typedef sbf_traits::Coeffs_t BasisFunctionVector_t
typedef sbf_traits::IntegralCoeffs_t BasisFunctionIntegralMatrix_t
typedef Eigen::Matrix< value_type, NbCoeffs, Eigen::Dynamic, Eigen::RowMajor > ParameterMatrix_t
typedef Eigen::Map< const vector_t, Eigen::Aligned > ConstParameterVector_t
typedef Eigen::Map< vector_t, Eigen::Aligned > ParameterVector_t
typedef boost::shared_ptr< Spline > Ptr_t
typedef boost::weak_ptr< Spline > WkPtr_t
Public Member Functions
virtual ~Hermite () throw ()
Destructor.
virtual PathPtr_t copy () const
Return a shared pointer to this.
virtual PathPtr_t copy (const ConstraintSetPtr_t &constraints) const
Return a shared pointer to a copy of this and set constraints.
DevicePtr_t device () const
Return the internal robot.
void v0 (const vectorIn_t &speed)
void v1 (const vectorIn_t &speed)
vector_t v0 () const
vector_t v1 () const
virtual Configuration_t initial () const
Get the initial configuration.
virtual Configuration_t end () const
Get the final configuration.
const value_type & hermiteLength () const
void computeHermiteLength ()
vector_t velocity (const value_type &t) const
Public Member Functions inherited from hpp::core::path::Spline< BernsteinBasis, 3 >
size_type parameterSize () const
void parameterDerivativeCoefficients (vectorOut_t res, const value_type &t) const
The partial derivative with respects to the parameters is of the form
\begin{eqnarray*} \frac{\partial S}{\partial p_{k}} (q, p, t) &=& B_k(t) \times I \\ \frac{\partial S}{\partial q_{base}} (q, p, t) &=& I \end{eqnarray*}
This method returns the coefficients \((B_k(t))_{k} \).
void parameterIntegrate (vectorIn_t dParam)
Adds dParam to the parameters.
value_type squaredNormIntegral (const size_type order) const
Returns \(\int S^{(k)}(t)^T \times S^{(k)}(t) dt \).
void squaredNormIntegralDerivative (const size_type order, vectorOut_t res) const
Returns the derivative of squaredNormIntegral wrt the parameters.
void basisFunctionDerivative (const size_type order, const value_type &u, BasisFunctionVector_t &res) const
Returns a vector \((v_i) \) as
\[ v_i = T^{-k} b_i^{(k)}(u) \]
.
void basisFunctionDerivative (const size_type order, const value_type &u, vectorOut_t res) const
void maxVelocity (vectorOut_t res) const
Returns an upper bound of the velocity on the complete interval.
void squaredNormBasisFunctionIntegral (const size_type order, BasisFunctionIntegralMatrix_t &res) const
Returns a matrix \((m_{i,j}) \) as
\[ m_{i,j} = T^{1-2k} \int_0^1 b_i^{(k)}(u) b_j^{(k)}(u) du \]
.
void squaredNormBasisFunctionIntegral (const size_type order, matrixOut_t res) const
const Configuration_t & base () const
Get the base configuration.
void base (const Configuration_t &q)
const ParameterMatrix_t & parameters () const
Each row corresponds to a velocity of the robot.
void parameters (const ParameterMatrix_t &m)
Returns the \((P_i^T) \).
ConstParameterVector_t rowParameters () const
Concatenate the parameters as one vector (P_0^T, ..., P_n^T).
void rowParameters (vectorIn_t p)
Set the parameters.
PathPtr_t copy () const
Return a shared pointer to a copy of this.
PathPtr_t copy (const ConstraintSetPtr_t &constraints) const
Return a shared pointer to a copy of this and set constraints.
virtual ~Spline () throw ()
Public Member Functions inherited from hpp::core::Path
virtual ~Path () throw ()
Destructor.
template<class T >
boost::shared_ptr< T > as (void)
Static cast into a derived type.
template<class T >
boost::shared_ptr< const T > as (void) const
Static cast into a derived type.
PathPtr_t extract (const interval_t &subInterval) const throw (projection_error)
PathPtr_t extract (const value_type &tmin, const value_type &tmax) const throw (projection_error)
virtual PathPtr_t reverse () const
Reversion of a path.
Configuration_t operator() (const value_type &time) const HPP_CORE_DEPRECATED
Configuration_t operator() (const value_type &time, bool &success) const
bool operator() (ConfigurationOut_t result, const value_type &time) const throw ()
Configuration_t eval (const value_type &time, bool &success) const
bool eval (ConfigurationOut_t result, const value_type &time) const throw ()
bool at (const value_type &time, ConfigurationOut_t result) const
Get the configuration at a parameter without applying the constraints.
void derivative (vectorOut_t result, const value_type &time, size_type order) const
Get derivative with respect to parameter at given parameter.
void velocityBound (vectorOut_t result, const value_type &t0, const value_type &t1) const
Get an upper bound of the velocity on a sub-interval.
size_type outputSize () const
Get size of configuration space.
size_type outputDerivativeSize () const
Get size of velocity.
const interval_t & timeRange () const
Get interval of definition.
virtual value_type length () const
Get length of definition interval.
const ConstraintSetPtr_t & constraints () const
Get constraints the path is subject to.
const interval_t & paramRange () const
Get interval of parameters.
void timeParameterization (const TimeParameterizationPtr_t &tp, const interval_t &tr)
Set the time parameterization function.
Static Public Member Functions
static HermitePtr_t create (const DevicePtr_t &device, ConfigurationIn_t init, ConfigurationIn_t end, ConstraintSetPtr_t constraints)
static HermitePtr_t createCopy (const HermitePtr_t &path)
Create copy and return shared pointer.
static HermitePtr_t createCopy (const HermitePtr_t &path, const ConstraintSetPtr_t &constraints)
Create copy and return shared pointer.
Static Public Member Functions inherited from hpp::core::path::Spline< BernsteinBasis, 3 >
static void timeFreeBasisFunctionDerivative (const size_type order, const value_type &u, BasisFunctionVector_t &res)
Returns a vector \((v_i) \) as
\[ v_i = b_i^{(k)}(u) \]
.
static void timeFreeBasisFunctionDerivative (const size_type order, const value_type &u, vectorOut_t res)
static Ptr_t create (const DevicePtr_t &robot, const interval_t &interval, const ConstraintSetPtr_t &constraints)
static void value (pinocchio::LiegroupElementConstRef base, Eigen::Ref< const ParameterMatrix_t > params, const value_type &u, ConfigurationOut_t config, vectorOut_t velocity)
Evaluate a spline.
Protected Member Functions
virtual std::ostream & print (std::ostream &os) const
Print path in a stream.
Hermite (const DevicePtr_t &robot, ConfigurationIn_t init, ConfigurationIn_t end)
Constructor.
Hermite (const DevicePtr_t &robot, ConfigurationIn_t init, ConfigurationIn_t end, ConstraintSetPtr_t constraints)
Constructor with constraints.
Hermite (const Hermite &path)
Copy constructor.
Hermite (const Hermite &path, const ConstraintSetPtr_t &constraints)
Copy constructor with constraints.
void init (HermitePtr_t self)
Protected Member Functions inherited from hpp::core::path::Spline< BernsteinBasis, 3 >
Spline (const DevicePtr_t &robot, const interval_t &interval, const ConstraintSetPtr_t &constraints)
Spline (const Spline &path)
Spline (const Spline &path, const ConstraintSetPtr_t &constraints)
void init (const Ptr_t &self)
std::ostream & print (std::ostream &os) const
Print interval of definition (and of parameters if relevant) in a stream.
bool impl_compute (ConfigurationOut_t configuration, value_type t) const
Function evaluation without applying constraints.
void impl_derivative (vectorOut_t res, const value_type &t, size_type order) const
Virtual implementation of derivative.
void impl_paramDerivative (vectorOut_t res, const value_type &t) const
void impl_paramIntegrate (vectorIn_t dParam)
void impl_velocityBound (vectorOut_t result, const value_type &t0, const value_type &t1) const
Virtual implementation of velocityBound.
Protected Member Functions inherited from hpp::core::Path
Path (const interval_t &interval, size_type outputSize, size_type outputDerivativeSize, const ConstraintSetPtr_t &constraints)
Constructor.
Path (const interval_t &interval, size_type outputSize, size_type outputDerivativeSize)
Constructor.
Path (const Path &path)
Copy constructor.
Path (const Path &path, const ConstraintSetPtr_t &constraints)
Copy constructor with constraints.
void init (const PathWkPtr_t &self)
Store weak pointer to itself.
void constraints (const ConstraintSetPtr_t &constraint)
Set the constraints.
virtual void checkPath () const
Should be called by child classes after having init.
void timeRange (const interval_t &timeRange)
const TimeParameterizationPtr_t & timeParameterization () const
value_type paramLength () const
Configuration_t configAtParam (const value_type &param, bool &success) const
virtual PathPtr_t impl_extract (const interval_t &paramInterval) const throw (projection_error)
Virtual implementation of extract.
Additional Inherited Members
Protected Attributes inherited from hpp::core::path::Spline< BernsteinBasis, 3 >
size_type parameterSize_
Robot number of degrees of freedom.
DevicePtr_t robot_
LiegroupElement base_
Base of the spline path.
ParameterMatrix_t parameters_
Parameters of the spline are stored in a matrix number of rows = degree of polynomial + 1 number of columns = robot number of degrees of freedom.
Protected Attributes inherited from hpp::core::Path
interval_t paramRange_
Interval of parameters.
Member Typedef Documentation
typedef Spline<BernsteinBasis,3> hpp::core::path::Hermite::parent_t
Constructor & Destructor Documentation
virtual hpp::core::path::Hermite::~Hermite () throw () inline virtual
Destructor.
hpp::core::path::Hermite::Hermite (const DevicePtr_t & robot, ConfigurationIn_t init, ConfigurationIn_t end) protected
Constructor.
hpp::core::path::Hermite::Hermite (const DevicePtr_t & robot, ConfigurationIn_t init, ConfigurationIn_t end, ConstraintSetPtr_t constraints) protected
Constructor with constraints.
hpp::core::path::Hermite::Hermite (const Hermite & path) protected
Copy constructor.
hpp::core::path::Hermite::Hermite (const Hermite & path, const ConstraintSetPtr_t & constraints) protected
Copy constructor with constraints.
Member Function Documentation
void hpp::core::path::Hermite::computeHermiteLength ()
virtual PathPtr_t hpp::core::path::Hermite::copy () const inline virtual
Return a shared pointer to this.
As StaightPath are immutable, and refered to by shared pointers, they do not need to be copied.
Implements hpp::core::Path.
virtual PathPtr_t hpp::core::path::Hermite::copy (const ConstraintSetPtr_t & constraints) const inline virtual
Return a shared pointer to a copy of this and set constraints.
Parameters
constraints constraints to apply to the copy
Precondition
*this should not have constraints.
Implements hpp::core::Path.
static HermitePtr_t hpp::core::path::Hermite::create (const DevicePtr_t & device, ConfigurationIn_t init, ConfigurationIn_t end, ConstraintSetPtr_t constraints) inline static
References init().
Referenced by hpp::core::steeringMethod::Hermite::impl_compute().
static HermitePtr_t hpp::core::path::Hermite::createCopy (const HermitePtr_t & path) inline static
Create copy and return shared pointer.
Parameters
path path to copy
References init().
static HermitePtr_t hpp::core::path::Hermite::createCopy (const HermitePtr_t & path, const ConstraintSetPtr_t & constraints) inline static
Create copy and return shared pointer.
Parameters
path path to copy
constraints the path is subject to
References init().
DevicePtr_t hpp::core::path::Hermite::device () const
Return the internal robot.
virtual Configuration_t hpp::core::path::Hermite::end () const inline virtual
Get the final configuration.
Reimplemented from hpp::core::path::Spline< BernsteinBasis, 3 >.
const value_type& hpp::core::path::Hermite::hermiteLength () const inline
void hpp::core::path::Hermite::init (HermitePtr_t self) protected
Referenced by create(), and createCopy().
virtual Configuration_t hpp::core::path::Hermite::initial () const inline virtual
Get the initial configuration.
Reimplemented from hpp::core::path::Spline< BernsteinBasis, 3 >.
virtual std::ostream& hpp::core::path::Hermite::print (std::ostream & os) const inline protected virtual
Print path in a stream.
Reimplemented from hpp::core::Path.
References hpp::core::Path::print().
void hpp::core::path::Hermite::v0 (const vectorIn_t & speed) inline
vector_t hpp::core::path::Hermite::v0 () const inline
void hpp::core::path::Hermite::v1 (const vectorIn_t & speed) inline
vector_t hpp::core::path::Hermite::v1 () const inline
vector_t hpp::core::path::Hermite::velocity (const value_type & t) const