hpp::core::steeringMethod::ConstantCurvature Class Reference
hpp::core::steeringMethod::ConstantCurvature Class Reference
Path of constant curvature for a carlike robot.
#include <hpp/core/steering-method/constant-curvature.hh>
Public Types
typedef Path parent_t
Public Member Functions
virtual ~ConstantCurvature () throw ()
virtual PathPtr_t copy () const
Return a shared pointer to a copy of this.
virtual PathPtr_t copy (const ConstraintSetPtr_t &constraints) const
Return a shared pointer to a copy of this with constraints.
Configuration_t initial () const
Get the initial configuration.
Configuration_t end () const
Get the final configuration.
Public Member Functions inherited from hpp::core::Path
virtual ~Path () throw ()
Destructor.
template<class T >
boost::shared_ptr< T > as (void)
Static cast into a derived type.
template<class T >
boost::shared_ptr< const T > as (void) const
Static cast into a derived type.
PathPtr_t extract (const interval_t &subInterval) const throw (projection_error)
PathPtr_t extract (const value_type &tmin, const value_type &tmax) const throw (projection_error)
virtual PathPtr_t reverse () const
Reversion of a path.
Configuration_t operator() (const value_type &time) const HPP_CORE_DEPRECATED
Configuration_t operator() (const value_type &time, bool &success) const
bool operator() (ConfigurationOut_t result, const value_type &time) const throw ()
Configuration_t eval (const value_type &time, bool &success) const
bool eval (ConfigurationOut_t result, const value_type &time) const throw ()
bool at (const value_type &time, ConfigurationOut_t result) const
Get the configuration at a parameter without applying the constraints.
void derivative (vectorOut_t result, const value_type &time, size_type order) const
Get derivative with respect to parameter at given parameter.
void velocityBound (vectorOut_t result, const value_type &t0, const value_type &t1) const
Get an upper bound of the velocity on a sub-interval.
size_type outputSize () const
Get size of configuration space.
size_type outputDerivativeSize () const
Get size of velocity.
const interval_t & timeRange () const
Get interval of definition.
virtual value_type length () const
Get length of definition interval.
const ConstraintSetPtr_t & constraints () const
Get constraints the path is subject to.
const interval_t & paramRange () const
Get interval of parameters.
void timeParameterization (const TimeParameterizationPtr_t &tp, const interval_t &tr)
Set the time parameterization function.
Static Public Member Functions
static ConstantCurvaturePtr_t create (const DevicePtr_t &robot, ConfigurationIn_t init, ConfigurationIn_t end, value_type curveLength, value_type pathLength, value_type curvature, size_type xyId, size_type rzId, const JointPtr_t rz, const std::vector< JointPtr_t > wheels, const ConstraintSetPtr_t &constraints)
Create instance and return shared pointer.
static ConstantCurvaturePtr_t createCopy (const ConstantCurvaturePtr_t &other)
Create instance and return shared pointer.
static ConstantCurvaturePtr_t createCopy (const ConstantCurvaturePtr_t &other, const ConstraintSetPtr_t &constraints)
Create instance and return shared pointer.
Protected Member Functions
virtual std::ostream & print (std::ostream &os) const
Print path in a stream.
ConstantCurvature (const DevicePtr_t &robot, ConfigurationIn_t init, ConfigurationIn_t end, value_type curveLength, value_type pathLength, value_type curvature, size_type xyId, size_type rzId, const JointPtr_t rz, const std::vector< JointPtr_t > wheels)
Constructor.
ConstantCurvature (const DevicePtr_t &robot, ConfigurationIn_t init, ConfigurationIn_t end, value_type curveLength, value_type pathLength, value_type curvature, size_type xyId, size_type rzId, const JointPtr_t rz, const std::vector< JointPtr_t > wheels, ConstraintSetPtr_t constraints)
Constructor.
ConstantCurvature (const ConstantCurvature &other)
Copy constructor.
ConstantCurvature (const ConstantCurvature &other, const ConstraintSetPtr_t &constraints)
Copy constructor with constraints.
virtual bool impl_compute (ConfigurationOut_t result, value_type param) const
Function evaluation without applying constraints.
virtual void impl_derivative (vectorOut_t result, const value_type &param, size_type order) const
Virtual implementation of derivative.
virtual void impl_velocityBound (vectorOut_t bound, const value_type &param0, const value_type &param1) const
Virtual implementation of velocity bound.
virtual PathPtr_t impl_extract (const interval_t &paramInterval) const throw (projection_error)
Virtual implementation of path extraction.
void init (const ConstantCurvatureWkPtr_t &weak)
store weak pointer to itself
Protected Member Functions inherited from hpp::core::Path
Path (const interval_t &interval, size_type outputSize, size_type outputDerivativeSize, const ConstraintSetPtr_t &constraints)
Constructor.
Path (const interval_t &interval, size_type outputSize, size_type outputDerivativeSize)
Constructor.
Path (const Path &path)
Copy constructor.
Path (const Path &path, const ConstraintSetPtr_t &constraints)
Copy constructor with constraints.
void init (const PathWkPtr_t &self)
Store weak pointer to itself.
void constraints (const ConstraintSetPtr_t &constraint)
Set the constraints.
virtual void checkPath () const
Should be called by child classes after having init.
void timeRange (const interval_t &timeRange)
const TimeParameterizationPtr_t & timeParameterization () const
value_type paramLength () const
Configuration_t configAtParam (const value_type &param, bool &success) const
Additional Inherited Members
Protected Attributes inherited from hpp::core::Path
interval_t paramRange_
Interval of parameters.
Detailed Description
Path of constant curvature for a carlike robot.
Member Typedef Documentation
typedef Path hpp::core::steeringMethod::ConstantCurvature::parent_t
Constructor & Destructor Documentation
virtual hpp::core::steeringMethod::ConstantCurvature::~ConstantCurvature () throw () inline virtual
References hpp::core::Path::constraints(), copy(), create(), createCopy(), end(), and init().
hpp::core::steeringMethod::ConstantCurvature::ConstantCurvature (const DevicePtr_t & robot, ConfigurationIn_t init, ConfigurationIn_t end, value_type curveLength, value_type pathLength, value_type curvature, size_type xyId, size_type rzId, const JointPtr_t rz, const std::vector< JointPtr_t > wheels) protected
Constructor.
Parameters
robot the carlike robot,
init,end Initial and final configurations of the path,
curveLength distance traveled by the middle of the rear wheel axis, negative values correspond to backward motions
pathLength length of the interval of definition. Should be positive,
curvature curvature of the path,
xyId id of degrees of freedom corresponding to (x,y) coordinates of robot,
rzId id of degrees of freedom corresponding to orientation of robot.
rz joint corresponding to orientation of robot,
wheels vector of joints corresponding to wheels.
Referenced by end().
hpp::core::steeringMethod::ConstantCurvature::ConstantCurvature (const DevicePtr_t & robot, ConfigurationIn_t init, ConfigurationIn_t end, value_type curveLength, value_type pathLength, value_type curvature, size_type xyId, size_type rzId, const JointPtr_t rz, const std::vector< JointPtr_t > wheels, ConstraintSetPtr_t constraints) protected
Constructor.
Parameters
robot the carlike robot,
init,end Initial and final configurations of the path,
curveLength distance traveled by the middle of the rear wheel axis, negative values correspond to backward motions
pathLength length of the interval of definition. Should be positive,
curvature curvature of the path,
xyId id of degrees of freedom corresponding to (x,y) coordinates of robot,
rzId id of degrees of freedom corresponding to orientation of robot.
rz joint corresponding to orientation of robot,
wheels vector of joints corresponding to wheels,
constraints set of contraints the path is suject to.
hpp::core::steeringMethod::ConstantCurvature::ConstantCurvature (const ConstantCurvature & other) protected
Copy constructor.
hpp::core::steeringMethod::ConstantCurvature::ConstantCurvature (const ConstantCurvature & other, const ConstraintSetPtr_t & constraints) protected
Copy constructor with constraints.
Member Function Documentation
virtual PathPtr_t hpp::core::steeringMethod::ConstantCurvature::copy () const virtual
Return a shared pointer to a copy of this.
Implements hpp::core::Path.
Referenced by ~ConstantCurvature().
virtual PathPtr_t hpp::core::steeringMethod::ConstantCurvature::copy (const ConstraintSetPtr_t & constraints) const inline virtual
Return a shared pointer to a copy of this with constraints.
Parameters
constraints constraints to apply to the copy
Precondition
*this should not have constraints.
Implements hpp::core::Path.
References hpp::core::Path::constraints(), and createCopy().
static ConstantCurvaturePtr_t hpp::core::steeringMethod::ConstantCurvature::create (const DevicePtr_t & robot, ConfigurationIn_t init, ConfigurationIn_t end, value_type curveLength, value_type pathLength, value_type curvature, size_type xyId, size_type rzId, const JointPtr_t rz, const std::vector< JointPtr_t > wheels, const ConstraintSetPtr_t & constraints) static
Create instance and return shared pointer.
Parameters
robot the carlike robot,
init,end Initial and final configurations of the path,
curveLength distance traveled by the middle of the rear wheel axis, negative values correspond to backward motions
pathLength length of the interval of definition. Should be positive,
curvature curvature of the path,
xyId id of degrees of freedom corresponding to (x,y) coordinates of robot,
rzId id of degrees of freedom corresponding to orientation of robot.
rz joint corresponding to orientation of robot,
wheels vector of joints corresponding to wheels,
constraints set of contraints the path is suject to.
Referenced by ~ConstantCurvature().
static ConstantCurvaturePtr_t hpp::core::steeringMethod::ConstantCurvature::createCopy (const ConstantCurvaturePtr_t & other) static
Create instance and return shared pointer.
Referenced by copy(), and ~ConstantCurvature().
static ConstantCurvaturePtr_t hpp::core::steeringMethod::ConstantCurvature::createCopy (const ConstantCurvaturePtr_t & other, const ConstraintSetPtr_t & constraints) static
Create instance and return shared pointer.
Configuration_t hpp::core::steeringMethod::ConstantCurvature::end () const inline virtual
Get the final configuration.
Implements hpp::core::Path.
References ConstantCurvature(), impl_compute(), impl_derivative(), impl_extract(), impl_velocityBound(), and print().
Referenced by ~ConstantCurvature().
virtual bool hpp::core::steeringMethod::ConstantCurvature::impl_compute (ConfigurationOut_t configuration, value_type param) const protected virtual
Function evaluation without applying constraints.
Returns
true if everything went good.
Implements hpp::core::Path.
Referenced by end().
virtual void hpp::core::steeringMethod::ConstantCurvature::impl_derivative (vectorOut_t result, const value_type & param, size_type order) const protected virtual
Virtual implementation of derivative.
Reimplemented from hpp::core::Path.
Referenced by end().
virtual PathPtr_t hpp::core::steeringMethod::ConstantCurvature::impl_extract (const interval_t & paramInterval) const throw (projection_error) protected virtual
Virtual implementation of path extraction.
Reimplemented from hpp::core::Path.
Referenced by end().
virtual void hpp::core::steeringMethod::ConstantCurvature::impl_velocityBound (vectorOut_t bound, const value_type & param0, const value_type & param1) const protected virtual
Virtual implementation of velocity bound.
Reimplemented from hpp::core::Path.
Referenced by end().
void hpp::core::steeringMethod::ConstantCurvature::init (const ConstantCurvatureWkPtr_t & weak) inline protected
store weak pointer to itself
References hpp::core::Path::init().
Referenced by ~ConstantCurvature().
Configuration_t hpp::core::steeringMethod::ConstantCurvature::initial () const inline virtual
Get the initial configuration.
Implements hpp::core::Path.
virtual std::ostream& hpp::core::steeringMethod::ConstantCurvature::print (std::ostream & os) const protected virtual
Print path in a stream.
Reimplemented from hpp::core::Path.
Referenced by end().