hpp::core::SubchainPath Class Reference
hpp::core::SubchainPath Class Reference
Path
Result of the selection of some configuration parameter of an original path.
#include <hpp/core/subchain-path.hh>
Public Types
typedef Path parent_t
Public Member Functions
virtual ~SubchainPath () throw ()
virtual PathPtr_t copy () const
Return a shared pointer to a copy of this.
virtual PathPtr_t copy (const ConstraintSetPtr_t &constraints) const
Return a shared pointer to a copy of this and set constraints.
virtual bool impl_compute (ConfigurationOut_t result, value_type param) const
Function evaluation without applying constraints.
Configuration_t initial () const
Get the initial configuration.
Configuration_t end () const
Get the final configuration.
void dofExtract (ConfigurationIn_t qin, ConfigurationOut_t qout) const
Public Member Functions inherited from hpp::core::Path
virtual ~Path () throw ()
Destructor.
template<class T >
boost::shared_ptr< T > as (void)
Static cast into a derived type.
template<class T >
boost::shared_ptr< const T > as (void) const
Static cast into a derived type.
PathPtr_t extract (const interval_t &subInterval) const throw (projection_error)
PathPtr_t extract (const value_type &tmin, const value_type &tmax) const throw (projection_error)
virtual PathPtr_t reverse () const
Reversion of a path.
Configuration_t operator() (const value_type &time) const HPP_CORE_DEPRECATED
Configuration_t operator() (const value_type &time, bool &success) const
bool operator() (ConfigurationOut_t result, const value_type &time) const throw ()
Configuration_t eval (const value_type &time, bool &success) const
bool eval (ConfigurationOut_t result, const value_type &time) const throw ()
bool at (const value_type &time, ConfigurationOut_t result) const
Get the configuration at a parameter without applying the constraints.
void derivative (vectorOut_t result, const value_type &time, size_type order) const
Get derivative with respect to parameter at given parameter.
void velocityBound (vectorOut_t result, const value_type &t0, const value_type &t1) const
Get an upper bound of the velocity on a sub-interval.
size_type outputSize () const
Get size of configuration space.
size_type outputDerivativeSize () const
Get size of velocity.
const interval_t & timeRange () const
Get interval of definition.
virtual value_type length () const
Get length of definition interval.
const ConstraintSetPtr_t & constraints () const
Get constraints the path is subject to.
const interval_t & paramRange () const
Get interval of parameters.
void timeParameterization (const TimeParameterizationPtr_t &tp, const interval_t &tr)
Set the time parameterization function.
Static Public Member Functions
static SubchainPathPtr_t create (const PathPtr_t &original, const segments_t &confIntervals, const segments_t &velIntervals)
Constructor.
static SubchainPathPtr_t createCopy (const SubchainPathPtr_t &path)
static SubchainPathPtr_t createCopy (const SubchainPathPtr_t &path, const ConstraintSetPtr_t &constraints)
Protected Member Functions
virtual std::ostream & print (std::ostream &os) const
Print path in a stream.
SubchainPath (const PathPtr_t &original, const segments_t &confIntervals, const segments_t &velIntervals)
Constructor.
SubchainPath (const SubchainPath &path)
SubchainPath (const SubchainPath &path, const ConstraintSetPtr_t &constraints)
void init (SubchainPathPtr_t self)
Protected Member Functions inherited from hpp::core::Path
Path (const interval_t &interval, size_type outputSize, size_type outputDerivativeSize, const ConstraintSetPtr_t &constraints)
Constructor.
Path (const interval_t &interval, size_type outputSize, size_type outputDerivativeSize)
Constructor.
Path (const Path &path)
Copy constructor.
Path (const Path &path, const ConstraintSetPtr_t &constraints)
Copy constructor with constraints.
void init (const PathWkPtr_t &self)
Store weak pointer to itself.
void constraints (const ConstraintSetPtr_t &constraint)
Set the constraints.
virtual void checkPath () const
Should be called by child classes after having init.
void timeRange (const interval_t &timeRange)
const TimeParameterizationPtr_t & timeParameterization () const
value_type paramLength () const
Configuration_t configAtParam (const value_type &param, bool &success) const
virtual void impl_derivative (vectorOut_t derivative, const value_type &param, size_type order) const
Virtual implementation of derivative.
virtual void impl_velocityBound (vectorOut_t bound, const value_type &param0, const value_type &param1) const
Virtual implementation of velocityBound.
virtual PathPtr_t impl_extract (const interval_t &paramInterval) const throw (projection_error)
Virtual implementation of extract.
Additional Inherited Members
Protected Attributes inherited from hpp::core::Path
interval_t paramRange_
Interval of parameters.
Detailed Description
Result of the selection of some configuration parameter of an original path.
Note
Decorator design pattern
Todo:
the configuration parameter cannot be rearranged.
Member Typedef Documentation
typedef Path hpp::core::SubchainPath::parent_t
Constructor & Destructor Documentation
virtual hpp::core::SubchainPath::~SubchainPath () throw () inline virtual
hpp::core::SubchainPath::SubchainPath (const PathPtr_t & original, const segments_t & confIntervals, const segments_t & velIntervals) inline protected
Constructor.
Parameters
original Path to extract,
confIntervals of the configuration parameters to be extracted
velIntervals of the configuration parameters to be extracted
Referenced by create(), and createCopy().
hpp::core::SubchainPath::SubchainPath (const SubchainPath & path) inline protected
hpp::core::SubchainPath::SubchainPath (const SubchainPath & path, const ConstraintSetPtr_t & constraints) inline protected
Member Function Documentation
virtual PathPtr_t hpp::core::SubchainPath::copy () const inline virtual
Return a shared pointer to a copy of this.
Implements hpp::core::Path.
References createCopy().
virtual PathPtr_t hpp::core::SubchainPath::copy (const ConstraintSetPtr_t & constraints) const inline virtual
Return a shared pointer to a copy of this and set constraints.
Parameters
constraints constraints to apply to the copy
Precondition
*this should not have constraints.
Implements hpp::core::Path.
References hpp::core::Path::constraints(), and createCopy().
static SubchainPathPtr_t hpp::core::SubchainPath::create (const PathPtr_t & original, const segments_t & confIntervals, const segments_t & velIntervals) inline static
Constructor.
Parameters
original Path to extract,
confIntervals of the configuration parameters to be extracted
velIntervals of the configuration parameters to be extracted
References init(), and SubchainPath().
static SubchainPathPtr_t hpp::core::SubchainPath::createCopy (const SubchainPathPtr_t & path) inline static
References init(), and SubchainPath().
Referenced by copy().
static SubchainPathPtr_t hpp::core::SubchainPath::createCopy (const SubchainPathPtr_t & path, const ConstraintSetPtr_t & constraints) inline static
References init(), and SubchainPath().
void hpp::core::SubchainPath::dofExtract (ConfigurationIn_t qin, ConfigurationOut_t qout) const inline
References Eigen::MatrixBlocksBase< Derived >::rview().
Referenced by end(), impl_compute(), and initial().
Configuration_t hpp::core::SubchainPath::end () const inline virtual
Get the final configuration.
Implements hpp::core::Path.
References dofExtract(), and hpp::core::Path::outputSize().
virtual bool hpp::core::SubchainPath::impl_compute (ConfigurationOut_t configuration, value_type param) const inline virtual
Function evaluation without applying constraints.
Returns
true if everything went good.
Implements hpp::core::Path.
References dofExtract().
void hpp::core::SubchainPath::init (SubchainPathPtr_t self) inline protected
References hpp::core::Path::init().
Referenced by create(), and createCopy().
Configuration_t hpp::core::SubchainPath::initial () const inline virtual
Get the initial configuration.
Implements hpp::core::Path.
References dofExtract(), and hpp::core::Path::outputSize().
virtual std::ostream& hpp::core::SubchainPath::print (std::ostream & os) const inline protected virtual
Print path in a stream.
Reimplemented from hpp::core::Path.