hpp::core::configurationShooter::Uniform Class Reference
hpp::core::configurationShooter::Uniform Class Reference
Configuration Sampling
Uniformly sample with bounds of degrees of freedom.
#include <hpp/core/configuration-shooter/uniform.hh>
Public Member Functions
virtual void shoot (Configuration_t &q) const
Shoot a random configuration.
void sampleExtraDOF (bool sampleExtraDOF)
Public Member Functions inherited from hpp::core::ConfigurationShooter
virtual ConfigurationPtr_t shoot () const
Shoot a random configuration.
virtual ~ConfigurationShooter ()
Static Public Member Functions
static UniformPtr_t create (const DevicePtr_t &robot)
Protected Member Functions
Uniform (const DevicePtr_t &robot)
Uniformly sample configuration space.
void init (const UniformPtr_t &self)
Protected Member Functions inherited from hpp::core::ConfigurationShooter
ConfigurationShooter ()
void init (const ConfigurationShooterWkPtr_t &weak)
Store weak pointer to itself.
Detailed Description
Uniformly sample with bounds of degrees of freedom.
Constructor & Destructor Documentation
hpp::core::configurationShooter::Uniform::Uniform (const DevicePtr_t & robot) inline protected
Uniformly sample configuration space.
Note that translation joints have to be bounded.
Member Function Documentation
static UniformPtr_t hpp::core::configurationShooter::Uniform::create (const DevicePtr_t & robot) inline static
References init().
void hpp::core::configurationShooter::Uniform::init (const UniformPtr_t & self) inline protected
References hpp::core::ConfigurationShooter::init().
Referenced by create().
void hpp::core::configurationShooter::Uniform::sampleExtraDOF (bool sampleExtraDOF) inline
virtual void hpp::core::configurationShooter::Uniform::shoot (Configuration_t & q) const virtual
Shoot a random configuration.
Parameters
q the configuration (resized if necessary).
Implements hpp::core::ConfigurationShooter.