Steering method and distance functions
Steering method and distance functions
Some system are subject to kinematic or dynamic constraints.
Classes
class hpp::core::distance::ReedsShepp
Reeds and Shepp distance.
class hpp::core::Distance
Abstract class for distance between configurations.
class hpp::core::KinodynamicDistance
This class computed the Distance between two states as the minimal time required to connect this two states with a "bang-bang" trajectory, given velocity and acceleration bounds.
class hpp::core::steeringMethod::CarLike
Abstract class that implements various type of trajectories for carlike vehicles.
class hpp::core::steeringMethod::Dubins
Steering method that creates DubinsPath instances.
class hpp::core::steeringMethod::Hermite
Steering method that creates path::Hermite instances.
class hpp::core::steeringMethod::Interpolated
Steering method that creates StraightPath instances.
class hpp::core::steeringMethod::ReedsShepp
Steering method that creates ReedsSheppPath instances.
class hpp::core::steeringMethod::Snibud
Steering method that creates backward Dubins paths.
class hpp::core::steeringMethod::Spline< _PolynomeBasis, _SplineOrder >
Steering method that creates path::Spline instances.
class hpp::core::steeringMethod::Kinodynamic
Steering method that creates KinodynamicPath instances.
class hpp::core::steeringMethod::Straight
Steering method that creates StraightPath instances.
class hpp::core::SteeringMethod
Steering method.
class hpp::core::WeighedDistance
Weighed distance between configurations.
Functions
static StraightPtr_t hpp::core::steeringMethod::Straight::create (const Problem &problem)
Create instance and return shared pointer.
static StraightPtr_t hpp::core::steeringMethod::Straight::createCopy (const StraightPtr_t &other)
Copy instance and return shared pointer.
virtual SteeringMethodPtr_t hpp::core::steeringMethod::Straight::copy () const
Copy instance and return shared pointer.
virtual PathPtr_t hpp::core::steeringMethod::Straight::impl_compute (ConfigurationIn_t q1, ConfigurationIn_t q2) const
create a path between two configurations
hpp::core::steeringMethod::Straight::Straight (const Problem &problem)
Constructor with robot Weighed distance is created from robot.
hpp::core::steeringMethod::Straight::Straight (const Straight &other)
Copy constructor.
void hpp::core::steeringMethod::Straight::init (StraightWkPtr_t weak)
Store weak pointer to itself.
Detailed Description
Some system are subject to kinematic or dynamic constraints.
Those constraints can be handled in path planning using a steering method that builds an admissible path between two configurations of the system. When using a steering method, it can be useful to use a distance function that accounts for the cost to go from a configuration to another.
Function Documentation
virtual SteeringMethodPtr_t hpp::core::steeringMethod::Straight::copy () const inline virtual
Copy instance and return shared pointer.
Implements hpp::core::SteeringMethod.
static StraightPtr_t hpp::core::steeringMethod::Straight::create (const Problem & problem) inline static
Create instance and return shared pointer.
References hpp::core::steeringMethod::Straight::init().
static StraightPtr_t hpp::core::steeringMethod::Straight::createCopy (const StraightPtr_t & other) inline static
Copy instance and return shared pointer.
References hpp::core::steeringMethod::Straight::init().
virtual PathPtr_t hpp::core::steeringMethod::Straight::impl_compute (ConfigurationIn_t q1, ConfigurationIn_t q2) const inline virtual
create a path between two configurations
Implements hpp::core::SteeringMethod.
References hpp::core::StraightPath::create(), and HPP_STATIC_PTR_CAST.
void hpp::core::steeringMethod::Straight::init (StraightWkPtr_t weak) inline protected
Store weak pointer to itself.
References hpp::core::SteeringMethod::init().
Referenced by hpp::core::steeringMethod::Straight::create(), and hpp::core::steeringMethod::Straight::createCopy().
hpp::core::steeringMethod::Straight::Straight (const Problem & problem) inline protected
Constructor with robot Weighed distance is created from robot.
hpp::core::steeringMethod::Straight::Straight (const Straight & other) inline protected
Copy constructor.