Path Optimization
Path Optimization
Path optimization algorithms derive from class hpp::core::PathOptimizer.
Namespaces
hpp::core::pathOptimization
Classes
struct hpp::core::pathOptimization::ConfigOptimizationTraits
Optimize the waypoints of the path and optionally add the constraint::ConfigurationConstraint to the ConfigProjector of the path.
class hpp::core::pathOptimization::ConfigOptimization
class hpp::core::pathOptimization::GradientBased
struct hpp::core::pathOptimization::PartialShortcutTraits
Partial shortcut.
class hpp::core::pathOptimization::PartialShortcut
struct hpp::core::pathOptimization::QuadraticProgram
class hpp::core::pathOptimization::RandomShortcut
Random shortcut.
class hpp::core::pathOptimization::SimpleShortcut
class hpp::core::pathOptimization::SimpleTimeParameterization
Add a TimeParameterization to paths so that the velocity does not exceeds the velocity limits.
struct hpp::core::pathOptimization::SplineGradientBasedAbstract< _PolynomeBasis, _SplineOrder >::SplineOptimizationData
class hpp::core::pathOptimization::SplineGradientBasedAbstract< _PolynomeBasis, _SplineOrder >
Common base for optimization-based path optimizer with splines.
class hpp::core::pathOptimization::SplineGradientBased< _PolynomeBasis, _SplineOrder >
class hpp::core::PathOptimizer
Abstraction of path optimizer.
Typedefs
typedef std::vector< CollisionConstraintsResult > hpp::core::pathOptimization::CollisionConstraintsResults_t
typedef Eigen::JacobiSVD< matrix_t > hpp::core::pathOptimization::QuadraticProgram::Decomposition_t
typedef Eigen::LLT< matrix_t, Eigen::Lower > hpp::core::pathOptimization::QuadraticProgram::LLT_t
typedef path::Spline< PolynomeBasis, SplineOrder > hpp::core::pathOptimization::SplineGradientBasedAbstract< _PolynomeBasis, _SplineOrder >::Spline
typedef Spline::Ptr_t hpp::core::pathOptimization::SplineGradientBasedAbstract< _PolynomeBasis, _SplineOrder >::SplinePtr_t
typedef std::vector< SplinePtr_t > hpp::core::pathOptimization::SplineGradientBasedAbstract< _PolynomeBasis, _SplineOrder >::Splines_t
typedef SplineGradientBasedAbstract< _PolynomeBasis, _SplineOrder > hpp::core::pathOptimization::SplineGradientBased< _PolynomeBasis, _SplineOrder >::Base
typedef boost::shared_ptr< SplineGradientBased > hpp::core::pathOptimization::SplineGradientBased< _PolynomeBasis, _SplineOrder >::Ptr_t
Enumerations
enum {
hpp::core::pathOptimization::SplineGradientBasedAbstract< _PolynomeBasis, _SplineOrder >::PolynomeBasis = _PolynomeBasis,
hpp::core::pathOptimization::SplineGradientBasedAbstract< _PolynomeBasis, _SplineOrder >::SplineOrder = _SplineOrder
}
enum {
hpp::core::pathOptimization::SplineGradientBased< _PolynomeBasis, _SplineOrder >::PolynomeBasis = _PolynomeBasis,
hpp::core::pathOptimization::SplineGradientBased< _PolynomeBasis, _SplineOrder >::SplineOrder = _SplineOrder
}
Functions
static GradientBasedPtr_t hpp::core::pathOptimization::GradientBased::create (const Problem &problem)
Return shared pointer to new object.
virtual PathVectorPtr_t hpp::core::pathOptimization::GradientBased::optimize (const PathVectorPtr_t &path)
Optimize path.
hpp::core::pathOptimization::GradientBased::GradientBased (const Problem &problem)
hpp::core::pathOptimization::QuadraticProgram::QuadraticProgram (size_type inputSize)
hpp::core::pathOptimization::QuadraticProgram::QuadraticProgram (const QuadraticProgram &QP, const LinearConstraint &lc)
hpp::core::pathOptimization::QuadraticProgram::QuadraticProgram (const QuadraticProgram &QP)
hpp::core::pathOptimization::QuadraticProgram::~QuadraticProgram ()
void hpp::core::pathOptimization::QuadraticProgram::addRows (const std::size_t &nbRows)
hpp::core::pathOptimization::SplineGradientBasedAbstract< _PolynomeBasis, _SplineOrder >::SplineGradientBasedAbstract (const Problem &problem)
hpp::core::pathOptimization::SplineGradientBasedAbstract< _PolynomeBasis, _SplineOrder >::SplineOptimizationData::SplineOptimizationData ()
hpp::core::pathOptimization::SplineGradientBasedAbstract< _PolynomeBasis, _SplineOrder >::SplineOptimizationData::SplineOptimizationData (size_type rDof)
PathVectorPtr_t hpp::core::pathOptimization::SplineGradientBasedAbstract< _PolynomeBasis, _SplineOrder >::buildPathVector (const Splines_t &splines) const
static Ptr_t hpp::core::pathOptimization::SplineGradientBased< _PolynomeBasis, _SplineOrder >::create (const Problem &problem)
Return shared pointer to new object.
virtual PathVectorPtr_t hpp::core::pathOptimization::SplineGradientBased< _PolynomeBasis, _SplineOrder >::optimize (const PathVectorPtr_t &path)
Optimize path.
hpp::core::pathOptimization::SplineGradientBased< _PolynomeBasis, _SplineOrder >::SplineGradientBased (const Problem &problem)
virtual hpp::core::PathOptimizer::~PathOptimizer ()
const Problem & hpp::core::PathOptimizer::problem () const
Get problem.
virtual PathVectorPtr_t hpp::core::PathOptimizer::optimize (const PathVectorPtr_t &path)=0
Optimize path.
void hpp::core::PathOptimizer::interrupt ()
Interrupt path optimization.
hpp::core::PathOptimizer::PathOptimizer (const Problem &problem)
PathPtr_t hpp::core::PathOptimizer::steer (ConfigurationIn_t q1, ConfigurationIn_t q2) const
Variables
ConstraintSetPtr_t hpp::core::pathOptimization::SplineGradientBasedAbstract< _PolynomeBasis, _SplineOrder >::SplineOptimizationData::set
The set of constraint of the corresponding path.
boost::shared_ptr< constraints::ExplicitConstraintSet > hpp::core::pathOptimization::SplineGradientBasedAbstract< _PolynomeBasis, _SplineOrder >::SplineOptimizationData::es
A copy of the explicit solver included in set.
RowBlockIndices hpp::core::pathOptimization::SplineGradientBasedAbstract< _PolynomeBasis, _SplineOrder >::SplineOptimizationData::activeParameters
Variable on which we can optimize.
DevicePtr_t hpp::core::pathOptimization::SplineGradientBasedAbstract< _PolynomeBasis, _SplineOrder >::robot_
bool hpp::core::pathOptimization::SplineGradientBased< _PolynomeBasis, _SplineOrder >::checkOptimum_
bool hpp::core::PathOptimizer::interrupt_
Whether to interrupt computation Set to false at start of optimize method, set to true by method interrupt.
Program subject to linear equality constraints.
void hpp::core::pathOptimization::QuadraticProgram::reduced (const LinearConstraint &lc, QuadraticProgram &QPr) const
void hpp::core::pathOptimization::QuadraticProgram::decompose ()
void hpp::core::pathOptimization::QuadraticProgram::solve ()
Program subject to linear equality and inequality constraints.
void hpp::core::pathOptimization::QuadraticProgram::computeLLT ()
double hpp::core::pathOptimization::QuadraticProgram::solve (const LinearConstraint &ce, const LinearConstraint &ci)
Compute solution using quadprog.
Model
matrix_t hpp::core::pathOptimization::QuadraticProgram::H
vector_t hpp::core::pathOptimization::QuadraticProgram::b
bool hpp::core::pathOptimization::QuadraticProgram::bIsZero
Data (for inequality constraints)
LLT_t hpp::core::pathOptimization::QuadraticProgram::llt
value_type hpp::core::pathOptimization::QuadraticProgram::trace
Eigen::VectorXi hpp::core::pathOptimization::QuadraticProgram::activeConstraint
int hpp::core::pathOptimization::QuadraticProgram::activeSetSize
Data (for equality constraints)
Decomposition_t hpp::core::pathOptimization::QuadraticProgram::dec
vector_t hpp::core::pathOptimization::QuadraticProgram::xStar
Spline convinience functions
static void hpp::core::pathOptimization::SplineGradientBasedAbstract< _PolynomeBasis, _SplineOrder >::copy (const Splines_t &in, Splines_t &out)
Copy a vector of Spline.
void hpp::core::pathOptimization::SplineGradientBasedAbstract< _PolynomeBasis, _SplineOrder >::updateSplines (Splines_t &spline, const vector_t &param) const
Sets the parameters each spline.
void hpp::core::pathOptimization::SplineGradientBasedAbstract< _PolynomeBasis, _SplineOrder >::updateParameters (vector_t &param, const Splines_t &spline) const
Gets the parameters each spline.
static void hpp::core::pathOptimization::SplineGradientBasedAbstract< _PolynomeBasis, _SplineOrder >::interpolate (const Splines_t &a, const Splines_t &b, const value_type &alpha, Splines_t &res)
Returns res = (1 - alpha) * a + alpha * b.
Spline creation
typedef steeringMethod::Spline< PolynomeBasis, SplineOrder > hpp::core::pathOptimization::SplineGradientBasedAbstract< _PolynomeBasis, _SplineOrder >::SSM_t
Spline steering method.
SSM_t::Ptr_t hpp::core::pathOptimization::SplineGradientBasedAbstract< _PolynomeBasis, _SplineOrder >::steeringMethod_
static PathVectorPtr_t hpp::core::pathOptimization::SplineGradientBasedAbstract< _PolynomeBasis, _SplineOrder >::cleanInput (const PathVectorPtr_t &input)
Flatten path and remove path of zero length.
void hpp::core::pathOptimization::SplineGradientBasedAbstract< _PolynomeBasis, _SplineOrder >::appendEquivalentSpline (const StraightPathPtr_t &path, Splines_t &splines) const
Convert a straight path into a spline and append to vector.
void hpp::core::pathOptimization::SplineGradientBasedAbstract< _PolynomeBasis, _SplineOrder >::appendEquivalentSpline (const InterpolatedPathPtr_t &path, Splines_t &splines) const
Convert an interpolated path into a spline and append to vector.
void hpp::core::pathOptimization::SplineGradientBasedAbstract< _PolynomeBasis, _SplineOrder >::appendEquivalentSpline (const PathVectorPtr_t &path, Splines_t &splines) const
For each subpath of path, cast it into a known path and calls appropriate appendEquivalentSpline.
Path validation
typedef std::vector< std::pair< PathValidationReportPtr_t, std::size_t > > hpp::core::pathOptimization::SplineGradientBasedAbstract< _PolynomeBasis, _SplineOrder >::Reports_t
std::vector< PathValidationPtr_t > hpp::core::pathOptimization::SplineGradientBasedAbstract< _PolynomeBasis, _SplineOrder >::validations_
Path validation Its size is the number of spline paths.
virtual void hpp::core::pathOptimization::SplineGradientBasedAbstract< _PolynomeBasis, _SplineOrder >::initializePathValidation (const Splines_t &splines)
Initialize validations_.
Reports_t hpp::core::pathOptimization::SplineGradientBasedAbstract< _PolynomeBasis, _SplineOrder >::validatePath (const Splines_t &splines, std::vector< std::size_t > &reordering, bool stopAtFirst, bool reorder) const
Calls each validations_ on the corresponding spline.
Constraint creation
typedef Eigen::RowBlockIndices hpp::core::pathOptimization::SplineGradientBasedAbstract< _PolynomeBasis, _SplineOrder >::RowBlockIndices
typedef std::vector< bool > hpp::core::pathOptimization::SplineGradientBasedAbstract< _PolynomeBasis, _SplineOrder >::Bools_t
typedef std::vector< size_type > hpp::core::pathOptimization::SplineGradientBasedAbstract< _PolynomeBasis, _SplineOrder >::Indices_t
typedef std::vector< SplineOptimizationData > hpp::core::pathOptimization::SplineGradientBasedAbstract< _PolynomeBasis, _SplineOrder >::SplineOptimizationDatas_t
void hpp::core::pathOptimization::SplineGradientBasedAbstract< _PolynomeBasis, _SplineOrder >::jointBoundConstraint (const Splines_t &splines, LinearConstraint &lc) const
std::size_t hpp::core::pathOptimization::SplineGradientBasedAbstract< _PolynomeBasis, _SplineOrder >::addBoundConstraints (const Indices_t &bci, const LinearConstraint &bc, Bools_t &activeConstraint, LinearConstraint &constraint) const
Unused.
Indices_t hpp::core::pathOptimization::SplineGradientBasedAbstract< _PolynomeBasis, _SplineOrder >::validateBounds (const Splines_t &splines, const LinearConstraint &lc) const
Mostly for debugging purpose.
void hpp::core::pathOptimization::SplineGradientBasedAbstract< _PolynomeBasis, _SplineOrder >::addContinuityConstraints (const Splines_t &splines, const size_type maxOrder, const SplineOptimizationDatas_t &ess, LinearConstraint &continuity)
Add the linear constraint to connect consecutive splines together.
Constraint creation
virtual void hpp::core::pathOptimization::SplineGradientBased< _PolynomeBasis, _SplineOrder >::addProblemConstraints (const PathVectorPtr_t &init, const Splines_t &splines, LinearConstraint &lc, SplineOptimizationDatas_t &sods) const
Compute a conservative linear representation of the constraints.
void hpp::core::pathOptimization::SplineGradientBased< _PolynomeBasis, _SplineOrder >::addProblemConstraintOnPath (const PathPtr_t &path, const size_type &idxSpline, const SplinePtr_t &spline, LinearConstraint &lc, SplineOptimizationData &sod) const
Eigen::RowBlockIndices hpp::core::pathOptimization::SplineGradientBased< _PolynomeBasis, _SplineOrder >::computeActiveParameters (const PathPtr_t &path, const constraints::solver::BySubstitution &hs, const value_type &guessThr=-1, const bool &useExplicitInput=false) const
Detailed Description
Path optimization algorithms derive from class hpp::core::PathOptimizer.
Simple shortcut.
Find shortest path composed of direct paths between all pairs of waypoints of input path.
To do so, the optimizer builds a roadmap the nodes of which are the input path waypoints and the edges of which are the collision-free output of the steering method between all pairs of nodes.
Typedef Documentation
template<int _PolynomeBasis, int _SplineOrder> typedef SplineGradientBasedAbstract<_PolynomeBasis, _SplineOrder> hpp::core::pathOptimization::SplineGradientBased< _PolynomeBasis, _SplineOrder >::Base
template<int _PolynomeBasis, int _SplineOrder> typedef std::vector<bool> hpp::core::pathOptimization::SplineGradientBasedAbstract< _PolynomeBasis, _SplineOrder >::Bools_t protected
typedef std::vector<CollisionConstraintsResult> hpp::core::pathOptimization::CollisionConstraintsResults_t
typedef Eigen::JacobiSVD< matrix_t > hpp::core::pathOptimization::QuadraticProgram::Decomposition_t
template<int _PolynomeBasis, int _SplineOrder> typedef std::vector<size_type> hpp::core::pathOptimization::SplineGradientBasedAbstract< _PolynomeBasis, _SplineOrder >::Indices_t protected
typedef Eigen::LLT<matrix_t, Eigen::Lower> hpp::core::pathOptimization::QuadraticProgram::LLT_t
template<int _PolynomeBasis, int _SplineOrder> typedef boost::shared_ptr<SplineGradientBased> hpp::core::pathOptimization::SplineGradientBased< _PolynomeBasis, _SplineOrder >::Ptr_t
template<int _PolynomeBasis, int _SplineOrder> typedef std::vector<std::pair <PathValidationReportPtr_t, std::size_t> > hpp::core::pathOptimization::SplineGradientBasedAbstract< _PolynomeBasis, _SplineOrder >::Reports_t protected
template<int _PolynomeBasis, int _SplineOrder> typedef Eigen::RowBlockIndices hpp::core::pathOptimization::SplineGradientBasedAbstract< _PolynomeBasis, _SplineOrder >::RowBlockIndices protected
template<int _PolynomeBasis, int _SplineOrder> typedef path::Spline<PolynomeBasis, SplineOrder> hpp::core::pathOptimization::SplineGradientBasedAbstract< _PolynomeBasis, _SplineOrder >::Spline
template<int _PolynomeBasis, int _SplineOrder> typedef std::vector<SplineOptimizationData> hpp::core::pathOptimization::SplineGradientBasedAbstract< _PolynomeBasis, _SplineOrder >::SplineOptimizationDatas_t protected
template<int _PolynomeBasis, int _SplineOrder> typedef Spline::Ptr_t hpp::core::pathOptimization::SplineGradientBasedAbstract< _PolynomeBasis, _SplineOrder >::SplinePtr_t
template<int _PolynomeBasis, int _SplineOrder> typedef std::vector<SplinePtr_t> hpp::core::pathOptimization::SplineGradientBasedAbstract< _PolynomeBasis, _SplineOrder >::Splines_t
template<int _PolynomeBasis, int _SplineOrder> typedef steeringMethod::Spline<PolynomeBasis, SplineOrder> hpp::core::pathOptimization::SplineGradientBasedAbstract< _PolynomeBasis, _SplineOrder >::SSM_t protected
Spline steering method.
Enumeration Type Documentation
template<int _PolynomeBasis, int _SplineOrder> anonymous enum
Enumerator
PolynomeBasis
SplineOrder
template<int _PolynomeBasis, int _SplineOrder> anonymous enum
Enumerator
PolynomeBasis
SplineOrder
Function Documentation
template<int _PolynomeBasis, int _SplineOrder> std::size_t hpp::core::pathOptimization::SplineGradientBasedAbstract< _PolynomeBasis, _SplineOrder >::addBoundConstraints (const Indices_t & bci, const LinearConstraint & bc, Bools_t & activeConstraint, LinearConstraint & constraint) const protected
Unused.
template<int _PolynomeBasis, int _SplineOrder> void hpp::core::pathOptimization::SplineGradientBasedAbstract< _PolynomeBasis, _SplineOrder >::addContinuityConstraints (const Splines_t & splines, const size_type maxOrder, const SplineOptimizationDatas_t & ess, LinearConstraint & continuity) protected
Add the linear constraint to connect consecutive splines together.
template<int _PolynomeBasis, int _SplineOrder> void hpp::core::pathOptimization::SplineGradientBased< _PolynomeBasis, _SplineOrder >::addProblemConstraintOnPath (const PathPtr_t & path, const size_type & idxSpline, const SplinePtr_t & spline, LinearConstraint & lc, SplineOptimizationData & sod) const protected
template<int _PolynomeBasis, int _SplineOrder> virtual void hpp::core::pathOptimization::SplineGradientBased< _PolynomeBasis, _SplineOrder >::addProblemConstraints (const PathVectorPtr_t & init, const Splines_t & splines, LinearConstraint & lc, SplineOptimizationDatas_t & sods) const protected virtual
Compute a conservative linear representation of the constraints.
It determines:
which DoFs can be computed explicitely. These DoFs are removed from the variables and computed explicitely.
which DoFs are constrained implicitely. These DoFs are removed from the variables and are set constant.
which DoFs are not constrained. These DoFs are kept as variables for optimization.
void hpp::core::pathOptimization::QuadraticProgram::addRows (const std::size_t & nbRows) inline
References hpp::core::pathOptimization::QuadraticProgram::b, and hpp::core::pathOptimization::QuadraticProgram::H.
template<int _PolynomeBasis, int _SplineOrder> void hpp::core::pathOptimization::SplineGradientBasedAbstract< _PolynomeBasis, _SplineOrder >::appendEquivalentSpline (const StraightPathPtr_t & path, Splines_t & splines) const protected
Convert a straight path into a spline and append to vector.
Parameters
path straight path,
Return values
splines vector of splines
Build a spline starting from straight path initial configuration and ending at straight path final configuration. derivatives (up to an order depending on the spline degree) at start and end are set to zero.
template<int _PolynomeBasis, int _SplineOrder> void hpp::core::pathOptimization::SplineGradientBasedAbstract< _PolynomeBasis, _SplineOrder >::appendEquivalentSpline (const InterpolatedPathPtr_t & path, Splines_t & splines) const protected
Convert an interpolated path into a spline and append to vector.
Parameters
path interpolated path,
Return values
splines vector of splines
Build a spline starting from interpolated path initial configuration and ending at interpolated path final configuration. derivatives (up to an order depending on the spline degree) at start and end are set to zero. If the interpolated path as only two waypoint, treat it as a straight path. Otherwise, throw an exception.
template<int _PolynomeBasis, int _SplineOrder> void hpp::core::pathOptimization::SplineGradientBasedAbstract< _PolynomeBasis, _SplineOrder >::appendEquivalentSpline (const PathVectorPtr_t & path, Splines_t & splines) const protected
For each subpath of path, cast it into a known path and calls appropriate appendEquivalentSpline.
Parameters
splines the output will be pushed back into this vector.
template<int _PolynomeBasis, int _SplineOrder> PathVectorPtr_t hpp::core::pathOptimization::SplineGradientBasedAbstract< _PolynomeBasis, _SplineOrder >::buildPathVector (const Splines_t & splines) const protected
template<int _PolynomeBasis, int _SplineOrder> static PathVectorPtr_t hpp::core::pathOptimization::SplineGradientBasedAbstract< _PolynomeBasis, _SplineOrder >::cleanInput (const PathVectorPtr_t & input) static protected
Flatten path and remove path of zero length.
template<int _PolynomeBasis, int _SplineOrder> Eigen::RowBlockIndices hpp::core::pathOptimization::SplineGradientBased< _PolynomeBasis, _SplineOrder >::computeActiveParameters (const PathPtr_t & path, const constraints::solver::BySubstitution & hs, const value_type & guessThr = -1, const bool & useExplicitInput = false) const protected
Parameters
guessThr Threshold used to check whether the Jacobian contains rows of zeros, in which case the corresponding DoF is considered passive.
void hpp::core::pathOptimization::QuadraticProgram::computeLLT ()
Referenced by hpp::core::pathOptimization::QuadraticProgram::solve().
template<int _PolynomeBasis, int _SplineOrder> static void hpp::core::pathOptimization::SplineGradientBasedAbstract< _PolynomeBasis, _SplineOrder >::copy (const Splines_t & in, Splines_t & out) static
Copy a vector of Spline.
static GradientBasedPtr_t hpp::core::pathOptimization::GradientBased::create (const Problem & problem) static
Return shared pointer to new object.
Default cost is path length.
template<int _PolynomeBasis, int _SplineOrder> static Ptr_t hpp::core::pathOptimization::SplineGradientBased< _PolynomeBasis, _SplineOrder >::create (const Problem & problem) static
Return shared pointer to new object.
Default cost is path length.
void hpp::core::pathOptimization::QuadraticProgram::decompose ()
Referenced by hpp::core::pathOptimization::QuadraticProgram::reduced().
hpp::core::pathOptimization::GradientBased::GradientBased (const Problem & problem) protected
template<int _PolynomeBasis, int _SplineOrder> virtual void hpp::core::pathOptimization::SplineGradientBasedAbstract< _PolynomeBasis, _SplineOrder >::initializePathValidation (const Splines_t & splines) protected virtual
Initialize validations_.
Store a pointer to the path validation of the problem for each spline.
template<int _PolynomeBasis, int _SplineOrder> static void hpp::core::pathOptimization::SplineGradientBasedAbstract< _PolynomeBasis, _SplineOrder >::interpolate (const Splines_t & a, const Splines_t & b, const value_type & alpha, Splines_t & res) static
Returns res = (1 - alpha) * a + alpha * b.
void hpp::core::PathOptimizer::interrupt () inline
Interrupt path optimization.
template<int _PolynomeBasis, int _SplineOrder> void hpp::core::pathOptimization::SplineGradientBasedAbstract< _PolynomeBasis, _SplineOrder >::jointBoundConstraint (const Splines_t & splines, LinearConstraint & lc) const protected
virtual PathVectorPtr_t hpp::core::pathOptimization::GradientBased::optimize (const PathVectorPtr_t & path) virtual
Optimize path.
Implements hpp::core::PathOptimizer.
virtual PathVectorPtr_t hpp::core::PathOptimizer::optimize (const PathVectorPtr_t & path) pure virtual
Optimize path.
Implemented in hpp::core::pathOptimization::SimpleTimeParameterization, hpp::core::pathOptimization::ConfigOptimization, hpp::core::pathOptimization::SplineGradientBased< _PolynomeBasis, _SplineOrder >, hpp::core::pathOptimization::PartialShortcut, hpp::core::pathOptimization::RandomShortcut, hpp::core::pathOptimization::SimpleShortcut, and hpp::core::pathOptimization::GradientBased.
template<int _PolynomeBasis, int _SplineOrder> virtual PathVectorPtr_t hpp::core::pathOptimization::SplineGradientBased< _PolynomeBasis, _SplineOrder >::optimize (const PathVectorPtr_t & path) virtual
Optimize path.
1) Transform straight paths into splines
2) Add continuity constraints
3) Add problem constraints
4) Make cost function
5) Compute explicit representation of linear constraints.
6)
- 6.1) Compute cost hessian
- 6.2) Compute optimum
- 6.3) Check path for collision. If no collision, return solution
- 6.4) add collision constraint
- 6.5) re-compute explicit representation of linear constraints.
7) - Build result path.
Implements hpp::core::PathOptimizer.
hpp::core::PathOptimizer::PathOptimizer (const Problem & problem) inline protected
const Problem& hpp::core::PathOptimizer::problem () const inline
Get problem.
hpp::core::pathOptimization::QuadraticProgram::QuadraticProgram (size_type inputSize) inline
References hpp::core::pathOptimization::QuadraticProgram::b, hpp::core::pathOptimization::QuadraticProgram::bIsZero, and hpp::core::pathOptimization::QuadraticProgram::H.
hpp::core::pathOptimization::QuadraticProgram::QuadraticProgram (const QuadraticProgram & QP, const LinearConstraint & lc) inline
References hpp::core::pathOptimization::QuadraticProgram::reduced().
hpp::core::pathOptimization::QuadraticProgram::QuadraticProgram (const QuadraticProgram & QP) inline
References hpp::core::pathOptimization::QuadraticProgram::~QuadraticProgram().
void hpp::core::pathOptimization::QuadraticProgram::reduced (const LinearConstraint & lc, QuadraticProgram & QPr) const inline
References hpp::core::pathOptimization::QuadraticProgram::b, hpp::core::pathOptimization::QuadraticProgram::bIsZero, hpp::core::pathOptimization::QuadraticProgram::decompose(), hpp::core::pathOptimization::QuadraticProgram::H, hpp::core::pathOptimization::LinearConstraint::PK, and hpp::core::pathOptimization::LinearConstraint::xStar.
Referenced by hpp::core::pathOptimization::QuadraticProgram::QuadraticProgram().
void hpp::core::pathOptimization::QuadraticProgram::solve () inline
References hpp::core::pathOptimization::QuadraticProgram::b, hpp::core::pathOptimization::QuadraticProgram::computeLLT(), hpp::core::pathOptimization::QuadraticProgram::dec, and hpp::core::pathOptimization::QuadraticProgram::xStar.
double hpp::core::pathOptimization::QuadraticProgram::solve (const LinearConstraint & ce, const LinearConstraint & ci)
Compute solution using quadprog.
Parameters
ce equality constraints
ci inequality constraints: \(ci.J * x \ge ci.b \)
Note
computeLLT must have been called before.
template<int _PolynomeBasis, int _SplineOrder> hpp::core::pathOptimization::SplineGradientBased< _PolynomeBasis, _SplineOrder >::SplineGradientBased (const Problem & problem) protected
template<int _PolynomeBasis, int _SplineOrder> hpp::core::pathOptimization::SplineGradientBasedAbstract< _PolynomeBasis, _SplineOrder >::SplineGradientBasedAbstract (const Problem & problem) protected
template<int _PolynomeBasis, int _SplineOrder> hpp::core::pathOptimization::SplineGradientBasedAbstract< _PolynomeBasis, _SplineOrder >::SplineOptimizationData::SplineOptimizationData () inline
template<int _PolynomeBasis, int _SplineOrder> hpp::core::pathOptimization::SplineGradientBasedAbstract< _PolynomeBasis, _SplineOrder >::SplineOptimizationData::SplineOptimizationData (size_type rDof) inline
PathPtr_t hpp::core::PathOptimizer::steer (ConfigurationIn_t q1, ConfigurationIn_t q2) const protected
template<int _PolynomeBasis, int _SplineOrder> void hpp::core::pathOptimization::SplineGradientBasedAbstract< _PolynomeBasis, _SplineOrder >::updateParameters (vector_t & param, const Splines_t & spline) const
Gets the parameters each spline.
Todo:
make this function static (currently, it only needs the robot number dof.
template<int _PolynomeBasis, int _SplineOrder> void hpp::core::pathOptimization::SplineGradientBasedAbstract< _PolynomeBasis, _SplineOrder >::updateSplines (Splines_t & spline, const vector_t & param) const
Sets the parameters each spline.
Todo:
make this function static (currently, it only needs the robot number dof.
template<int _PolynomeBasis, int _SplineOrder> Indices_t hpp::core::pathOptimization::SplineGradientBasedAbstract< _PolynomeBasis, _SplineOrder >::validateBounds (const Splines_t & splines, const LinearConstraint & lc) const protected
Mostly for debugging purpose.
template<int _PolynomeBasis, int _SplineOrder> Reports_t hpp::core::pathOptimization::SplineGradientBasedAbstract< _PolynomeBasis, _SplineOrder >::validatePath (const Splines_t & splines, std::vector< std::size_t > & reordering, bool stopAtFirst, bool reorder) const protected
Calls each validations_ on the corresponding spline.
Parameters
reordering order in which the path validation is run. It is assumed that reordering is a permutation of [0, splines.size()[.
stopAtFirst if true, then return only at most one report corresponding to the first encountered collision.
reorder Put the portion in collision first in order to improve performance of next collision check.
virtual hpp::core::PathOptimizer::~PathOptimizer () inline virtual
hpp::core::pathOptimization::QuadraticProgram::~QuadraticProgram ()
Referenced by hpp::core::pathOptimization::QuadraticProgram::QuadraticProgram().
Variable Documentation
Eigen::VectorXi hpp::core::pathOptimization::QuadraticProgram::activeConstraint
template<int _PolynomeBasis, int _SplineOrder> RowBlockIndices hpp::core::pathOptimization::SplineGradientBasedAbstract< _PolynomeBasis, _SplineOrder >::SplineOptimizationData::activeParameters
Variable on which we can optimize.
Other variables are fully constrained.
int hpp::core::pathOptimization::QuadraticProgram::activeSetSize
vector_t hpp::core::pathOptimization::QuadraticProgram::b
Referenced by hpp::core::pathOptimization::QuadraticProgram::addRows(), hpp::core::pathOptimization::QuadraticProgram::QuadraticProgram(), hpp::core::pathOptimization::QuadraticProgram::reduced(), and hpp::core::pathOptimization::QuadraticProgram::solve().
bool hpp::core::pathOptimization::QuadraticProgram::bIsZero
Referenced by hpp::core::pathOptimization::QuadraticProgram::QuadraticProgram(), and hpp::core::pathOptimization::QuadraticProgram::reduced().
template<int _PolynomeBasis, int _SplineOrder> bool hpp::core::pathOptimization::SplineGradientBased< _PolynomeBasis, _SplineOrder >::checkOptimum_ protected
Decomposition_t hpp::core::pathOptimization::QuadraticProgram::dec
Referenced by hpp::core::pathOptimization::QuadraticProgram::solve().
template<int _PolynomeBasis, int _SplineOrder> boost::shared_ptr<constraints::ExplicitConstraintSet> hpp::core::pathOptimization::SplineGradientBasedAbstract< _PolynomeBasis, _SplineOrder >::SplineOptimizationData::es
A copy of the explicit solver included in set.
matrix_t hpp::core::pathOptimization::QuadraticProgram::H
Referenced by hpp::core::pathOptimization::QuadraticProgram::addRows(), hpp::core::pathOptimization::QuadraticProgram::QuadraticProgram(), and hpp::core::pathOptimization::QuadraticProgram::reduced().
bool hpp::core::PathOptimizer::interrupt_ protected
Whether to interrupt computation Set to false at start of optimize method, set to true by method interrupt.
LLT_t hpp::core::pathOptimization::QuadraticProgram::llt
template<int _PolynomeBasis, int _SplineOrder> DevicePtr_t hpp::core::pathOptimization::SplineGradientBasedAbstract< _PolynomeBasis, _SplineOrder >::robot_ protected
template<int _PolynomeBasis, int _SplineOrder> ConstraintSetPtr_t hpp::core::pathOptimization::SplineGradientBasedAbstract< _PolynomeBasis, _SplineOrder >::SplineOptimizationData::set
The set of constraint of the corresponding path.
template<int _PolynomeBasis, int _SplineOrder> SSM_t::Ptr_t hpp::core::pathOptimization::SplineGradientBasedAbstract< _PolynomeBasis, _SplineOrder >::steeringMethod_ protected
value_type hpp::core::pathOptimization::QuadraticProgram::trace
template<int _PolynomeBasis, int _SplineOrder> std::vector<PathValidationPtr_t> hpp::core::pathOptimization::SplineGradientBasedAbstract< _PolynomeBasis, _SplineOrder >::validations_ protected
Path validation Its size is the number of spline paths.
vector_t hpp::core::pathOptimization::QuadraticProgram::xStar
Referenced by hpp::core::pathOptimization::QuadraticProgram::solve().