# DO NOT EDIT THIS FILE!
#
# Python module hpp.core_idl.configuration_shooter generated by omniidl

import omniORB
omniORB.updateModule("hpp_idl.hpp.core_idl.configuration_shooter")

# ** 1. Stub files contributing to this module
import hpp_stubs.core.configuration_shooters_idl

# ** 2. Sub-modules

# ** 3. End
