gepetto::gui::BodyTreeItem Class Reference
gepetto::gui::BodyTreeItem Class Reference
#include <gepetto/gui/tree-item.hh>
Public Slots
void setViewingMode (QString mode)
void setVisibilityMode (QString mode)
void removeFromGroup ()
void remove ()
void removeAll ()
void addLandmark ()
void deleteLandmark ()
QString text () const
Signals
void requestInitialize ()
Public Member Functions
BodyTreeItem (QObject *parent, NodePtr_t node)
void initialize ()
virtual QStandardItem * clone () const
virtual int type ()
NodePtr_t node () const
void populateContextMenu (QMenu *menu)
void setParentGroup (const std::string &parent)
QWidget * propertyEditors () const
virtual ~BodyTreeItem ()
void attachToWindow (unsigned int windowID)
Friends
class VisibilityItem
Constructor & Destructor Documentation
gepetto::gui::BodyTreeItem::BodyTreeItem (QObject * parent, NodePtr_t node)
virtual gepetto::gui::BodyTreeItem::~BodyTreeItem () virtual
Referenced by propertyEditors().
Member Function Documentation
void gepetto::gui::BodyTreeItem::addLandmark () slot
Referenced by propertyEditors().
void gepetto::gui::BodyTreeItem::attachToWindow (unsigned int windowID)
Referenced by propertyEditors().
virtual QStandardItem* gepetto::gui::BodyTreeItem::clone () const virtual
void gepetto::gui::BodyTreeItem::deleteLandmark () slot
Referenced by propertyEditors().
void gepetto::gui::BodyTreeItem::initialize ()
NodePtr_t gepetto::gui::BodyTreeItem::node () const
Referenced by type().
void gepetto::gui::BodyTreeItem::populateContextMenu (QMenu * menu)
Referenced by type().
QWidget* gepetto::gui::BodyTreeItem::propertyEditors () const inline
References addLandmark(), attachToWindow(), deleteLandmark(), removeAll(), removeFromGroup(), setViewingMode(), setVisibilityMode(), and ~BodyTreeItem().
void gepetto::gui::BodyTreeItem::remove () slot
void gepetto::gui::BodyTreeItem::removeAll () slot
Referenced by propertyEditors().
void gepetto::gui::BodyTreeItem::removeFromGroup () slot
Referenced by propertyEditors().
void gepetto::gui::BodyTreeItem::requestInitialize () signal
Referenced by text().
void gepetto::gui::BodyTreeItem::setParentGroup (const std::string & parent)
Referenced by type().
void gepetto::gui::BodyTreeItem::setViewingMode (QString mode) slot
Referenced by propertyEditors().
void gepetto::gui::BodyTreeItem::setVisibilityMode (QString mode) slot
Referenced by propertyEditors().
QString gepetto::gui::BodyTreeItem::text () const inline slot
References requestInitialize().
virtual int gepetto::gui::BodyTreeItem::type () inline virtual
References node(), populateContextMenu(), and setParentGroup().
Friends And Related Function Documentation
friend class VisibilityItem friend