hpp::manipulation::srdf::HandleFactory Class Reference
hpp::manipulation::srdf::HandleFactory Class Reference
Factories
Build an object of type hpp::manipulation::Handle.
#include <hpp/manipulation/srdf/factories/handle.hh>
Public Member Functions
HandleFactory (ObjectFactory *parent, const XMLElement *element)
virtual void finishTags ()
HandlePtr_t handle () const
Protected Attributes
HandlePtr_t handle_
Transform3f localPosition_
The element required to build the handle.
std::string linkName_
Detailed Description
Build an object of type hpp::manipulation::Handle.
Constructor & Destructor Documentation
hpp::manipulation::srdf::HandleFactory::HandleFactory (ObjectFactory * parent, const XMLElement * element) inline
References finishTags(), and handle().
Member Function Documentation
virtual void hpp::manipulation::srdf::HandleFactory::finishTags () virtual
Referenced by HandleFactory().
HandlePtr_t hpp::manipulation::srdf::HandleFactory::handle () const
Referenced by HandleFactory().
Member Data Documentation
HandlePtr_t hpp::manipulation::srdf::HandleFactory::handle_ protected
std::string hpp::manipulation::srdf::HandleFactory::linkName_ protected
Transform3f hpp::manipulation::srdf::HandleFactory::localPosition_ protected
The element required to build the handle.