hpp::manipulation::steeringMethod::CrossStateOptimization Class Reference
hpp::manipulation::steeringMethod::CrossStateOptimization Class Reference
Steering method and distance functions
Optimization-based steering method.
#include <hpp/manipulation/steering-method/cross-state-optimization.hh>
Public Member Functions
core::SteeringMethodPtr_t copy () const
Public Member Functions inherited from hpp::manipulation::SteeringMethod
const core::SteeringMethodPtr_t & innerSteeringMethod () const
void innerSteeringMethod (const core::SteeringMethodPtr_t &sm)
Public Member Functions inherited from hpp::core::SteeringMethod
PathPtr_t operator() (ConfigurationIn_t q1, ConfigurationIn_t q2) const
PathPtr_t steer (ConfigurationIn_t q1, ConfigurationIn_t q2) const
virtual ~SteeringMethod ()
const Problem & problem () const
void constraints (const ConstraintSetPtr_t &constraints)
const ConstraintSetPtr_t & constraints () const
void constraints (const ConstraintSetPtr_t &constraints)
const ConstraintSetPtr_t & constraints () const
Static Public Member Functions
static CrossStateOptimizationPtr_t create (const Problem &problem)
static CrossStateOptimizationPtr_t create (const core::Problem &problem)
template<typename T >
static CrossStateOptimizationPtr_t create (const core::Problem &problem)
Protected Member Functions
CrossStateOptimization (const Problem &problem)
CrossStateOptimization (const CrossStateOptimization &other)
core::PathPtr_t impl_compute (ConfigurationIn_t q1, ConfigurationIn_t q2) const
void init (CrossStateOptimizationWkPtr_t weak)
Protected Member Functions inherited from hpp::manipulation::SteeringMethod
SteeringMethod (const Problem &problem)
Constructor.
SteeringMethod (const SteeringMethod &other)
Copy constructor.
void init (SteeringMethodWkPtr_t weak)
Protected Member Functions inherited from hpp::core::SteeringMethod
SteeringMethod (const Problem &problem)
SteeringMethod (const SteeringMethod &other)
void init (SteeringMethodWkPtr_t weak)
Additional Inherited Members
Protected Attributes inherited from hpp::manipulation::SteeringMethod
const Problem & problem_
A pointer to the manipulation problem.
core::SteeringMethodPtr_t steeringMethod_
The encapsulated steering method.
Protected Attributes inherited from hpp::core::SteeringMethod
const Problem & problem_
Detailed Description
Optimization-based steering method.
Methodology
Given two configuration , this class formulates and solves the problem as follows.
Compute the corresponding states .
For a each path between in the constraint graph, do:
define intermediate configuration ,
initialize the optimization problem, as explained below,
solve the optimization problem, which gives ,
in case of failure, continue the loop.
call the Edge::build of each for each consecutive .
Problem formulation
Find such that:
,
,
is in state between , (StateFunction)
are reachable with transition (EdgeFunction).
Constructor & Destructor Documentation
hpp::manipulation::steeringMethod::CrossStateOptimization::CrossStateOptimization (const Problem & problem) inline protected
hpp::manipulation::steeringMethod::CrossStateOptimization::CrossStateOptimization (const CrossStateOptimization & other) inline protected
References impl_compute().
Member Function Documentation
core::SteeringMethodPtr_t hpp::manipulation::steeringMethod::CrossStateOptimization::copy () const virtual
Implements hpp::core::SteeringMethod.
static CrossStateOptimizationPtr_t hpp::manipulation::steeringMethod::CrossStateOptimization::create (const Problem & problem) static
Referenced by create(), and init().
static CrossStateOptimizationPtr_t hpp::manipulation::steeringMethod::CrossStateOptimization::create (const core::Problem & problem) static
Warning
core::Problem will be casted to Problem
template<typename T > CrossStateOptimizationPtr_t hpp::manipulation::steeringMethod::CrossStateOptimization::create (const core::Problem & problem) static
References create(), and create().
core::PathPtr_t hpp::manipulation::steeringMethod::CrossStateOptimization::impl_compute (ConfigurationIn_t q1, ConfigurationIn_t q2) const protected virtual
Implements hpp::core::SteeringMethod.
void hpp::manipulation::steeringMethod::CrossStateOptimization::init (CrossStateOptimizationWkPtr_t weak) inline protected
References create(), and hpp::manipulation::SteeringMethod::init().