hpp::manipulation::Handle Class Reference
hpp::manipulation::Handle Class Reference
Part of an object that is aimed at being grasped.
#include <hpp/manipulation/handle.hh>
Public Member Functions
virtual ~Handle ()
virtual HandlePtr_t clone () const
Return a pointer to the copy of this.
const Transform3f & localPosition () const
Get local position in joint frame.
void mask (const std::vector< bool > &mask)
Set constraint mask.
const std::vector< bool > & mask () const
Get constraint mask See mask(const std::vector<bool>&)
virtual ImplicitPtr_t createGrasp (const GripperPtr_t &gripper, std::string name) const
Create constraint corresponding to a gripper grasping this handle.
virtual ImplicitPtr_t createGraspComplement (const GripperPtr_t &gripper, std::string name) const
Create complement constraint of gripper grasping this handle.
virtual ImplicitPtr_t createGraspAndComplement (const GripperPtr_t &gripper, std::string name) const
Create constraint composed of grasp constraint and its complement.
virtual ImplicitPtr_t createPreGrasp (const GripperPtr_t &gripper, const value_type &shift, std::string name) const
Create constraint corresponding to a pregrasping task.
value_type clearance () const
Get the clearance.
void clearance (const value_type &clearance)
Set the clearance.
Name
const std::string & name () const
Get name.
void name (const std::string &n)
Set name.
Joint
const JointPtr_t & joint () const
Get joint to which the handle is linked.
void joint (const JointPtr_t &joint)
Set joint to which the handle is linked.
DevicePtr_t robot () const
Static Public Member Functions
static HandlePtr_t create (const std::string &name, const Transform3f &localPosition, const DeviceWkPtr_t &robot, const JointPtr_t &joint)
Create constraint corresponding to a gripper grasping this object.
Static Public Attributes
static std::string className
Protected Member Functions
Handle (const std::string &name, const Transform3f &localPosition, const DeviceWkPtr_t &robot, const JointPtr_t &joint)
Constructor.
void init (HandleWkPtr_t weakPtr)
virtual std::ostream & print (std::ostream &os) const
Friends
std::ostream & operator<< (std::ostream &, const Handle &)
Detailed Description
Part of an object that is aimed at being grasped.
Constructor & Destructor Documentation
virtual hpp::manipulation::Handle::~Handle () inline virtual
hpp::manipulation::Handle::Handle (const std::string & name, const Transform3f & localPosition, const DeviceWkPtr_t & robot, const JointPtr_t & joint) inline protected
Constructor.
Parameters
robot the robot that grasps the handle,
grasp object containing the grasp information
Returns
the constraint of relative position between the handle and the gripper.
Member Function Documentation
value_type hpp::manipulation::Handle::clearance () const inline
Get the clearance.
The clearance is a distance, from the center of the gripper and along the x-aixs, that "ensures" an object being at that distance is not colliding with this gripper. It also gives an order of magnitude of the size of the gripper.
void hpp::manipulation::Handle::clearance (const value_type & clearance) inline
Set the clearance.
See also
clearance()
virtual HandlePtr_t hpp::manipulation::Handle::clone () const virtual
Return a pointer to the copy of this.
static HandlePtr_t hpp::manipulation::Handle::create (const std::string & name, const Transform3f & localPosition, const DeviceWkPtr_t & robot, const JointPtr_t & joint) inline static
Create constraint corresponding to a gripper grasping this object.
Parameters
robot the robot that grasps the handle,
grasp object containing the grasp information
Returns
the constraint of relative position between the handle and the gripper.
References init().
virtual ImplicitPtr_t hpp::manipulation::Handle::createGrasp (const GripperPtr_t & gripper, std::string name) const virtual
Create constraint corresponding to a gripper grasping this handle.
Parameters
gripper object containing the gripper information
Returns
the constraint of relative transformation between the handle and the gripper. The degrees of freedom of the relative transformation that are constrained are determined by the mask.
See also
constraints::Implicit::mask. The constraint is not parameterizable (has constant right hand side).
virtual ImplicitPtr_t hpp::manipulation::Handle::createGraspAndComplement (const GripperPtr_t & gripper, std::string name) const virtual
Create constraint composed of grasp constraint and its complement.
Parameters
gripper object containing the gripper information
Returns
the composition of grasp constraint and its complement, that that is a full relative transformation constraint.
virtual ImplicitPtr_t hpp::manipulation::Handle::createGraspComplement (const GripperPtr_t & gripper, std::string name) const virtual
Create complement constraint of gripper grasping this handle.
Parameters
gripper object containing the gripper information
Returns
complement constraint: constraint combined with its complement constitute a full relative transformation constraint. The complement constraint is parameterizable (has non constant right hand side).
virtual ImplicitPtr_t hpp::manipulation::Handle::createPreGrasp (const GripperPtr_t & gripper, const value_type & shift, std::string name) const virtual
Create constraint corresponding to a pregrasping task.
Parameters
gripper object containing the gripper information
Returns
the constraint of relative transformation between the handle and the gripper.
Note
6 DOFs of the relative transformation between the handle and the gripper are constrained. The transformation is shifted along x-axis of value shift.
void hpp::manipulation::Handle::init (HandleWkPtr_t weakPtr) inline protected
References hpp::manipulation::operator<<(), and robot_.
Referenced by create().
const JointPtr_t& hpp::manipulation::Handle::joint () const inline
Get joint to which the handle is linked.
void hpp::manipulation::Handle::joint (const JointPtr_t & joint) inline
Set joint to which the handle is linked.
const Transform3f& hpp::manipulation::Handle::localPosition () const inline
Get local position in joint frame.
void hpp::manipulation::Handle::mask (const std::vector< bool > & mask)
Set constraint mask.
const std::vector<bool>& hpp::manipulation::Handle::mask () const inline
Get constraint mask See mask(const std::vector<bool>&)
const std::string& hpp::manipulation::Handle::name () const inline
Get name.
void hpp::manipulation::Handle::name (const std::string & n) inline
Set name.
virtual std::ostream& hpp::manipulation::Handle::print (std::ostream & os) const protected virtual
DevicePtr_t hpp::manipulation::Handle::robot () const inline
References robot_.
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & , const Handle &) friend
Member Data Documentation
std::string hpp::manipulation::Handle::className static