hpp::manipulation::SteeringMethod Class Reference
hpp::manipulation::SteeringMethod Class Reference
Steering method and distance functions
#include <hpp/manipulation/steering-method/graph.hh>
Public Member Functions
const core::SteeringMethodPtr_t & innerSteeringMethod () const
void innerSteeringMethod (const core::SteeringMethodPtr_t &sm)
Public Member Functions inherited from hpp::core::SteeringMethod
PathPtr_t operator() (ConfigurationIn_t q1, ConfigurationIn_t q2) const
PathPtr_t steer (ConfigurationIn_t q1, ConfigurationIn_t q2) const
virtual ~SteeringMethod ()
virtual SteeringMethodPtr_t copy () const =0
const Problem & problem () const
void constraints (const ConstraintSetPtr_t &constraints)
const ConstraintSetPtr_t & constraints () const
void constraints (const ConstraintSetPtr_t &constraints)
const ConstraintSetPtr_t & constraints () const
Protected Member Functions
SteeringMethod (const Problem &problem)
Constructor.
SteeringMethod (const SteeringMethod &other)
Copy constructor.
void init (SteeringMethodWkPtr_t weak)
Protected Member Functions inherited from hpp::core::SteeringMethod
SteeringMethod (const Problem &problem)
SteeringMethod (const SteeringMethod &other)
virtual PathPtr_t impl_compute (ConfigurationIn_t q1, ConfigurationIn_t q2) const =0
void init (SteeringMethodWkPtr_t weak)
Protected Attributes
const Problem & problem_
A pointer to the manipulation problem.
core::SteeringMethodPtr_t steeringMethod_
The encapsulated steering method.
Protected Attributes inherited from hpp::core::SteeringMethod
const Problem & problem_
Constructor & Destructor Documentation
hpp::manipulation::SteeringMethod::SteeringMethod (const Problem & problem) protected
Constructor.
hpp::manipulation::SteeringMethod::SteeringMethod (const SteeringMethod & other) protected
Copy constructor.
Member Function Documentation
void hpp::manipulation::SteeringMethod::init (SteeringMethodWkPtr_t weak) inline protected
References hpp::core::SteeringMethod::init().
Referenced by hpp::manipulation::steeringMethod::CrossStateOptimization::init(), and hpp::manipulation::steeringMethod::Graph::init().
const core::SteeringMethodPtr_t& hpp::manipulation::SteeringMethod::innerSteeringMethod () const inline
References steeringMethod_.
void hpp::manipulation::SteeringMethod::innerSteeringMethod (const core::SteeringMethodPtr_t & sm) inline
References problem(), and steeringMethod_.
Member Data Documentation
const Problem& hpp::manipulation::SteeringMethod::problem_ protected
A pointer to the manipulation problem.
core::SteeringMethodPtr_t hpp::manipulation::SteeringMethod::steeringMethod_ protected
The encapsulated steering method.