// This file is generated by omniidl (C++ backend)- omniORB_4_1. Do not edit.
#ifndef hpp_core_idl__path__planners_hh__
#define hpp_core_idl__path__planners_hh__

#ifndef __CORBA_H_EXTERNAL_GUARD__
#include <omniORB4/CORBA.h>
#endif

#ifndef  USE_stub_in_nt_dll
# define USE_stub_in_nt_dll_NOT_DEFINED_path__planners
#endif
#ifndef  USE_core_stub_in_nt_dll
# define USE_core_stub_in_nt_dll_NOT_DEFINED_path__planners
#endif
#ifndef  USE_dyn_stub_in_nt_dll
# define USE_dyn_stub_in_nt_dll_NOT_DEFINED_path__planners
#endif



#ifndef hpp_core_idl__common_hh_EXTERNAL_GUARD__
#define hpp_core_idl__common_hh_EXTERNAL_GUARD__
#include <hpp/common-idl.hh>
#endif
#ifndef hpp_core_idl__paths_hh_EXTERNAL_GUARD__
#define hpp_core_idl__paths_hh_EXTERNAL_GUARD__
#include <hpp/core_idl/paths-idl.hh>
#endif



#ifdef USE_stub_in_nt_dll
# ifndef USE_core_stub_in_nt_dll
#  define USE_core_stub_in_nt_dll
# endif
# ifndef USE_dyn_stub_in_nt_dll
#  define USE_dyn_stub_in_nt_dll
# endif
#endif

#ifdef _core_attr
# error "A local CPP macro _core_attr has already been defined."
#else
# ifdef  USE_core_stub_in_nt_dll
#  define _core_attr _OMNIORB_NTDLL_IMPORT
# else
#  define _core_attr
# endif
#endif

#ifdef _dyn_attr
# error "A local CPP macro _dyn_attr has already been defined."
#else
# ifdef  USE_dyn_stub_in_nt_dll
#  define _dyn_attr _OMNIORB_NTDLL_IMPORT
# else
#  define _dyn_attr
# endif
#endif





_CORBA_MODULE hpp

_CORBA_MODULE_BEG

  _CORBA_MODULE core_idl

  _CORBA_MODULE_BEG

#ifndef __hpp_mcore__idl_mPathPlanner__
#define __hpp_mcore__idl_mPathPlanner__

    class PathPlanner;
    class _objref_PathPlanner;
    class _impl_PathPlanner;
    
    typedef _objref_PathPlanner* PathPlanner_ptr;
    typedef PathPlanner_ptr PathPlannerRef;

    class PathPlanner_Helper {
    public:
      typedef PathPlanner_ptr _ptr_type;

      static _ptr_type _nil();
      static _CORBA_Boolean is_nil(_ptr_type);
      static void release(_ptr_type);
      static void duplicate(_ptr_type);
      static void marshalObjRef(_ptr_type, cdrStream&);
      static _ptr_type unmarshalObjRef(cdrStream&);
    };

    typedef _CORBA_ObjRef_Var<_objref_PathPlanner, PathPlanner_Helper> PathPlanner_var;
    typedef _CORBA_ObjRef_OUT_arg<_objref_PathPlanner,PathPlanner_Helper > PathPlanner_out;

#endif

    // interface PathPlanner
    class PathPlanner {
    public:
      // Declarations for this interface type.
      typedef PathPlanner_ptr _ptr_type;
      typedef PathPlanner_var _var_type;

      static _ptr_type _duplicate(_ptr_type);
      static _ptr_type _narrow(::CORBA::Object_ptr);
      static _ptr_type _unchecked_narrow(::CORBA::Object_ptr);
      
      static _ptr_type _nil();

      static inline void _marshalObjRef(_ptr_type, cdrStream&);

      static inline _ptr_type _unmarshalObjRef(cdrStream& s) {
        omniObjRef* o = omniObjRef::_unMarshal(_PD_repoId,s);
        if (o)
          return (_ptr_type) o->_ptrToObjRef(_PD_repoId);
        else
          return _nil();
      }

      static _core_attr const char* _PD_repoId;

      // Other IDL defined within this scope.
      
    };

    class _objref_PathPlanner :
      public virtual ::CORBA::Object,
      public virtual omniObjRef
    {
    public:
      PathVector_ptr solve();
      void startSolve();
      void tryConnectInitAndGoals();
      void oneStep();
      PathVector_ptr computePath();
      PathVector_ptr finishSolve(::hpp::core_idl::PathVector_ptr path);
      void interrupt();
      void maxIterations(::hpp::size_type n);
      void timeOut(::hpp::value_type seconds);

      inline _objref_PathPlanner()  { _PR_setobj(0); }  // nil
      _objref_PathPlanner(omniIOR*, omniIdentity*);

    protected:
      virtual ~_objref_PathPlanner();

      
    private:
      virtual void* _ptrToObjRef(const char*);

      _objref_PathPlanner(const _objref_PathPlanner&);
      _objref_PathPlanner& operator = (const _objref_PathPlanner&);
      // not implemented

      friend class PathPlanner;
    };

    class _pof_PathPlanner : public _OMNI_NS(proxyObjectFactory) {
    public:
      inline _pof_PathPlanner() : _OMNI_NS(proxyObjectFactory)(PathPlanner::_PD_repoId) {}
      virtual ~_pof_PathPlanner();

      virtual omniObjRef* newObjRef(omniIOR*,omniIdentity*);
      virtual _CORBA_Boolean is_a(const char*) const;
    };

    class _impl_PathPlanner :
      public virtual omniServant
    {
    public:
      virtual ~_impl_PathPlanner();

      virtual PathVector_ptr solve() = 0;
      virtual void startSolve() = 0;
      virtual void tryConnectInitAndGoals() = 0;
      virtual void oneStep() = 0;
      virtual PathVector_ptr computePath() = 0;
      virtual PathVector_ptr finishSolve(::hpp::core_idl::PathVector_ptr path) = 0;
      virtual void interrupt() = 0;
      virtual void maxIterations(::hpp::size_type n) = 0;
      virtual void timeOut(::hpp::value_type seconds) = 0;
      
    public:  // Really protected, workaround for xlC
      virtual _CORBA_Boolean _dispatch(omniCallHandle&);

    private:
      virtual void* _ptrToInterface(const char*);
      virtual const char* _mostDerivedRepoId();
      
    };


  _CORBA_MODULE_END

_CORBA_MODULE_END



_CORBA_MODULE POA_hpp
_CORBA_MODULE_BEG

  _CORBA_MODULE core_idl
  _CORBA_MODULE_BEG

    class PathPlanner :
      public virtual hpp::core_idl::_impl_PathPlanner,
      public virtual ::PortableServer::ServantBase
    {
    public:
      virtual ~PathPlanner();

      inline ::hpp::core_idl::PathPlanner_ptr _this() {
        return (::hpp::core_idl::PathPlanner_ptr) _do_this(::hpp::core_idl::PathPlanner::_PD_repoId);
      }
    };

  _CORBA_MODULE_END

_CORBA_MODULE_END



_CORBA_MODULE OBV_hpp
_CORBA_MODULE_BEG

  _CORBA_MODULE core_idl
  _CORBA_MODULE_BEG

  _CORBA_MODULE_END

_CORBA_MODULE_END





#undef _core_attr
#undef _dyn_attr



inline void
hpp::core_idl::PathPlanner::_marshalObjRef(::hpp::core_idl::PathPlanner_ptr obj, cdrStream& s) {
  omniObjRef::_marshal(obj->_PR_getobj(),s);
}




#ifdef   USE_stub_in_nt_dll_NOT_DEFINED_path__planners
# undef  USE_stub_in_nt_dll
# undef  USE_stub_in_nt_dll_NOT_DEFINED_path__planners
#endif
#ifdef   USE_core_stub_in_nt_dll_NOT_DEFINED_path__planners
# undef  USE_core_stub_in_nt_dll
# undef  USE_core_stub_in_nt_dll_NOT_DEFINED_path__planners
#endif
#ifdef   USE_dyn_stub_in_nt_dll_NOT_DEFINED_path__planners
# undef  USE_dyn_stub_in_nt_dll
# undef  USE_dyn_stub_in_nt_dll_NOT_DEFINED_path__planners
#endif

#endif  // __path__planners_hh__

