// This file is generated by omniidl (C++ backend)- omniORB_4_1. Do not edit.
#ifndef hpp_core_idl__path__validations_hh__
#define hpp_core_idl__path__validations_hh__

#ifndef __CORBA_H_EXTERNAL_GUARD__
#include <omniORB4/CORBA.h>
#endif

#ifndef  USE_stub_in_nt_dll
# define USE_stub_in_nt_dll_NOT_DEFINED_path__validations
#endif
#ifndef  USE_core_stub_in_nt_dll
# define USE_core_stub_in_nt_dll_NOT_DEFINED_path__validations
#endif
#ifndef  USE_dyn_stub_in_nt_dll
# define USE_dyn_stub_in_nt_dll_NOT_DEFINED_path__validations
#endif



#ifndef hpp_core_idl__common_hh_EXTERNAL_GUARD__
#define hpp_core_idl__common_hh_EXTERNAL_GUARD__
#include <hpp/common-idl.hh>
#endif
#ifndef hpp_core_idl__paths_hh_EXTERNAL_GUARD__
#define hpp_core_idl__paths_hh_EXTERNAL_GUARD__
#include <hpp/core_idl/paths-idl.hh>
#endif



#ifdef USE_stub_in_nt_dll
# ifndef USE_core_stub_in_nt_dll
#  define USE_core_stub_in_nt_dll
# endif
# ifndef USE_dyn_stub_in_nt_dll
#  define USE_dyn_stub_in_nt_dll
# endif
#endif

#ifdef _core_attr
# error "A local CPP macro _core_attr has already been defined."
#else
# ifdef  USE_core_stub_in_nt_dll
#  define _core_attr _OMNIORB_NTDLL_IMPORT
# else
#  define _core_attr
# endif
#endif

#ifdef _dyn_attr
# error "A local CPP macro _dyn_attr has already been defined."
#else
# ifdef  USE_dyn_stub_in_nt_dll
#  define _dyn_attr _OMNIORB_NTDLL_IMPORT
# else
#  define _dyn_attr
# endif
#endif





_CORBA_MODULE hpp

_CORBA_MODULE_BEG

  _CORBA_MODULE core_idl

  _CORBA_MODULE_BEG

    typedef char* PathValidationReport;
    typedef ::CORBA::String_var PathValidationReport_var;
    typedef ::CORBA::String_out PathValidationReport_out;

#ifndef __hpp_mcore__idl_mPathValidation__
#define __hpp_mcore__idl_mPathValidation__

    class PathValidation;
    class _objref_PathValidation;
    class _impl_PathValidation;
    
    typedef _objref_PathValidation* PathValidation_ptr;
    typedef PathValidation_ptr PathValidationRef;

    class PathValidation_Helper {
    public:
      typedef PathValidation_ptr _ptr_type;

      static _ptr_type _nil();
      static _CORBA_Boolean is_nil(_ptr_type);
      static void release(_ptr_type);
      static void duplicate(_ptr_type);
      static void marshalObjRef(_ptr_type, cdrStream&);
      static _ptr_type unmarshalObjRef(cdrStream&);
    };

    typedef _CORBA_ObjRef_Var<_objref_PathValidation, PathValidation_Helper> PathValidation_var;
    typedef _CORBA_ObjRef_OUT_arg<_objref_PathValidation,PathValidation_Helper > PathValidation_out;

#endif

    // interface PathValidation
    class PathValidation {
    public:
      // Declarations for this interface type.
      typedef PathValidation_ptr _ptr_type;
      typedef PathValidation_var _var_type;

      static _ptr_type _duplicate(_ptr_type);
      static _ptr_type _narrow(::CORBA::Object_ptr);
      static _ptr_type _unchecked_narrow(::CORBA::Object_ptr);
      
      static _ptr_type _nil();

      static inline void _marshalObjRef(_ptr_type, cdrStream&);

      static inline _ptr_type _unmarshalObjRef(cdrStream& s) {
        omniObjRef* o = omniObjRef::_unMarshal(_PD_repoId,s);
        if (o)
          return (_ptr_type) o->_ptrToObjRef(_PD_repoId);
        else
          return _nil();
      }

      static _core_attr const char* _PD_repoId;

      // Other IDL defined within this scope.
      
    };

    class _objref_PathValidation :
      public virtual ::CORBA::Object,
      public virtual omniObjRef
    {
    public:
      ::CORBA::Boolean validate(::hpp::core_idl::Path_ptr p, ::CORBA::Boolean reverse, ::hpp::core_idl::Path_out validPart, ::hpp::core_idl::PathValidationReport_out report);

      inline _objref_PathValidation()  { _PR_setobj(0); }  // nil
      _objref_PathValidation(omniIOR*, omniIdentity*);

    protected:
      virtual ~_objref_PathValidation();

      
    private:
      virtual void* _ptrToObjRef(const char*);

      _objref_PathValidation(const _objref_PathValidation&);
      _objref_PathValidation& operator = (const _objref_PathValidation&);
      // not implemented

      friend class PathValidation;
    };

    class _pof_PathValidation : public _OMNI_NS(proxyObjectFactory) {
    public:
      inline _pof_PathValidation() : _OMNI_NS(proxyObjectFactory)(PathValidation::_PD_repoId) {}
      virtual ~_pof_PathValidation();

      virtual omniObjRef* newObjRef(omniIOR*,omniIdentity*);
      virtual _CORBA_Boolean is_a(const char*) const;
    };

    class _impl_PathValidation :
      public virtual omniServant
    {
    public:
      virtual ~_impl_PathValidation();

      virtual ::CORBA::Boolean validate(::hpp::core_idl::Path_ptr p, ::CORBA::Boolean reverse, ::hpp::core_idl::Path_out validPart, ::hpp::core_idl::PathValidationReport_out report) = 0;
      
    public:  // Really protected, workaround for xlC
      virtual _CORBA_Boolean _dispatch(omniCallHandle&);

    private:
      virtual void* _ptrToInterface(const char*);
      virtual const char* _mostDerivedRepoId();
      
    };


  _CORBA_MODULE_END

_CORBA_MODULE_END



_CORBA_MODULE POA_hpp
_CORBA_MODULE_BEG

  _CORBA_MODULE core_idl
  _CORBA_MODULE_BEG

    class PathValidation :
      public virtual hpp::core_idl::_impl_PathValidation,
      public virtual ::PortableServer::ServantBase
    {
    public:
      virtual ~PathValidation();

      inline ::hpp::core_idl::PathValidation_ptr _this() {
        return (::hpp::core_idl::PathValidation_ptr) _do_this(::hpp::core_idl::PathValidation::_PD_repoId);
      }
    };

  _CORBA_MODULE_END

_CORBA_MODULE_END



_CORBA_MODULE OBV_hpp
_CORBA_MODULE_BEG

  _CORBA_MODULE core_idl
  _CORBA_MODULE_BEG

  _CORBA_MODULE_END

_CORBA_MODULE_END





#undef _core_attr
#undef _dyn_attr



inline void
hpp::core_idl::PathValidation::_marshalObjRef(::hpp::core_idl::PathValidation_ptr obj, cdrStream& s) {
  omniObjRef::_marshal(obj->_PR_getobj(),s);
}




#ifdef   USE_stub_in_nt_dll_NOT_DEFINED_path__validations
# undef  USE_stub_in_nt_dll
# undef  USE_stub_in_nt_dll_NOT_DEFINED_path__validations
#endif
#ifdef   USE_core_stub_in_nt_dll_NOT_DEFINED_path__validations
# undef  USE_core_stub_in_nt_dll
# undef  USE_core_stub_in_nt_dll_NOT_DEFINED_path__validations
#endif
#ifdef   USE_dyn_stub_in_nt_dll_NOT_DEFINED_path__validations
# undef  USE_dyn_stub_in_nt_dll
# undef  USE_dyn_stub_in_nt_dll_NOT_DEFINED_path__validations
#endif

#endif  // __path__validations_hh__

