hpp::fcl::BVHModel< BV > Class Template Reference
hpp::fcl::BVHModel< BV > Class Template Reference
A class describing the bounding hierarchy of a mesh model or a point cloud model (which is viewed as a degraded version of mesh)
#include <hpp/fcl/BVH/BVH_model.h>
Public Member Functions
BVHModelType getModelType () const
Model type described by the instance.
BVHModel ()
Constructing an empty BVH.
BVHModel (const BVHModel &other)
copy from another BVH
~BVHModel ()
deconstruction, delete mesh data related.
const BVNode< BV > & getBV (int id) const
We provide getBV() and getNumBVs() because BVH may be compressed (in future), so we must provide some flexibility here.
BVNode< BV > & getBV (int id)
Access the bv giving the its index.
int getNumBVs () const
Get the number of bv in the BVH.
OBJECT_TYPE getObjectType () const
Get the object type: it is a BVH.
NODE_TYPE getNodeType () const
Get the BV type: default is unknown.
void computeLocalAABB ()
Compute the AABB for the BVH, used for broad-phase collision.
int beginModel (int num_tris=0, int num_vertices=0)
Begin a new BVH model.
int addVertex (const Vec3f &p)
Add one point in the new BVH model.
int addTriangle (const Vec3f &p1, const Vec3f &p2, const Vec3f &p3)
Add one triangle in the new BVH model.
int addSubModel (const std::vector< Vec3f > &ps, const std::vector< Triangle > &ts)
Add a set of triangles in the new BVH model.
int addSubModel (const std::vector< Vec3f > &ps)
Add a set of points in the new BVH model.
int endModel ()
End BVH model construction, will build the bounding volume hierarchy.
int beginReplaceModel ()
Replace the geometry information of current frame (i.e. should have the same mesh topology with the previous frame)
int replaceVertex (const Vec3f &p)
Replace one point in the old BVH model.
int replaceTriangle (const Vec3f &p1, const Vec3f &p2, const Vec3f &p3)
Replace one triangle in the old BVH model.
int replaceSubModel (const std::vector< Vec3f > &ps)
Replace a set of points in the old BVH model.
int endReplaceModel (bool refit=true, bool bottomup=true)
End BVH model replacement, will also refit or rebuild the bounding volume hierarchy.
int beginUpdateModel ()
Replace the geometry information of current frame (i.e.
int updateVertex (const Vec3f &p)
Update one point in the old BVH model.
int updateTriangle (const Vec3f &p1, const Vec3f &p2, const Vec3f &p3)
Update one triangle in the old BVH model.
int updateSubModel (const std::vector< Vec3f > &ps)
Update a set of points in the old BVH model.
int endUpdateModel (bool refit=true, bool bottomup=true)
End BVH model update, will also refit or rebuild the bounding volume hierarchy.
int memUsage (int msg) const
Check the number of memory used.
void makeParentRelative ()
This is a special acceleration: BVH_model default stores the BV's transform in world coordinate.
Vec3f computeCOM () const
compute center of mass
FCL_REAL computeVolume () const
compute the volume
Matrix3f computeMomentofInertia () const
compute the inertia matrix, related to the origin
template<>
NODE_TYPE getNodeType () const
Specialization of getNodeType() for BVHModel with different BV types.
template<>
NODE_TYPE getNodeType () const
get the node type
template<>
NODE_TYPE getNodeType () const
get the node type
template<>
NODE_TYPE getNodeType () const
get the node type
template<>
NODE_TYPE getNodeType () const
get the node type
template<>
NODE_TYPE getNodeType () const
get the node type
template<>
NODE_TYPE getNodeType () const
get the node type
template<>
NODE_TYPE getNodeType () const
get the node type
Public Member Functions inherited from hpp::fcl::CollisionGeometry
CollisionGeometry ()
virtual ~CollisionGeometry ()
void * getUserData () const
get user data in geometry
void setUserData (void *data)
set user data in geometry
bool isOccupied () const HPP_FCL_DEPRECATED
whether the object is completely occupied
bool isFree () const HPP_FCL_DEPRECATED
whether the object is completely free
bool isUncertain () const HPP_FCL_DEPRECATED
whether the object has some uncertainty
virtual Matrix3f computeMomentofInertiaRelatedToCOM () const
compute the inertia matrix, related to the com
Public Attributes
Vec3f * vertices
Geometry point data.
Triangle * tri_indices
Geometry triangle index data, will be NULL for point clouds.
Vec3f * prev_vertices
Geometry point data in previous frame.
int num_tris
Number of triangles.
int num_vertices
Number of points.
BVHBuildState build_state
The state of BVH building process.
boost::shared_ptr< BVSplitterBase< BV > > bv_splitter
Split rule to split one BV node into two children.
boost::shared_ptr< BVFitterBase< BV > > bv_fitter
Fitting rule to fit a BV node to a set of geometry primitives.
Public Attributes inherited from hpp::fcl::CollisionGeometry
Vec3f aabb_center
AABB center in local coordinate.
FCL_REAL aabb_radius
AABB radius.
AABB aabb_local
AABB in local coordinate, used for tight AABB when only translation transform.
void * user_data
pointer to user defined data specific to this object
FCL_REAL cost_density
collision cost for unit volume
FCL_REAL threshold_occupied
threshold for occupied (>= is occupied)
FCL_REAL threshold_free
threshold for free (<= is free)
Detailed Description
template<typename BV>
class hpp::fcl::BVHModel< BV >
A class describing the bounding hierarchy of a mesh model or a point cloud model (which is viewed as a degraded version of mesh)
Constructor & Destructor Documentation
template<typename BV> hpp::fcl::BVHModel< BV >::BVHModel () inline
Constructing an empty BVH.
Referenced by hpp::fcl::BVHModel< OBBRSS >::BVHModel().
template<typename BV> hpp::fcl::BVHModel< BV >::BVHModel (const BVHModel< BV > & other)
copy from another BVH
template<typename BV> hpp::fcl::BVHModel< BV >::~BVHModel () inline
deconstruction, delete mesh data related.
Member Function Documentation
template<typename BV> int hpp::fcl::BVHModel< BV >::addSubModel (const std::vector< Vec3f > & ps, const std::vector< Triangle > & ts)
Add a set of triangles in the new BVH model.
Referenced by hpp::fcl::generateBVHModel(), and hpp::fcl::BVHModel< OBBRSS >::getNodeType().
template<typename BV> int hpp::fcl::BVHModel< BV >::addSubModel (const std::vector< Vec3f > & ps)
Add a set of points in the new BVH model.
template<typename BV> int hpp::fcl::BVHModel< BV >::addTriangle (const Vec3f & p1, const Vec3f & p2, const Vec3f & p3)
Add one triangle in the new BVH model.
Referenced by hpp::fcl::BVHModel< OBBRSS >::getNodeType().
template<typename BV> int hpp::fcl::BVHModel< BV >::addVertex (const Vec3f & p)
Add one point in the new BVH model.
Referenced by hpp::fcl::BVHModel< OBBRSS >::getNodeType().
template<typename BV> int hpp::fcl::BVHModel< BV >::beginModel (int num_tris = 0, int num_vertices = 0)
Begin a new BVH model.
Referenced by hpp::fcl::generateBVHModel(), and hpp::fcl::BVHModel< OBBRSS >::getNodeType().
template<typename BV> int hpp::fcl::BVHModel< BV >::beginReplaceModel ()
Replace the geometry information of current frame (i.e. should have the same mesh topology with the previous frame)
Referenced by hpp::fcl::BVHModel< OBBRSS >::getNodeType(), and hpp::fcl::initialize().
template<typename BV> int hpp::fcl::BVHModel< BV >::beginUpdateModel ()
Replace the geometry information of current frame (i.e.
should have the same mesh topology with the previous frame). The current frame will be saved as the previous frame in prev_vertices.
Referenced by hpp::fcl::BVHModel< OBBRSS >::getNodeType().
template<typename BV> Vec3f hpp::fcl::BVHModel< BV >::computeCOM () const inline virtual
compute center of mass
Reimplemented from hpp::fcl::CollisionGeometry.
template<typename BV> void hpp::fcl::BVHModel< BV >::computeLocalAABB () virtual
Compute the AABB for the BVH, used for broad-phase collision.
Implements hpp::fcl::CollisionGeometry.
Referenced by hpp::fcl::generateBVHModel(), and hpp::fcl::BVHModel< OBBRSS >::getNodeType().
template<typename BV> Matrix3f hpp::fcl::BVHModel< BV >::computeMomentofInertia () const inline virtual
compute the inertia matrix, related to the origin
Reimplemented from hpp::fcl::CollisionGeometry.
template<typename BV> FCL_REAL hpp::fcl::BVHModel< BV >::computeVolume () const inline virtual
compute the volume
Reimplemented from hpp::fcl::CollisionGeometry.
template<typename BV> int hpp::fcl::BVHModel< BV >::endModel ()
End BVH model construction, will build the bounding volume hierarchy.
Referenced by hpp::fcl::generateBVHModel(), and hpp::fcl::BVHModel< OBBRSS >::getNodeType().
template<typename BV> int hpp::fcl::BVHModel< BV >::endReplaceModel (bool refit = true, bool bottomup = true)
End BVH model replacement, will also refit or rebuild the bounding volume hierarchy.
Referenced by hpp::fcl::BVHModel< OBBRSS >::getNodeType(), and hpp::fcl::initialize().
template<typename BV> int hpp::fcl::BVHModel< BV >::endUpdateModel (bool refit = true, bool bottomup = true)
End BVH model update, will also refit or rebuild the bounding volume hierarchy.
Referenced by hpp::fcl::BVHModel< OBBRSS >::getNodeType().
template<typename BV> const BVNode<BV>& hpp::fcl::BVHModel< BV >::getBV (int id) const inline
We provide getBV() and getNumBVs() because BVH may be compressed (in future), so we must provide some flexibility here.
Access the bv giving the its index
Referenced by hpp::fcl::BVHExpand(), and hpp::fcl::OcTreeSolver< NarrowPhaseSolver >::ShapeOcTreeDistance().
template<typename BV> BVNode<BV>& hpp::fcl::BVHModel< BV >::getBV (int id) inline
Access the bv giving the its index.
template<typename BV> BVHModelType hpp::fcl::BVHModel< BV >::getModelType () const inline
Model type described by the instance.
Referenced by hpp::fcl::initialize(), and hpp::fcl::details::setupShapeMeshDistanceOrientedNode().
template<typename BV> NODE_TYPE hpp::fcl::BVHModel< BV >::getNodeType () const inline virtual
Get the BV type: default is unknown.
Reimplemented from hpp::fcl::CollisionGeometry.
template<> NODE_TYPE hpp::fcl::BVHModel< AABB >::getNodeType () const virtual
Specialization of getNodeType() for BVHModel with different BV types.
Reimplemented from hpp::fcl::CollisionGeometry.
template<> NODE_TYPE hpp::fcl::BVHModel< OBB >::getNodeType () const virtual
get the node type
Reimplemented from hpp::fcl::CollisionGeometry.
template<> NODE_TYPE hpp::fcl::BVHModel< RSS >::getNodeType () const virtual
get the node type
Reimplemented from hpp::fcl::CollisionGeometry.
template<> NODE_TYPE hpp::fcl::BVHModel< kIOS >::getNodeType () const virtual
get the node type
Reimplemented from hpp::fcl::CollisionGeometry.
template<> NODE_TYPE hpp::fcl::BVHModel< OBBRSS >::getNodeType () const virtual
get the node type
Reimplemented from hpp::fcl::CollisionGeometry.
template<> NODE_TYPE hpp::fcl::BVHModel< KDOP< 16 > >::getNodeType () const virtual
get the node type
Reimplemented from hpp::fcl::CollisionGeometry.
template<> NODE_TYPE hpp::fcl::BVHModel< KDOP< 18 > >::getNodeType () const virtual
get the node type
Reimplemented from hpp::fcl::CollisionGeometry.
template<> NODE_TYPE hpp::fcl::BVHModel< KDOP< 24 > >::getNodeType () const virtual
get the node type
Reimplemented from hpp::fcl::CollisionGeometry.
template<typename BV> int hpp::fcl::BVHModel< BV >::getNumBVs () const inline
Get the number of bv in the BVH.
template<typename BV> OBJECT_TYPE hpp::fcl::BVHModel< BV >::getObjectType () const inline virtual
Get the object type: it is a BVH.
Reimplemented from hpp::fcl::CollisionGeometry.
template<typename BV> void hpp::fcl::BVHModel< BV >::makeParentRelative () inline
This is a special acceleration: BVH_model default stores the BV's transform in world coordinate.
However, we can also store each BV's transform related to its parent BV node. When traversing the BVH, this can save one matrix transformation.
template<typename BV> int hpp::fcl::BVHModel< BV >::memUsage (int msg) const
Check the number of memory used.
Referenced by hpp::fcl::BVHModel< OBBRSS >::getNodeType().
template<typename BV> int hpp::fcl::BVHModel< BV >::replaceSubModel (const std::vector< Vec3f > & ps)
Replace a set of points in the old BVH model.
Referenced by hpp::fcl::BVHModel< OBBRSS >::getNodeType(), and hpp::fcl::initialize().
template<typename BV> int hpp::fcl::BVHModel< BV >::replaceTriangle (const Vec3f & p1, const Vec3f & p2, const Vec3f & p3)
Replace one triangle in the old BVH model.
Referenced by hpp::fcl::BVHModel< OBBRSS >::getNodeType().
template<typename BV> int hpp::fcl::BVHModel< BV >::replaceVertex (const Vec3f & p)
Replace one point in the old BVH model.
Referenced by hpp::fcl::BVHModel< OBBRSS >::getNodeType().
template<typename BV> int hpp::fcl::BVHModel< BV >::updateSubModel (const std::vector< Vec3f > & ps)
Update a set of points in the old BVH model.
Referenced by hpp::fcl::BVHModel< OBBRSS >::getNodeType().
template<typename BV> int hpp::fcl::BVHModel< BV >::updateTriangle (const Vec3f & p1, const Vec3f & p2, const Vec3f & p3)
Update one triangle in the old BVH model.
Referenced by hpp::fcl::BVHModel< OBBRSS >::getNodeType().
template<typename BV> int hpp::fcl::BVHModel< BV >::updateVertex (const Vec3f & p)
Update one point in the old BVH model.
Referenced by hpp::fcl::BVHModel< OBBRSS >::getNodeType().
Member Data Documentation
template<typename BV> BVHBuildState hpp::fcl::BVHModel< BV >::build_state
The state of BVH building process.
template<typename BV> boost::shared_ptr<BVFitterBase<BV> > hpp::fcl::BVHModel< BV >::bv_fitter
Fitting rule to fit a BV node to a set of geometry primitives.
template<typename BV> boost::shared_ptr<BVSplitterBase<BV> > hpp::fcl::BVHModel< BV >::bv_splitter
Split rule to split one BV node into two children.
template<typename BV> int hpp::fcl::BVHModel< BV >::num_tris
Number of triangles.
Referenced by hpp::fcl::BVHModel< OBBRSS >::computeCOM(), hpp::fcl::BVHModel< OBBRSS >::computeMomentofInertia(), hpp::fcl::BVHModel< OBBRSS >::computeVolume(), hpp::fcl::BVHModel< OBBRSS >::getModelType(), and hpp::fcl::BVHModel< OBBRSS >::getNodeType().
template<typename BV> int hpp::fcl::BVHModel< BV >::num_vertices
Number of points.
Referenced by hpp::fcl::BVHModel< OBBRSS >::getModelType(), hpp::fcl::BVHModel< OBBRSS >::getNodeType(), and hpp::fcl::initialize().
template<typename BV> Vec3f* hpp::fcl::BVHModel< BV >::prev_vertices
Geometry point data in previous frame.
Referenced by hpp::fcl::BVHModel< OBBRSS >::~BVHModel().
template<typename BV> Triangle* hpp::fcl::BVHModel< BV >::tri_indices
Geometry triangle index data, will be NULL for point clouds.
Referenced by hpp::fcl::BVHModel< OBBRSS >::computeCOM(), hpp::fcl::BVHModel< OBBRSS >::computeMomentofInertia(), hpp::fcl::BVHModel< OBBRSS >::computeVolume(), hpp::fcl::initialize(), hpp::fcl::details::setupShapeMeshDistanceOrientedNode(), hpp::fcl::OcTreeSolver< NarrowPhaseSolver >::ShapeOcTreeDistance(), and hpp::fcl::BVHModel< OBBRSS >::~BVHModel().
template<typename BV> Vec3f* hpp::fcl::BVHModel< BV >::vertices
Geometry point data.
Referenced by hpp::fcl::BVHExpand(), hpp::fcl::BVHModel< OBBRSS >::computeCOM(), hpp::fcl::BVHModel< OBBRSS >::computeMomentofInertia(), hpp::fcl::BVHModel< OBBRSS >::computeVolume(), hpp::fcl::initialize(), hpp::fcl::details::setupShapeMeshDistanceOrientedNode(), hpp::fcl::OcTreeSolver< NarrowPhaseSolver >::ShapeOcTreeDistance(), and hpp::fcl::BVHModel< OBBRSS >::~BVHModel().