hpp::fcl::MeshCollisionTraversalNode< BV, _Options > Class Template Reference
hpp::fcl::MeshCollisionTraversalNode< BV, _Options > Class Template Reference
Traversal node for collision between two meshes.
#include <hpp/fcl/traversal/traversal_node_bvhs.h>
Public Types
enum {
Options = _Options,
RTIsIdentity = _Options & RelativeTransformationIsIdentity
}
Public Member Functions
MeshCollisionTraversalNode (const CollisionRequest &request)
bool BVTesting (int b1, int b2) const
BV culling test in one BVTT node.
bool BVTesting (int b1, int b2, FCL_REAL &sqrDistLowerBound) const
BV test between b1 and b2.
void leafTesting (int b1, int b2, FCL_REAL &sqrDistLowerBound) const
Intersection testing between leaves (two triangles)
bool canStop () const
Whether the traversal process can stop early.
Public Member Functions inherited from hpp::fcl::BVHCollisionTraversalNode< BV >
BVHCollisionTraversalNode (const CollisionRequest &request)
bool isFirstNodeLeaf (int b) const
Whether the BV node in the first BVH tree is leaf.
bool isSecondNodeLeaf (int b) const
Whether the BV node in the second BVH tree is leaf.
bool firstOverSecond (int b1, int b2) const
Determine the traversal order, is the first BVTT subtree better.
int getFirstLeftChild (int b) const
Obtain the left child of BV node in the first BVH.
int getFirstRightChild (int b) const
Obtain the right child of BV node in the first BVH.
int getSecondLeftChild (int b) const
Obtain the left child of BV node in the second BVH.
int getSecondRightChild (int b) const
Obtain the right child of BV node in the second BVH.
Public Member Functions inherited from hpp::fcl::CollisionTraversalNodeBase
CollisionTraversalNodeBase (const CollisionRequest &request_)
virtual ~CollisionTraversalNodeBase ()
void enableStatistics (bool enable)
Whether store some statistics information during traversal.
Public Member Functions inherited from hpp::fcl::TraversalNodeBase
virtual ~TraversalNodeBase ()
virtual void preprocess ()
virtual void postprocess ()
Public Attributes
Vec3f * vertices1
Vec3f * vertices2
Triangle * tri_indices1
Triangle * tri_indices2
details::RelativeTransformation<!bool(RTIsIdentity)> RT
Public Attributes inherited from hpp::fcl::BVHCollisionTraversalNode< BV >
const BVHModel< BV > * model1
The first BVH model.
const BVHModel< BV > * model2
The second BVH model.
int num_bv_tests
statistical information
int num_leaf_tests
FCL_REAL query_time_seconds
Public Attributes inherited from hpp::fcl::CollisionTraversalNodeBase
const CollisionRequest & request
request setting for collision
CollisionResult * result
collision result kept during the traversal iteration
bool enable_statistics
Whether stores statistics.
Public Attributes inherited from hpp::fcl::TraversalNodeBase
Transform3f tf1
configuation of first object
Transform3f tf2
configuration of second object
Detailed Description
template<typename BV, int _Options = RelativeTransformationIsIdentity>
class hpp::fcl::MeshCollisionTraversalNode< BV, _Options >
Traversal node for collision between two meshes.
Member Enumeration Documentation
template<typename BV, int _Options = RelativeTransformationIsIdentity> anonymous enum
Enumerator
Options
RTIsIdentity
Constructor & Destructor Documentation
template<typename BV, int _Options = RelativeTransformationIsIdentity> hpp::fcl::MeshCollisionTraversalNode< BV, _Options >::MeshCollisionTraversalNode (const CollisionRequest & request) inline
Member Function Documentation
template<typename BV, int _Options = RelativeTransformationIsIdentity> bool hpp::fcl::MeshCollisionTraversalNode< BV, _Options >::BVTesting (int b1, int b2) const inline virtual
BV culling test in one BVTT node.
Implements hpp::fcl::CollisionTraversalNodeBase.
References hpp::fcl::CollisionTraversalNodeBase::enable_statistics, hpp::fcl::BVHCollisionTraversalNode< BV >::model1, hpp::fcl::BVHCollisionTraversalNode< BV >::model2, hpp::fcl::BVHCollisionTraversalNode< BV >::num_bv_tests, and hpp::fcl::overlap().
template<typename BV, int _Options = RelativeTransformationIsIdentity> bool hpp::fcl::MeshCollisionTraversalNode< BV, _Options >::BVTesting (int b1, int b2, FCL_REAL & sqrDistLowerBound) const inline virtual
BV test between b1 and b2.
Parameters
b1,b2 Bounding volumes to test,
Return values
sqrDistLowerBound square of a lower bound of the minimal distance between bounding volumes.
Implements hpp::fcl::CollisionTraversalNodeBase.
References hpp::fcl::CollisionTraversalNodeBase::enable_statistics, hpp::fcl::BVHCollisionTraversalNode< BV >::model1, hpp::fcl::BVHCollisionTraversalNode< BV >::model2, hpp::fcl::BVHCollisionTraversalNode< BV >::num_bv_tests, hpp::fcl::overlap(), and hpp::fcl::CollisionTraversalNodeBase::request.
template<typename BV, int _Options = RelativeTransformationIsIdentity> bool hpp::fcl::MeshCollisionTraversalNode< BV, _Options >::canStop () const inline virtual
Whether the traversal process can stop early.
Reimplemented from hpp::fcl::CollisionTraversalNodeBase.
References hpp::fcl::CollisionRequest::isSatisfied(), hpp::fcl::CollisionTraversalNodeBase::request, and hpp::fcl::CollisionTraversalNodeBase::result.
template<typename BV, int _Options = RelativeTransformationIsIdentity> void hpp::fcl::MeshCollisionTraversalNode< BV, _Options >::leafTesting (int b1, int b2, FCL_REAL & sqrDistLowerBound) const inline virtual
Intersection testing between leaves (two triangles)
Parameters
b1,b2 id of primitive in bounding volume hierarchy
Return values
sqrDistLowerBound squared lower bound of distance between primitives if they are not in collision.
This method supports a security margin. If the distance between the primitives is less than the security margin, the objects are considered as in collision. in this case a contact point is returned in the CollisionResult.
Note
If the distance between objects is less than the security margin, and the object are not colliding, the penetration depth is negative.
Reimplemented from hpp::fcl::CollisionTraversalNodeBase.
References hpp::fcl::CollisionResult::addContact(), hpp::fcl::distance(), hpp::fcl::CollisionTraversalNodeBase::enable_statistics, hpp::fcl::BVHCollisionTraversalNode< BV >::model1, hpp::fcl::BVHCollisionTraversalNode< BV >::model2, hpp::fcl::BVHCollisionTraversalNode< BV >::num_leaf_tests, hpp::fcl::CollisionRequest::num_max_contacts, hpp::fcl::CollisionResult::numContacts(), hpp::fcl::BVNodeBase::primitiveId(), hpp::fcl::CollisionTraversalNodeBase::request, hpp::fcl::CollisionTraversalNodeBase::result, hpp::fcl::CollisionRequest::security_margin, hpp::fcl::GJKSolver_indep::shapeDistance(), hpp::fcl::TraversalNodeBase::tf1, and hpp::fcl::TraversalNodeBase::tf2.
Member Data Documentation
template<typename BV, int _Options = RelativeTransformationIsIdentity> details::RelativeTransformation<!bool(RTIsIdentity)> hpp::fcl::MeshCollisionTraversalNode< BV, _Options >::RT
template<typename BV, int _Options = RelativeTransformationIsIdentity> Triangle* hpp::fcl::MeshCollisionTraversalNode< BV, _Options >::tri_indices1
Referenced by hpp::fcl::initialize().
template<typename BV, int _Options = RelativeTransformationIsIdentity> Triangle* hpp::fcl::MeshCollisionTraversalNode< BV, _Options >::tri_indices2
Referenced by hpp::fcl::initialize().
template<typename BV, int _Options = RelativeTransformationIsIdentity> Vec3f* hpp::fcl::MeshCollisionTraversalNode< BV, _Options >::vertices1
Referenced by hpp::fcl::initialize().
template<typename BV, int _Options = RelativeTransformationIsIdentity> Vec3f* hpp::fcl::MeshCollisionTraversalNode< BV, _Options >::vertices2
Referenced by hpp::fcl::initialize().