hpp::fcl::OcTree Class Reference
hpp::fcl::OcTree Class Reference
Octree is one type of collision geometry which can encode uncertainty information in the sensor data.
#include <hpp/fcl/octree.h>
Public Types
typedef octomap::OcTreeNode OcTreeNode
Public Member Functions
OcTree (FCL_REAL resolution)
construct octree with a given resolution
OcTree (const boost::shared_ptr< const octomap::OcTree > &tree_)
construct octree from octomap
void computeLocalAABB ()
compute the AABB for the octree in its local coordinate system
AABB getRootBV () const
get the bounding volume for the root
OcTreeNode * getRoot () const
get the root node of the octree
bool isNodeOccupied (const OcTreeNode *node) const
whether one node is completely occupied
bool isNodeFree (const OcTreeNode *node) const
whether one node is completely free
bool isNodeUncertain (const OcTreeNode *node) const
whether one node is uncertain
std::vector< boost::array< FCL_REAL, 6 > > toBoxes () const
transform the octree into a bunch of boxes; uncertainty information is kept in the boxes.
FCL_REAL getOccupancyThres () const
the threshold used to decide whether one node is occupied, this is NOT the octree occupied_thresold
FCL_REAL getFreeThres () const
the threshold used to decide whether one node is occupied, this is NOT the octree free_threshold
FCL_REAL getDefaultOccupancy () const
void setCellDefaultOccupancy (FCL_REAL d)
void setOccupancyThres (FCL_REAL d)
void setFreeThres (FCL_REAL d)
OcTreeNode * getNodeChild (OcTreeNode *node, unsigned int childIdx)
const OcTreeNode * getNodeChild (const OcTreeNode *node, unsigned int childIdx) const
bool nodeChildExists (const OcTreeNode *node, unsigned int childIdx) const
return true if the child at childIdx exists
bool nodeHasChildren (const OcTreeNode *node) const
return true if node has at least one child
OBJECT_TYPE getObjectType () const
return object type, it is an octree
NODE_TYPE getNodeType () const
return node type, it is an octree
Public Member Functions inherited from hpp::fcl::CollisionGeometry
CollisionGeometry ()
virtual ~CollisionGeometry ()
void * getUserData () const
get user data in geometry
void setUserData (void *data)
set user data in geometry
bool isOccupied () const HPP_FCL_DEPRECATED
whether the object is completely occupied
bool isFree () const HPP_FCL_DEPRECATED
whether the object is completely free
bool isUncertain () const HPP_FCL_DEPRECATED
whether the object has some uncertainty
virtual Vec3f computeCOM () const
compute center of mass
virtual Matrix3f computeMomentofInertia () const
compute the inertia matrix, related to the origin
virtual FCL_REAL computeVolume () const
compute the volume
virtual Matrix3f computeMomentofInertiaRelatedToCOM () const
compute the inertia matrix, related to the com
Additional Inherited Members
Public Attributes inherited from hpp::fcl::CollisionGeometry
Vec3f aabb_center
AABB center in local coordinate.
FCL_REAL aabb_radius
AABB radius.
AABB aabb_local
AABB in local coordinate, used for tight AABB when only translation transform.
void * user_data
pointer to user defined data specific to this object
FCL_REAL cost_density
collision cost for unit volume
FCL_REAL threshold_occupied
threshold for occupied (>= is occupied)
FCL_REAL threshold_free
threshold for free (<= is free)
Detailed Description
Octree is one type of collision geometry which can encode uncertainty information in the sensor data.
Member Typedef Documentation
typedef octomap::OcTreeNode hpp::fcl::OcTree::OcTreeNode
Constructor & Destructor Documentation
hpp::fcl::OcTree::OcTree (FCL_REAL resolution) inline
construct octree with a given resolution
hpp::fcl::OcTree::OcTree (const boost::shared_ptr< const octomap::OcTree > & tree_) inline
construct octree from octomap
Member Function Documentation
void hpp::fcl::OcTree::computeLocalAABB () inline virtual
compute the AABB for the octree in its local coordinate system
Implements hpp::fcl::CollisionGeometry.
References hpp::fcl::CollisionGeometry::aabb_center, hpp::fcl::CollisionGeometry::aabb_local, hpp::fcl::CollisionGeometry::aabb_radius, hpp::fcl::AABB::center(), getRootBV(), and hpp::fcl::AABB::min_.
FCL_REAL hpp::fcl::OcTree::getDefaultOccupancy () const inline
FCL_REAL hpp::fcl::OcTree::getFreeThres () const inline
the threshold used to decide whether one node is occupied, this is NOT the octree free_threshold
OcTreeNode* hpp::fcl::OcTree::getNodeChild (OcTreeNode * node, unsigned int childIdx) inline
Returns
ptr to child number childIdx of node
Referenced by hpp::fcl::OcTreeSolver< NarrowPhaseSolver >::ShapeOcTreeDistance().
const OcTreeNode* hpp::fcl::OcTree::getNodeChild (const OcTreeNode * node, unsigned int childIdx) const inline
Returns
const ptr to child number childIdx of node
NODE_TYPE hpp::fcl::OcTree::getNodeType () const inline virtual
return node type, it is an octree
Reimplemented from hpp::fcl::CollisionGeometry.
References hpp::fcl::GEOM_OCTREE.
OBJECT_TYPE hpp::fcl::OcTree::getObjectType () const inline virtual
return object type, it is an octree
Reimplemented from hpp::fcl::CollisionGeometry.
References hpp::fcl::OT_OCTREE.
FCL_REAL hpp::fcl::OcTree::getOccupancyThres () const inline
the threshold used to decide whether one node is occupied, this is NOT the octree occupied_thresold
OcTreeNode* hpp::fcl::OcTree::getRoot () const inline
get the root node of the octree
Referenced by hpp::fcl::OcTreeSolver< NarrowPhaseSolver >::MeshOcTreeDistance(), hpp::fcl::OcTreeSolver< NarrowPhaseSolver >::MeshOcTreeIntersect(), hpp::fcl::OcTreeSolver< NarrowPhaseSolver >::OcTreeDistance(), hpp::fcl::OcTreeSolver< NarrowPhaseSolver >::OcTreeIntersect(), hpp::fcl::OcTreeSolver< NarrowPhaseSolver >::OcTreeMeshDistance(), hpp::fcl::OcTreeSolver< NarrowPhaseSolver >::OcTreeMeshIntersect(), hpp::fcl::OcTreeSolver< NarrowPhaseSolver >::OcTreeShapeDistance(), hpp::fcl::OcTreeSolver< NarrowPhaseSolver >::OcTreeShapeIntersect(), hpp::fcl::OcTreeSolver< NarrowPhaseSolver >::ShapeOcTreeDistance(), and hpp::fcl::OcTreeSolver< NarrowPhaseSolver >::ShapeOcTreeIntersect().
AABB hpp::fcl::OcTree::getRootBV () const inline
get the bounding volume for the root
Referenced by computeLocalAABB(), hpp::fcl::OcTreeSolver< NarrowPhaseSolver >::MeshOcTreeDistance(), hpp::fcl::OcTreeSolver< NarrowPhaseSolver >::MeshOcTreeIntersect(), hpp::fcl::OcTreeSolver< NarrowPhaseSolver >::OcTreeDistance(), hpp::fcl::OcTreeSolver< NarrowPhaseSolver >::OcTreeIntersect(), hpp::fcl::OcTreeSolver< NarrowPhaseSolver >::OcTreeMeshDistance(), hpp::fcl::OcTreeSolver< NarrowPhaseSolver >::OcTreeMeshIntersect(), hpp::fcl::OcTreeSolver< NarrowPhaseSolver >::OcTreeShapeDistance(), hpp::fcl::OcTreeSolver< NarrowPhaseSolver >::OcTreeShapeIntersect(), hpp::fcl::OcTreeSolver< NarrowPhaseSolver >::ShapeOcTreeDistance(), and hpp::fcl::OcTreeSolver< NarrowPhaseSolver >::ShapeOcTreeIntersect().
bool hpp::fcl::OcTree::isNodeFree (const OcTreeNode * node) const inline
whether one node is completely free
Referenced by isNodeUncertain(), and hpp::fcl::OcTreeSolver< NarrowPhaseSolver >::ShapeOcTreeDistance().
bool hpp::fcl::OcTree::isNodeOccupied (const OcTreeNode * node) const inline
whether one node is completely occupied
Referenced by isNodeUncertain(), hpp::fcl::OcTreeSolver< NarrowPhaseSolver >::ShapeOcTreeDistance(), and toBoxes().
bool hpp::fcl::OcTree::isNodeUncertain (const OcTreeNode * node) const inline
whether one node is uncertain
References isNodeFree(), and isNodeOccupied().
Referenced by hpp::fcl::OcTreeSolver< NarrowPhaseSolver >::ShapeOcTreeDistance().
bool hpp::fcl::OcTree::nodeChildExists (const OcTreeNode * node, unsigned int childIdx) const inline
return true if the child at childIdx exists
Referenced by hpp::fcl::OcTreeSolver< NarrowPhaseSolver >::ShapeOcTreeDistance().
bool hpp::fcl::OcTree::nodeHasChildren (const OcTreeNode * node) const inline
return true if node has at least one child
Referenced by hpp::fcl::OcTreeSolver< NarrowPhaseSolver >::ShapeOcTreeDistance().
void hpp::fcl::OcTree::setCellDefaultOccupancy (FCL_REAL d) inline
void hpp::fcl::OcTree::setFreeThres (FCL_REAL d) inline
void hpp::fcl::OcTree::setOccupancyThres (FCL_REAL d) inline
std::vector<boost::array<FCL_REAL, 6> > hpp::fcl::OcTree::toBoxes () const inline
transform the octree into a bunch of boxes; uncertainty information is kept in the boxes.
However, we only keep the occupied boxes (i.e., the boxes whose occupied probability is higher enough).
References isNodeOccupied().