hpp::fcl::MeshShapeDistanceTraversalNodeOBBRSS< S, NarrowPhaseSolver > Class Template Reference
hpp::fcl::MeshShapeDistanceTraversalNodeOBBRSS< S, NarrowPhaseSolver > Class Template Reference
#include <hpp/fcl/traversal/traversal_node_bvh_shape.h>
Public Member Functions
MeshShapeDistanceTraversalNodeOBBRSS ()
void preprocess ()
void postprocess ()
FCL_REAL BVTesting (int b1, int) const
BV test between b1 and b2.
void leafTesting (int b1, int b2) const
Leaf test between node b1 and b2, if they are both leafs.
Public Member Functions inherited from hpp::fcl::MeshShapeDistanceTraversalNode< OBBRSS, S, NarrowPhaseSolver >
MeshShapeDistanceTraversalNode ()
void leafTesting (int b1, int) const
Distance testing between leaves (one triangle and one shape)
bool canStop (FCL_REAL c) const
Whether the traversal process can stop early.
Public Member Functions inherited from hpp::fcl::BVHShapeDistanceTraversalNode< OBBRSS, S >
BVHShapeDistanceTraversalNode ()
bool isFirstNodeLeaf (int b) const
Whether the BV node in the first BVH tree is leaf.
int getFirstLeftChild (int b) const
Obtain the left child of BV node in the first BVH.
int getFirstRightChild (int b) const
Obtain the right child of BV node in the first BVH.
FCL_REAL BVTesting (int b1, int) const
BV culling test in one BVTT node.
Public Member Functions inherited from hpp::fcl::DistanceTraversalNodeBase
DistanceTraversalNodeBase ()
virtual ~DistanceTraversalNodeBase ()
void enableStatistics (bool enable)
Whether store some statistics information during traversal.
Public Member Functions inherited from hpp::fcl::TraversalNodeBase
virtual ~TraversalNodeBase ()
virtual bool isSecondNodeLeaf (int b) const
Whether b is a leaf node in the second BVH tree.
virtual bool firstOverSecond (int b1, int b2) const
Traverse the subtree of the node in the first tree first.
virtual int getSecondLeftChild (int b) const
Get the left child of the node b in the second tree.
virtual int getSecondRightChild (int b) const
Get the right child of the node b in the second tree.
Additional Inherited Members
Public Attributes inherited from hpp::fcl::MeshShapeDistanceTraversalNode< OBBRSS, S, NarrowPhaseSolver >
Vec3f * vertices
Triangle * tri_indices
FCL_REAL rel_err
FCL_REAL abs_err
const NarrowPhaseSolver * nsolver
Public Attributes inherited from hpp::fcl::BVHShapeDistanceTraversalNode< OBBRSS, S >
const BVHModel< OBBRSS > * model1
const S * model2
OBBRSS model2_bv
int num_bv_tests
int num_leaf_tests
FCL_REAL query_time_seconds
Public Attributes inherited from hpp::fcl::DistanceTraversalNodeBase
DistanceRequest request
request setting for distance
DistanceResult * result
distance result kept during the traversal iteration
bool enable_statistics
Whether stores statistics.
Public Attributes inherited from hpp::fcl::TraversalNodeBase
Transform3f tf1
configuation of first object
Transform3f tf2
configuration of second object
Constructor & Destructor Documentation
template<typename S, typename NarrowPhaseSolver> hpp::fcl::MeshShapeDistanceTraversalNodeOBBRSS< S, NarrowPhaseSolver >::MeshShapeDistanceTraversalNodeOBBRSS () inline
Member Function Documentation
template<typename S, typename NarrowPhaseSolver> FCL_REAL hpp::fcl::MeshShapeDistanceTraversalNodeOBBRSS< S, NarrowPhaseSolver >::BVTesting (int b1, int b2) const inline virtual
BV test between b1 and b2.
Returns
a lower bound of the distance between the two BV.
Note
except for OBB, this method returns the distance.
Reimplemented from hpp::fcl::DistanceTraversalNodeBase.
References hpp::fcl::distance(), hpp::fcl::CollisionTraversalNodeBase::enable_statistics, hpp::fcl::Transform3f::getRotation(), hpp::fcl::Transform3f::getTranslation(), hpp::fcl::BVHShapeCollisionTraversalNode< BV, S >::model1, hpp::fcl::BVHShapeCollisionTraversalNode< BV, S >::model2_bv, hpp::fcl::BVHShapeCollisionTraversalNode< BV, S >::num_bv_tests, and hpp::fcl::TraversalNodeBase::tf1.
template<typename S, typename NarrowPhaseSolver> void hpp::fcl::MeshShapeDistanceTraversalNodeOBBRSS< S, NarrowPhaseSolver >::leafTesting (int b1, int b2) const inline virtual
Leaf test between node b1 and b2, if they are both leafs.
Implements hpp::fcl::DistanceTraversalNodeBase.
References hpp::fcl::CollisionTraversalNodeBase::enable_statistics, hpp::fcl::BVHShapeCollisionTraversalNode< BV, S >::model1, hpp::fcl::BVHShapeCollisionTraversalNode< BV, S >::model2, hpp::fcl::BVHShapeCollisionTraversalNode< BV, S >::num_leaf_tests, hpp::fcl::CollisionTraversalNodeBase::request, hpp::fcl::CollisionTraversalNodeBase::result, hpp::fcl::TraversalNodeBase::tf1, and hpp::fcl::TraversalNodeBase::tf2.
template<typename S, typename NarrowPhaseSolver> void hpp::fcl::MeshShapeDistanceTraversalNodeOBBRSS< S, NarrowPhaseSolver >::postprocess () inline virtual
Reimplemented from hpp::fcl::TraversalNodeBase.
template<typename S, typename NarrowPhaseSolver> void hpp::fcl::MeshShapeDistanceTraversalNodeOBBRSS< S, NarrowPhaseSolver >::preprocess () inline virtual
Reimplemented from hpp::fcl::TraversalNodeBase.
References hpp::fcl::BVHShapeCollisionTraversalNode< BV, S >::model1, hpp::fcl::BVHShapeCollisionTraversalNode< BV, S >::model2, hpp::fcl::CollisionTraversalNodeBase::request, hpp::fcl::CollisionTraversalNodeBase::result, hpp::fcl::TraversalNodeBase::tf1, and hpp::fcl::TraversalNodeBase::tf2.