hpp::fcl::time Namespace Reference
hpp::fcl::time Namespace Reference
Namespace containing time datatypes and time operations.
Typedefs
typedef boost::posix_time::ptime point
Representation of a point in time.
typedef boost::posix_time::time_duration duration
Representation of a time duration.
Functions
point now (void)
Get the current time point.
duration seconds (double sec)
Return the time duration representing a given number of seconds.
double seconds (const duration &d)
Return the number of seconds that a time duration represents.
Detailed Description
Namespace containing time datatypes and time operations.
Typedef Documentation
typedef boost::posix_time::time_duration hpp::fcl::time::duration
Representation of a time duration.
typedef boost::posix_time::ptime hpp::fcl::time::point
Representation of a point in time.
Function Documentation
point hpp::fcl::time::now (void) inline
Get the current time point.
Referenced by hpp::fcl::tools::Profiler::Running().
duration hpp::fcl::time::seconds (double sec) inline
Return the time duration representing a given number of seconds.
References seconds().
double hpp::fcl::time::seconds (const duration & d) inline
Return the number of seconds that a time duration represents.
Referenced by seconds().