hpp::fcl::ShapeMeshDistanceTraversalNodeRSS< S, NarrowPhaseSolver > Class Template Reference
hpp::fcl::ShapeMeshDistanceTraversalNodeRSS< S, NarrowPhaseSolver > Class Template Reference
#include <hpp/fcl/traversal/traversal_node_bvh_shape.h>
Public Member Functions
ShapeMeshDistanceTraversalNodeRSS ()
void preprocess ()
void postprocess ()
FCL_REAL BVTesting (int b1, int b2) const
BV test between b1 and b2.
void leafTesting (int b1, int b2) const
Leaf test between node b1 and b2, if they are both leafs.
Public Member Functions inherited from hpp::fcl::ShapeMeshDistanceTraversalNode< S, RSS, NarrowPhaseSolver >
ShapeMeshDistanceTraversalNode ()
void leafTesting (int b1, int b2) const
Distance testing between leaves (one shape and one triangle)
bool canStop (FCL_REAL c) const
Whether the traversal process can stop early.
Public Member Functions inherited from hpp::fcl::ShapeBVHDistanceTraversalNode< S, RSS >
ShapeBVHDistanceTraversalNode ()
bool isSecondNodeLeaf (int b) const
Whether the BV node in the second BVH tree is leaf.
int getSecondLeftChild (int b) const
Obtain the left child of BV node in the second BVH.
int getSecondRightChild (int b) const
Obtain the right child of BV node in the second BVH.
FCL_REAL BVTesting (int b1, int b2) const
BV culling test in one BVTT node.
Public Member Functions inherited from hpp::fcl::DistanceTraversalNodeBase
DistanceTraversalNodeBase ()
virtual ~DistanceTraversalNodeBase ()
void enableStatistics (bool enable)
Whether store some statistics information during traversal.
Public Member Functions inherited from hpp::fcl::TraversalNodeBase
virtual ~TraversalNodeBase ()
virtual bool isFirstNodeLeaf (int b) const
Whether b is a leaf node in the first BVH tree.
virtual bool firstOverSecond (int b1, int b2) const
Traverse the subtree of the node in the first tree first.
virtual int getFirstLeftChild (int b) const
Get the left child of the node b in the first tree.
virtual int getFirstRightChild (int b) const
Get the right child of the node b in the first tree.
Additional Inherited Members
Public Attributes inherited from hpp::fcl::ShapeMeshDistanceTraversalNode< S, RSS, NarrowPhaseSolver >
Vec3f * vertices
Triangle * tri_indices
FCL_REAL rel_err
FCL_REAL abs_err
const NarrowPhaseSolver * nsolver
Public Attributes inherited from hpp::fcl::ShapeBVHDistanceTraversalNode< S, RSS >
const S * model1
const BVHModel< RSS > * model2
RSS model1_bv
int num_bv_tests
int num_leaf_tests
FCL_REAL query_time_seconds
Public Attributes inherited from hpp::fcl::DistanceTraversalNodeBase
DistanceRequest request
request setting for distance
DistanceResult * result
distance result kept during the traversal iteration
bool enable_statistics
Whether stores statistics.
Public Attributes inherited from hpp::fcl::TraversalNodeBase
Transform3f tf1
configuation of first object
Transform3f tf2
configuration of second object
Constructor & Destructor Documentation
template<typename S, typename NarrowPhaseSolver> hpp::fcl::ShapeMeshDistanceTraversalNodeRSS< S, NarrowPhaseSolver >::ShapeMeshDistanceTraversalNodeRSS () inline
Member Function Documentation
template<typename S, typename NarrowPhaseSolver> FCL_REAL hpp::fcl::ShapeMeshDistanceTraversalNodeRSS< S, NarrowPhaseSolver >::BVTesting (int b1, int b2) const inline virtual
BV test between b1 and b2.
Returns
a lower bound of the distance between the two BV.
Note
except for OBB, this method returns the distance.
Reimplemented from hpp::fcl::DistanceTraversalNodeBase.
References hpp::fcl::distance(), hpp::fcl::CollisionTraversalNodeBase::enable_statistics, hpp::fcl::Transform3f::getRotation(), hpp::fcl::Transform3f::getTranslation(), hpp::fcl::BVHShapeCollisionTraversalNode< BV, S >::model2, hpp::fcl::BVHShapeCollisionTraversalNode< BV, S >::num_bv_tests, and hpp::fcl::TraversalNodeBase::tf2.
template<typename S, typename NarrowPhaseSolver> void hpp::fcl::ShapeMeshDistanceTraversalNodeRSS< S, NarrowPhaseSolver >::leafTesting (int b1, int b2) const inline virtual
Leaf test between node b1 and b2, if they are both leafs.
Implements hpp::fcl::DistanceTraversalNodeBase.
References hpp::fcl::CollisionTraversalNodeBase::enable_statistics, hpp::fcl::BVHShapeCollisionTraversalNode< BV, S >::model1, hpp::fcl::BVHShapeCollisionTraversalNode< BV, S >::model2, hpp::fcl::BVHShapeCollisionTraversalNode< BV, S >::num_leaf_tests, hpp::fcl::CollisionTraversalNodeBase::request, hpp::fcl::CollisionTraversalNodeBase::result, hpp::fcl::TraversalNodeBase::tf1, and hpp::fcl::TraversalNodeBase::tf2.
template<typename S, typename NarrowPhaseSolver> void hpp::fcl::ShapeMeshDistanceTraversalNodeRSS< S, NarrowPhaseSolver >::postprocess () inline virtual
Reimplemented from hpp::fcl::TraversalNodeBase.
template<typename S, typename NarrowPhaseSolver> void hpp::fcl::ShapeMeshDistanceTraversalNodeRSS< S, NarrowPhaseSolver >::preprocess () inline virtual
Reimplemented from hpp::fcl::TraversalNodeBase.
References hpp::fcl::BVHShapeCollisionTraversalNode< BV, S >::model1, hpp::fcl::BVHShapeCollisionTraversalNode< BV, S >::model2, hpp::fcl::CollisionTraversalNodeBase::request, hpp::fcl::CollisionTraversalNodeBase::result, hpp::fcl::TraversalNodeBase::tf1, and hpp::fcl::TraversalNodeBase::tf2.