hpp::fcl::Variance3f Class Reference
hpp::fcl::Variance3f Class Reference
Class for variance matrix in 3d.
#include <hpp/fcl/math/matrix_3f.h>
Public Member Functions
Variance3f ()
Variance3f (const Matrix3f &S)
void init ()
init the Variance
Variance3f & sqrt ()
Compute the sqrt of Sigma matrix based on the eigen decomposition result, this is useful when the uncertainty matrix is initialized as a square variation matrix.
Public Attributes
Matrix3f Sigma
Variation matrix.
Matrix3f::Scalar sigma [3]
Variations along the eign axes.
Vec3f axis [3]
Eigen axes of the variation matrix.
Detailed Description
Class for variance matrix in 3d.
Constructor & Destructor Documentation
hpp::fcl::Variance3f::Variance3f () inline
hpp::fcl::Variance3f::Variance3f (const Matrix3f & S) inline
References init().
Member Function Documentation
void hpp::fcl::Variance3f::init () inline
init the Variance
References hpp::fcl::eigen().
Referenced by Variance3f().
Variance3f& hpp::fcl::Variance3f::sqrt () inline
Compute the sqrt of Sigma matrix based on the eigen decomposition result, this is useful when the uncertainty matrix is initialized as a square variation matrix.
References Sigma.
Member Data Documentation
Vec3f hpp::fcl::Variance3f::axis[3]
Eigen axes of the variation matrix.
Referenced by hpp::fcl::BVHExpand().
Matrix3f hpp::fcl::Variance3f::Sigma
Variation matrix.
Referenced by sqrt().
Matrix3f::Scalar hpp::fcl::Variance3f::sigma[3]
Variations along the eign axes.
Referenced by hpp::fcl::BVHExpand().