hpp::fcl::Transform3f Class Reference
hpp::fcl::Transform3f Class Reference
Simple transform class used locally by InterpMotion.
#include <hpp/fcl/math/transform.h>
Public Member Functions
Transform3f ()
Default transform is no movement.
Transform3f (const Matrix3f &R_, const Vec3f &T_)
Construct transform from rotation and translation.
Transform3f (const Quaternion3f &q_, const Vec3f &T_)
Construct transform from rotation and translation.
Transform3f (const Matrix3f &R_)
Construct transform from rotation.
Transform3f (const Quaternion3f &q_)
Construct transform from rotation.
Transform3f (const Vec3f &T_)
Construct transform from translation.
Transform3f (const Transform3f &tf)
Construct transform from another transform.
Transform3f & operator= (const Transform3f &tf)
operator =
const Vec3f & getTranslation () const
get translation
const Matrix3f & getRotation () const
get rotation
const Quaternion3f & getQuatRotation () const
get quaternion
void setTransform (const Matrix3f &R_, const Vec3f &T_)
set transform from rotation and translation
void setTransform (const Quaternion3f &q_, const Vec3f &T_)
set transform from rotation and translation
template<typename Derived >
void setRotation (const Eigen::MatrixBase< Derived > &R_)
set transform from rotation
template<typename Derived >
void setTranslation (const Eigen::MatrixBase< Derived > &T_)
set transform from translation
void setQuatRotation (const Quaternion3f &q_)
set transform from rotation
template<typename Derived >
Vec3f transform (const Eigen::MatrixBase< Derived > &v) const
transform a given vector by the transform
Transform3f & inverse ()
inverse transform
Transform3f inverseTimes (const Transform3f &other) const
inverse the transform and multiply with another
const Transform3f & operator*= (const Transform3f &other)
multiply with another transform
Transform3f operator* (const Transform3f &other) const
multiply with another transform
bool isIdentity () const
check whether the transform is identity
void setIdentity ()
set the transform to be identity transform
bool operator== (const Transform3f &other) const
bool operator!= (const Transform3f &other) const
Detailed Description
Simple transform class used locally by InterpMotion.
Constructor & Destructor Documentation
hpp::fcl::Transform3f::Transform3f () inline
Default transform is no movement.
References setIdentity().
Referenced by inverseTimes(), and operator*().
hpp::fcl::Transform3f::Transform3f (const Matrix3f & R_, const Vec3f & T_) inline
Construct transform from rotation and translation.
hpp::fcl::Transform3f::Transform3f (const Quaternion3f & q_, const Vec3f & T_) inline
Construct transform from rotation and translation.
hpp::fcl::Transform3f::Transform3f (const Matrix3f & R_) inline
Construct transform from rotation.
hpp::fcl::Transform3f::Transform3f (const Quaternion3f & q_) inline
Construct transform from rotation.
hpp::fcl::Transform3f::Transform3f (const Vec3f & T_) inline
Construct transform from translation.
hpp::fcl::Transform3f::Transform3f (const Transform3f & tf) inline
Construct transform from another transform.
Member Function Documentation
const Quaternion3f& hpp::fcl::Transform3f::getQuatRotation () const inline
get quaternion
Referenced by operator==().
const Matrix3f& hpp::fcl::Transform3f::getRotation () const inline
get rotation
Referenced by hpp::fcl::details::boxBoxIntersect(), hpp::fcl::details::boxHalfspaceIntersect(), hpp::fcl::details::boxPlaneIntersect(), hpp::fcl::details::boxSphereDistance(), hpp::fcl::MeshShapeCollisionTraversalNode< kIOS, S, NarrowPhaseSolver, 0 >::BVTesting(), hpp::fcl::ShapeMeshCollisionTraversalNode< S, OBB, NarrowPhaseSolver, 0 >::BVTesting(), hpp::fcl::MeshShapeDistanceTraversalNodeRSS< S, NarrowPhaseSolver >::BVTesting(), hpp::fcl::MeshShapeDistanceTraversalNodekIOS< S, NarrowPhaseSolver >::BVTesting(), hpp::fcl::MeshShapeDistanceTraversalNodeOBBRSS< S, NarrowPhaseSolver >::BVTesting(), hpp::fcl::ShapeMeshDistanceTraversalNodeRSS< S, NarrowPhaseSolver >::BVTesting(), hpp::fcl::ShapeMeshDistanceTraversalNodekIOS< S, NarrowPhaseSolver >::BVTesting(), hpp::fcl::ShapeMeshDistanceTraversalNodeOBBRSS< S, NarrowPhaseSolver >::BVTesting(), hpp::fcl::details::capsuleHalfspaceIntersect(), hpp::fcl::details::capsulePlaneIntersect(), hpp::fcl::details::coneHalfspaceIntersect(), hpp::fcl::details::conePlaneIntersect(), hpp::fcl::details::cylinderHalfspaceIntersect(), hpp::fcl::details::cylinderPlaneIntersect(), hpp::fcl::details::setupShapeMeshDistanceOrientedNode(), hpp::fcl::GJKSolver_indep::shapeDistance(), hpp::fcl::GJKSolver_indep::shapeIntersect(), hpp::fcl::GJKSolver_indep::shapeTriangleInteraction(), and hpp::fcl::details::sphereCylinderDistance().
const Vec3f& hpp::fcl::Transform3f::getTranslation () const inline
get translation
Referenced by hpp::fcl::details::boxBoxIntersect(), hpp::fcl::details::boxHalfspaceIntersect(), hpp::fcl::details::boxPlaneIntersect(), hpp::fcl::details::boxSphereDistance(), hpp::fcl::MeshShapeCollisionTraversalNode< kIOS, S, NarrowPhaseSolver, 0 >::BVTesting(), hpp::fcl::ShapeMeshCollisionTraversalNode< S, OBB, NarrowPhaseSolver, 0 >::BVTesting(), hpp::fcl::MeshShapeDistanceTraversalNodeRSS< S, NarrowPhaseSolver >::BVTesting(), hpp::fcl::MeshShapeDistanceTraversalNodekIOS< S, NarrowPhaseSolver >::BVTesting(), hpp::fcl::MeshShapeDistanceTraversalNodeOBBRSS< S, NarrowPhaseSolver >::BVTesting(), hpp::fcl::ShapeMeshDistanceTraversalNodeRSS< S, NarrowPhaseSolver >::BVTesting(), hpp::fcl::ShapeMeshDistanceTraversalNodekIOS< S, NarrowPhaseSolver >::BVTesting(), hpp::fcl::ShapeMeshDistanceTraversalNodeOBBRSS< S, NarrowPhaseSolver >::BVTesting(), hpp::fcl::details::capsuleHalfspaceIntersect(), hpp::fcl::details::capsulePlaneIntersect(), hpp::fcl::details::coneHalfspaceIntersect(), hpp::fcl::details::conePlaneIntersect(), hpp::fcl::details::cylinderHalfspaceIntersect(), hpp::fcl::details::cylinderPlaneIntersect(), operator==(), hpp::fcl::details::setupShapeMeshDistanceOrientedNode(), hpp::fcl::details::sphereCapsuleDistance(), hpp::fcl::details::sphereCapsuleIntersect(), hpp::fcl::details::sphereCylinderDistance(), hpp::fcl::details::sphereHalfspaceIntersect(), hpp::fcl::details::spherePlaneIntersect(), hpp::fcl::details::sphereSphereDistance(), hpp::fcl::details::sphereSphereIntersect(), hpp::fcl::details::sphereTriangleDistance(), and hpp::fcl::details::sphereTriangleIntersect().
Transform3f& hpp::fcl::Transform3f::inverse () inline
inverse transform
Referenced by operator!=(), hpp::fcl::details::sphereCapsuleDistance(), and hpp::fcl::details::sphereCapsuleIntersect().
Transform3f hpp::fcl::Transform3f::inverseTimes (const Transform3f & other) const inline
inverse the transform and multiply with another
References Transform3f().
Referenced by hpp::fcl::GJKSolver_indep::shapeDistance(), hpp::fcl::GJKSolver_indep::shapeIntersect(), and hpp::fcl::GJKSolver_indep::shapeTriangleInteraction().
bool hpp::fcl::Transform3f::isIdentity () const inline
check whether the transform is identity
References hpp::fcl::isQuatIdentity().
Referenced by hpp::fcl::initialize().
bool hpp::fcl::Transform3f::operator!= (const Transform3f & other) const inline
References inverse(), hpp::fcl::relativeTransform(), and hpp::fcl::relativeTransform2().
Transform3f hpp::fcl::Transform3f::operator* (const Transform3f & other) const inline
multiply with another transform
References Transform3f().
const Transform3f& hpp::fcl::Transform3f::operator*= (const Transform3f & other) inline
multiply with another transform
Transform3f& hpp::fcl::Transform3f::operator= (const Transform3f & tf) inline
operator =
bool hpp::fcl::Transform3f::operator== (const Transform3f & other) const inline
References hpp::fcl::areQuatEquals(), getQuatRotation(), and getTranslation().
void hpp::fcl::Transform3f::setIdentity () inline
set the transform to be identity transform
Referenced by hpp::fcl::initialize(), and Transform3f().
void hpp::fcl::Transform3f::setQuatRotation (const Quaternion3f & q_) inline
set transform from rotation
template<typename Derived > void hpp::fcl::Transform3f::setRotation (const Eigen::MatrixBase< Derived > & R_) inline
set transform from rotation
void hpp::fcl::Transform3f::setTransform (const Matrix3f & R_, const Vec3f & T_) inline
set transform from rotation and translation
void hpp::fcl::Transform3f::setTransform (const Quaternion3f & q_, const Vec3f & T_) inline
set transform from rotation and translation
template<typename Derived > void hpp::fcl::Transform3f::setTranslation (const Eigen::MatrixBase< Derived > & T_) inline
set transform from translation
template<typename Derived > Vec3f hpp::fcl::Transform3f::transform (const Eigen::MatrixBase< Derived > & v) const inline
transform a given vector by the transform
Referenced by hpp::fcl::details::computePenetration(), hpp::fcl::details::convexHalfspaceIntersect(), hpp::fcl::details::convexPlaneIntersect(), hpp::fcl::generateBVHModel(), hpp::fcl::details::halfspaceTriangleIntersect(), hpp::fcl::initialize(), hpp::fcl::details::planeTriangleIntersect(), hpp::fcl::GJKSolver_indep::shapeDistance(), hpp::fcl::GJKSolver_indep::shapeIntersect(), hpp::fcl::OcTreeSolver< NarrowPhaseSolver >::ShapeOcTreeDistance(), hpp::fcl::GJKSolver_indep::shapeTriangleInteraction(), hpp::fcl::details::sphereCapsuleDistance(), hpp::fcl::details::sphereCapsuleIntersect(), hpp::fcl::details::sphereCylinderDistance(), hpp::fcl::details::sphereTriangleDistance(), and hpp::fcl::details::MinkowskiDiff::support1().