# Python stubs generated by omniidl from /local/devel/hpp/src/hpp-corbaserver/idl/hpp/core_idl/path_validations.idl

import omniORB, _omnipy
from omniORB import CORBA, PortableServer
_0_CORBA = CORBA

_omnipy.checkVersion(3,0, __file__)

# #include "hpp/common.idl"
import hpp_stubs.common_idl
_0_hpp = omniORB.openModule("hpp_stubs.hpp")
_0_hpp__POA = omniORB.openModule("hpp_stubs.hpp__POA")
# #include "hpp/core_idl/paths.idl"
import hpp_stubs.core.paths_idl
_0_hpp = omniORB.openModule("hpp_idl.hpp")
_0_hpp__POA = omniORB.openModule("hpp_idl.hpp__POA")
_0_hpp.core_idl = omniORB.openModule("hpp_idl.hpp.core_idl")
_0_hpp__POA.core_idl = omniORB.openModule("hpp_idl.hpp__POA.core_idl")

#
# Start of module "hpp"
#
__name__ = "hpp_idl.hpp"
_0_hpp = omniORB.openModule("hpp_idl.hpp", r"/local/devel/hpp/src/hpp-corbaserver/idl/hpp/core_idl/path_validations.idl")
_0_hpp__POA = omniORB.openModule("hpp_idl.hpp__POA", r"/local/devel/hpp/src/hpp-corbaserver/idl/hpp/core_idl/path_validations.idl")


#
# Start of module "hpp.core_idl"
#
__name__ = "hpp_idl.hpp.core_idl"
_0_hpp.core_idl = omniORB.openModule("hpp_idl.hpp.core_idl", r"/local/devel/hpp/src/hpp-corbaserver/idl/hpp/core_idl/path_validations.idl")
_0_hpp__POA.core_idl = omniORB.openModule("hpp_idl.hpp__POA.core_idl", r"/local/devel/hpp/src/hpp-corbaserver/idl/hpp/core_idl/path_validations.idl")


# typedef ... PathValidationReport
class PathValidationReport:
    _NP_RepositoryId = "IDL:hpp/core_idl/PathValidationReport:1.0"
    def __init__(self, *args, **kw):
        raise RuntimeError("Cannot construct objects of this type.")
_0_hpp.core_idl.PathValidationReport = PathValidationReport
_0_hpp.core_idl._d_PathValidationReport  = (omniORB.tcInternal.tv_string,0)
_0_hpp.core_idl._ad_PathValidationReport = (omniORB.tcInternal.tv_alias, PathValidationReport._NP_RepositoryId, "PathValidationReport", (omniORB.tcInternal.tv_string,0))
_0_hpp.core_idl._tc_PathValidationReport = omniORB.tcInternal.createTypeCode(_0_hpp.core_idl._ad_PathValidationReport)
omniORB.registerType(PathValidationReport._NP_RepositoryId, _0_hpp.core_idl._ad_PathValidationReport, _0_hpp.core_idl._tc_PathValidationReport)
del PathValidationReport

# interface PathValidation
_0_hpp.core_idl._d_PathValidation = (omniORB.tcInternal.tv_objref, "IDL:hpp/core_idl/PathValidation:1.0", "PathValidation")
omniORB.typeMapping["IDL:hpp/core_idl/PathValidation:1.0"] = _0_hpp.core_idl._d_PathValidation
_0_hpp.core_idl.PathValidation = omniORB.newEmptyClass()
class PathValidation :
    _NP_RepositoryId = _0_hpp.core_idl._d_PathValidation[1]

    def __init__(self, *args, **kw):
        raise RuntimeError("Cannot construct objects of this type.")

    _nil = CORBA.Object._nil


_0_hpp.core_idl.PathValidation = PathValidation
_0_hpp.core_idl._tc_PathValidation = omniORB.tcInternal.createTypeCode(_0_hpp.core_idl._d_PathValidation)
omniORB.registerType(PathValidation._NP_RepositoryId, _0_hpp.core_idl._d_PathValidation, _0_hpp.core_idl._tc_PathValidation)

# PathValidation operations and attributes
PathValidation._d_validate = ((omniORB.typeMapping["IDL:hpp/core_idl/Path:1.0"], omniORB.tcInternal.tv_boolean), (omniORB.tcInternal.tv_boolean, omniORB.typeMapping["IDL:hpp/core_idl/Path:1.0"], omniORB.typeMapping["IDL:hpp/core_idl/PathValidationReport:1.0"]), {_0_hpp.Error._NP_RepositoryId: _0_hpp._d_Error})

# PathValidation object reference
class _objref_PathValidation (CORBA.Object):
    _NP_RepositoryId = PathValidation._NP_RepositoryId

    def __init__(self):
        CORBA.Object.__init__(self)

    def validate(self, *args):
        return _omnipy.invoke(self, "validate", _0_hpp.core_idl.PathValidation._d_validate, args)

    __methods__ = ["validate"] + CORBA.Object.__methods__

omniORB.registerObjref(PathValidation._NP_RepositoryId, _objref_PathValidation)
_0_hpp.core_idl._objref_PathValidation = _objref_PathValidation
del PathValidation, _objref_PathValidation

# PathValidation skeleton
__name__ = "hpp_idl.hpp__POA.core_idl"
class PathValidation (PortableServer.Servant):
    _NP_RepositoryId = _0_hpp.core_idl.PathValidation._NP_RepositoryId


    _omni_op_d = {"validate": _0_hpp.core_idl.PathValidation._d_validate}

PathValidation._omni_skeleton = PathValidation
_0_hpp__POA.core_idl.PathValidation = PathValidation
omniORB.registerSkeleton(PathValidation._NP_RepositoryId, PathValidation)
del PathValidation
__name__ = "hpp_idl.hpp.core_idl"

#
# End of module "hpp.core_idl"
#
__name__ = "hpp_idl.hpp"


#
# End of module "hpp"
#
__name__ = "hpp_stubs.core.path_validations_idl"

_exported_modules = ( "hpp_idl.hpp", "hpp_idl.hpp.core_idl")

# The end.
