# DO NOT EDIT THIS FILE!
#
# Python module hpp.corbaserver.manipulation generated by omniidl

import omniORB
omniORB.updateModule("hpp_idl.hpp.corbaserver.manipulation")

# ** 1. Stub files contributing to this module
import hpp_stubs.corbaserver.manipulation.graph_idl
import hpp_stubs.corbaserver.manipulation.problem_idl
import hpp_stubs.corbaserver.manipulation.robot_idl

# ** 2. Sub-modules

# ** 3. End
