# DO NOT EDIT THIS FILE!
#
# Python module hpp.corbaserver generated by omniidl

import omniORB
omniORB.updateModule("hpp_idl.hpp.corbaserver")

# ** 1. Stub files contributing to this module
import hpp_stubs.corbaserver.obstacle_idl
import hpp_stubs.corbaserver.problem_idl
import hpp_stubs.corbaserver.robot_idl

# ** 2. Sub-modules

# ** 3. End
