# DO NOT EDIT THIS FILE!
#
# Python module hpp.constraints_idl generated by omniidl

import omniORB
omniORB.updateModule("hpp_idl.hpp.constraints_idl")

# ** 1. Stub files contributing to this module
import hpp_stubs.core._constraints_idl
import hpp_stubs.constraints.constraints_idl

# ** 2. Sub-modules

# ** 3. End
