hpp::pinocchio::Gripper Class Reference
hpp::pinocchio::Gripper Class Reference
Definition of a robot gripper.
#include <hpp/pinocchio/gripper.hh>
Public Member Functions
const JointPtr_t & joint () const
Get joint to which the gripper is attached.
const FrameIndex & frameId () const
Get the frame Id of the gripper in the vector of frame of the Model.
const Transform3f & objectPositionInJoint () const
Get handle position in the the Grippering joint.
const std::string & name () const
get name
value_type clearance () const
Get the clearance.
void clearance (const value_type &clearance)
Set the clearance.
GripperPtr_t clone () const
std::ostream & print (std::ostream &os) const
Static Public Member Functions
static GripperPtr_t create (const std::string &name, const DeviceWkPtr_t &device)
Return a shared pointer to new instance.
static GripperPtr_t createCopy (const GripperPtr_t &gripper, const DeviceWkPtr_t &otherDevice)
Protected Member Functions
Gripper (const std::string &name, const DeviceWkPtr_t &device)
Constructor.
void init (GripperWkPtr_t weakPtr)
Detailed Description
Definition of a robot gripper.
This class represent a robot gripper as a frame attached to the joint of the robot that holds the gripper.
To graps a box-shaped object with small lengths along x and y, the gripper frame should coincide with the object frame.
Constructor & Destructor Documentation
hpp::pinocchio::Gripper::Gripper (const std::string & name, const DeviceWkPtr_t & device) protected
Constructor.
Parameters
name of the gripper in the device,
device
Todo:
device should be of type DeviceConstPtr_t but the constructor of JointPtr_t needs a DevicePtr_t.
Member Function Documentation
value_type hpp::pinocchio::Gripper::clearance () const inline
Get the clearance.
The clearance is a distance, from the center of the gripper and along the x-aixs, that "ensures" an object being at that distance is not colliding with this gripper. It also gives an order of magnitude of the size of the gripper.
Referenced by createCopy().
void hpp::pinocchio::Gripper::clearance (const value_type & clearance) inline
Set the clearance.
See also
clearance()
GripperPtr_t hpp::pinocchio::Gripper::clone () const
static GripperPtr_t hpp::pinocchio::Gripper::create (const std::string & name, const DeviceWkPtr_t & device) inline static
Return a shared pointer to new instance.
Parameters
name of the gripper in the device,
device
References init().
static GripperPtr_t hpp::pinocchio::Gripper::createCopy (const GripperPtr_t & gripper, const DeviceWkPtr_t & otherDevice) inline static
References clearance(), and init().
const FrameIndex& hpp::pinocchio::Gripper::frameId () const inline
Get the frame Id of the gripper in the vector of frame of the Model.
void hpp::pinocchio::Gripper::init (GripperWkPtr_t weakPtr) inline protected
Referenced by create(), and createCopy().
const JointPtr_t& hpp::pinocchio::Gripper::joint () const inline
Get joint to which the gripper is attached.
const std::string& hpp::pinocchio::Gripper::name () const inline
get name
const Transform3f& hpp::pinocchio::Gripper::objectPositionInJoint () const
Get handle position in the the Grippering joint.
std::ostream& hpp::pinocchio::Gripper::print (std::ostream & os) const
Referenced by hpp::pinocchio::operator<<().