hpp::pinocchio::LiegroupSpace Class Reference
hpp::pinocchio::LiegroupSpace Class Reference
Lie group
Cartesian product of elementary Lie groups.
#include <hpp/pinocchio/liegroup-space.hh>
Public Member Functions
size_type nq () const
Dimension of the vector representation.
size_type nv () const
Dimension of the Lie group tangent space.
size_type nq (const std::size_t &rank) const
Dimension of elementary Liegroup at given rank.
size_type nv (const std::size_t &rank) const
Dimension of elementary Liegroup tangent space at given rank.
const std::vector< LiegroupType > & liegroupTypes () const
Get reference to vector of elementary types.
LiegroupElement neutral () const
Return the neutral element as a vector.
LiegroupElement element (vectorIn_t q) const
Create a LiegroupElement from a configuration.
LiegroupElementRef elementRef (vectorOut_t q) const
Create a LiegroupElementRef from a configuration.
LiegroupElementConstRef elementConstRef (vectorIn_t q) const
Create a LiegroupElementRef from a configuration.
LiegroupElement exp (vectorIn_t v) const
Return exponential of a tangent vector.
template<DerivativeProduct side>
void dIntegrate_dq (LiegroupElementConstRef q, vectorIn_t v, matrixOut_t Jq) const
Compute the Jacobian of the integration operation with respect to q.
template<DerivativeProduct side>
void dIntegrate_dv (LiegroupElementConstRef q, vectorIn_t v, matrixOut_t Jv) const
Compute the Jacobian of the integration operation with respect to v.
template<bool ApplyOnTheLeft>
void Jdifference (vectorIn_t q0, vectorIn_t q1, matrixOut_t J0, matrixOut_t J1) const
template<DerivativeProduct side>
void dDifference_dq0 (vectorIn_t q0, vectorIn_t q1, matrixOut_t J0) const
Compute the Jacobian matrices of the difference operation.
template<DerivativeProduct side>
void dDifference_dq1 (vectorIn_t q0, vectorIn_t q1, matrixOut_t J1) const
Compute the Jacobian matrices of the difference operation.
std::string name () const
Return name of Lie group.
void mergeVectorSpaces ()
LiegroupSpacePtr_t vectorSpacesMerged () const
bool isVectorSpace () const
bool operator== (const LiegroupSpace &other) const
bool operator!= (const LiegroupSpace &other) const
LiegroupSpacePtr_t operator*= (const LiegroupSpaceConstPtr_t &other)
Static Public Member Functions
static LiegroupSpacePtr_t create (const size_type &size)
Create instance of vector space of given size.
static LiegroupSpacePtr_t createCopy (const LiegroupSpaceConstPtr_t &other)
Create copy.
static LiegroupSpacePtr_t create (const LiegroupType &type)
Create instance with one Elementary Lie group.
Elementary Lie groups
static LiegroupSpacePtr_t Rn (const size_type &n)
Return as a Lie group.
static LiegroupSpacePtr_t R1 ()
Return as a Lie group.
static LiegroupSpacePtr_t R2 ()
Return as a Lie group.
static LiegroupSpacePtr_t R3 ()
Return as a Lie group.
static LiegroupSpacePtr_t SE2 ()
Return .
static LiegroupSpacePtr_t SE3 ()
Return .
static LiegroupSpacePtr_t SO2 ()
Return .
static LiegroupSpacePtr_t SO3 ()
Return .
static LiegroupSpacePtr_t R2xSO2 ()
Return .
static LiegroupSpacePtr_t R3xSO3 ()
Return .
static LiegroupSpacePtr_t empty ()
Return empty Lie group.
Protected Member Functions
LiegroupSpace (const size_type &size)
Constructor of vector space of given size.
LiegroupSpace (const LiegroupSpace &other)
LiegroupSpace (const LiegroupType &type)
Detailed Description
Cartesian product of elementary Lie groups.
Some values produced and manipulated by functions belong to Lie groups For instance rotations, rigid-body motions are element of Lie groups.
Elements of Lie groups are usually applied common operations, like
integrating a velocity from a given element during unit time,
computing the constant velocity that moves from one element to another one in unit time.
By analogy with vector spaces that are a particular type of Lie group, the above operations are implemented as operators + and - respectively acting on LiegroupElement instances.
This class represents a Lie group as the cartesian product of elementaty Lie groups. Those elementary Lie groups are gathered in a variant called LiegroupType.
Elements of a Lie group are represented by class LiegroupElement.
Constructor & Destructor Documentation
hpp::pinocchio::LiegroupSpace::LiegroupSpace (const size_type & size) protected
Constructor of vector space of given size.
hpp::pinocchio::LiegroupSpace::LiegroupSpace (const LiegroupSpace & other) protected
hpp::pinocchio::LiegroupSpace::LiegroupSpace (const LiegroupType & type) protected
Member Function Documentation
static LiegroupSpacePtr_t hpp::pinocchio::LiegroupSpace::create (const size_type & size) inline static
Create instance of vector space of given size.
References createCopy().
static LiegroupSpacePtr_t hpp::pinocchio::LiegroupSpace::create (const LiegroupType & type) inline static
Create instance with one Elementary Lie group.
static LiegroupSpacePtr_t hpp::pinocchio::LiegroupSpace::createCopy (const LiegroupSpaceConstPtr_t & other) inline static
Create copy.
Referenced by create().
template<DerivativeProduct side> void hpp::pinocchio::LiegroupSpace::dDifference_dq0 (vectorIn_t q0, vectorIn_t q1, matrixOut_t J0) const
Compute the Jacobian matrices of the difference operation.
Given ,
Compute matrices and such that
Parameters
[in] q0,q1 Lie group elements,
[out] J0 the Jacobian of v with respect to q0.
Referenced by liegroupTypes().
template<DerivativeProduct side> void hpp::pinocchio::LiegroupSpace::dDifference_dq1 (vectorIn_t q0, vectorIn_t q1, matrixOut_t J1) const
Compute the Jacobian matrices of the difference operation.
Given ,
Compute matrices and such that
Parameters
[in] q0,q1 Lie group elements,
[out] J1 the Jacobian of v with respect to q1.
Referenced by liegroupTypes().
template<DerivativeProduct side> void hpp::pinocchio::LiegroupSpace::dIntegrate_dq (LiegroupElementConstRef q, vectorIn_t v, matrixOut_t Jq) const
Compute the Jacobian of the integration operation with respect to q.
Given , compute such that
for constant
Parameters
q the configuration,
v the velocity vector,
Return values
Jq the Jacobian (initialized as identity)
Note
For each elementary Lie group in q.space (), ranging over indices , the Jacobian is computed by method pinocchio::LieGroupBase::dIntegrate_dq. lines of Jq are then left multiplied by .
Referenced by liegroupTypes().
template<DerivativeProduct side> void hpp::pinocchio::LiegroupSpace::dIntegrate_dv (LiegroupElementConstRef q, vectorIn_t v, matrixOut_t Jv) const
Compute the Jacobian of the integration operation with respect to v.
Given , compute such that
for constant
Parameters
q the configuration,
v the velocity vector,
Return values
Jv the Jacobian (initialized to identity)
Note
For each elementary Lie group in q.space (), ranging over indices , the Jacobian is computed by method pinocchio::LieGroupBase::dIntegrate_dq. lines of Jv are then left multiplied by .
Referenced by liegroupTypes().
LiegroupElement hpp::pinocchio::LiegroupSpace::element (vectorIn_t q) const
Create a LiegroupElement from a configuration.
Referenced by liegroupTypes().
LiegroupElementConstRef hpp::pinocchio::LiegroupSpace::elementConstRef (vectorIn_t q) const
Create a LiegroupElementRef from a configuration.
Referenced by liegroupTypes().
LiegroupElementRef hpp::pinocchio::LiegroupSpace::elementRef (vectorOut_t q) const
Create a LiegroupElementRef from a configuration.
Referenced by liegroupTypes().
static LiegroupSpacePtr_t hpp::pinocchio::LiegroupSpace::empty () static
Return empty Lie group.
LiegroupElement hpp::pinocchio::LiegroupSpace::exp (vectorIn_t v) const
Return exponential of a tangent vector.
Referenced by liegroupTypes().
bool hpp::pinocchio::LiegroupSpace::isVectorSpace () const
Referenced by liegroupTypes().
template<bool ApplyOnTheLeft> void hpp::pinocchio::LiegroupSpace::Jdifference (vectorIn_t q0, vectorIn_t q1, matrixOut_t J0, matrixOut_t J1) const
Deprecated:
Use dDifference_dq0 and dDifference_dq1
Referenced by liegroupTypes().
const std::vector<LiegroupType>& hpp::pinocchio::LiegroupSpace::liegroupTypes () const inline
Get reference to vector of elementary types.
References dDifference_dq0(), dDifference_dq1(), dIntegrate_dq(), dIntegrate_dv(), element(), elementConstRef(), elementRef(), exp(), isVectorSpace(), Jdifference(), mergeVectorSpaces(), name(), neutral(), operator!=(), operator*=(), operator==(), and vectorSpacesMerged().
void hpp::pinocchio::LiegroupSpace::mergeVectorSpaces ()
Referenced by liegroupTypes().
std::string hpp::pinocchio::LiegroupSpace::name () const
Return name of Lie group.
Referenced by liegroupTypes(), and hpp::pinocchio::operator<<().
LiegroupElement hpp::pinocchio::LiegroupSpace::neutral () const
Return the neutral element as a vector.
Referenced by liegroupTypes().
size_type hpp::pinocchio::LiegroupSpace::nq () const inline
Dimension of the vector representation.
Referenced by nv().
size_type hpp::pinocchio::LiegroupSpace::nq (const std::size_t & rank) const
Dimension of elementary Liegroup at given rank.
size_type hpp::pinocchio::LiegroupSpace::nv () const inline
Dimension of the Lie group tangent space.
References nq().
size_type hpp::pinocchio::LiegroupSpace::nv (const std::size_t & rank) const
Dimension of elementary Liegroup tangent space at given rank.
bool hpp::pinocchio::LiegroupSpace::operator!= (const LiegroupSpace & other) const
Referenced by liegroupTypes().
LiegroupSpacePtr_t hpp::pinocchio::LiegroupSpace::operator*= (const LiegroupSpaceConstPtr_t & other)
Referenced by liegroupTypes().
bool hpp::pinocchio::LiegroupSpace::operator== (const LiegroupSpace & other) const
Referenced by liegroupTypes().
static LiegroupSpacePtr_t hpp::pinocchio::LiegroupSpace::R1 () static
Return as a Lie group.
static LiegroupSpacePtr_t hpp::pinocchio::LiegroupSpace::R2 () static
Return as a Lie group.
static LiegroupSpacePtr_t hpp::pinocchio::LiegroupSpace::R2xSO2 () static
Return .
static LiegroupSpacePtr_t hpp::pinocchio::LiegroupSpace::R3 () static
Return as a Lie group.
static LiegroupSpacePtr_t hpp::pinocchio::LiegroupSpace::R3xSO3 () static
Return .
static LiegroupSpacePtr_t hpp::pinocchio::LiegroupSpace::Rn (const size_type & n) static
Return as a Lie group.
Parameters
n dimension of vector space
static LiegroupSpacePtr_t hpp::pinocchio::LiegroupSpace::SE2 () static
Return .
static LiegroupSpacePtr_t hpp::pinocchio::LiegroupSpace::SE3 () static
Return .
static LiegroupSpacePtr_t hpp::pinocchio::LiegroupSpace::SO2 () static
Return .
static LiegroupSpacePtr_t hpp::pinocchio::LiegroupSpace::SO3 () static
Return .
LiegroupSpacePtr_t hpp::pinocchio::LiegroupSpace::vectorSpacesMerged () const
Referenced by liegroupTypes().