hpp::pinocchio::LiegroupElementBase< vector_type > Class Template Reference
hpp::pinocchio::LiegroupElementBase< vector_type > Class Template Reference
Lie group
Writable element of a Lie group.
#include <hpp/pinocchio/liegroup-element.hh>
Public Types
typedef LiegroupElementConstBase< vector_type > Base
Public Member Functions
LiegroupElementBase (const vector_type &value, const LiegroupSpacePtr_t &space)
Constructor.
LiegroupElementBase (const LiegroupSpacePtr_t &space)
Constructor.
LiegroupElementBase (const vector_type &value)
Constructor.
template<typename vector_type2 >
LiegroupElementBase (const LiegroupElementConstBase< vector_type2 > &other)
Copy constructor.
template<typename vector_type2 >
LiegroupElementBase (const LiegroupElementBase< vector_type2 > &other)
Copy constructor.
template<typename vector_type2 >
LiegroupElementBase (LiegroupElementBase< vector_type2 > &other)
Casting operator from LiegroupElement to LiegroupElementRef
LiegroupElementBase ()
Constructor of trivial element.
const vector_type & vector () const
Const vector representation.
vector_type & vector ()
Modifiable vector representation.
void setNeutral ()
Set element to neutral element.
LiegroupElementBase & operator+= (vectorIn_t v)
Inplace integration of a velocity vector.
template<typename vector_type2 >
LiegroupElementBase & operator= (const LiegroupElementConstBase< vector_type2 > &other)
Assignment from another LiegroupElement.
template<typename Vector >
LiegroupElementBase & operator= (const Eigen::MatrixBase< Vector > &v)
Assignment from a vector.
Public Member Functions inherited from hpp::pinocchio::LiegroupElementConstBase< vector_type >
template<typename Derived >
LiegroupElementConstBase (const Eigen::EigenBase< Derived > &value, const LiegroupSpacePtr_t &liegroupSpace)
Constructor.
template<typename Derived >
LiegroupElementConstBase (const Eigen::EigenBase< Derived > &value)
Constructor.
template<typename vector_type2 >
LiegroupElementConstBase (const LiegroupElementConstBase< vector_type2 > &other)
Constructor to allow casting LiegroupElement and LiegroupElementRef into a LiegroupElementConstRef.
const LiegroupSpacePtr_t & space () const
get reference to vector of Lie groups
const vector_type & vector () const
Const vector representation.
size_type size () const
Size of the vector representation.
void check () const
Check that size of vector fits size of space.
Additional Inherited Members
Protected Member Functions inherited from hpp::pinocchio::LiegroupElementConstBase< vector_type >
template<typename Derived >
LiegroupElementConstBase (const Eigen::EigenBase< Derived > &value, const LiegroupSpacePtr_t &space, void *)
Protected Attributes inherited from hpp::pinocchio::LiegroupElementConstBase< vector_type >
vector_type value_
LiegroupSpacePtr_t space_
Detailed Description
template<typename vector_type>
class hpp::pinocchio::LiegroupElementBase< vector_type >
Writable element of a Lie group.
See also
LiegroupSpace, LiegroupElement, LiegroupElementRef
Member Typedef Documentation
template<typename vector_type> typedef LiegroupElementConstBase<vector_type> hpp::pinocchio::LiegroupElementBase< vector_type >::Base
Constructor & Destructor Documentation
template<typename vector_type> hpp::pinocchio::LiegroupElementBase< vector_type >::LiegroupElementBase (const vector_type & value, const LiegroupSpacePtr_t & space) inline
Constructor.
Parameters
value vector representation,
space space the element belongs to.
template<typename vector_type> hpp::pinocchio::LiegroupElementBase< vector_type >::LiegroupElementBase (const LiegroupSpacePtr_t & space) inline
Constructor.
Parameters
space space the element belongs to.
template<typename vector_type> hpp::pinocchio::LiegroupElementBase< vector_type >::LiegroupElementBase (const vector_type & value) inline explicit
Constructor.
Parameters
value vector representation,
By default the space containing the value is a vector space.
References create().
template<typename vector_type> template<typename vector_type2 > hpp::pinocchio::LiegroupElementBase< vector_type >::LiegroupElementBase (const LiegroupElementConstBase< vector_type2 > & other) inline
Copy constructor.
Handles the following case:
LiegroupElement <- LiegroupElementConstRef
template<typename vector_type> template<typename vector_type2 > hpp::pinocchio::LiegroupElementBase< vector_type >::LiegroupElementBase (const LiegroupElementBase< vector_type2 > & other) inline
Copy constructor.
Handles the following cases:
LiegroupElement <- LiegroupElement
LiegroupElementRef <- LiegroupElementRef
LiegroupElement <- LiegroupElementRef
template<typename vector_type> template<typename vector_type2 > hpp::pinocchio::LiegroupElementBase< vector_type >::LiegroupElementBase (LiegroupElementBase< vector_type2 > & other) inline
Casting operator from LiegroupElement to LiegroupElementRef
template<typename vector_type> hpp::pinocchio::LiegroupElementBase< vector_type >::LiegroupElementBase () inline
Constructor of trivial element.
Member Function Documentation
template<typename vector_type> LiegroupElementBase& hpp::pinocchio::LiegroupElementBase< vector_type >::operator+= (vectorIn_t v)
Inplace integration of a velocity vector.
template<typename vector_type> template<typename vector_type2 > LiegroupElementBase& hpp::pinocchio::LiegroupElementBase< vector_type >::operator= (const LiegroupElementConstBase< vector_type2 > & other) inline
Assignment from another LiegroupElement.
References hpp::pinocchio::LiegroupElementConstBase< vector_type >::space_, and hpp::pinocchio::LiegroupElementConstBase< vector_type >::value_.
template<typename vector_type> template<typename Vector > LiegroupElementBase& hpp::pinocchio::LiegroupElementBase< vector_type >::operator= (const Eigen::MatrixBase< Vector > & v) inline
Assignment from a vector.
References hpp::pinocchio::log(), hpp::pinocchio::operator+(), hpp::pinocchio::operator-(), hpp::pinocchio::LiegroupElementConstBase< vector_type >::space_, and hpp::pinocchio::LiegroupElementConstBase< vector_type >::value_.
template<typename vector_type> void hpp::pinocchio::LiegroupElementBase< vector_type >::setNeutral () inline
Set element to neutral element.
References hpp::pinocchio::LiegroupElementConstBase< vector_type >::space_, and hpp::pinocchio::LiegroupElementConstBase< vector_type >::value_.
template<typename vector_type> const vector_type& hpp::pinocchio::LiegroupElementBase< vector_type >::vector () const inline
Const vector representation.
template<typename vector_type> vector_type& hpp::pinocchio::LiegroupElementBase< vector_type >::vector () inline
Modifiable vector representation.
References hpp::pinocchio::LiegroupElementConstBase< vector_type >::value_.