hpp::pinocchio::Joint Class Reference
hpp::pinocchio::Joint Class Reference
Robot joint.
#include <hpp/pinocchio/joint.hh>
Public Member Functions
DeviceConstPtr_t robot () const
Access robot owning the object.
DevicePtr_t robot ()
Access robot owning the object.
std::ostream & display (std::ostream &os) const
Display joint.
LiegroupSpacePtr_t configurationSpace () const
Get configuration space of joint.
LiegroupSpacePtr_t RnxSOnConfigurationSpace () const
Get configuration space of joint.
Name
const std::string & name () const
Get name.
Position
const Transform3f & currentTransformation () const
Joint transformation.
const Transform3f & currentTransformation (const DeviceData &data) const
Joint transformation.
Size and rank
size_type numberDof () const
Return number of degrees of freedom.
size_type configSize () const
Return number of degrees of freedom.
size_type rankInConfiguration () const
Return rank of the joint in the configuration vector.
size_type rankInVelocity () const
Return rank of the joint in the velocity vector.
Kinematic chain
JointPtr_t parentJoint () const
Get a pointer to the parent joint (if any).
std::size_t numberChildJoints () const
Number of child joints.
JointPtr_t childJoint (std::size_t rank) const
Get child joint.
const Transform3f & positionInParentFrame () const
Get (constant) placement of joint in parent frame, i.e. model.jointPlacement[idx].
Bounds
void isBounded (size_type rank, bool bounded)
Set whether given degree of freedom is bounded.
bool isBounded (size_type rank) const
Get whether given degree of freedom is bounded.
value_type lowerBound (size_type rank) const
Get lower bound of given degree of freedom.
value_type upperBound (size_type rank) const
Get upper bound of given degree of freedom.
void lowerBound (size_type rank, value_type lowerBound)
Set lower bound of given degree of freedom.
void upperBound (size_type rank, value_type upperBound)
Set upper bound of given degree of freedom.
void lowerBounds (vectorIn_t lowerBounds)
Set lower bounds.
void upperBounds (vectorIn_t upperBounds)
Set upper bounds.
value_type upperBoundLinearVelocity () const
Get upper bound on linear velocity of the joint frame.
value_type upperBoundAngularVelocity () const
Get upper bound on angular velocity of the joint frame.
const value_type & maximalDistanceToParent () const
Maximal distance of joint origin to parent origin.
Jacobian
JointJacobian_t & jacobian (const bool localFrame=true) const
Get non const reference to Jacobian.
JointJacobian_t & jacobian (DeviceData &data, const bool localFrame=true) const
Get reference to Jacobian.
Body linked to the joint
BodyPtr_t linkedBody () const
Get linked body.
Pinocchio API
const JointIndex & index () const
const JointModel & jointModel () const
Protected Member Functions
void computeMaximalDistanceToParent ()
Compute the maximal distance.
void setChildList ()
Store list of childrens.
Model & model ()
const Model & model () const
DeviceData & data () const
void selfAssert () const
Assert that the members of the struct are valid (no null pointer, etc).
Protected Attributes
value_type maximalDistanceToParent_
DeviceWkPtr_t devicePtr
JointIndex jointIndex
std::vector< JointIndex > children
Friends
class Device
Construction and copy and destruction
static JointPtr_t create (DeviceWkPtr_t device, JointIndex indexInJointList)
Create a new joint Returns a null pointer if indexInJointList is 0.
Joint (DeviceWkPtr_t device, JointIndex indexInJointList)
Constructor.
~Joint ()
Detailed Description
Robot joint.
A joint maps an input vector to a transformation of SE(3) from the parent frame to the joint frame.
The input vector is provided through the configuration vector of the robot the joint belongs to. The joint input vector is composed of the components of the robot configuration starting at Joint::rankInConfiguration.
The joint input vector represents a element of a Lie group, either
a vector space for JointTranslation, and bounded JointRotation,
the unit circle for non-bounded JointRotation joints,
an element of SO(3) for JointSO3, represented by a unit quaternion.
Operations specific to joints (uniform sampling of input space, straight interpolation, distance, ...) are performed by a JointConfiguration instance that has the same class hierarchy as Joint.
Constructor & Destructor Documentation
hpp::pinocchio::Joint::Joint (DeviceWkPtr_t device, JointIndex indexInJointList)
Constructor.
Parameters
device pointer on the device the joint is belonging to.
indexInJointList index of the joint, i.e. joint = device.model.joints[index]
hpp::pinocchio::Joint::~Joint () inline
Member Function Documentation
JointPtr_t hpp::pinocchio::Joint::childJoint (std::size_t rank) const
Get child joint.
void hpp::pinocchio::Joint::computeMaximalDistanceToParent () protected
Compute the maximal distance.
See also
maximalDistanceToParent
size_type hpp::pinocchio::Joint::configSize () const
Return number of degrees of freedom.
LiegroupSpacePtr_t hpp::pinocchio::Joint::configurationSpace () const
Get configuration space of joint.
static JointPtr_t hpp::pinocchio::Joint::create (DeviceWkPtr_t device, JointIndex indexInJointList) static
Create a new joint Returns a null pointer if indexInJointList is 0.
const Transform3f& hpp::pinocchio::Joint::currentTransformation () const inline
Joint transformation.
References currentTransformation().
Referenced by currentTransformation().
const Transform3f& hpp::pinocchio::Joint::currentTransformation (const DeviceData & data) const
Joint transformation.
DeviceData& hpp::pinocchio::Joint::data () const protected
std::ostream& hpp::pinocchio::Joint::display (std::ostream & os) const
Display joint.
Referenced by hpp::pinocchio::operator<<().
const JointIndex& hpp::pinocchio::Joint::index () const inline
void hpp::pinocchio::Joint::isBounded (size_type rank, bool bounded)
Set whether given degree of freedom is bounded.
Warning
Joint always has bounds. When bounded == false, the bounds are -infinity and infinity.
bool hpp::pinocchio::Joint::isBounded (size_type rank) const
Get whether given degree of freedom is bounded.
JointJacobian_t& hpp::pinocchio::Joint::jacobian (const bool localFrame = true) const inline
Get non const reference to Jacobian.
Parameters
localFrame if true, compute the jacobian (6d) in the local frame, whose linear part corresponds to the velocity of the center of the frame. If false, the jacobian is expressed in the global frame and its linear part corresponds to the value of the velocity vector field at the center of the world.
References jacobian().
Referenced by jacobian().
JointJacobian_t& hpp::pinocchio::Joint::jacobian (DeviceData & data, const bool localFrame = true) const
Get reference to Jacobian.
Parameters
localFrame if true, compute the jacobian (6d) in the local frame, whose linear part corresponds to the velocity of the center of the frame. If false, the jacobian is expressed in the global frame and its linear part corresponds to the value of the velocity vector field at the center of the world.
const JointModel& hpp::pinocchio::Joint::jointModel () const
BodyPtr_t hpp::pinocchio::Joint::linkedBody () const
Get linked body.
value_type hpp::pinocchio::Joint::lowerBound (size_type rank) const
Get lower bound of given degree of freedom.
void hpp::pinocchio::Joint::lowerBound (size_type rank, value_type lowerBound)
Set lower bound of given degree of freedom.
void hpp::pinocchio::Joint::lowerBounds (vectorIn_t lowerBounds)
Set lower bounds.
const value_type& hpp::pinocchio::Joint::maximalDistanceToParent () const inline
Maximal distance of joint origin to parent origin.
Model& hpp::pinocchio::Joint::model () protected
const Model& hpp::pinocchio::Joint::model () const protected
const std::string& hpp::pinocchio::Joint::name () const
Get name.
std::size_t hpp::pinocchio::Joint::numberChildJoints () const
Number of child joints.
size_type hpp::pinocchio::Joint::numberDof () const
Return number of degrees of freedom.
JointPtr_t hpp::pinocchio::Joint::parentJoint () const
Get a pointer to the parent joint (if any).
const Transform3f& hpp::pinocchio::Joint::positionInParentFrame () const
Get (constant) placement of joint in parent frame, i.e. model.jointPlacement[idx].
size_type hpp::pinocchio::Joint::rankInConfiguration () const
Return rank of the joint in the configuration vector.
size_type hpp::pinocchio::Joint::rankInVelocity () const
Return rank of the joint in the velocity vector.
LiegroupSpacePtr_t hpp::pinocchio::Joint::RnxSOnConfigurationSpace () const
Get configuration space of joint.
Use R^n x SO(n) instead of SE(n).
DeviceConstPtr_t hpp::pinocchio::Joint::robot () const inline
Access robot owning the object.
DevicePtr_t hpp::pinocchio::Joint::robot () inline
Access robot owning the object.
References hpp::pinocchio::display().
void hpp::pinocchio::Joint::selfAssert () const protected
Assert that the members of the struct are valid (no null pointer, etc).
void hpp::pinocchio::Joint::setChildList () protected
Store list of childrens.
value_type hpp::pinocchio::Joint::upperBound (size_type rank) const
Get upper bound of given degree of freedom.
void hpp::pinocchio::Joint::upperBound (size_type rank, value_type upperBound)
Set upper bound of given degree of freedom.
value_type hpp::pinocchio::Joint::upperBoundAngularVelocity () const
Get upper bound on angular velocity of the joint frame.
Returns
coefficient such that
where
is any joint configuration,
is the joint velocity, and
is the angular velocity of the joint frame.
value_type hpp::pinocchio::Joint::upperBoundLinearVelocity () const
Get upper bound on linear velocity of the joint frame.
Returns
coefficient such that
where
is any joint configuration,
is the joint velocity, and
is the linear velocity of the joint frame.
void hpp::pinocchio::Joint::upperBounds (vectorIn_t upperBounds)
Set upper bounds.
Friends And Related Function Documentation
friend class Device friend
Member Data Documentation
std::vector<JointIndex> hpp::pinocchio::Joint::children protected
DeviceWkPtr_t hpp::pinocchio::Joint::devicePtr protected
JointIndex hpp::pinocchio::Joint::jointIndex protected
value_type hpp::pinocchio::Joint::maximalDistanceToParent_ protected