hpp::pinocchio::Device Class Reference
hpp::pinocchio::Device Class Reference
Robot with geometric and dynamic pinocchio.
#include <hpp/pinocchio/device.hh>
Public Types
typedef std::pair< JointPtr_t, JointPtr_t > CollisionPair_t
Collision pairs between bodies.
typedef std::list< CollisionPair_t > CollisionPairs_t
Public Member Functions
virtual std::ostream & print (std::ostream &os) const
Print object in a stream.
fcl::AABB computeAABB () const
Compute an aligned bounding around the robot.
void controlComputation (const Computation_t &flag)
Select computation Optimize computation time by selecting only necessary values in method computeForwardKinematics.
Set pinocchio models and datas
void setModel (ModelPtr_t modelPtr)
Set pinocchio model.
void setGeomModel (GeomModelPtr_t geomModelPtr)
Set pinocchio geom.
void setData (DataPtr_t dataPtr)
Set Pinocchio data corresponding to model.
void createData ()
Create Pinocchio data from model.
void setGeomData (GeomDataPtr_t geomDataPtr)
Set Pinocchio geomData corresponding to model.
void createGeomData ()
Create Pinocchio geomData from model.
Joints
JointPtr_t rootJoint () const
Get root joint.
Frame rootFrame () const
Get root frame.
size_type nbJoints () const
Get number of joints.
JointPtr_t jointAt (const size_type &i) const
Access i-th joint.
JointPtr_t getJointAtConfigRank (const size_type &r) const
Get the joint at configuration rank r.
JointPtr_t getJointAtVelocityRank (const size_type &r) const
Get the joint at velocity rank r.
JointPtr_t getJointByName (const std::string &name) const
Get joint by name.
JointPtr_t getJointByBodyName (const std::string &name) const
Get joint by body name.
Frame getFrameByName (const std::string &name) const
Get frame by name.
size_type configSize () const
Size of configuration vectors Sum of joint dimensions and of extra configuration space dimension.
size_type numberDof () const
Size of velocity vectors Sum of joint number of degrees of freedom and of extra configuration space dimension.
const LiegroupSpacePtr_t & configSpace () const
Returns a LiegroupSpace representing the configuration space.
LiegroupSpacePtr_t RnxSOnConfigSpace () const
See Joint::RnxSOnConfigurationSpace.
Configuration_t neutralConfiguration () const
Get the neutral configuration.
Extra configuration space
ExtraConfigSpace & extraConfigSpace ()
Get degrees of freedom to store internal values in configurations.
const ExtraConfigSpace & extraConfigSpace () const
Get degrees of freedom to store internal values in configurations.
virtual void setDimensionExtraConfigSpace (const size_type &dimension)
Set dimension of extra configuration space.
Grippers
void addGripper (const GripperPtr_t &gripper)
Add a gripper to the Device.
Grippers_t & grippers ()
Return list of grippers of the Device.
const Grippers_t & grippers () const
Return list of grippers of the Device.
Collision and distance computation
BodyPtr_t obstacles () const
Get the static obstacles It corresponds to the geometries attached to the universe in pinocchio.
size_type nbObjects () const
Number of objects.
CollisionObjectPtr_t objectAt (const size_type &i) const
Access the i-th object.
bool collisionTest (const bool stopAtFirstCollision=true)
Test collision of current configuration.
void computeDistances ()
Compute distances between pairs of objects stored in bodies.
const DistanceResults_t & distanceResults () const
Get result of distance computations.
Multithreading
See DeviceSync for how to enable thread safety.
void numberDeviceData (const size_type &s)
Set the maximum number of concurrent use of the Device.
size_type numberDeviceData () const
Get the number of DeviceData.
Public Member Functions inherited from hpp::pinocchio::AbstractDevice
ModelConstPtr_t modelPtr () const
Access to pinocchio model.
ModelPtr_t modelPtr ()
Access to pinocchio model.
const Model & model () const
Access to pinocchio model.
Model & model ()
Access to pinocchio model.
GeomModelConstPtr_t geomModelPtr () const
Access to pinocchio geomModel.
GeomModelPtr_t geomModelPtr ()
Access to pinocchio geomModel.
const GeomModel & geomModel () const
Access to pinocchio geomModel.
GeomModel & geomModel ()
Access to pinocchio geomModel.
DataConstPtr_t dataPtr () const
Access to Pinocchio data/.
DataPtr_t dataPtr ()
Access to Pinocchio data/.
const Data & data () const
Access to Pinocchio data/.
Data & data ()
Access to Pinocchio data/.
GeomDataConstPtr_t geomDataPtr () const
Access to Pinocchio geomData/.
GeomDataPtr_t geomDataPtr ()
Access to Pinocchio geomData/.
const GeomData & geomData () const
Access to Pinocchio geomData/.
GeomData & geomData ()
Access to Pinocchio geomData/.
const Configuration_t & currentConfiguration () const
Get current configuration.
virtual bool currentConfiguration (ConfigurationIn_t configuration)
Set current configuration.
const vector_t & currentVelocity () const
Get current velocity.
bool currentVelocity (vectorIn_t velocity)
Set current velocity.
const vector_t & currentAcceleration () const
Get current acceleration.
bool currentAcceleration (vectorIn_t acceleration)
Set current acceleration.
const value_type & mass () const
Get mass of robot.
const vector3_t & positionCenterOfMass () const
Get position of center of mass.
const ComJacobian_t & jacobianCenterOfMass () const
Get Jacobian of center of mass with respect to configuration.
Computation_t computationFlag () const
Get computation flag.
void computeForwardKinematics ()
Compute forward kinematics.
void computeFramesForwardKinematics ()
Compute frame forward kinematics.
void updateGeometryPlacements ()
Update the geometry placement to the currentConfiguration.
Protected Member Functions
Device (const std::string &name)
Constructor.
void init (const DeviceWkPtr_t &weakPtr)
Initialization.
void initCopy (const DeviceWkPtr_t &weakPtr, const Device &other)
Initialization of of a clone device.
Device (const Device &device)
Copy Constructor.
DeviceData & d ()
DeviceData const & d () const
void invalidate ()
Protected Member Functions inherited from hpp::pinocchio::AbstractDevice
AbstractDevice ()
AbstractDevice (const ModelPtr_t &m, const GeomModelPtr_t &gm)
Protected Attributes
DeviceData d_
std::string name_
Grippers_t grippers_
LiegroupSpacePtr_t configSpace_
ExtraConfigSpace extraConfigSpace_
DeviceWkPtr_t weakPtr_
Protected Attributes inherited from hpp::pinocchio::AbstractDevice
ModelPtr_t model_
GeomModelPtr_t geomModel_
Friends
class Joint
class Frame
class DeviceSync
class CollisionObject
Construction, copy and destruction
virtual ~Device ()
virtual DevicePtr_t clone () const
Clone as a CkwsDevice The pinocchio model is not copied (only copy the pointer).
DevicePtr_t cloneConst () const
Clone as a CkwsDevice Both pinocchio objects model and data are copied.
const std::string & name () const
Get name of device.
static DevicePtr_t create (const std::string &name)
Creation of a new device.
static DevicePtr_t createCopy (const DevicePtr_t &device)
Copy of a device.
static DevicePtr_t createCopyConst (const DeviceConstPtr_t &device)
Detailed Description
Robot with geometric and dynamic pinocchio.
The creation of the device is done by Device::create(const std::string name). This function returns a shared pointer to the newly created object.
See also
Smart pointers documentation: http://www.boost.org/libs/smart_ptr/smart_ptr.htm
Member Typedef Documentation
typedef std::pair<JointPtr_t, JointPtr_t> hpp::pinocchio::Device::CollisionPair_t
Collision pairs between bodies.
typedef std::list<CollisionPair_t> hpp::pinocchio::Device::CollisionPairs_t
Constructor & Destructor Documentation
virtual hpp::pinocchio::Device::~Device () virtual
hpp::pinocchio::Device::Device (const std::string & name) protected
Constructor.
hpp::pinocchio::Device::Device (const Device & device) protected
Copy Constructor.
Member Function Documentation
void hpp::pinocchio::Device::addGripper (const GripperPtr_t & gripper) inline
Add a gripper to the Device.
virtual DevicePtr_t hpp::pinocchio::Device::clone () const inline virtual
Clone as a CkwsDevice The pinocchio model is not copied (only copy the pointer).
A new Pinocchio "data" is created. As the model is not copied, cloning is a non constant operation.
See also
cloneConst
Reimplemented in hpp::pinocchio::HumanoidRobot.
DevicePtr_t hpp::pinocchio::Device::cloneConst () const inline
Clone as a CkwsDevice Both pinocchio objects model and data are copied.
TODO: this method is not implemented yet (assert if called)
bool hpp::pinocchio::Device::collisionTest (const bool stopAtFirstCollision = true)
Test collision of current configuration.
Parameters
stopAtFirstCollision act as named
Warning
Users should call computeForwardKinematics first.
fcl::AABB hpp::pinocchio::Device::computeAABB () const
Compute an aligned bounding around the robot.
The bounding box is computed as follows:
for each direct children of the universe joint:
compute a bounding box of its center (using the bounds in translation)
compute the maximal distance between the its center and each bodies attach its subtree.
sum the two.
sum all the BB obtained.
void hpp::pinocchio::Device::computeDistances ()
Compute distances between pairs of objects stored in bodies.
Warning
Users should call computeForwardKinematics first.
size_type hpp::pinocchio::Device::configSize () const
Size of configuration vectors Sum of joint dimensions and of extra configuration space dimension.
const LiegroupSpacePtr_t& hpp::pinocchio::Device::configSpace () const inline
Returns a LiegroupSpace representing the configuration space.
void hpp::pinocchio::Device::controlComputation (const Computation_t & flag) virtual
Select computation Optimize computation time by selecting only necessary values in method computeForwardKinematics.
Reimplemented from hpp::pinocchio::AbstractDevice.
static DevicePtr_t hpp::pinocchio::Device::create (const std::string & name) static
Creation of a new device.
Returns
a shared pointer to the new device
Parameters
name Name of the device
static DevicePtr_t hpp::pinocchio::Device::createCopy (const DevicePtr_t & device) static
Copy of a device.
Returns
A shared pointer to new device.
Parameters
device Device to be copied. The pinocchio model is not copied (only copy the pointer). A new Pinocchio "data" is created.
static DevicePtr_t hpp::pinocchio::Device::createCopyConst (const DeviceConstPtr_t & device) static
void hpp::pinocchio::Device::createData ()
Create Pinocchio data from model.
void hpp::pinocchio::Device::createGeomData ()
Create Pinocchio geomData from model.
DeviceData& hpp::pinocchio::Device::d () inline protected virtual
Implements hpp::pinocchio::AbstractDevice.
DeviceData const& hpp::pinocchio::Device::d () const inline protected virtual
Implements hpp::pinocchio::AbstractDevice.
const DistanceResults_t& hpp::pinocchio::Device::distanceResults () const
Get result of distance computations.
ExtraConfigSpace& hpp::pinocchio::Device::extraConfigSpace () inline
Get degrees of freedom to store internal values in configurations.
In some applications, it is useful to store extra variables with the configuration vector. For instance, when planning motions in state space using roadmap based methods, the velocity of the robot is stored in the nodes of the roadmap.
const ExtraConfigSpace& hpp::pinocchio::Device::extraConfigSpace () const inline
Get degrees of freedom to store internal values in configurations.
In some applications, it is useful to store extra variables with the configuration vector. For instance, when planning motions in state space using roadmap based methods, the velocity of the robot is stored in the nodes of the roadmap.
Frame hpp::pinocchio::Device::getFrameByName (const std::string & name) const
Get frame by name.
Parameters
name name of the frame.
Exceptions
runtime_error if device has no frame with this name
JointPtr_t hpp::pinocchio::Device::getJointAtConfigRank (const size_type & r) const
Get the joint at configuration rank r.
Returns
joint j such that j->rankInConfiguration () <= r < j->rankInConfiguration () + j->configSize ()
JointPtr_t hpp::pinocchio::Device::getJointAtVelocityRank (const size_type & r) const
Get the joint at velocity rank r.
Returns
joint j such that j->rankInVelocity () <= r < j->rankInVelocity () + j->numberDof ()
JointPtr_t hpp::pinocchio::Device::getJointByBodyName (const std::string & name) const
Get joint by body name.
Exceptions
runtime_error if device has no body with this name
JointPtr_t hpp::pinocchio::Device::getJointByName (const std::string & name) const
Get joint by name.
Parameters
name name of the joint.
Exceptions
runtime_error if device has no joint with this name
Grippers_t& hpp::pinocchio::Device::grippers () inline
Return list of grippers of the Device.
const Grippers_t& hpp::pinocchio::Device::grippers () const inline
Return list of grippers of the Device.
void hpp::pinocchio::Device::init (const DeviceWkPtr_t & weakPtr) protected
Initialization.
void hpp::pinocchio::Device::initCopy (const DeviceWkPtr_t & weakPtr, const Device & other) protected
Initialization of of a clone device.
void hpp::pinocchio::Device::invalidate () inline protected
References hpp::pinocchio::DeviceData::invalidate().
JointPtr_t hpp::pinocchio::Device::jointAt (const size_type & i) const
Access i-th joint.
const std::string& hpp::pinocchio::Device::name () const inline
Get name of device.
References create().
size_type hpp::pinocchio::Device::nbJoints () const
Get number of joints.
size_type hpp::pinocchio::Device::nbObjects () const
Number of objects.
Configuration_t hpp::pinocchio::Device::neutralConfiguration () const
Get the neutral configuration.
void hpp::pinocchio::Device::numberDeviceData (const size_type & s)
Set the maximum number of concurrent use of the Device.
size_type hpp::pinocchio::Device::numberDeviceData () const
Get the number of DeviceData.
size_type hpp::pinocchio::Device::numberDof () const
Size of velocity vectors Sum of joint number of degrees of freedom and of extra configuration space dimension.
CollisionObjectPtr_t hpp::pinocchio::Device::objectAt (const size_type & i) const
Access the i-th object.
See also
Device::nbObjects() const
BodyPtr_t hpp::pinocchio::Device::obstacles () const
Get the static obstacles It corresponds to the geometries attached to the universe in pinocchio.
virtual std::ostream& hpp::pinocchio::Device::print (std::ostream & os) const virtual
Print object in a stream.
Referenced by hpp::pinocchio::operator<<().
LiegroupSpacePtr_t hpp::pinocchio::Device::RnxSOnConfigSpace () const
See Joint::RnxSOnConfigurationSpace.
Frame hpp::pinocchio::Device::rootFrame () const
Get root frame.
JointPtr_t hpp::pinocchio::Device::rootJoint () const
Get root joint.
void hpp::pinocchio::Device::setData (DataPtr_t dataPtr) inline
Set Pinocchio data corresponding to model.
virtual void hpp::pinocchio::Device::setDimensionExtraConfigSpace (const size_type & dimension) inline virtual
Set dimension of extra configuration space.
void hpp::pinocchio::Device::setGeomData (GeomDataPtr_t geomDataPtr) inline
Set Pinocchio geomData corresponding to model.
void hpp::pinocchio::Device::setGeomModel (GeomModelPtr_t geomModelPtr) inline
Set pinocchio geom.
void hpp::pinocchio::Device::setModel (ModelPtr_t modelPtr) inline
Set pinocchio model.
Friends And Related Function Documentation
friend class CollisionObject friend
friend class DeviceSync friend
friend class Frame friend
friend class Joint friend
Member Data Documentation
LiegroupSpacePtr_t hpp::pinocchio::Device::configSpace_ protected
DeviceData hpp::pinocchio::Device::d_ protected
ExtraConfigSpace hpp::pinocchio::Device::extraConfigSpace_ protected
Grippers_t hpp::pinocchio::Device::grippers_ protected
std::string hpp::pinocchio::Device::name_ protected
DeviceWkPtr_t hpp::pinocchio::Device::weakPtr_ protected