Lie group
Lie group
Configurations of robots, as well as some values like the position of a robot joint with respect to a fixed frame belong to differential manifolds that have the structure of Lie groups.
Classes
class hpp::pinocchio::LiegroupElementConstBase< vector_type >
Const reference to a LiegroupElement.
class hpp::pinocchio::LiegroupElementBase< vector_type >
Writable element of a Lie group.
class hpp::pinocchio::LiegroupSpace
Cartesian product of elementary Lie groups.
Typedefs
typedef ABoostVariant hpp::pinocchio::LiegroupType
Elementary Lie groups A boost variant with the following classes:
Enumerations
enum hpp::pinocchio::DerivativeProduct {
hpp::pinocchio::DerivativeTimesInput,
hpp::pinocchio::InputTimesDerivative
}
Functions
template<typename vector_type >
LiegroupElement hpp::pinocchio::operator+ (const LiegroupElementConstBase< vector_type > &e, vectorIn_t v)
Integration of a velocity vector from a configuration.
template<typename vector_type1 , typename vector_type2 >
vector_t hpp::pinocchio::operator- (const LiegroupElementConstBase< vector_type1 > &e1, const LiegroupElementConstBase< vector_type2 > &e2)
Difference between two configurations.
std::ostream & hpp::pinocchio::operator<< (std::ostream &os, const LiegroupSpace &space)
Writing in a stream.
hpp::pinocchio::LiegroupSpacePtr_t boost::operator* (const hpp::pinocchio::LiegroupSpaceConstPtr_t &sp1, const hpp::pinocchio::LiegroupSpaceConstPtr_t &sp2)
Cartesian product between Lie groups.
hpp::pinocchio::LiegroupSpacePtr_t boost::operator^ (const hpp::pinocchio::LiegroupSpaceConstPtr_t &sp, hpp::pinocchio::size_type n)
Cartesian power by an integer.
Detailed Description
Configurations of robots, as well as some values like the position of a robot joint with respect to a fixed frame belong to differential manifolds that have the structure of Lie groups.
These manifolds are the cartesian products of the following elementary Lie groups
,
the group of rotations in the plane represented by a vector of dimension 2 for a rotation of angle ,
the group of rotations in the 3d space represented by a quaternion (ie a vector of dimension 4),
the group of rigid-body motions in the plane, represented by a vector of dimention 4 ,
, the group of rigid-body motion in 3d space, represented by a vector of dimension 7 .
Typedef Documentation
typedef ABoostVariant hpp::pinocchio::LiegroupType
Elementary Lie groups A boost variant with the following classes:
, where is either 1, 2, 3 or dynamic,
, where is either 2 or 3,
, where is either 2 or 3,
, where is either 2 or 3.
See also
hpp::pinocchio::liegroup::VectorSpaceOperation, hpp::pinocchio::liegroup::CartesianProductOperation, hpp::pinocchio::liegroup::SpecialOrthogonalOperation, hpp::pinocchio::liegroup::SpecialEuclideanOperation,
Enumeration Type Documentation
enum hpp::pinocchio::DerivativeProduct
Enumerator
DerivativeTimesInput
InputTimesDerivative
Function Documentation
hpp::pinocchio::LiegroupSpacePtr_t boost::operator* (const hpp::pinocchio::LiegroupSpaceConstPtr_t & sp1, const hpp::pinocchio::LiegroupSpaceConstPtr_t & sp2)
Cartesian product between Lie groups.
template<typename vector_type > LiegroupElement hpp::pinocchio::operator+ (const LiegroupElementConstBase< vector_type > & e, vectorIn_t v)
Integration of a velocity vector from a configuration.
Parameters
e element of the Lie group,
v element of the tangent space of the Lie group.
Returns
the element of the Lie group resulting from the integration
By extension of the vector space case, we represent the integration of a constant velocity during unit time by an addition
Referenced by hpp::pinocchio::LiegroupElementBase< vector_type >::operator=().
template<typename vector_type1 , typename vector_type2 > vector_t hpp::pinocchio::operator- (const LiegroupElementConstBase< vector_type1 > & e1, const LiegroupElementConstBase< vector_type2 > & e2)
Difference between two configurations.
Parameters
e1,e2 elements of the Lie group,
Returns
the velocity that integrated from e2 yiels e1
By extension of the vector space case, we represent the integration of a constant velocity during unit time by an addition
Referenced by hpp::pinocchio::LiegroupElementBase< vector_type >::operator=().
std::ostream& hpp::pinocchio::operator<< (std::ostream & os, const LiegroupSpace & space) inline
Writing in a stream.
References hpp::pinocchio::LiegroupSpace::name().
hpp::pinocchio::LiegroupSpacePtr_t boost::operator^ (const hpp::pinocchio::LiegroupSpaceConstPtr_t & sp, hpp::pinocchio::size_type n)
Cartesian power by an integer.