pinocchio: pinocchio::srdf Namespace Reference
pinocchio::srdf Namespace Reference
SRDF parsing.
Functions
template<typename Scalar , int Options, template< typename, int > class JointCollectionTpl>
PINOCCHIO_DEPRECATED ModelTpl< Scalar, Options, JointCollectionTpl >::ConfigVectorType getNeutralConfiguration (ModelTpl< Scalar, Options, JointCollectionTpl > &model, const std::string &filename, const bool verbose=false)
Get the neutral configuration of a given model associated to a SRDF file. It throws if the SRDF file is incorrect.
template<typename Scalar , int Options, template< typename, int > class JointCollectionTpl>
PINOCCHIO_DEPRECATED ModelTpl< Scalar, Options, JointCollectionTpl >::ConfigVectorType getNeutralConfigurationFromSrdf (ModelTpl< Scalar, Options, JointCollectionTpl > &model, const std::string &filename, const bool verbose=false)
Get the neutral configuration of a given model associated to a SRDF file. It throws if the SRDF file is incorrect.
template<typename Scalar , int Options, template< typename, int > class JointCollectionTpl>
void loadReferenceConfigurations (ModelTpl< Scalar, Options, JointCollectionTpl > &model, const std::string &filename, const bool verbose=false)
Get the reference configurations of a given model associated to a SRDF file. It throws if the SRDF file is incorrect. The reference configurations are saved in a map indexed by the configuration name (model.referenceConfigurations).
template<typename Scalar , int Options, template< typename, int > class JointCollectionTpl>
void loadReferenceConfigurationsFromXML (ModelTpl< Scalar, Options, JointCollectionTpl > &model, std::istream &xmlStream, const bool verbose=false)
Get the reference configurations of a given model associated to a SRDF file. It throws if the SRDF file is incorrect. The reference configurations are saved in a map indexed by the configuration name (model.referenceConfigurations).
template<typename Scalar , int Options, template< typename, int > class JointCollectionTpl>
bool loadRotorParameters (ModelTpl< Scalar, Options, JointCollectionTpl > &model, const std::string &filename, const bool verbose=false)
Load the rotor params of a given model associated to a SRDF file. It throws if the SRDF file is incorrect.
template<typename Scalar , int Options, template< typename, int > class JointCollectionTpl>
PINOCCHIO_DEPRECATED bool loadRotorParamsFromSrdf (ModelTpl< Scalar, Options, JointCollectionTpl > &model, const std::string &filename, const bool verbose=false)
Load the rotor params of a given model associated to a SRDF file. It throws if the SRDF file is incorrect.
template<typename Scalar , int Options, template< typename, int > class JointCollectionTpl>
void removeCollisionPairs (const ModelTpl< Scalar, Options, JointCollectionTpl > &model, GeometryModel &geomModel, const std::string &filename, const bool verbose=false)
Deactive all possible collision pairs mentioned in the SRDF file. It throws if the SRDF file is incorrect.
template<typename Scalar , int Options, template< typename, int > class JointCollectionTpl>
PINOCCHIO_DEPRECATED void removeCollisionPairsFromSrdf (const ModelTpl< Scalar, Options, JointCollectionTpl > &model, GeometryModel &geomModel, const std::string &filename, const bool verbose=false)
Deactive all possible collision pairs mentioned in the SRDF file. It throws if the SRDF file is incorrect.
template<typename Scalar , int Options, template< typename, int > class JointCollectionTpl>
PINOCCHIO_DEPRECATED void removeCollisionPairsFromSrdfString (const ModelTpl< Scalar, Options, JointCollectionTpl > &model, GeometryModel &geomModel, const std::string &xmlString, const bool verbose=false)
Deactive all possible collision pairs mentioned in the SRDF file.
template<typename Scalar , int Options, template< typename, int > class JointCollectionTpl>
void removeCollisionPairsFromXML (const ModelTpl< Scalar, Options, JointCollectionTpl > &model, GeometryModel &geomModel, const std::string &xmlString, const bool verbose=false)
Deactive all possible collision pairs mentioned in the SRDF file.
Detailed Description
SRDF parsing.
Function Documentation
PINOCCHIO_DEPRECATED ModelTpl<Scalar,Options,JointCollectionTpl>::ConfigVectorType pinocchio::srdf::getNeutralConfiguration (ModelTpl< Scalar, Options, JointCollectionTpl > & model, const std::string & filename, const bool verbose = false)
Get the neutral configuration of a given model associated to a SRDF file. It throws if the SRDF file is incorrect.
Parameters
[in] model The Model for which we want the neutral config
[in] filename The complete path to the SRDF file.
[in] verbose Verbosity mode.
Returns
The neutral configuration as an eigen vector
Referenced by getNeutralConfigurationFromSrdf(), and removeCollisionPairsFromSrdfString().
PINOCCHIO_DEPRECATED ModelTpl<Scalar,Options,JointCollectionTpl>::ConfigVectorType pinocchio::srdf::getNeutralConfigurationFromSrdf (ModelTpl< Scalar, Options, JointCollectionTpl > & model, const std::string & filename, const bool verbose = false)
Get the neutral configuration of a given model associated to a SRDF file. It throws if the SRDF file is incorrect.
Parameters
[in] model The Model for which we want the neutral config
[in] filename The complete path to the SRDF file.
[in] verbose Verbosity mode.
Returns
The neutral configuration as an eigen vector
Definition at line 94 of file srdf.hpp.
References getNeutralConfiguration(), loadReferenceConfigurations(), loadReferenceConfigurationsFromXML(), and loadRotorParameters().
void pinocchio::srdf::loadReferenceConfigurations (ModelTpl< Scalar, Options, JointCollectionTpl > & model, const std::string & filename, const bool verbose = false)
Get the reference configurations of a given model associated to a SRDF file. It throws if the SRDF file is incorrect. The reference configurations are saved in a map indexed by the configuration name (model.referenceConfigurations).
Parameters
[in] model The Model for which we want the reference configs.
[in] filename The complete path to the SRDF file.
[in] verbose Verbosity mode.
Referenced by getNeutralConfigurationFromSrdf().
void pinocchio::srdf::loadReferenceConfigurationsFromXML (ModelTpl< Scalar, Options, JointCollectionTpl > & model, std::istream & xmlStream, const bool verbose = false)
Get the reference configurations of a given model associated to a SRDF file. It throws if the SRDF file is incorrect. The reference configurations are saved in a map indexed by the configuration name (model.referenceConfigurations).
Parameters
[in] model The Model for which we want the reference configs.
[in] xmlStream a stream containing the content of a SRDF.
[in] verbose Verbosity mode.
Referenced by getNeutralConfigurationFromSrdf().
bool pinocchio::srdf::loadRotorParameters (ModelTpl< Scalar, Options, JointCollectionTpl > & model, const std::string & filename, const bool verbose = false)
Load the rotor params of a given model associated to a SRDF file. It throws if the SRDF file is incorrect.
Parameters
[in] model The Model for which we want the rotor parmeters
[in] filename The complete path to the SRDF file.
[in] verbose Verbosity mode.
Returns
Boolean whether it loads or not.
Referenced by getNeutralConfigurationFromSrdf(), and loadRotorParamsFromSrdf().
PINOCCHIO_DEPRECATED bool pinocchio::srdf::loadRotorParamsFromSrdf (ModelTpl< Scalar, Options, JointCollectionTpl > & model, const std::string & filename, const bool verbose = false)
Load the rotor params of a given model associated to a SRDF file. It throws if the SRDF file is incorrect.
Parameters
[in] model The Model for which we want the rotor parmeters
[in] filename The complete path to the SRDF file.
[in] verbose Verbosity mode.
Returns
Boolean whether it loads or not.
Definition at line 147 of file srdf.hpp.
References loadRotorParameters().
void pinocchio::srdf::removeCollisionPairs (const ModelTpl< Scalar, Options, JointCollectionTpl > & model, GeometryModel & geomModel, const std::string & filename, const bool verbose = false)
Deactive all possible collision pairs mentioned in the SRDF file. It throws if the SRDF file is incorrect.
Parameters
[in] model Model of the kinematic tree.
[in] geomModel Model of the geometries.
[out] data_geom Data containing the active collision pairs.
[in] filename The complete path to the SRDF file.
[in] verbose Verbosity mode (print removed collision pairs and undefined link inside the model).
Referenced by removeCollisionPairsFromSrdf().
PINOCCHIO_DEPRECATED void pinocchio::srdf::removeCollisionPairsFromSrdf (const ModelTpl< Scalar, Options, JointCollectionTpl > & model, GeometryModel & geomModel, const std::string & filename, const bool verbose = false)
Deactive all possible collision pairs mentioned in the SRDF file. It throws if the SRDF file is incorrect.
Parameters
[in] model Model of the kinematic tree.
[in] geomModel Model of the geometries.
[out] data_geom Data containing the active collision pairs.
[in] filename The complete path to the SRDF file.
[in] verbose Verbosity mode (print removed collision pairs and undefined link inside the model).
Definition at line 37 of file srdf.hpp.
References removeCollisionPairs(), and removeCollisionPairsFromXML().
PINOCCHIO_DEPRECATED void pinocchio::srdf::removeCollisionPairsFromSrdfString (const ModelTpl< Scalar, Options, JointCollectionTpl > & model, GeometryModel & geomModel, const std::string & xmlString, const bool verbose = false)
Deactive all possible collision pairs mentioned in the SRDF file.
Parameters
[in] model Model of the kinematic tree.
[in] geomModel Model of the geometries.
[out] data_geom Data containing the active collision pairs.
[in] xmlString constaining the XML SRDF string.
[in] verbose Verbosity mode (print removed collision pairs and undefined link inside the model).
Definition at line 63 of file srdf.hpp.
References getNeutralConfiguration(), and removeCollisionPairsFromXML().
void pinocchio::srdf::removeCollisionPairsFromXML (const ModelTpl< Scalar, Options, JointCollectionTpl > & model, GeometryModel & geomModel, const std::string & xmlString, const bool verbose = false)
Deactive all possible collision pairs mentioned in the SRDF file.
Parameters
[in] model Model of the kinematic tree.
[in] geomModel Model of the geometries.
[out] data_geom Data containing the active collision pairs.
[in] xmlString constaining the XML SRDF string.
[in] verbose Verbosity mode (print removed collision pairs and undefined link inside the model).
Referenced by removeCollisionPairsFromSrdf(), and removeCollisionPairsFromSrdfString().