pinocchio: CartesianProductOperationVariant Struct Reference
CartesianProductOperationVariant Struct Reference
Dynamic Cartesian product composed of elementary Lie groups defined in LieGroupVariant.
#include <multibody/liegroup/cartesian-product-variant.hpp>
Public Member Functions
CartesianProductOperationVariant ()
Default constructor.
CartesianProductOperationVariant (const LieGroupVariant &lg)
Constructor with one single Lie group.
CartesianProductOperationVariant (const LieGroupVariant &lg1, const LieGroupVariant &lg2)
Constructor with two Lie groups.
void append (const LieGroupVariant &lg)
Append a Lie group to the Cartesian product.
template<class ConfigIn_t , class Velocity_t , class ConfigOut_t >
void integrate_impl (const Eigen::MatrixBase< ConfigIn_t > &q, const Eigen::MatrixBase< Velocity_t > &v, const Eigen::MatrixBase< ConfigOut_t > &qout) const
std::string name () const
ConfigVector_t neutral () const
int nq () const
int nv () const
PINOCCHIO_LIE_GROUP_PUBLIC_INTERFACE (CartesianProductOperationVariant)
Protected Attributes
std::vector< Index > lg_nqs
std::vector< Index > lg_nvs
std::vector< LieGroupVariant > liegroups
std::string m_name
ConfigVector_t m_neutral
Index m_nq
Index m_nv
Detailed Description
Dynamic Cartesian product composed of elementary Lie groups defined in LieGroupVariant.
Definition at line 32 of file cartesian-product-variant.hpp.
Constructor & Destructor Documentation
CartesianProductOperationVariant (const LieGroupVariant & lg) inline
Constructor with one single Lie group.
Parameters
[in] lg Lie group variant to insert inside the Cartesian product
Definition at line 48 of file cartesian-product-variant.hpp.
CartesianProductOperationVariant (const LieGroupVariant & lg1, const LieGroupVariant & lg2) inline
Constructor with two Lie groups.
Parameters
[in] lg1 Lie group variant to insert inside the Cartesian product
[in] lg2 Lie group variant to insert inside the Cartesian product
Definition at line 59 of file cartesian-product-variant.hpp.
Member Function Documentation
void append (const LieGroupVariant & lg) inline
Append a Lie group to the Cartesian product.
Parameters
[in] lg Lie group variant to insert inside the Cartesian product
Definition at line 70 of file cartesian-product-variant.hpp.
References pinocchio::name(), pinocchio::neutral(), pinocchio::nq(), and pinocchio::nv().
The documentation for this struct was generated from the following file:
cartesian-product-variant.hpp