pinocchio: ModelTpl< _Scalar, _Options, JointCollectionTpl > Struct Template Reference
ModelTpl< _Scalar, _Options, JointCollectionTpl > Struct Template Reference
Public Types
enum { Options = _Options }
typedef std::map< std::string, ConfigVectorType > ConfigVectorMap
typedef VectorXs ConfigVectorType
Dense vectorized version of a joint configuration vector.
typedef DataTpl< Scalar, Options, JointCollectionTpl > Data
typedef ForceTpl< Scalar, Options > Force
typedef FrameTpl< Scalar, Options > Frame
typedef pinocchio::FrameIndex FrameIndex
typedef container::aligned_vector< Frame > FrameVector
typedef pinocchio::GeomIndex GeomIndex
typedef pinocchio::Index Index
typedef std::vector< Index > IndexVector
typedef InertiaTpl< Scalar, Options > Inertia
typedef JointCollectionTpl< Scalar, Options > JointCollection
typedef JointDataTpl< Scalar, Options, JointCollectionTpl > JointData
typedef container::aligned_vector< JointData > JointDataVector
typedef pinocchio::JointIndex JointIndex
typedef JointModelTpl< Scalar, Options, JointCollectionTpl > JointModel
typedef container::aligned_vector< JointModel > JointModelVector
typedef MotionTpl< Scalar, Options > Motion
typedef _Scalar Scalar
typedef SE3Tpl< Scalar, Options > SE3
typedef VectorXs TangentVectorType
Dense vectorized version of a joint tangent vector (e.g. velocity, acceleration, etc). It also handles the notion of co-tangent vector (e.g. torque, etc).
typedef Eigen::Matrix< Scalar, 3, 1, Options > Vector3
typedef Eigen::Matrix< Scalar, Eigen::Dynamic, 1, Options > VectorXs
Public Member Functions
ModelTpl ()
Default constructor. Builds an empty model with no joints.
int addBodyFrame (const std::string &body_name, const JointIndex &parentJoint, const SE3 &body_placement=SE3::Identity(), int previousFrame=-1)
Add a body to the frame tree.
int addFrame (const Frame &frame)
Adds a frame to the kinematic tree.
template<typename JointModelDerived >
JointIndex addJoint (const JointIndex parent, const JointModelBase< JointModelDerived > &joint_model, const SE3 &joint_placement, const std::string &joint_name, const VectorXs &max_effort, const VectorXs &max_velocity, const VectorXs &min_config, const VectorXs &max_config)
Add a joint to the kinematic tree with given bounds.
template<typename JointModelDerived >
JointIndex addJoint (const JointIndex parent, const JointModelBase< JointModelDerived > &joint_model, const SE3 &joint_placement, const std::string &joint_name)
Add a joint to the kinematic tree with infinite bounds.
int addJointFrame (const JointIndex &jointIndex, int frameIndex=-1)
Add a joint to the frame tree.
void appendBodyToJoint (const JointIndex joint_index, const Inertia &Y, const SE3 &body_placement=SE3::Identity())
Append a body to a given joint of the kinematic tree.
template<typename NewScalar >
ModelTpl< NewScalar, Options, JointCollectionTpl > cast () const
template<typename D >
bool check (const AlgorithmCheckerBase< D > &checker=AlgorithmCheckerBase< D >()) const
bool check () const
Run check(fusion::list) with DEFAULT_CHECKERS as argument.
bool check (const Data &data) const
bool existBodyName (const std::string &name) const
Check if a body given by its name exists.
bool existFrame (const std::string &name, const FrameType &type=(FrameType)(JOINT|FIXED_JOINT|BODY|OP_FRAME|SENSOR)) const
Checks if a frame given by its name exists.
bool existJointName (const std::string &name) const
Check if a joint given by its name exists.
JointIndex getBodyId (const std::string &name) const
Return the index of a body given by its name.
FrameIndex getFrameId (const std::string &name, const FrameType &type=(FrameType)(JOINT|FIXED_JOINT|BODY|OP_FRAME|SENSOR)) const
Returns the index of a frame given by its name.
JointIndex getJointId (const std::string &name) const
Return the index of a joint given by its name.
PINOCCHIO_DEPRECATED const std::string & getJointName (const JointIndex index) const
Get the name of a joint given by its index.
bool operator!= (const ModelTpl &other) const
bool operator== (const ModelTpl &other) const
Equality comparison operator.
Public Member Functions inherited from Serializable< ModelTpl< _Scalar, _Options, JointCollectionTpl > >
void loadFromBinary (const std::string &filename)
Loads a Derived object from an binary file.
void loadFromText (const std::string &filename)
Loads a Derived object from a text file.
void loadFromXML (const std::string &filename, const std::string &tag_name)
Loads a Derived object from an XML file.
void saveToBinary (const std::string &filename) const
Saves a Derived object as an binary file.
void saveToText (const std::string &filename) const
Saves a Derived object as a text file.
void saveToXML (const std::string &filename, const std::string &tag_name) const
Saves a Derived object as an XML file.
Public Attributes
TangentVectorType effortLimit
Vector of maximal joint torques.
FrameVector frames
Vector of operational frames registered on the model.
Motion gravity
Spatial gravity of the model.
container::aligned_vector< Inertia > inertias
Spatial inertias of the body i expressed in the supporting joint frame i.
container::aligned_vector< SE3 > jointPlacements
Placement (SE3) of the input of joint i regarding to the parent joint output li.
JointModelVector joints
Model of joint i, encapsulated in a JointModelAccessor.
VectorXs lowerPositionLimit
Lower joint configuration limit.
std::string name
Model name;.
std::vector< std::string > names
Name of joint i
int nbodies
Number of bodies.
PINOCCHIO_DEPRECATED ConfigVectorType neutralConfiguration
Vector of joint's neutral configurations.
int nframes
Number of operational frames.
int njoints
Number of joints.
int nq
Dimension of the configuration vector representation.
int nv
Dimension of the velocity vector space.
std::vector< JointIndex > parents
Joint parent of joint i, denoted li (li==parents[i]).
ConfigVectorMap referenceConfigurations
Map of reference configurations, indexed by user given names.
VectorXs rotorGearRatio
Vector of rotor gear ratio parameters.
VectorXs rotorInertia
Vector of rotor inertia parameters.
std::vector< IndexVector > subtrees
Vector of subtrees. subtree[j] corresponds to the subtree supported by the joint j. The first element of subtree[j] is the index of the joint j itself.
VectorXs upperPositionLimit
Upper joint configuration limit.
TangentVectorType velocityLimit
Vector of maximal joint velocities.
Static Public Attributes
static const Vector3 gravity981
Default 3D gravity vector (=(0,0,-9.81)).
Protected Member Functions
void addJointIndexToParentSubtrees (const JointIndex joint_id)
Add the joint_id to its parent subtrees.
Detailed Description
template<typename _Scalar, int _Options, template< typename, int > class JointCollectionTpl>
struct pinocchio::ModelTpl< _Scalar, _Options, JointCollectionTpl >
Definition at line 19 of file multibody/fwd.hpp.
Member Function Documentation
int addBodyFrame (const std::string & body_name, const JointIndex & parentJoint, const SE3 & body_placement = SE3::Identity(), int previousFrame = -1)
Add a body to the frame tree.
Parameters
[in] body_name Name of the body.
[in] parentJoint Index of the parent joint.
[in] body_placement The relative placement of the body regarding to the parent joint. Set default to the Identity placement.
[in] previousFrame Index of the parent frame. If negative, the parent frame is the frame of the parent joint.
Returns
The index of the new frame or -1 in case of error.
Referenced by ModelTpl< ADScalar, Options >::operator!=().
int addFrame (const Frame & frame)
Adds a frame to the kinematic tree.
Parameters
[in] frame The frame to add to the kinematic tree.
Returns
Returns the index of the frame if it has been successfully added, -1 otherwise.
Referenced by ModelTpl< ADScalar, Options >::ModelTpl(), and ModelTpl< ADScalar, Options >::operator!=().
JointIndex addJoint (const JointIndex parent, const JointModelBase< JointModelDerived > & joint_model, const SE3 & joint_placement, const std::string & joint_name, const VectorXs & max_effort, const VectorXs & max_velocity, const VectorXs & min_config, const VectorXs & max_config)
Add a joint to the kinematic tree with given bounds.
Remarks
This method does not add a Frame of same name to the vector of frames. Use Model::addJointFrame.
The inertia supported by the joint is set to Zero.
Template Parameters
JointModelDerived The type of the joint model.
Parameters
[in] parent Index of the parent joint.
[in] joint_model The joint model.
[in] joint_placement Placement of the joint inside its parent joint.
[in] joint_name Name of the joint. If empty, the name is random.
[in] max_effort Maximal joint torque.
[in] max_velocity Maximal joint velocity.
[in] min_config Lower joint configuration.
[in] max_config Upper joint configuration.
Returns
The index of the new joint.
See also
Model::appendBodyToJoint, Model::addJointFrame
Referenced by ModelTpl< ADScalar, Options >::operator!=().
JointIndex addJoint (const JointIndex parent, const JointModelBase< JointModelDerived > & joint_model, const SE3 & joint_placement, const std::string & joint_name)
Add a joint to the kinematic tree with infinite bounds.
Remarks
This method also adds a Frame of same name to the vector of frames.
The inertia supported by the joint is set to Zero.
Template Parameters
JointModelDerived The type of the joint model.
Parameters
[in] parent Index of the parent joint.
[in] joint_model The joint model.
[in] joint_placement Placement of the joint inside its parent joint.
[in] joint_name Name of the joint. If empty, the name is random.
Returns
The index of the new joint.
See also
Model::appendBodyToJoint
int addJointFrame (const JointIndex & jointIndex, int frameIndex = -1)
Add a joint to the frame tree.
Parameters
[in] jointIndex Index of the joint.
[in] frameIndex Index of the parent frame. If negative, the parent frame is the frame of the parent joint.
Returns
The index of the new frame or -1 in case of error.
Referenced by ModelTpl< ADScalar, Options >::operator!=().
void addJointIndexToParentSubtrees (const JointIndex joint_id) protected
Add the joint_id to its parent subtrees.
Parameters
[in] joint_id The id of the joint to add to the subtrees
Referenced by ModelTpl< ADScalar, Options >::check().
void appendBodyToJoint (const JointIndex joint_index, const Inertia & Y, const SE3 & body_placement = SE3::Identity())
Append a body to a given joint of the kinematic tree.
Parameters
[in] joint_index Index of the supporting joint.
[in] Y Spatial inertia of the body.
[in] body_placement The relative placement of the body regarding to the parent joint. Set default to the Identity placement.
See also
Model::addJoint
Referenced by ModelTpl< ADScalar, Options >::operator!=().
ModelTpl<NewScalar,Options,JointCollectionTpl> cast () const inline
Returns
An expression of *this with the Scalar type casted to NewScalar.
Eigen Vectors TODO: remove this pragma when neutralConfiguration will be removed
reserve vectors
copy into vectors
Definition at line 170 of file multibody/model.hpp.
bool check (const AlgorithmCheckerBase< D > & checker = AlgorithmCheckerBase<D>()) const inline
Check the validity of the attributes of Model with respect to the specification of some algorithms.
The method is a template so that the checkers can be defined in each algorithms.
Parameters
[in] checker a class, typically defined in the algorithm module, that validates the attributes of model.
Returns
true if the Model is valid, false otherwise.
Definition at line 513 of file multibody/model.hpp.
Referenced by pinocchio::kineticEnergy(), and pinocchio::potentialEnergy().
bool check (const Data & data) const inline
Run checkData on data and current model.
Parameters
[in] data to be checked wrt *this.
Returns
true if the data is valid, false otherwise.
bool existBodyName (const std::string & name) const
Check if a body given by its name exists.
Parameters
[in] name Name of the body.
Returns
True if the body exists in the kinematic tree.
Referenced by ModelTpl< ADScalar, Options >::operator!=().
bool existFrame (const std::string & name, const FrameType & type = (FrameType)(JOINT|FIXED_JOINT|BODY|OP_FRAME|SENSOR)) const
Checks if a frame given by its name exists.
Parameters
[in] name Name of the frame.
[in] type Type of the frame.
Returns
Returns true if the frame exists.
Referenced by ModelTpl< ADScalar, Options >::operator!=().
bool existJointName (const std::string & name) const
Check if a joint given by its name exists.
Parameters
[in] name Name of the joint.
Returns
True if the joint exists in the kinematic tree.
Referenced by ModelTpl< ADScalar, Options >::operator!=().
JointIndex getBodyId (const std::string & name) const
Return the index of a body given by its name.
Warning
If no body is found, return the number of elements at time T. This can lead to errors if the model is expanded after this method is called (for example to get the id of a parent body)
Parameters
[in] name Name of the body.
Returns
Index of the body.
Referenced by ModelTpl< ADScalar, Options >::operator!=().
FrameIndex getFrameId (const std::string & name, const FrameType & type = (FrameType)(JOINT|FIXED_JOINT|BODY|OP_FRAME|SENSOR)) const
Returns the index of a frame given by its name.
See also
Model::existFrame to check if the frame exists or not.
Warning
If no frame is found, returns the size of the vector of Model::frames. This can lead to errors if the model is expanded after this method is called (for example to get the id of a parent frame).
Parameters
[in] name Name of the frame.
[in] type Type of the frame.
Returns
Index of the frame.
Referenced by ModelTpl< ADScalar, Options >::operator!=().
JointIndex getJointId (const std::string & name) const
Return the index of a joint given by its name.
Warning
If no joint is found, return the number of elements at time T. This can lead to errors if the model is expanded after this method is called (for example to get the id of a parent joint)
Parameters
[in] name Name of the joint.
Returns
Index of the joint.
Referenced by ModelTpl< ADScalar, Options >::operator!=().
PINOCCHIO_DEPRECATED const std::string& getJointName (const JointIndex index) const
Get the name of a joint given by its index.
Parameters
[in] index Index of the joint.
Returns
Name of the joint.
Referenced by ModelTpl< ADScalar, Options >::operator!=().
bool operator!= (const ModelTpl< _Scalar, _Options, JointCollectionTpl > & other) const inline
Returns
true if *this is NOT equal to other.
Definition at line 314 of file multibody/model.hpp.
bool operator== (const ModelTpl< _Scalar, _Options, JointCollectionTpl > & other) const inline
Equality comparison operator.
Returns
true if *this is equal to other.
TODO: remove this pragma when neutralConfiguration will be removed
Definition at line 234 of file multibody/model.hpp.
The documentation for this struct was generated from the following files:
multibody/fwd.hpp
multibody/model.hpp
default-check.hpp