hpp::corbaServer::constraints_idl::DifferentiableFunctionServant< _Base, _Storage > Class Template Reference
hpp::corbaServer::constraints_idl::DifferentiableFunctionServant< _Base, _Storage > Class Template Reference
#include <hpp/corbaserver/constraints_idl/constraints.hh>
Public Member Functions
DifferentiableFunctionServant (Server *server, const Storage &s)
virtual ~DifferentiableFunctionServant ()
floatSeq * value (const floatSeq &arg) throw (Error)
floatSeqSeq * jacobian (const floatSeq &arg) throw (Error)
size_type inputSize () throw (Error)
size_type inputDerivativeSize () throw (Error)
size_type outputSize () throw (Error)
size_type outputDerivativeSize () throw (Error)
char * name () throw (Error)
char * str () throw (Error)
Public Member Functions inherited from hpp::corbaServer::ServantBase< constraints::DifferentiableFunction, _Storage >
virtual ~ServantBase ()
virtual TShPtr_t get () const
StorageElementShPtr_t getT () const
const Storage & getS () const
void persistantStorage (bool persistant)
Set to true if the servant should take ownership of this object.
bool persistantStorage () const
See persistantStorage(bool)
Public Member Functions inherited from hpp::corbaServer::AbstractServantBase< constraints::DifferentiableFunction >
virtual ~AbstractServantBase ()
virtual Server::ServantKey getServantKey () const
Additional Inherited Members
Public Types inherited from hpp::corbaServer::ServantBase< constraints::DifferentiableFunction, _Storage >
typedef _Storage Storage
typedef boost::weak_ptr< typename Storage::element_type > StorageElementWkPtr_t
typedef boost::shared_ptr< typename Storage::element_type > StorageElementShPtr_t
Public Types inherited from hpp::corbaServer::AbstractServantBase< constraints::DifferentiableFunction >
typedef boost::shared_ptr< constraints::DifferentiableFunction > TShPtr_t
typedef boost::weak_ptr< constraints::DifferentiableFunction > TWkPtr_t
Protected Member Functions inherited from hpp::corbaServer::ServantBase< constraints::DifferentiableFunction, _Storage >
ServantBase (Server *server, const Storage &_s)
Protected Member Functions inherited from hpp::corbaServer::AbstractServantBase< constraints::DifferentiableFunction >
AbstractServantBase (Server *server)
Protected Attributes inherited from hpp::corbaServer::ServantBase< constraints::DifferentiableFunction, _Storage >
Storage s
Protected Attributes inherited from hpp::corbaServer::AbstractServantBase< constraints::DifferentiableFunction >
Server * server_
Constructor & Destructor Documentation
template<typename _Base , typename _Storage > hpp::corbaServer::constraints_idl::DifferentiableFunctionServant< _Base, _Storage >::DifferentiableFunctionServant (Server * server, const Storage & s) inline
template<typename _Base , typename _Storage > virtual hpp::corbaServer::constraints_idl::DifferentiableFunctionServant< _Base, _Storage >::~DifferentiableFunctionServant () inline virtual
Member Function Documentation
template<typename _Base , typename _Storage > size_type hpp::corbaServer::constraints_idl::DifferentiableFunctionServant< _Base, _Storage >::inputDerivativeSize () throw (Error) inline
Referenced by hpp::corbaServer::constraints_idl::DifferentiableFunctionServant< _Base, _Storage >::jacobian().
template<typename _Base , typename _Storage > size_type hpp::corbaServer::constraints_idl::DifferentiableFunctionServant< _Base, _Storage >::inputSize () throw (Error) inline
Referenced by hpp::corbaServer::constraints_idl::ImplicitServant< _Base, _Storage >::setRightHandSideFromConfig(), and hpp::corbaServer::constraints_idl::DifferentiableFunctionServant< _Base, _Storage >::value().
template<typename _Base , typename _Storage > floatSeqSeq* hpp::corbaServer::constraints_idl::DifferentiableFunctionServant< _Base, _Storage >::jacobian (const floatSeq & arg) throw (Error) inline
References hpp::corbaServer::floatSeqToVector(), hpp::corbaServer::constraints_idl::DifferentiableFunctionServant< _Base, _Storage >::inputDerivativeSize(), hpp::corbaServer::matrixToFloatSeqSeq(), and hpp::corbaServer::constraints_idl::DifferentiableFunctionServant< _Base, _Storage >::outputDerivativeSize().
template<typename _Base , typename _Storage > char* hpp::corbaServer::constraints_idl::DifferentiableFunctionServant< _Base, _Storage >::name () throw (Error) inline
References hpp::corbaServer::c_str().
template<typename _Base , typename _Storage > size_type hpp::corbaServer::constraints_idl::DifferentiableFunctionServant< _Base, _Storage >::outputDerivativeSize () throw (Error) inline
Referenced by hpp::corbaServer::constraints_idl::DifferentiableFunctionServant< _Base, _Storage >::jacobian().
template<typename _Base , typename _Storage > size_type hpp::corbaServer::constraints_idl::DifferentiableFunctionServant< _Base, _Storage >::outputSize () throw (Error) inline
template<typename _Base , typename _Storage > char* hpp::corbaServer::constraints_idl::DifferentiableFunctionServant< _Base, _Storage >::str () throw (Error) inline
template<typename _Base , typename _Storage > floatSeq* hpp::corbaServer::constraints_idl::DifferentiableFunctionServant< _Base, _Storage >::value (const floatSeq & arg) throw (Error) inline
References hpp::corbaServer::floatSeqToVector(), hpp::corbaServer::constraints_idl::DifferentiableFunctionServant< _Base, _Storage >::inputSize(), and hpp::corbaServer::vectorToFloatSeq().