hpp::corbaServer::BasicServer Class Reference
hpp::corbaServer::BasicServer Class Reference abstract
#include <basic-server.hh>
Public Member Functions
virtual ~ServerPlugin ()
virtual void startCorbaServer (const std::string &contextId, const std::string &contextKind)=0
Start corba server.
virtual std::string name () const =0
core::ProblemSolverPtr_t problemSolver () const throw (std::logic_error)
ProblemSolverMapPtr_t problemSolverMap () const
void setProblemSolverMap (ProblemSolverMapPtr_t psMap)
Set planner that will be controlled by server.
BasicServer (Server *parent)
~BasicServer ()
void startCorbaServer (const std::string &contextId, const std::string &contextKind)
Start corba server.
std::string name () const
Public Member Functions inherited from hpp::corbaServer::ServerPlugin
Server * parent ()
core::ProblemSolverPtr_t problemSolver () const throw (std::logic_error)
ProblemSolverMapPtr_t problemSolverMap () const
void setProblemSolverMap (ProblemSolverMapPtr_t psMap)
Set planner that will be controlled by server.
Protected Member Functions
ServerPlugin (bool multithread)
Protected Member Functions inherited from hpp::corbaServer::ServerPlugin
ServerPlugin (Server *parent)
Protected Attributes
bool multithread_
ProblemSolverMapPtr_t problemSolverMap_
Protected Attributes inherited from hpp::corbaServer::ServerPlugin
Server * parent_
ProblemSolverMapPtr_t problemSolverMap_
Constructor & Destructor Documentation
virtual hpp::corbaServer::BasicServer::~ServerPlugin () inline virtual
Reimplemented from hpp::corbaServer::ServerPlugin.
hpp::corbaServer::BasicServer::BasicServer (Server * parent)
hpp::corbaServer::BasicServer::~BasicServer ()
Member Function Documentation
std::string hpp::corbaServer::BasicServer::name () const pure virtual
Implements hpp::corbaServer::ServerPlugin.
std::string hpp::corbaServer::BasicServer::name () const virtual
Implements hpp::corbaServer::ServerPlugin.
core::ProblemSolverPtr_t hpp::corbaServer::BasicServer::problemSolver () const throw (std::logic_error) inline
ProblemSolverMapPtr_t hpp::corbaServer::BasicServer::problemSolverMap () const inline
hpp::corbaServer::BasicServer::ServerPlugin (bool multithread) inline protected
void hpp::corbaServer::BasicServer::setProblemSolverMap (ProblemSolverMapPtr_t psMap) inline
Set planner that will be controlled by server.
void hpp::corbaServer::BasicServer::startCorbaServer (const std::string & contextId, const std::string & contextKind) pure virtual
Start corba server.
Implements hpp::corbaServer::ServerPlugin.
References hpp::corba::Server< T >::implementation(), hpp::corbaServer::Server::multiThread(), hpp::corbaServer::ServerPlugin::parent(), and hpp::corba::Server< T >::startCorbaServer().
void hpp::corbaServer::BasicServer::startCorbaServer (const std::string & contextId, const std::string & contextKind) virtual
Start corba server.
Implements hpp::corbaServer::ServerPlugin.
Member Data Documentation
bool hpp::corbaServer::BasicServer::multithread_ protected
ProblemSolverMapPtr_t hpp::corbaServer::BasicServer::problemSolverMap_ protected