hpp::corbaServer::impl::Obstacle Class Reference
hpp::corbaServer::impl::Obstacle Class Reference
#include <obstacle.impl.hh>
Public Member Functions
Obstacle ()
void setServer (ServerPlugin *server)
virtual void loadObstacleModel (const char *package, const char *filename, const char *prefix) throw (hpp::Error)
virtual void removeObstacleFromJoint (const char *objectName, const char *jointName, Boolean collision, Boolean distance) throw (hpp::Error)
virtual void cutObstacle (const char *objectName, const floatSeq &aabb) throw (Error)
virtual void addObstacle (const char *polyhedronName, Boolean collision, Boolean distance) throw (hpp::Error)
virtual void moveObstacle (const char *polyName, const Transform_ cfg) throw (hpp::Error)
virtual void getObstaclePosition (const char *objectName, Transform_ cfg) throw (hpp::Error)
virtual Names_t * getObstacleNames (bool collision, bool distance) throw (hpp::Error)
virtual void createPolyhedron (const char *polyhedronName) throw (hpp::Error)
virtual void createBox (const char *boxName, Double x, Double y, Double z) throw (hpp::Error)
virtual void createSphere (const char *name, Double radius) throw (hpp::Error)
virtual void createCylinder (const char *name, Double radius, Double length) throw (hpp::Error)
virtual ULong addPoint (const char *polyhedronName, Double x, Double y, Double z) throw (hpp::Error)
virtual ULong addTriangle (const char *polyhedronName, ULong pt1, ULong pt2, ULong pt3) throw (hpp::Error)
Constructor & Destructor Documentation
hpp::corbaServer::impl::Obstacle::Obstacle ()
Member Function Documentation
virtual void hpp::corbaServer::impl::Obstacle::addObstacle (const char * polyhedronName, Boolean collision, Boolean distance) throw (hpp::Error) virtual
Referenced by setServer().
virtual ULong hpp::corbaServer::impl::Obstacle::addPoint (const char * polyhedronName, Double x, Double y, Double z) throw (hpp::Error) virtual
Referenced by setServer().
virtual ULong hpp::corbaServer::impl::Obstacle::addTriangle (const char * polyhedronName, ULong pt1, ULong pt2, ULong pt3) throw (hpp::Error) virtual
Referenced by setServer().
virtual void hpp::corbaServer::impl::Obstacle::createBox (const char * boxName, Double x, Double y, Double z) throw (hpp::Error) virtual
Referenced by setServer().
virtual void hpp::corbaServer::impl::Obstacle::createCylinder (const char * name, Double radius, Double length) throw (hpp::Error) virtual
Referenced by setServer().
virtual void hpp::corbaServer::impl::Obstacle::createPolyhedron (const char * polyhedronName) throw (hpp::Error) virtual
Referenced by setServer().
virtual void hpp::corbaServer::impl::Obstacle::createSphere (const char * name, Double radius) throw (hpp::Error) virtual
Referenced by setServer().
virtual void hpp::corbaServer::impl::Obstacle::cutObstacle (const char * objectName, const floatSeq & aabb) throw (Error) virtual
Referenced by setServer().
virtual Names_t* hpp::corbaServer::impl::Obstacle::getObstacleNames (bool collision, bool distance) throw (hpp::Error) virtual
Referenced by setServer().
virtual void hpp::corbaServer::impl::Obstacle::getObstaclePosition (const char * objectName, Transform_ cfg) throw (hpp::Error) virtual
Referenced by setServer().
virtual void hpp::corbaServer::impl::Obstacle::loadObstacleModel (const char * package, const char * filename, const char * prefix) throw (hpp::Error) virtual
Referenced by setServer().
virtual void hpp::corbaServer::impl::Obstacle::moveObstacle (const char * polyName, const Transform_ cfg) throw (hpp::Error) virtual
Referenced by setServer().
virtual void hpp::corbaServer::impl::Obstacle::removeObstacleFromJoint (const char * objectName, const char * jointName, Boolean collision, Boolean distance) throw (hpp::Error) virtual
Referenced by setServer().
void hpp::corbaServer::impl::Obstacle::setServer (ServerPlugin * server) inline
References addObstacle(), addPoint(), addTriangle(), createBox(), createCylinder(), createPolyhedron(), createSphere(), cutObstacle(), distance(), getObstacleNames(), getObstaclePosition(), loadObstacleModel(), moveObstacle(), and removeObstacleFromJoint().