hpp::corbaServer::impl::Robot Class Reference
hpp::corbaServer::impl::Robot Class Reference
Robots and obstacles are stored in object core::Planner.
#include <robot.impl.hh>
Public Member Functions
Robot ()
void setServer (ServerPlugin *server)
virtual void createRobot (const char *robotName) throw (hpp::Error)
virtual void loadRobotModel (const char *robotName, const char *rootJointType, const char *packageName, const char *modelName, const char *urdfSuffix, const char *srdfSuffix) throw (hpp::Error)
virtual void loadHumanoidModel (const char *robotName, const char *rootJointType, const char *packageName, const char *modelName, const char *urdfSuffix, const char *srdfSuffix) throw (hpp::Error)
virtual void loadRobotModelFromString (const char *robotName, const char *rootJointType, const char *urdfString, const char *srdfString) throw (hpp::Error)
virtual void loadHumanoidModelFromString (const char *robotName, const char *rootJointType, const char *urdfString, const char *srdfString) throw (hpp::Error)
virtual char * getRobotName () throw (hpp::Error)
virtual Long getConfigSize () throw (hpp::Error)
virtual Long getNumberDof () throw (hpp::Error)
virtual void appendJoint (const char *parentName, const char *jointName, const char *jointType, const Transform_ pos) throw (hpp::Error)
virtual Names_t * getJointNames () throw (hpp::Error)
virtual Names_t * getJointTypes () throw (hpp::Error)
virtual Names_t * getAllJointNames () throw (hpp::Error)
virtual Names_t * getChildJointNames (const char *jointName) throw (hpp::Error)
virtual char * getParentJointName (const char *jointName) throw (hpp::Error)
virtual hpp::floatSeq * getJointConfig (const char *jointName) throw (hpp::Error)
virtual void setJointConfig (const char *jointName, const floatSeq &cfg) throw (hpp::Error)
virtual char * getJointType (const char *jointName) throw (hpp::Error)
virtual floatSeq * jointIntegrate (const floatSeq &jointCfg, const char *jointName, const floatSeq &dq, bool saturate) throw (hpp::Error)
virtual hpp::floatSeqSeq * getCurrentTransformation (const char *jointName) throw (hpp::Error)
virtual Transform__slice * getJointPositionInParentFrame (const char *jointName) throw (hpp::Error)
virtual Transform__slice * getJointPosition (const char *jointName) throw (hpp::Error)
virtual TransformSeq * getJointsPosition (const floatSeq &q, const Names_t &jointNames) throw (hpp::Error)
virtual floatSeq * getJointVelocity (const char *jointName) throw (hpp::Error)
virtual floatSeq * getJointVelocityInLocalFrame (const char *jointName) throw (hpp::Error)
virtual Transform__slice * getRootJointPosition () throw (hpp::Error)
virtual void setRootJointPosition (const Transform_ position) throw (hpp::Error)
virtual void setJointPositionInParentFrame (const char *jointName, const Transform_ position) throw (hpp::Error)
virtual Long getJointNumberDof (const char *jointName) throw (hpp::Error)
virtual Long getJointConfigSize (const char *jointName) throw (hpp::Error)
virtual hpp::floatSeq * getJointBounds (const char *jointName) throw (hpp::Error)
virtual void setJointBounds (const char *jointName, const hpp::floatSeq &jointBound) throw (hpp::Error)
virtual Transform__slice * getLinkPosition (const char *linkName) throw (hpp::Error)
virtual TransformSeq * getLinksPosition (const floatSeq &q, const Names_t &linkName) throw (hpp::Error)
virtual Names_t * getLinkNames (const char *jointName) throw (hpp::Error)
virtual void setDimensionExtraConfigSpace (ULong dimension) throw (hpp::Error)
virtual ULong getDimensionExtraConfigSpace () throw (hpp::Error)
virtual void setExtraConfigSpaceBounds (const hpp::floatSeq &bounds) throw (hpp::Error)
virtual void setCurrentConfig (const hpp::floatSeq &dofArray) throw (hpp::Error)
virtual hpp::floatSeq * shootRandomConfig () throw (hpp::Error)
virtual hpp::floatSeq * getCurrentConfig () throw (hpp::Error)
virtual void setCurrentVelocity (const hpp::floatSeq &qDot) throw (hpp::Error)
virtual hpp::floatSeq * getCurrentVelocity () throw (hpp::Error)
virtual Names_t * getJointInnerObjects (const char *bodyName) throw (hpp::Error)
virtual Names_t * getJointOuterObjects (const char *bodyName) throw (hpp::Error)
virtual void getObjectPosition (const char *objectName, Transform_ cfg) throw (hpp::Error)
virtual void isConfigValid (const hpp::floatSeq &dofArray, Boolean &validity, CORBA::String_out report) throw (hpp::Error)
virtual void distancesToCollision (hpp::floatSeq_out distances, Names_t_out innerObjects, Names_t_out outerObjects, hpp::floatSeqSeq_out innerPoints, hpp::floatSeqSeq_out outerPoints) throw (hpp::Error)
virtual void autocollisionCheck (hpp::boolSeq_out collide) throw (hpp::Error)
virtual void autocollisionPairs (Names_t_out innerObjects, Names_t_out outerObjects, boolSeq_out active) throw (hpp::Error)
virtual void setAutoCollision (const char *innerObject, const char *outerObject, bool active) throw (hpp::Error)
virtual Double getMass () throw (hpp::Error)
virtual hpp::floatSeq * getCenterOfMass () throw (hpp::Error)
virtual hpp::floatSeq * getCenterOfMassVelocity () throw (hpp::Error)
virtual hpp::floatSeqSeq * getJacobianCenterOfMass () throw (hpp::Error)
virtual void createPolyhedron (const char *polyhedronName) throw (hpp::Error)
virtual void createBox (const char *name, Double x, Double y, Double z) throw (hpp::Error)
virtual void createSphere (const char *name, Double radius) throw (hpp::Error)
virtual void createCylinder (const char *name, Double radius, Double length) throw (hpp::Error)
virtual ULong addPoint (const char *polyhedronName, Double x, Double y, Double z) throw (hpp::Error)
virtual ULong addTriangle (const char *polyhedronName, ULong pt1, ULong pt2, ULong pt3) throw (hpp::Error)
virtual void addObjectToJoint (const char *jointName, const char *objectName, const Transform_ config) throw (hpp::Error)
virtual void addPartialCom (const char *comName, const Names_t &jointNames) throw (hpp::Error)
virtual hpp::floatSeq * getPartialCom (const char *comName) throw (hpp::Error)
virtual hpp::floatSeqSeq * getJacobianPartialCom (const char *comName) throw (hpp::Error)
virtual hpp::floatSeq * getVelocityPartialCom (const char *comName) throw (hpp::Error)
virtual floatSeq * getRobotAABB () throw (hpp::Error)
Detailed Description
Robots and obstacles are stored in object core::Planner.
The kinematic part of a robot is stored in a CkppDeviceComponent object (see KineoWorks documentation).
To each joint is attached a body (CkwsBody).
Each body contains a list of CkcdObject (derived into CkppKCDPolyhedron).
A polyhedron is defined by a set of vertices and a set of facets.
Obstacles are stored in collision lists (CkcdCollisionList) composed of polyhedra (CkppKCDPolyhedron).Implementation of corba interface hpp::Robot.
The construction of a
Constructor & Destructor Documentation
hpp::corbaServer::impl::Robot::Robot ()
Member Function Documentation
virtual void hpp::corbaServer::impl::Robot::addObjectToJoint (const char * jointName, const char * objectName, const Transform_ config) throw (hpp::Error) virtual
Referenced by setServer().
virtual void hpp::corbaServer::impl::Robot::addPartialCom (const char * comName, const Names_t & jointNames) throw (hpp::Error) virtual
Referenced by setServer().
virtual ULong hpp::corbaServer::impl::Robot::addPoint (const char * polyhedronName, Double x, Double y, Double z) throw (hpp::Error) virtual
Referenced by setServer().
virtual ULong hpp::corbaServer::impl::Robot::addTriangle (const char * polyhedronName, ULong pt1, ULong pt2, ULong pt3) throw (hpp::Error) virtual
Referenced by setServer().
virtual void hpp::corbaServer::impl::Robot::appendJoint (const char * parentName, const char * jointName, const char * jointType, const Transform_ pos) throw (hpp::Error) virtual
Referenced by setServer().
virtual void hpp::corbaServer::impl::Robot::autocollisionCheck (hpp::boolSeq_out collide) throw (hpp::Error) virtual
Referenced by setServer().
virtual void hpp::corbaServer::impl::Robot::autocollisionPairs (Names_t_out innerObjects, Names_t_out outerObjects, boolSeq_out active) throw (hpp::Error) virtual
Referenced by setServer().
virtual void hpp::corbaServer::impl::Robot::createBox (const char * name, Double x, Double y, Double z) throw (hpp::Error) virtual
Referenced by setServer().
virtual void hpp::corbaServer::impl::Robot::createCylinder (const char * name, Double radius, Double length) throw (hpp::Error) virtual
Referenced by setServer().
virtual void hpp::corbaServer::impl::Robot::createPolyhedron (const char * polyhedronName) throw (hpp::Error) virtual
Referenced by setServer().
virtual void hpp::corbaServer::impl::Robot::createRobot (const char * robotName) throw (hpp::Error) virtual
Referenced by setServer().
virtual void hpp::corbaServer::impl::Robot::createSphere (const char * name, Double radius) throw (hpp::Error) virtual
Referenced by setServer().
virtual void hpp::corbaServer::impl::Robot::distancesToCollision (hpp::floatSeq_out distances, Names_t_out innerObjects, Names_t_out outerObjects, hpp::floatSeqSeq_out innerPoints, hpp::floatSeqSeq_out outerPoints) throw (hpp::Error) virtual
Referenced by setServer().
virtual Names_t* hpp::corbaServer::impl::Robot::getAllJointNames () throw (hpp::Error) virtual
Referenced by setServer().
virtual hpp::floatSeq* hpp::corbaServer::impl::Robot::getCenterOfMass () throw (hpp::Error) virtual
Referenced by setServer().
virtual hpp::floatSeq* hpp::corbaServer::impl::Robot::getCenterOfMassVelocity () throw (hpp::Error) virtual
Referenced by setServer().
virtual Names_t* hpp::corbaServer::impl::Robot::getChildJointNames (const char * jointName) throw (hpp::Error) virtual
Referenced by setServer().
virtual Long hpp::corbaServer::impl::Robot::getConfigSize () throw (hpp::Error) virtual
Referenced by setServer().
virtual hpp::floatSeq* hpp::corbaServer::impl::Robot::getCurrentConfig () throw (hpp::Error) virtual
Referenced by setServer().
virtual hpp::floatSeqSeq* hpp::corbaServer::impl::Robot::getCurrentTransformation (const char * jointName) throw (hpp::Error) virtual
Referenced by setServer().
virtual hpp::floatSeq* hpp::corbaServer::impl::Robot::getCurrentVelocity () throw (hpp::Error) virtual
Referenced by setServer().
virtual ULong hpp::corbaServer::impl::Robot::getDimensionExtraConfigSpace () throw (hpp::Error) virtual
Referenced by setServer().
virtual hpp::floatSeqSeq* hpp::corbaServer::impl::Robot::getJacobianCenterOfMass () throw (hpp::Error) virtual
Referenced by setServer().
virtual hpp::floatSeqSeq* hpp::corbaServer::impl::Robot::getJacobianPartialCom (const char * comName) throw (hpp::Error) virtual
Referenced by setServer().
virtual hpp::floatSeq* hpp::corbaServer::impl::Robot::getJointBounds (const char * jointName) throw (hpp::Error) virtual
Referenced by hpp.corbaserver.robot.Robot::getSaturated(), and setServer().
virtual hpp::floatSeq* hpp::corbaServer::impl::Robot::getJointConfig (const char * jointName) throw (hpp::Error) virtual
Referenced by setServer().
virtual Long hpp::corbaServer::impl::Robot::getJointConfigSize (const char * jointName) throw (hpp::Error) virtual
Referenced by setServer().
virtual Names_t* hpp::corbaServer::impl::Robot::getJointInnerObjects (const char * bodyName) throw (hpp::Error) virtual
Referenced by setServer().
virtual Names_t* hpp::corbaServer::impl::Robot::getJointNames () throw (hpp::Error) virtual
Referenced by setServer().
virtual Long hpp::corbaServer::impl::Robot::getJointNumberDof (const char * jointName) throw (hpp::Error) virtual
Referenced by setServer().
virtual Names_t* hpp::corbaServer::impl::Robot::getJointOuterObjects (const char * bodyName) throw (hpp::Error) virtual
Referenced by setServer().
virtual Transform__slice* hpp::corbaServer::impl::Robot::getJointPosition (const char * jointName) throw (hpp::Error) virtual
Referenced by setServer().
virtual Transform__slice* hpp::corbaServer::impl::Robot::getJointPositionInParentFrame (const char * jointName) throw (hpp::Error) virtual
Referenced by setServer().
virtual TransformSeq* hpp::corbaServer::impl::Robot::getJointsPosition (const floatSeq & q, const Names_t & jointNames) throw (hpp::Error) virtual
Referenced by setServer().
virtual char* hpp::corbaServer::impl::Robot::getJointType (const char * jointName) throw (hpp::Error) virtual
Referenced by setServer().
virtual Names_t* hpp::corbaServer::impl::Robot::getJointTypes () throw (hpp::Error) virtual
Referenced by setServer().
virtual floatSeq* hpp::corbaServer::impl::Robot::getJointVelocity (const char * jointName) throw (hpp::Error) virtual
Referenced by setServer().
virtual floatSeq* hpp::corbaServer::impl::Robot::getJointVelocityInLocalFrame (const char * jointName) throw (hpp::Error) virtual
Referenced by setServer().
virtual Names_t* hpp::corbaServer::impl::Robot::getLinkNames (const char * jointName) throw (hpp::Error) virtual
Referenced by setServer().
virtual Transform__slice* hpp::corbaServer::impl::Robot::getLinkPosition (const char * linkName) throw (hpp::Error) virtual
Referenced by setServer().
virtual TransformSeq* hpp::corbaServer::impl::Robot::getLinksPosition (const floatSeq & q, const Names_t & linkName) throw (hpp::Error) virtual
Referenced by setServer().
virtual Double hpp::corbaServer::impl::Robot::getMass () throw (hpp::Error) virtual
Referenced by setServer().
virtual Long hpp::corbaServer::impl::Robot::getNumberDof () throw (hpp::Error) virtual
Referenced by setServer().
virtual void hpp::corbaServer::impl::Robot::getObjectPosition (const char * objectName, Transform_ cfg) throw (hpp::Error) virtual
Referenced by setServer().
virtual char* hpp::corbaServer::impl::Robot::getParentJointName (const char * jointName) throw (hpp::Error) virtual
Referenced by setServer().
virtual hpp::floatSeq* hpp::corbaServer::impl::Robot::getPartialCom (const char * comName) throw (hpp::Error) virtual
Referenced by setServer().
virtual floatSeq* hpp::corbaServer::impl::Robot::getRobotAABB () throw (hpp::Error) virtual
Referenced by setServer().
virtual char* hpp::corbaServer::impl::Robot::getRobotName () throw (hpp::Error) virtual
Referenced by setServer().
virtual Transform__slice* hpp::corbaServer::impl::Robot::getRootJointPosition () throw (hpp::Error) virtual
Referenced by setServer().
virtual hpp::floatSeq* hpp::corbaServer::impl::Robot::getVelocityPartialCom (const char * comName) throw (hpp::Error) virtual
Referenced by setServer().
virtual void hpp::corbaServer::impl::Robot::isConfigValid (const hpp::floatSeq & dofArray, Boolean & validity, CORBA::String_out report) throw (hpp::Error) virtual
Referenced by setServer().
virtual floatSeq* hpp::corbaServer::impl::Robot::jointIntegrate (const floatSeq & jointCfg, const char * jointName, const floatSeq & dq, bool saturate) throw (hpp::Error) virtual
Referenced by setServer().
virtual void hpp::corbaServer::impl::Robot::loadHumanoidModel (const char * robotName, const char * rootJointType, const char * packageName, const char * modelName, const char * urdfSuffix, const char * srdfSuffix) throw (hpp::Error) virtual
Referenced by setServer().
virtual void hpp::corbaServer::impl::Robot::loadHumanoidModelFromString (const char * robotName, const char * rootJointType, const char * urdfString, const char * srdfString) throw (hpp::Error) virtual
Referenced by setServer().
virtual void hpp::corbaServer::impl::Robot::loadRobotModel (const char * robotName, const char * rootJointType, const char * packageName, const char * modelName, const char * urdfSuffix, const char * srdfSuffix) throw (hpp::Error) virtual
Referenced by setServer().
virtual void hpp::corbaServer::impl::Robot::loadRobotModelFromString (const char * robotName, const char * rootJointType, const char * urdfString, const char * srdfString) throw (hpp::Error) virtual
Referenced by setServer().
virtual void hpp::corbaServer::impl::Robot::setAutoCollision (const char * innerObject, const char * outerObject, bool active) throw (hpp::Error) virtual
Referenced by setServer().
virtual void hpp::corbaServer::impl::Robot::setCurrentConfig (const hpp::floatSeq & dofArray) throw (hpp::Error) virtual
Referenced by hpp.corbaserver.robot.StaticStabilityConstraintsFactory::createSlidingStabilityConstraint(), hpp.corbaserver.robot.StaticStabilityConstraintsFactory::createStaticStabilityConstraint(), and setServer().
virtual void hpp::corbaServer::impl::Robot::setCurrentVelocity (const hpp::floatSeq & qDot) throw (hpp::Error) virtual
Referenced by setServer().
virtual void hpp::corbaServer::impl::Robot::setDimensionExtraConfigSpace (ULong dimension) throw (hpp::Error) virtual
Referenced by setServer().
virtual void hpp::corbaServer::impl::Robot::setExtraConfigSpaceBounds (const hpp::floatSeq & bounds) throw (hpp::Error) virtual
Referenced by setServer().
virtual void hpp::corbaServer::impl::Robot::setJointBounds (const char * jointName, const hpp::floatSeq & jointBound) throw (hpp::Error) virtual
Referenced by setServer().
virtual void hpp::corbaServer::impl::Robot::setJointConfig (const char * jointName, const floatSeq & cfg) throw (hpp::Error) virtual
Referenced by setServer().
virtual void hpp::corbaServer::impl::Robot::setJointPositionInParentFrame (const char * jointName, const Transform_ position) throw (hpp::Error) virtual
Referenced by setServer().
virtual void hpp::corbaServer::impl::Robot::setRootJointPosition (const Transform_ position) throw (hpp::Error) virtual
Referenced by setServer().
void hpp::corbaServer::impl::Robot::setServer (ServerPlugin * server) inline
References addObjectToJoint(), addPartialCom(), addPoint(), addTriangle(), appendJoint(), autocollisionCheck(), autocollisionPairs(), createBox(), createCylinder(), createPolyhedron(), createRobot(), createSphere(), distancesToCollision(), getAllJointNames(), getCenterOfMass(), getCenterOfMassVelocity(), getChildJointNames(), getConfigSize(), getCurrentConfig(), getCurrentTransformation(), getCurrentVelocity(), getDimensionExtraConfigSpace(), getJacobianCenterOfMass(), getJacobianPartialCom(), getJointBounds(), getJointConfig(), getJointConfigSize(), getJointInnerObjects(), getJointNames(), getJointNumberDof(), getJointOuterObjects(), getJointPosition(), getJointPositionInParentFrame(), getJointsPosition(), getJointType(), getJointTypes(), getJointVelocity(), getJointVelocityInLocalFrame(), getLinkNames(), getLinkPosition(), getLinksPosition(), getMass(), getNumberDof(), getObjectPosition(), getParentJointName(), getPartialCom(), getRobotAABB(), getRobotName(), getRootJointPosition(), getVelocityPartialCom(), isConfigValid(), jointIntegrate(), loadHumanoidModel(), loadHumanoidModelFromString(), loadRobotModel(), loadRobotModelFromString(), saturate(), setAutoCollision(), setCurrentConfig(), setCurrentVelocity(), setDimensionExtraConfigSpace(), setExtraConfigSpaceBounds(), setJointBounds(), setJointConfig(), setJointPositionInParentFrame(), setRootJointPosition(), and shootRandomConfig().
virtual hpp::floatSeq* hpp::corbaServer::impl::Robot::shootRandomConfig () throw (hpp::Error) virtual
Referenced by setServer().