OmniOrbServerPlugin Class Reference
OmniOrbServerPlugin Class Reference
Launch a OmniORB CORBA server for remote access to the GUI.
#include </local/devel/hpp/src/gepetto-viewer-corba/plugins/omniorbserver/plugin.hh>
Public Member Functions
OmniOrbServerPlugin ()
~OmniOrbServerPlugin ()
QString name () const
void stopServer ()
Public Member Functions inherited from gepetto::gui::PluginInterface
PluginInterface ()
virtual ~PluginInterface ()
void doInit ()
bool isInit () const
const QString & errorMsg () const
Protected Member Functions
void init ()
Detailed Description
Launch a OmniORB CORBA server for remote access to the GUI.
Constructor & Destructor Documentation
OmniOrbServerPlugin::OmniOrbServerPlugin ()
OmniOrbServerPlugin::~OmniOrbServerPlugin ()
Member Function Documentation
void OmniOrbServerPlugin::init () protected virtual
Implements gepetto::gui::PluginInterface.
Referenced by name().
QString OmniOrbServerPlugin::name () const inline virtual
Implements gepetto::gui::PluginInterface.
References init(), and stopServer().
void OmniOrbServerPlugin::stopServer ()
Referenced by name().